### ISSUE TITLE
Missing Feature? Maybe some suggestions.

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#100]
Ranks, like admin, mod, etc...

Commands like /broadcast, /mute, ETC

BarAPI for saw the coundtowns on the top?

Admin Chat for communications within admins?

**Comment by twizmwazin** [comment]
We have /a already, we plan to implement our own system for doing match timers rather than using BarAPI. This will allow us to do translations for the bar. More commands will be coming.

**Comment by AngelCasillas01** [comment]
Thanks!!!! Really like this plugin and your plans so far! Very nice work!
