### ISSUE TITLE
When you kill someone on SkyBridge Practice by void the title respawn doesn't work.

### ISSUE THREAD

**Issue by Betah** [twizmwazin/CardinalPGM#1005]

**Comment by Alfalik** [comment]
No need to double issues, you can edit whenever you want the titles.  
Would you upload your XML to pastebin or github gist? You **must **also add your cardinal version, to make sure you are not using an outdated version of it.

**Comment by Pablete1234** [comment]
@Alfalik this happens because the xml (i made that xml) applies a fast velocity downwards to kill you faster in the void, for some reason, it doesn't get properly filtered with the events

**Comment by Betah** [comment]
@Alfalik Isn't a duplicate issue.

**Comment by TiTo-418** [comment]
Error logs: http://pastebin.com/tsBUK7r7

**Comment by Pablete1234** [comment]
fixed in 1378bad

**Comment by Betah** [comment]
Good job, thank you so much.

**Comment by MrTheSharpie** [comment]
Why apply a high velocity when you can include the voith-death thingy?

**Comment by Pablete1234** [comment]
@MrTheSharpie the void death xml is relatively new, the xml i made is like one year old
