### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ElementProHD** [twizmwazin/CardinalPGM#1018]
I can't get the /rank add command to work! Ive tried things like...
<permission>cardinal.rank.add</permission>

And this doesnt work does anyone know what the perms are for this?

**Comment by Prodigy4532** [comment]
cardinal.ranks.add

**Comment by Pablete1234** [comment]
I'm closing this as it was awnsered, if you can't get it working, comment again and I'll reopen it

**Comment by ElementProHD** [comment]
This does not work still :/ Help! please reopen!

<permission>cardinal.ranks.add</permission>
