### ISSUE TITLE
Rank permissions are not prefixed with cardinal.

### ISSUE THREAD

**Issue by ElementProHD** [twizmwazin/CardinalPGM#1020]
Permissions are not working I have done as you told me using cardinal.ranks.add ... and I still have no permission...
![ello](https://cloud.githubusercontent.com/assets/11372746/15741807/3f71d1a0-28b3-11e6-8bb6-f4d40e2834e1.PNG)
![2016-06-02_11 12 48](https://cloud.githubusercontent.com/assets/11372746/15741819/4d80637e-28b3-11e6-95f8-5e02fccaab0d.png)

???

**Comment by TiTo-418** [comment]
Please run `/rank info Admin -a` and post it

**Comment by iEli2tyree011** [comment]
I told you the fix already in the other issue.  
  
The permissions are ranks.add and ranks.remove. They should be prefixed with cardinal., and that will be changed in the future, but for now you can use those permissions.

**Comment by ElementProHD** [comment]
What do you mean by prefix?

**Comment by Pablete1234** [comment]
@ElementProHD The permissions at the moment are "ranks.add" and "ranks.remove" they should be prefixed with "cardinal." so that they become "cardinal.ranks.add" and "cardinal.ranks.remove"

**Comment by ElementProHD** [comment]
That's what I've done in the photo

**Comment by Pablete1234** [comment]
@ElementProHD it should be changed in the code! the code, at the moment, understeands permissions "ranks.add" and "ranks.remove", but it should be changed to "cardinal.ranks.add" and "cardinal.ranks.remove", it's a bug, so just use  "ranks.add" and "ranks.remove" for now, and i'll fix the bug soon

**Comment by ElementProHD** [comment]
So in the code i should put <permission>.ranks.add<\permission>

**Comment by Pablete1234** [comment]
@ElementProHD Code = cardinal code, not xml, in your xml, for now, use "ranks.add"

**Comment by ElementProHD** [comment]
I ment ranks.add no Cardinal infront

**Comment by ElementProHD** [comment]
Sorry I'm new to this

**Comment by Pablete1234** [comment]
@ElementProHD I fixed this, if you update to lastest cardinal build now, you can use "cardinal.ranks.add" or "cardinal.ranks.add.*" or "cardinal.ranks.add.rankName" to give the permission to give the permission to give permission for a specific rank
