### ISSUE TITLE
Map does not load, how would I find out the issue?

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [twizmwazin/CardinalPGM#1054]
I am trying to make a test map for CardinalPGM.  When I make a basic XML file I can't seem to get the thing to load.  The XML file can be found [here](https://github.com/CoWinkKeyDinkInc/CardinalPGM-Maps/blob/master/CardinalPGM%20Test/map.xml).  The map does not load and thus can't be selected ingame.

I don't know if you allow feature requests, but I think you should add something to the terminal that could highlight or show which lines the program can't interpret correctly that causes the map to fail loading.  It would make it much more handy to find out what's wrong.

**Comment by SungMatt** [comment]
It is already a feature. Enable showMapLoadErrors in options.txt.

**Comment by Pablete1234** [comment]
@CoWinkKeyDinkInc line 87 you never get to close box

**Comment by CoWinkKeyDinkInc** [comment]
@SungMatt I didn't know that, thank you!!
@Pablete1234 I meant to complete that, thanks for pointing that out.
