### ISSUE TITLE
Maps loaded from a sub folder that require additional XML files doesn't find them from files above

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [twizmwazin/CardinalPGM#1055]
![screen shot 2016-09-29 at 9 05 03 pm](https://cloud.githubusercontent.com/assets/7586568/18979503/b80df96c-8688-11e6-8d2d-9019b6902caf.png)

For example here, it loads my map Oculo and many others that are located in sub-folders.  Some of them require extra XML files like `tutorial.xml` and `blitz-global.xml` which as you can see is inside the front directory of the maps folder.  The map gets the XML files if it's only in the same folder as where the map itself is stored.  So if like `blitz-global.xml` was in the Blitz folder than CardinalPGM would find it and apply it properly.

**Comment by Pablete1234** [comment]
#1045

**Comment by Pablete1234** [comment]
Fixed in 7df14c3, imports should be imported from anywhere in all your repo now
