### ISSUE TITLE
Boot error

### ISSUE THREAD

**Issue by ElementProHD** [twizmwazin/CardinalPGM#1056]
01.10 08:32:26 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
01.10 08:32:26 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:570) [sportbukkit.jar:git-Bukkit-35485e3]
01.10 08:32:26 [Server] INFO at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:666) [sportbukkit.jar:git-Bukkit-35485e3]
01.10 08:32:26 [Server] INFO at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:365) [sportbukkit.jar:git-Bukkit-35485e3]
01.10 08:32:26 [Server] INFO at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:705) [sportbukkit.jar:git-Bukkit-35485e3]
01.10 08:32:26 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [sportbukkit.jar:git-Bukkit-35485e3]
01.10 08:32:26 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53) ~[sportbukkit.jar:git-Bukkit-35485e3]
01.10 08:32:26 [Server] INFO at in.twizmwaz.cardinal.tabList.TabList$3.run(TabList.java:113) ~[?:?]
01.10 08:32:26 [Server] INFO at in.twizmwaz.cardinal.util.Teams.getTeams(Teams.java:82) ~[?:?]
01.10 08:32:26 [Server] INFO java.lang.NullPointerException
01.10 08:32:26 [Server] ERROR Task #4 for Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d5a5d64 generated an exception

Does anyone know this issue

**Comment by twizmwazin** [comment]
It appears to be related to the tablist.

**Comment by Pablete1234** [comment]
@ElementProHD do you have ffa maps in your repo? Tab list crashes if you try to cycle to an ffa map

**Comment by Pablete1234** [comment]
Closing as nothing else has been said, if you are still having the issue, just comment and i'll reopen it
