### ISSUE TITLE
Missing Feature: No temporary rank assigned to players in lobby.

### ISSUE THREAD

**Issue by luckcolors** [twizmwazin/CardinalPGM#1059]
As my understanding of the plugin.
Right now is not yet possible to assign permissions to only players who are obsverving and haven't yet joined the game. This would be usefull for adding the permission to users for using the compass while observing.

**Comment by Pablete1234** [comment]
Compass is a permission given to ovservers by the plugin

**Comment by luckcolors** [comment]
The compass didn't work in my freshly installed instance.

**Comment by Pablete1234** [comment]
Did you install both cardinal and world edit?
