### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by Joserex65** [twizmwazin/CardinalPGM#106]
Hi,

I cannot compile due to one maven repository server is down.

**Comment by CaptainElliott** [comment]
I can compile just fine. When reporting an issue you could give the error log?

make sure your running `mvn clean install`

**Comment by Joserex65** [comment]
When had you compiled for last time?

**Comment by CaptainElliott** [comment]
I checked just before I made the comment

**Comment by Joserex65** [comment]
https://gist.github.com/Joserex65/20b929e1b3c6a8babd9f

**Comment by CaptainElliott** [comment]
Looks like you did not install your dependencies from the pom, are you using eclipse or InteliJ?

**Comment by Joserex65** [comment]
I am not using eclipse or ItenlliJ. Just compilling with maven.

**Comment by CaptainElliott** [comment]
You need to install the maven dependencies before compiling

**Comment by Joserex65** [comment]
"mpile and run the latest development version of CardinalPGM, you will need JDK7 and Maven. On most Linux distributions, you can find both packages in your default repositories. To compile, simply run mvn clean install. The plugin should be found in target/.2

**Comment by Joserex65** [comment]
"To compile and run the latest development version of CardinalPGM, you will need JDK7 and Maven. On most Linux distributions, you can find both packages in your default repositories. To compile, simply run mvn clean install. The plugin should be found in target/."

**Comment by Joserex65** [comment]
>To compile and run the latest development version of CardinalPGM, you will need JDK7 and Maven. On most Linux distributions, you can find both packages in your default repositories. To compile, simply run mvn clean install. The plugin should be found in target/.

**Comment by CaptainElliott** [comment]
Yes, but to compile you need to have the dependencies from the pom.xml. Hence why they are called "dependencies" the plugin is dependent on them

**Comment by Joserex65** [comment]
So, what do I have to do?

**Comment by CaptainElliott** [comment]
What IDE are you using?

**Comment by Joserex65** [comment]
7

**Comment by CaptainElliott** [comment]
no, and IDE is a development environment (Eclipse/IntelliJ are examples of it)

**Comment by Joserex65** [comment]
Ups, Eclipse.

**Comment by Joserex65** [comment]
?

**Comment by CaptainElliott** [comment]
I'm not too sure how eclipse works but you need to import the dependencies. there should be a "maven Dependencies" directory inside the Eclipse package manager, is there anything in there?

**Comment by Joserex65** [comment]
But, I don't want to use Eclipse. I am just wanting to compile the plugin jar using mvn clean install.

**Comment by Joserex65** [comment]
?

**Comment by Joserex65** [comment]
Why not publishing the jar over the releases page of the github project?

**Comment by Joserex65** [comment]
Anyone there?

**Comment by GChevy** [comment]
There is not jar archives in The proyect because it's not an official realse.

**Comment by Joserex65** [comment]
So, what do I do?

**Comment by twizmwazin** [comment]
@CaptainElliott He shouldn't need to manually install dependencies, that is what maven is for.

@Joserex65 If for whatever reason maven cannot resolve dependencies, compile [this] (https://github.com/OvercastNetwork/ProtocolLib) and [this] (https://github.com/ParaPenguin/Commons). After copiling those using `mvn clean install`, try compiling Cardinal again.

**Comment by Joserex65** [comment]
Ok. I think one repo is down. I am trying now.

**Comment by Joserex65** [comment]
I cannot compile ProtocolLib.

**Comment by CaptainElliott** [comment]
@twizmwazin Yea I know that, I  had the problem previously and I had to re-import the dependencies using maven, I did not mean to manually install the jars

**Comment by Joserex65** [comment]
Can you give me a compiled jar?

**Comment by twizmwazin** [comment]
@Joserex65 Make sure you are in the directory that has the `pom.xml`.

**Comment by Joserex65** [comment]
I am.

**Comment by twizmwazin** [comment]
Post your log

**Comment by Joserex65** [comment]
Commons compilation:
http://gyazo.com/ec2bef4e7a8ac1653abbbe450a163e42

ProtocolLib compilation:
http://gyazo.com/7a6a7f3971eaca42533a7d39f237afde

CardinalPGM compilation:
https://gist.github.com/Joserex65/20b929e1b3c6a8babd9f

**Comment by twizmwazin** [comment]
The ProtocolLib issue is because CraftBukkit downloads are no longer available. For commons, are you on the latest version of either JDK 1.7 or 1.8?

**Comment by Joserex65** [comment]
Yes, I am.

**Comment by twizmwazin** [comment]
What OS are you on?

**Comment by Joserex65** [comment]
Windows 8.1

**Comment by Joserex65** [comment]
(I tried also to compile on Ubuntu Server 14.01 64-bit)

**Comment by twizmwazin** [comment]
Try temporarily disabling any firewalls or antiviruses that may stop maven from acquiring dependencies. Did you get an identical result on Ubuntu?

**Comment by Joserex65** [comment]
Yes.

**Comment by Joserex65** [comment]
Still same error.

**Comment by Joserex65** [comment]
One thing, Why don't you use the releases page?

**Comment by twizmwazin** [comment]
[Freshly written] (https://github.com/twizmwazin/CardinalPGM/wiki/FAQ-(English))

**Comment by Joserex65** [comment]
Ok.

And, do you know why is the maven error.

**Comment by twizmwazin** [comment]
Not really. Try to see if anyone else has the issue, this isn't really the place for technical support.

**Comment by Joserex65** [comment]
But, can you please give me the plugin jar file compiled?

**Comment by CaptainElliott** [comment]
@Joserex65 wait for the plugin to be finished, or get the compiling to work

**Comment by Joserex65** [comment]
Ok. I've solved it.

Just needed to remove all repository files on the folder /YourUsername/.m2 and recompile.

Just publishing if anyone else needs this.

**Comment by twizmwazin** [comment]
Alternatively on Linux is is /home/username/.m2

**Comment by GChevy** [comment]
I uninstall Maven to see if it work. But the last time the same error happen.

**Comment by Joserex65** [comment]
?

**Comment by iEli2tyree011** [comment]
Maven is necessary to compile the plugin.

**Comment by Joserex65** [comment]
Just install maven, try compiling it, and if it doesn't works, try posting the log.
