### ISSUE TITLE
FAQ: XML documentation?

### ISSUE THREAD

**Issue by luckcolors** [twizmwazin/CardinalPGM#1060]
Is there documentation available for making the xml files?
Does CardinalPGM fully supports project ares XML documentation?

Thanks in advance. :)

**Comment by Pablete1234** [comment]
CardinalPGM uses the same format as project ares, some modules are missing (check issues) but most of the stuff is supported

**Comment by luckcolors** [comment]
Thanks!
Be sure to add this to the faq.

**Comment by CoWinkKeyDinkInc** [comment]
If you're looking for XML docs, go to docs.oc.tc
