### ISSUE TITLE
Hi, sorry

### ISSUE THREAD

**Issue by Pandita00** [twizmwazin/CardinalPGM#1066]
Sorry, could you help me to "customize" the book of the hotbar when entering? ... Also a bug ... the leather helmet does not work the first time on the server ...
i use
-SportBukkit 1.8.7

Help me please :c

**Comment by Pablete1234** [comment]
This plugin is for sportbukkit 1.10.2 (soon to be for 1.11), if you are using and outdated version i can't help you, the leather helmet bug has been fixed long ago. Regarding the book, it's contents are downloaded from the web so it can be modified without the need of an update, the book content can be found on: https://github.com/twizmwazin/CardinalNotifications/blob/master/book
