### ISSUE TITLE
Sportbukkit link in docs down.

### ISSUE THREAD

**Issue by ghost** [twizmwazin/CardinalPGM#1071]
The link in the docs to sportbukkit.jar is broken someone needs to re-upload to somewhere else.

**Comment by Pablete1234** [comment]
No one uploads such a jar, it's the output from the build server.
The repository went down as oc.tc closed, new builds may be found in https://repo.extension.ws , the issue is you can't have a link to the latest, you need to scroll down to get the latest sportbukkit

**Comment by Zenzoh** [comment]
Pablete me salvaste la vida, pensé que tendría que descargas esas weas del maven. que flojera
