### ISSUE TITLE
Can't Download CardinalPGM

### ISSUE THREAD

**Issue by Neox189** [twizmwazin/CardinalPGM#1072]
Hello everyone, I'm trying to download the Cardinal and I can't find a link in operation, all the download pages are dead ... could someone please pass me a link to download the latest plugin. Thank you :)

**Comment by CoWinkKeyDinkInc** [comment]
CardinalPGM is dead lmao. Go check out the Stratus Network repository as the original PvP Game Manager was open sourced.

https://github.com/StratusNetwork/projectares

If you really want to Cardinal jar for some reason you can just download this repository as a zip and compile it yourself on your computer.

**Comment by twizmwazin** [comment]
You can't download it as a zip and compile it without tweaking, I made sure that didn't work because then I'd have no way of knowing what version people were using when reporting bugs. You can clone it and compile, but you'll need to do the same for a few libraries, sportbukkit and sk89q-command-framework from OCN, as the maven repo they were hosted on is long gone.

**Comment by Neox189** [comment]
> CardinalPGM is dead lmao. Go check out the Stratus Network repository as the original PvP Game Manager was open sourced.
> 
> https://github.com/StratusNetwork/projectares
> 
> If you really want to Cardinal jar for some reason you can just download this repository as a zip and compile it yourself on your computer.


Perfect, I installed that plugin, I only have one problem, where the maps are saved to play, because the maps folder does not recognize me

**Comment by Neox189** [comment]
![1](https://user-images.githubusercontent.com/49927222/56740783-f9a21a00-6747-11e9-83f1-cc41a6eabed5.png)
![2](https://user-images.githubusercontent.com/49927222/56740784-f9a21a00-6747-11e9-818a-5b6a7a777ad7.png)
![3](https://user-images.githubusercontent.com/49927222/56740785-f9a21a00-6747-11e9-9ca8-d3b8b22dbf80.png)


Do you have any solution for this? I can not think of how to fix it :(
