### ISSUE TITLE
Problem with setnext command

### ISSUE THREAD

**Issue by Neox189** [twizmwazin/CardinalPGM#1073]
![Sin título](https://user-images.githubusercontent.com/49927222/56871992-5cbad780-69fa-11e9-9781-a49e772ba29d.png)
I cant select for example Limbo because when I put /sn Limbo appear (photo text), same with Golden Drought, exist any solution for that?

**Comment by twizmwazin** [comment]
I think you should be able to specify with the number. It's been a long time since most people have looked at this.
