### ISSUE TITLE
NullPointerException onBlockPlace

### ISSUE THREAD

**Issue by maestro34** [twizmwazin/CardinalPGM#110]
I got a NullPointerException on BlockPlaceEvent
Log: http://pastebin.com/gHKFzaWj

**Comment by twizmwazin** [comment]
What map was this?

**Comment by maestro34** [comment]
Fortress Battles

**Comment by maestro34** [comment]
Fixed

**Comment by iEli2tyree011** [comment]
This hasn't been fixed yet

**Comment by iEli2tyree011** [comment]
This was fixed when filter parsing was added to, thanks for reporting!
