### ISSUE TITLE
NullPointerException onBlockBreak

### ISSUE THREAD

**Issue by maestro34** [twizmwazin/CardinalPGM#111]
I got a NullPointerException on BlockBreakEvent.
Log: http://pastebin.com/8Rhzt9AP

**Comment by twizmwazin** [comment]
What map was this?

**Comment by rywarsaw** [comment]
@twizmwazin I believe all 3 of these are on Cannon Duel. I could not replicate the problem.

**Comment by rywarsaw** [comment]
@maestro34 Try updating to the latest version, to see if that will fix your problem.

**Comment by maestro34** [comment]
It was on Fortress Battles

**Comment by maestro34** [comment]
@rywarsaw I did it and it doesn't fix the problem :/

**Comment by iEli2tyree011** [comment]
Are you compiling while checking out the applied branch or master branch?

**Comment by maestro34** [comment]
@iEli2tyree011 I tried with the master branch, I'm going to try with the applied branch

**Comment by maestro34** [comment]
It's fixed with the applied branch

**Comment by rywarsaw** [comment]
Good to hear this problem was resolved!

**Comment by iEli2tyree011** [comment]
This hasn't been fixed yet

**Comment by iEli2tyree011** [comment]
This was fixed when filter parsing was added to, thanks for reporting!
