### ISSUE TITLE
TODO: Add an ItemUtil 

### ISSUE THREAD

**Issue by CaptainElliott** [twizmwazin/CardinalPGM#117]
Have a central place for item parsing where you send an `<item>` element and it will strip it of all attributes and return the appropriate enchantments, attributes, amounts etc

**Comment by iEli2tyree011** [comment]
You can use KitBuilder.getKit([parent element of item], [doc], true) to force it to get a kit even though it's not <kit>

**Comment by CaptainElliott** [comment]
I haven't checked, but doesn't that require things like the item slot which are only compatible with kits

**Comment by iEli2tyree011** [comment]
No, I changed it so item slots are no longer required. It works for the killstreak module, so I'm pretty sure it should be fine.

**Comment by CaptainElliott** [comment]
But that would return Kit. I want it so it can be added to an item stack so a ItemUtil would be the best solution

**Comment by iEli2tyree011** [comment]
Okay, this can be implemented then. Just out of curiosity, what do you plan to use this for?

**Comment by CaptainElliott** [comment]
Blockdrops, already implemented it though, haven't figured out how to evaluate the filter yet
