### ISSUE TITLE
When you do /map it shows the description of another map.

### ISSUE THREAD

**Issue by felipufeliu** [twizmwazin/CardinalPGM#118]
http://i.imgur.com/RYURSFY.png

**Comment by iEli2tyree011** [comment]
This is due to 79b0d5f. Thanks for reporting!

**Comment by iEli2tyree011** [comment]
This still happens if the plugin tries to cycle to another map, fails, then sucessfully cycles to another map.

**Comment by twizmwazin** [comment]
If the plugin fails to cycle to another map, everything is broken. Really what the plugin needs is a cycling fail-safe
