### ISSUE TITLE
BoomBox Ice Pillar cannot be destroyed by TNT

### ISSUE THREAD

**Issue by iEli2tyree011** [twizmwazin/CardinalPGM#120]

**Comment by Alfalik** [comment]
Same with Ender Blast.

**Comment by SuHoney** [comment]
Where can I download the BoomBox?

**Comment by Alfalik** [comment]
Is privated, and isn´t related with this issue.

**Comment by TiTi-418** [comment]
Isn't fixed with Ender Blast

**Comment by iEli2tyree011** [comment]
@TiTi-418 This issue is related to BoomBox

**Comment by TiTi-418** [comment]
Yes, but it is the same with ender blast
