### ISSUE TITLE
(Bug) Cant break or open chests in the wool rooms

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#124]
Hi in the CTW maps i cant break blocks in the wool rooms and open chests.
http://prntscr.com/5zuiky: Map RFV2

**Comment by rywarsaw** [comment]
I thought this was intentionally done in RFV2

**Comment by Alfalik** [comment]
Is an XML error, not the plugin.

**Comment by CaptainElliott** [comment]
Make sure you have the updated xml from maps.oc.tc.

**Comment by ItzWid13** [comment]
ok sorry

**Comment by twizmwazin** [comment]
It appears you cannot open chests in wool rooms that you can go in.

**Comment by Alfalik** [comment]
Can I see the XML?

**Comment by twizmwazin** [comment]
maps.oc.tc

**Comment by Alfalik** [comment]
I know that maps.oc.tc exists, just want to see the XML of Wid Map.

**Comment by rywarsaw** [comment]
@Alfalik Thats where the XML is .-.

**Comment by twizmwazin** [comment]
https://maps.oc.tc/CTW/Standard/Race%20for%20Victory%202/map.xml this?

**Comment by Alfalik** [comment]
In publics you can, so the error is in the Plugin.

@twizmwazin You didn´t understand. nvm

**Comment by felipufeliu** [comment]
I think the same happend on spawn points if they are protected on the xml, at least that happend on my RFV 2 and the XML is from maps.oc.tc.

**Comment by AngelCasillas01** [comment]
This is the plugin, like 1 week ago the plugin allows you to enter to a wool, but you can enter to your own wool, but, with this update maybe the filter of the wools colapsed :P

**Comment by CaptainElliott** [comment]
1 week ago filter and the application of filters were not implemented @AngelCasillas01
