### ISSUE TITLE
When you are playing and then you join to observers, the observers are invisible

### ISSUE THREAD

**Issue by felipufeliu** [twizmwazin/CardinalPGM#125]
http://i.imgur.com/zvUyxjT.png

**Comment by felipufeliu** [comment]
Not only in tab.

**Comment by SuHoney** [comment]
I think hill is not working too

**Comment by felipufeliu** [comment]
They already know that, they will work on it the following days/weeks because actually the KotH gamemode is hard to do

**Comment by twizmwazin** [comment]
@SuHoney KoTH is a work in progress, and therefore does not yet function.
