### ISSUE TITLE
[BUG] When you do /sn "MAP" and then /cycle "<X>" and you type again the /cycle X it cycles the map you have setnext and continues cycling like if you have done 2 times

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#126]
^^

**Comment by twizmwazin** [comment]
I'll look into this

**Comment by CaptainElliott** [comment]
running the cycle command should automatically clear all countdowns before executing

**Comment by AngelCasillas01** [comment]
For me it dosen't work, i put /Cancel and continues cycling idkw

**Comment by twizmwazin** [comment]
Are you on the latest version? If you can make a short video of what you mean that would be very helpful in fixing the issue.

**Comment by Alfalik** [comment]
@AngelCasillas01 Works fine for me. You should compile the last version.

http://youtu.be/nsMGlVf5cmg
