### ISSUE TITLE
Adding Boss Bar for countdowns

### ISSUE THREAD

**Issue by maestro34** [twizmwazin/CardinalPGM#127]
Why don't you add a boss bar message while the starting, the cycling and the game countdowns are running ?
This is a missing feature that you can add.

**Comment by twizmwazin** [comment]
We are going to do this, the plugin is not yet compete. The reason why this hasn't yet been implemented is because we are waiting for translations are complete before adding this feature.

**Comment by maestro34** [comment]
Nice to heard it :)

**Comment by elespawol** [comment]
One cuestion,
The translations will be per client o per server config?
El dia 02/02/2015 16.35, "maestro34" <notifications@github.com> va escriure:

**Comment by iEli2tyree011** [comment]
@elespawol The actual translations will be done by the server, but it will look at your client's language and then send a message based on what language you are using.

**Comment by elespawol** [comment]
Cool!
El dia 02/02/2015 19.30, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by AngelCasillas01** [comment]
Add this for all countdpwns, like fo gold core, glass core, and in cannon duelthe coundowns of the map

**Comment by twizmwazin** [comment]
We know that we need to add, this feature is just a complicated one and it will take time.

**Comment by dentmaged** [comment]
@twizmwazin Will the countdown use BarAPI? Or something custom coded?

**Comment by elespawol** [comment]
+1
El dia 16/02/2015 8.39, "dentmaged" <notifications@github.com> va escriure:

**Comment by twizmwazin** [comment]
@dentmaged I want to minimize use of external dependencies when possible. Bar API has a host of limitations, one being the inability to do localization efficiently. Because it is just sending some packets, I plan on doing this myself.

**Comment by Jair07mx** [comment]
Mean that you can not add this? It would be great, tried to add BarAPI your plugin? you will think of something.

**Comment by iEli2tyree011** [comment]
@Jair07mx The answer to your question is right above your comment:
"I want to minimize use of external dependencies when possible. Bar API has a host of limitations, one being the inability to do localization efficiently. Because it is just sending some packets, I plan on doing this myself."

**Comment by ParaPenguin** [comment]
@twizmwazin You can send boss bars per-client, thus you can do localisation just fine with BarAPI.

**Comment by twizmwazin** [comment]
@ParaPenguin BarAPI is like 2 classes though, which could both be easily rewritten in Cardinal. Either way, I am waiting until we move to 1.8 to do this. SportBukkit 1.8 is currently mostly ready, it can b e found in [this PR](https://github.com/OvercastNetwork/SportBukkit/pull/132). As soon as it hits master, I'm going to update Cardinal to support it. SportBukkit's custom API is not consistent between versions, so I will not be able to have cross version compatibility.

**Comment by ParaPenguin** [comment]
@twizmwazin If SportBukkit doesn't cross per version, it would probably be best to use reflection to achieve the best result across versions.

**Comment by twizmwazin** [comment]
@ParaPenguin Perhaps, although I'm not too concerned with supporting older Minecraft versions.

**Comment by ParaPenguin** [comment]
@twizmwazin I think most people would at least expect the support of 1.7 until 1.8 is launched

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/commit/9f9f043486655dab73655d357f84a28382156920

**Comment by twizmwazin** [comment]
I'll close the issue when the bar is fully implemented

**Comment by TiTo-418** [comment]
Yeah, i know, GL

**Comment by twizmwazin** [comment]
Before I go for the night:
[:D](https://i.imgur.com/WRVOmGR.png)

**Comment by SungMatt** [comment]
Congrats @twizmwazin ! Good night!

Or is this made using cropping O_o

**Comment by twizmwazin** [comment]
@SungMatt This was 100% legit taken in Cardinal

**Comment by SungMatt** [comment]
@twizmwazin Doesn't help that today is April Fools, does it :p

So close to the completing the milestone's objectives!

**Comment by twizmwazin** [comment]
@SungMatt Still the 31st for me

**Comment by TiTo-418** [comment]
Congrats!!! When that will be avabile?

**Comment by dentmaged** [comment]
@twizmwazin When will this feature be done? I'll implement it on myself if you're too busy.

**Comment by twizmwazin** [comment]
@dentmaged I ran into a lot of issues and inconsistencies. If you want to take a stab at it, be my guest.

**Comment by dentmaged** [comment]
@twizmwazin I have began work on it. How can I tell when a core is about to go into a mode (gold core mode for example)?

**Comment by TiTo-418** [comment]
GOLD CORE MODE in {0} seconds

**Comment by dentmaged** [comment]
@TiTo-418 What colours are used?

**Comment by TiTo-418** [comment]
Maybe @CaptainElliott know

**Comment by iEli2tyree011** [comment]
@dentmaged Just wondering, before you work on all the different possibilities for displaying the boss bar, did you make it reliable?

**Comment by CaptainElliott** [comment]
@dentmaged also do you have compatibility for localisation?

**Comment by dentmaged** [comment]
@CaptainElliott Yep!
@iEli2tyree011 What do you mean by "reliable"? I don't think there will be any problems in the future (unless SportBukkit changes)

**Comment by TiTo-418** [comment]
TiTi-418, pl0x

**Comment by iEli2tyree011** [comment]
@dentmaged Did you write your own module then?

**Comment by dentmaged** [comment]
Yes. It is a wrapper for the BossBar module.

**Comment by Zenzoh** [comment]
05/05/15, this is not added.

**Comment by TiTo-418** [comment]
@Zenzoh Be patient...

**Comment by Pablete1234** [comment]
is this ready to be implemented yet?

**Comment by TiTo-418** [comment]
<a href="http://imgur.com/s0bmQLx"><img src="http://i.imgur.com/s0bmQLx.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/fXSsfrx"><img src="http://i.imgur.com/fXSsfrx.jpg" title="source: imgur.com" /></a>

**Comment by Alfalik** [comment]
Implemented completely on 857eeab
