### ISSUE TITLE
Offset filter in translate regions are inverted positive/negative

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#133]
Positive take it to negative / negative take it to positive. Tried to fix it in a commit but didn´t find it.

- Test with correct XML [offset="-66,0,0"] in NextGen:

http://youtu.be/LdAvgBeD8Ek

- Test with new XML [offset="66,0,0"] in NextGen:

http://youtu.be/l9sTCkgZqNg

**Comment by ElFlambMC** [comment]
Alfalik me pasas el maña ascendance

**Comment by ElFlambMC** [comment]
Mapa

**Comment by Alfalik** [comment]
Primero que nada es privado, y segundo no comentes cosas que no esten relacionadas directamente con este bug, usa Skype preferentemente

**Comment by twizmwazin** [comment]
@Alfalik Can you add me on Skype?

**Comment by twizmwazin** [comment]
I wasn't able to reproduce the exact same issues. All the wool rooms seemed to function properly, with the exception of 2 of the wool rooms were offset by 1 block.

**Comment by Alfalik** [comment]
Check just yellow wool room, it doesnt work. (Compiled 5 minutes ago).

**Comment by twizmwazin** [comment]
When I invert them, all wool rooms except lime work correctly.

**Comment by twizmwazin** [comment]
Get back to me on how that works

**Comment by Alfalik** [comment]
Tested it on NextGen and the unique error was one wool room offset by 1 block. The second test was on BoomBox, and apparently the translate regions doesnt work with <union> but alone work correctly. 

http://youtu.be/cnOymlkord4
