### ISSUE TITLE
BoomBox Problems

### ISSUE THREAD

**Issue by elespawol** [twizmwazin/CardinalPGM#134]
- Quartz can be broken, 
- Defenders ''private skybase'' can be broken with tnt and with the hand
- Attacker tubes can be destroyed
- I can put water on attacker tubes

IMGUR: http://imgur.com/a/bKhP9

**Comment by elespawol** [comment]
- A I can put water on attacker tubes

**Comment by elespawol** [comment]
Ignore the ''A'' :S

**Comment by twizmwazin** [comment]
This appears to be more of a collection of issues, however they all are related to appled regions not functioning properly.

**Comment by elespawol** [comment]
Soo are things that are not implemented yet no?

**Comment by twizmwazin** [comment]
@elespawol It comes down to applied regions not being completed yet.

**Comment by elespawol** [comment]
A oookk

**Comment by AngelCasillas01** [comment]
I have BoomBox and it perfectly work for me (compiled after comment :p)

**Comment by elespawol** [comment]
But u have edited the map or de xml?

**Comment by SuHoney** [comment]
Can I have a download for BoomBox?
(I'm searching on it)

**Comment by elespawol** [comment]
It's private.
El dia 05/02/2015 15.20, "SuHoney" <notifications@github.com> va escriure:

**Comment by AngelCasillas01** [comment]
@elespawol no, i got the original one, you are right, some tubes are broken, otherwise other tubes dosent broke lol

**Comment by Alfalik** [comment]
@AngelCasillas01 I think is related to #133

**Comment by Alfalik** [comment]
+ Already fixed in the latest version
+ The same as first
+ Will be fixed in #491
+ Same as the third

**Comment by elespawol** [comment]
No, it's private
El dia 05/02/2015 15.20, "SuHoney" <notifications@github.com> va escriure:

**Comment by iEli2tyree011** [comment]
Closing this as the only problems remaining can be found in #491, which is more specific to what the issues are.
