### ISSUE TITLE
Sometimes when you cycle to another map, people still having the armor.

### ISSUE THREAD

**Issue by felipufeliu** [twizmwazin/CardinalPGM#141]
http://i.imgur.com/i4EtvBx.png

**Comment by AngelCasillas01** [comment]
Just an observation, this happens on the PGM of the OCN too

**Comment by CaptainElliott** [comment]
Is the player using the macro mod?

**Comment by twizmwazin** [comment]
@AngelCasillas01 Even though the issue is present in PGM as well, we still want to fix the issue.

**Comment by AngelCasillas01** [comment]
@twizmwazin :D i like thissss

**Comment by Superjd10** [comment]
This only happens when players are using the macro mod / some forge mods (or when the player intentionally glitch in a block as obs before the map cycles)

**Comment by felipufeliu** [comment]
@CaptainElliot only Google_Chrome was using (Forge), ElWeonDeLaNoche not. And both appear with the armor

**Comment by CaptainElliott** [comment]
This only happens when the player is using the macro mod, perhaps its to do with forge.
Try it without any mods installed

**Comment by felipufeliu** [comment]
@CaptainElliot When I take the screenshot I was only using Optifine, same for LaWeaDeLaNoche

**Comment by Superjd10** [comment]
@felipufeliu Try without mods (optifine is a mod too)

**Comment by iEli2tyree011** [comment]
No one else seems to be able to recreate this issue; if you're still having it with the latest version, please let me know.
