### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#143]
Do you will implement the TAB techonology like in OCN

**Comment by rywarsaw** [comment]
This isn't a bug.

**Comment by ElFlambMC** [comment]
You ser Question?

**Comment by Alfalik** [comment]
First, I don´t think that TAB teams are useful in a Scrimmage Plugin, second, isn´t an issue and third, stop spamming here questions that can be answered in Skype.

**Comment by AngelCasillas01** [comment]
I don't have any devs on skype, and here you can ask questions too, isn't just bugs or errors

**Comment by CaptainElliott** [comment]
The Issue tracker is designed for issues with the plugin (problems or bugs)

**Comment by AngelCasillas01** [comment]
ok

**Comment by twizmwazin** [comment]
@Alfalik That was a bit rude. 
@AngelCasillas01 For Cardinal, the plan is to implement as many features as we can that are present in OCN's PGM, regardless of the feature's usefulness in a scirm.

**Comment by AngelCasillas01** [comment]
@twizmwazin was just an idea, I'm sorry it was so bad :S

**Comment by twizmwazin** [comment]
@AngelCasillas01 It wasn't bad, and we will eventually implement the OCN player list.

**Comment by Alfalik** [comment]
@AngelCasillas01 @twizmwazin Didnt want to be rude, sorry.
