### ISSUE TITLE
Add version utility that uses Git and hashes

### ISSUE THREAD

**Issue by rywarsaw** [twizmwazin/CardinalPGM#146]
Adding a /version command that returns a hash for each version would be extremely helpful when debugging CardinalPGM. Sometimes people submitting issues are using older versions of CardinalPGM which means the bug might have been fixed, or isn't able to be replicated on the current build.

What I propose is a similar to the one Spigot uses. This would take a few hours to implement but I think it will help the issue reports tremendously and streamline the process. This is just a idea for anyone who has the time to implement a feature.

**Comment by rywarsaw** [comment]
Edit: The reason I did post this here is because I am pretty sure PGM implements a similar system.

**Comment by twizmwazin** [comment]
I've been hoping someone could do this, as I've wanted one for a while now. I think this could be done with a maven plug-in. If anyone would like to make a pull request with this feature, that would be awesome. To avoid conflicts, /cardinal with the -v flag would be ideal.

**Comment by rywarsaw** [comment]
@twizmwazin Not sure if this is what your talking about? 

https://github.com/ktoso/maven-git-commit-id-plugin

**Comment by twizmwazin** [comment]
@rywarsaw Looks like it, if you could implement this and make a pr, I'd be happy to merge it.

**Comment by CaptainElliott** [comment]
I'm not really familiar with this but why not just return the the latest git revision code?

**Comment by rywarsaw** [comment]
I had a brief talk with some of the guys on SpigotMC IRC, and apparently MD5 wrote a utility for doing this, and its open source! :)

https://github.com/SpigotMC/Scriptus

**Comment by twizmwazin** [comment]
@rywarsaw I will look into this tonight if I have time. Either way, I'd be happy to accept this as a pull request.

**Comment by rywarsaw** [comment]
@twizmwazin If your implying that you wish for me to send a pull request, I'm afraid I don't have the time to code this. I just brought it up as a suggestion to anyone who did have the time.
