### ISSUE TITLE
[SUG] Add timer spawn module?

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#147]
i got ssb te, Iris DTC TE, etc... all those maps contains timer XML's on it, i put it on my server with cardinalpgm and maps aren't working, if you can put this on work pls do it will be so op :)

**Comment by ElFlambMC** [comment]
Me puedes pasar mapas

**Comment by CaptainElliott** [comment]
We have timers but they are integrated with the score module, would be best to make it into its own separate module

**Comment by ElFlambMC** [comment]
Porfavor

**Comment by Alfalik** [comment]
Isnt a feature, spawn timers just use kits, regions and portals. Here is a test.

http://youtu.be/LRYbC2ghnq8

**Comment by AngelCasillas01** [comment]
@ElFlambMC Porfavor para de pedir mapas por este portal, usa un metod privado si quieres que al menos lean tu pedido, gracias
@Alfalik Alfa pero no llegaste la mapa, pues osea es verdad que el timer anda pero no le tepea a donde va, agregue todos los XML que habian en maps.oc.tc, puse los xmls del timer dentro del mapa, un xml de HoC tambie lo puse, esos codigos no iran en el plugin?
@CaptainElliott Ok, Thanks!

**Comment by Alfalik** [comment]
@AngelCasillas01 Los portales al parecer no estan funcionando correctamente, dejame hacer un par de pruebas.
Va todo en el XML, no en el plugin.

**Comment by twizmwazin** [comment]
The maps from HoC use a spawn timer through the <includes/> element. I made a branch where I tried to implement this, however it isn't working just yet.

**Comment by Alfalik** [comment]
@twizmwazin Kits applied in regions work fine, but the portals, first give errors when using "@" in filters and second, don´t teleporting correctly.

**Comment by twizmwazin** [comment]
What maps (and versions) exactly are you testing this on?

**Comment by Alfalik** [comment]
Just tested Fractal Descent HoC version, heres the XML: http://pastebin.com/nqLh70ee

**Comment by AngelCasillas01** [comment]
I have tested SSB TE, It dosent work, For Iris DTC TE dosent even cycle :P

**Comment by twizmwazin** [comment]
@ElFlambMC 
Porfavor para de preguntar por los mapas, este sector es para los bugs del plugin y tu estas hablando fuera de topic. Si continuas con esto seras bloqueado.

**Comment by AngelCasillas01** [comment]
Like Alfalik say, all of this maps use the timer and is on the XML the tmer, it is use regions, but you should add a file which accept that type of XML , that type of code... So any type of map makers can use ti if they want too...

**Comment by twizmwazin** [comment]
Closing as this isn't a module in itself, rather manipulation of other modules.
