### ISSUE TITLE
Bug- Cannon Duel

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#148]
I just test cannon duel and when it says "Dropping You into the Map" the floor doesnt dissapear

**Comment by ElFlambMC** [comment]
Specificate

**Comment by AngelCasillas01** [comment]
Yes it works.

**Comment by ItzWid13** [comment]
Nope :c

**Comment by Alfalik** [comment]
The map work fine for me, but please, report plugin errors, dont map errors. Back in the map, check if it is in the right coords.

**Comment by ItzWid13** [comment]
I have the HoC Version

**Comment by AngelCasillas01** [comment]
@ItzWid13 i have HoC too, it works fine

**Comment by ItzWid13** [comment]
Ahhh i got a nother version of the plugin xd :c
