### ISSUE TITLE
BUG- REVENGE TE- When i cycle to this map the plugin crashes, and i can put block, etc...

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#150]

**Comment by Rafitamolin** [comment]
Could you please provide more info so Elly and Twiz can work on it?

**Comment by CaptainElliott** [comment]
Could you show a screenshot of the error or provide logs

**Comment by ItzWid13** [comment]
http://prntscr.com/61ht6i
http://prntscr.com/61htrm

**Comment by CaptainElliott** [comment]
You cropped parts out of that stack trace, could you just paste the error in here please?

**Comment by ItzWid13** [comment]
Here: 05.02 13:28:58 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server_custom170.jar:git-SportBukkit-1.5.2-R1.0-425-g809715a]
05.02 13:28:58 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:472) [server_custom170.jar:git-SportBukkit-1.5.2-R1.0-425-g809715a]
05.02 13:28:58 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:559) [server_custom170.jar:git-SportBukkit-1.5.2-R1.0-425-g809715a]
05.02 13:28:58 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [server_custom170.jar:git-SportBukkit-1.5.2-R1.0-425-g809715a]
05.02 13:28:58 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:602) [server_custom170.jar:git-SportBukkit-1.5.2-R1.0-425-g809715a]
05.02 13:28:58 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [server_custom170.jar:git-SportBukkit-1.5.2-R1.0-425-g809715a]
05.02 13:28:58 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53) ~[server_custom170.jar:git-SportBukkit-1.5.2-R1.0-425-g809715a]
05.02 13:28:58 [Server] INFO at in.twizmwaz.cardinal.cycle.CycleTimer.run(CycleTimer.java:34) ~[?:?]
05.02 13:28:58 [Server] INFO at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:44) ~[?:?]
05.02 13:28:58 [Server] INFO at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:62) ~[?:?]
05.02 13:28:58 [Server] INFO at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:100) ~[?:?]
05.02 13:28:58 [Server] INFO at in.twizmwaz.cardinal.module.modules.portal.PortalBuilder.load(PortalBuilder.java:103) ~[?:?]
05.02 13:28:58 [Server] INFO at in.twizmwaz.cardinal.util.NumUtils.parseDouble(NumUtils.java:33) ~[?:?]
05.02 13:28:58 [Server] INFO at java.lang.Double.parseDouble(Double.java:540) ~[?:1.7.0_65]
05.02 13:28:58 [Server] INFO at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250) ~[?:1.7.0_65]
05.02 13:28:58 [Server] INFO java.lang.NumberFormatException: For input string: "@0"
05.02 13:28:58 [Server] INFO [13:28:58 ERROR]: [CardinalPGM] Task #43047 for cardinal v1.0-DEV generated an exception
05.02 13:28:58 [Server] INFO [13:28:58 INFO]: Preparing start region for level 4 (Seed: 0)
05.02 13:28:57 [Server] INFO [13:28:57 INFO]: Cycling to Revenge TE in 1 second
05.02 13:28:51 [Server] INFO [13:28:51 INFO]: Next map set to Revenge TE

**Comment by twizmwazin** [comment]
While map compatibility needs to be fixed, the issue reported here is a larger issue regarding no safeguards against failing to load a map. I'm going to close this for now, as the map issue is redundant.
