### ISSUE TITLE
BUG-DATAbasin

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#152]
when i go the other base, i cant place blocks, it says this: 
http://prntscr.com/61kcgy

**Comment by CaptainElliott** [comment]
This is an intentional feature by the map maker, has nothing to do with the plugin

**Comment by SuHoney** [comment]
Where can I get these Primed maps?

**Comment by ItzWid13** [comment]
CaptainEllit but i put wood

**Comment by twizmwazin** [comment]
@ItzWid13 If you could record a short demonstration video of your plugin it would be helpful.

**Comment by ItzWid13** [comment]
ok :D

**Comment by elespawol** [comment]
Me, happens the same
El dia 06/02/2015 1.44, "ItzWid13" <notifications@github.com> va escriure:
