### ISSUE TITLE
DATAstation Problem

### ISSUE THREAD

**Issue by SwiftGFX** [twizmwazin/CardinalPGM#153]
Theres no error in console.

Video : https://youtu.be/z2_xHMsBYnE

(English is not my first language)

**Comment by twizmwazin** [comment]
What it appears is that the server stalls on something until you time out. Might have to do with the massive monument.

**Comment by SuHoney** [comment]
I tried another PC, but same

(Here is my server log file ; http://pastebin.com/qWeGZJqZ )

**Comment by TiTo-418** [comment]
@SuHoney Can you put the video unlisted?

**Comment by SuHoney** [comment]
@TiTo-418 Unlisted it.

**Comment by elespawol** [comment]
Me happens the same,
El dia 01/04/2015 0.55, "SuHoney" <notifications@github.com> va escriure:

**Comment by Alfalik** [comment]
As you can see in this video, the server doesn't crash/stall anymore caused by the massive monument.

+ Video: https://youtu.be/yu252bNIRIM

**Comment by TiTi-418** [comment]
Related with https://github.com/twizmwazin/CardinalPGM/issues/120#issuecomment-94109008 ?

**Comment by TiTo-418** [comment]
@Alfalik Then this should be closed and use https://github.com/twizmwazin/CardinalPGM/issues/153

**Comment by Alfalik** [comment]
@TiTo-418 Totally agree, the other issue is more complete and accurate with the errors. Also, this has already been fixed.

**Comment by TiTo-418** [comment]
@twizmwazin Opinions?

**Comment by Prodigy4532** [comment]
Need a big server?

**Comment by TiTo-418** [comment]
I guess that this can be closed now.
