### ISSUE TITLE
Duplicate error message on Wit's End

### ISSUE THREAD

**Issue by maestro34** [twizmwazin/CardinalPGM#155]
When I'm trying to place a block to the wool placement it shows me two errors messages:
http://uplmg.com/leo

Version: 1.0-git-CardinalPGM-a804596

**Comment by CaptainElliott** [comment]
Could you provide a video of how this is happenin?

**Comment by maestro34** [comment]
I don't think I need to provide a video, you just need to place a random block where the wool need to be placed at and it will shows you both messages.
