### ISSUE TITLE
Can enter and modify own wool rooms on some maps.

### ISSUE THREAD

**Issue by Vixo1** [twizmwazin/CardinalPGM#162]
Here's a video that explain what I mean... http://youtu.be/uRK_tjnZ-8A
Also here's the xml of the two maps that I tested:
RFV2: http://pastebin.com/PY03EESP
Dynamo: http://pastebin.com/TkHZFpeM

**Comment by CaptainElliott** [comment]
You are using outdated versions of the XML.
Always get the XML for maps.oc,tc as the one that comes with the download is often broken or outdated to old protocols

https://maps.oc.tc/CTW/Standard/Dynamo/map.xml

**Comment by Vixo1** [comment]
I tested with the dynamo xml of maps.oc.tc but the map don't load, it shows this error in the console and don't cycle http://prntscr.com/633awg

**Comment by CaptainElliott** [comment]
is known https://github.com/twizmwazin/CardinalPGM/issues/77

**Comment by ItzWid13** [comment]
Is,your problem you need to have the maps.oc.tc xml :c i have it and it works properly.

**Comment by iEli2tyree011** [comment]
This issue cannot be re-created by anyone else, it seems. Make sure you have the latest version of **all** of the following: the plugin, map XML, and the actual map.
