### ISSUE TITLE
[BUG] Command Errors

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#163]
I think i'm spaming this idk but well, sometimes, you try /ban /kick /tp etc... Dosent let you :( an error on console appear

**Comment by twizmwazin** [comment]
Please post your logs as well as the output of `/cardinal -v`

**Comment by AngelCasillas01** [comment]
Compiles and tested 1min ago, same errors

**Comment by AngelCasillas01** [comment]
@twizmwazin 10.02 20:49:44 [Server] INFO [20:49:44 INFO]: This server is running CardinalPGM version 1.0-git-CardinalPGM-73f9f90

**Comment by Superjd10** [comment]
@AngelCasillas01 He is asking for logs (whatever the console outputs when you do those commands)

**Comment by AngelCasillas01** [comment]
@Superjd10 This server is running CardinalPGM version 1.0-git-CardinalPGM-73f9f90

This?

**Comment by twizmwazin** [comment]
@AngelCasillas01 I need to see the errors to fix them

**Comment by AngelCasillas01** [comment]
@twizmwazin okay! 

Other thing, when you update your gamemode, your name is colored yellow, not like your tag, for example, you join blue, and you update your gamemode, appears yellow, /msg (almost all commands of the commands file are bugged :( )

**Comment by twizmwazin** [comment]
@AngelCasillas01 You need to give an explanation of what "bugged" means. It could mean anything from incorrect behavior or wrong colors, to causing the server to stop.

**Comment by Superjd10** [comment]
@AngelCasillas01 He means what is the complete output of the console, it looks like: error at twizmwazin.cardinalpgm.afolder.something.else

Sportbukkit usually saves the log in the /logs folder, check them out and upload them to a site like Pastebin.

**Comment by AngelCasillas01** [comment]
@twizmwazin @Superjd10 Tomorrow i'll make a video for show to you, the error log othe console i will upload to pastebin ;)

**Comment by rywarsaw** [comment]
I think it is time to close this issue, any thoughts guys?

**Comment by CaptainElliott** [comment]
@rywarsaw Why should this issue be closed, it could be a valid issue

**Comment by rywarsaw** [comment]
@CaptainElliott The user hasn't provided a log or pastebin and I am not able to replicate this problem on the latest CardinalPGM version.

**Comment by CaptainElliott** [comment]
That is no reason for it to be close, it should only be closed if it is declared invalid. That we do not know yet. Moreover it has only been 2 days.

**Comment by rywarsaw** [comment]
@CaptainElliott There is no reason to keep this open until the user has more information. Once the user has more information he/she can re-open this issue on their own.

**Comment by CaptainElliott** [comment]
Not at all, this issue has been reported and there is no need to close it until it has proven to be resolved.

Besides that it has only been 2 days for crying out loud

**Comment by twizmwazin** [comment]
@rywarsaw Please do not try to administrate my repository. The only people who can close an issue are the creator of the issue, myself, and Elly. Issues will be closed when one of us feels it is ready, and we do not need your assistance.

**Comment by AngelCasillas01** [comment]
@twizmwazin I'm sorry i'll getting late, it's becaue i'm on a soccer tourney, and all this week i was so busy, today i'll make a video and all this things and posted here :)

**Comment by AngelCasillas01** [comment]
@twizmwazin @CaptainElliott 
Heres is the test on a video, is not yet, i'm going to sleep and let the video uploading, should be ready when you see this, i'll try too put /cardinal -v and dosen't work btw!

**Comment by AngelCasillas01** [comment]
http://youtu.be/FxC8Xa-1L7g

**Comment by CaptainElliott** [comment]
@AngelCasillas01 We need to see the stack trace of the error

Upload the logs of when you were executing the command to something like pastbin or gist

**Comment by knightopress** [comment]
You might be using an outdated version of CardinalPGM or SportBukkit, I'm not getting any of those errors with the latest versions.

**Comment by AngelCasillas01** [comment]
after some test, this is working fine, my fault :c
