### ISSUE TITLE
Checking es.xml

### ISSUE THREAD

**Issue by angelitorb99** [twizmwazin/CardinalPGM#164]
In message es.xml Some bugs fixed
alreadyObs - Ya estás observando</alreadyObs>
teamExists - Ya existe un equipo con el nombre {0}</teamExists>
movedForBalance - Has sido movido a {0} para equilibrar el tamaño de los equipos</movedForBalance>
autoJoinSwitch - (no elegiste un equipo, así que asumimos que no te importará)</autoJoinSwitch>

**Comment by twizmwazin** [comment]
If you wish to improve Cardinal, please follow [this] (https://help.github.com/articles/creating-a-pull-request/) guide to create a pull erquest so it can be reviewed.
