### ISSUE TITLE
Wools can't be placed on Victory Monument

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#165]
I can't place any wool in any map on the Victory Monument (xml are from maps.oc.tc).
Version: http://prntscr.com/63icks

**Comment by CaptainElliott** [comment]
Is there any error? what map were you doing it on?

**Comment by MrTheSharpie** [comment]
It says you cant placer blocks at spawn. First I did it con Ring Race, then I tried ok Deepwind and RFV2. If you want I can be more detailed with screenshots por vídeo tomorrow.

**Comment by MrTheSharpie** [comment]
Also, I tried using XML from maps.oc.tc but it continued doing the same

**Comment by twizmwazin** [comment]
I think what is happening is that the block is being denied by the spawn region after being accepted by the WoolModule. This should be easily fixed by adjusting priorities.

**Comment by MrTheSharpie** [comment]
So is it a problem of the plugin or of the XML? Because I tried with different maps :S

**Comment by xDofah** [comment]
fix it pls,i need that plugin

**Comment by twizmwazin** [comment]
@MrTheSharpie Most likely the plugin. I will try to correct it tonight.

@xDofah That comment is entirely unhelpful

**Comment by xDofah** [comment]
@twizmwazin i know,and thats my objective,okno.

Thanks to try to fix tonight :P

**Comment by MrTheSharpie** [comment]
Thank you! And goob job with this, is the best PGM i have seen (Parapenguin did a good job also)
