### ISSUE TITLE
How i can fix this?

### ISSUE THREAD

**Issue by RubeGamerV** [twizmwazin/CardinalPGM#168]
<a><img src="http://i.gyazo.com/344206d32e485c6d282dbe096e323d02.png" /></a>

**Comment by CaptainElliott** [comment]
You need to import the dependancies form the POM.xml using maven
Most modern IDEs will do this.
I would suggest using IntelliJ but Eclipse is also an option

**Comment by twizmwazin** [comment]
In IntelliJ you need to manually go and enable auto-importing of maven dependencies if you didn't enable it when importing the project. I think Eclipse is more automated (you might need a plugin though). Don't use NetBeans.

**Comment by RubeGamerV** [comment]
Wich plugin need for Eclipse?

**Comment by twizmwazin** [comment]
http://eclipse.org/m2e/

**Comment by RubeGamerV** [comment]
I only need to copy and paste this codes in eclipse, compile this on maven and i can test this?

**Comment by twizmwazin** [comment]
If you are just trying to compile, I suggest referring to [this] (https://github.com/twizmwazin/CardinalPGM/wiki/Instalando-CardinalPGM) guide.

**Comment by RubeGamerV** [comment]
Can i have a NO REALESE to can test? or see it?

**Comment by twizmwazin** [comment]
@RubeGamerV I have no idea what that means.

**Comment by RubeGamerV** [comment]
Like a "beta" of the cardinal.jar to can test and see

**Comment by felipufeliu** [comment]
@RubeGamerV Para eso debes tu mismo compilar el plugin, aun no hay una 1.0 del plugin y si quieres hacer uso del plugin antes de la 1.0 tu debes compilarlo.

**Comment by RubeGamerV** [comment]
@felipufeliu esque me da problema el eclipse cuando le pongo el codigo de arriba.

**Comment by RubeGamerV** [comment]
y no me deja construirlo

**Comment by felipufeliu** [comment]
@RubeGamerV Te recomiendo construirlo con Maven, esta guia (https://github.com/twizmwazin/CardinalPGM/wiki/Instalando-CardinalPGM) podria ayudarte ya que yo personalmente no se como construirlo con Eclipse.

**Comment by RubeGamerV** [comment]
@felipufeliu y cual sportbukkit usas? el sportbukkit-api? o el normal? Grax

**Comment by felipufeliu** [comment]
@RubeGamerV El normal

**Comment by RubeGamerV** [comment]
@felipufeliu aa okok simplemente pongo los codigos que me da en la src de este repositorio y luego lo construyo directamente en maven?

**Comment by felipufeliu** [comment]
@RubeGamerV No entiendo muy bien lo que quieres decir, pero mejor revisa la guia y leela completa ya que yo no sabría como explicarte

**Comment by RubeGamerV** [comment]
@felipufeliu me pasas tu skype?

**Comment by RubeGamerV** [comment]
@twizmwazin Why i cant use Net Beans?

**Comment by twizmwazin** [comment]
@RubeGamerV You can, but I don't have any experience with it and it generally has little support compared to IntelliJ or Eclipse.

**Comment by RubeGamerV** [comment]
@twizmwazin bcus the plugin that you send me ( http://eclipse.org/m2e/ ) dosn´t work

**Comment by twizmwazin** [comment]
@RubeGamerV Are you just trying to compile Cardinal or are you trying to develop it?

**Comment by RubeGamerV** [comment]
compile

**Comment by twizmwazin** [comment]
You don't need an IDE to compile. Please refer to [this] (https://github.com/twizmwazin/CardinalPGM/wiki/Instalando-CardinalPGM) guide.

**Comment by RubeGamerV** [comment]
using last sportbukkit <a href="http://gyazo.com/74fdcb6491e514cb5629724b7a8c4bb4"><img src="http://i.gyazo.com/74fdcb6491e514cb5629724b7a8c4bb4.png" /></a>

**Comment by twizmwazin** [comment]
@RubeGamerV Please make a pastebin of the entire log, your screenshot isn't enough.

**Comment by RubeGamerV** [comment]
the server close automatically

**Comment by RubeGamerV** [comment]
This is all that i can see <a href="http://gyazo.com/88be7c62e4b136e2cc09a3538c2af67d"><img src="http://i.gyazo.com/88be7c62e4b136e2cc09a3538c2af67d.png" /></a>

**Comment by RubeGamerV** [comment]
i fix it, thanks 4 support!

**Comment by twizmwazin** [comment]
@RubeGamerV This issue doesn't appear to be related to Cardinal, rather the map it is attempting to load. What map are you trying to load, it is probably broken somehow. Also, please use `git clone [repo]` to get Cardinal's source rather than using the download zip button. It helps us debug.

**Comment by RubeGamerV** [comment]
But really i didnt know how compile the plugin

**Comment by twizmwazin** [comment]
https://github.com/twizmwazin/CardinalPGM/wiki/Instalando-CardinalPGM

**Comment by RubeGamerV** [comment]
i read it thanks!

**Comment by RubeGamerV** [comment]
so difficult to instal maven on windows

**Comment by RubeGamerV** [comment]
@twizmwazin i need a special lib from sk89q?

**Comment by dentmaged** [comment]
@RubeGamerV Maven automatically downloads dependencies

**Comment by CaptainElliott** [comment]
Use IntelliJ and enable auto import of maven dependencies
