### ISSUE TITLE
[SUG] Add admin icon prefix "❖" to op players

### ISSUE THREAD

**Issue by RubeGamerV** [twizmwazin/CardinalPGM#169]

**Comment by rywarsaw** [comment]
The issues section is for issues regarding CardinalPGM. This isn't a issue.

**Comment by twizmwazin** [comment]
We plan to implement a fairly robust rank system into Cardinal, thanks for the suggestion.

**Comment by RubeGamerV** [comment]
Thanks 4 reply

**Comment by CoWinkKeyDinkInc** [comment]
Does this plugin do exactly what Rube is asking for?

https://github.com/rmsy/Flair

**Comment by twizmwazin** [comment]
@CoWinkKeyDinkInc I'm not full sure, either way Cardinal will have it's own implementation.
