### ISSUE TITLE
You can only get water from an infinite source if you are OP.

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#170]
Video evidence: http://youtu.be/f0K9Jdlgf9g
Version: http://prntscr.com/64xb5s

**Comment by Rafitamolin** [comment]
If you aren't op, can you place blocks there? If not, it's an error of your XML file.

**Comment by MrTheSharpie** [comment]
I can place, but I can't break them after placing them.

**Comment by Rafitamolin** [comment]
Wow, that's strange then.

**Comment by MrTheSharpie** [comment]
And also it happens with XML from docs.oc.tc

**Comment by iEli2tyree011** [comment]
Can you go into your server.properties file and tell me what spawn-protection is set to?

**Comment by MrTheSharpie** [comment]
Oh lol that was the problem. Thank you
