### ISSUE TITLE
You can't see wool touches if you are observer

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#171]
Version: http://prntscr.com/64xb5s
Video evidence: http://youtu.be/3r_7tyHAGfw

This issue only happens on CTW.

**Comment by CaptainElliott** [comment]
THanks for reporting, will look into it

**Comment by MrTheSharpie** [comment]
You are welcome :)

**Comment by twizmwazin** [comment]
This is because of my new chat system, I'll fix this. I forgot to send messages to the obs channel.

**Comment by MrTheSharpie** [comment]
Okey. But it's not only chat, also scoreboard doesnt appear.

**Comment by CaptainElliott** [comment]
@twizmwazin the score board does not show the touched icon

**Comment by MrTheSharpie** [comment]
Thank you
