### ISSUE TITLE
/G doesn't work 

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#174]
It worked before the update to show touches http://prntscr.com/655ozt

**Comment by CaptainElliott** [comment]
We need to know the exact error, please past the error

**Comment by twizmwazin** [comment]
I'm working on revising the command and chat system, the issue will be addressed soon

**Comment by MrTheSharpie** [comment]
Okey. The exact error is something simmilar to "This command doesnt exist"

**Comment by elespawol** [comment]
Me happens the same, its says that that command doesn't exist..
El dia 14/02/2015 23.05, "Elliott" <notifications@github.com> va escriure:

**Comment by MrTheSharpie** [comment]
Thank you! Keep doing this work. Btw, i have made a tutorial to compile the plugin in spanish. Would you consider including it on the Spanish guide?

**Comment by twizmwazin** [comment]
Go ahead, add it
