### ISSUE TITLE
When you cycle too BoomBox it appears like you are on Race For Victory 2 

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#175]
On the server, appears that you are playing BoomBox and the XML is working fine, but appears like you are on RFV2 on the MotD and everything

**Comment by elespawol** [comment]
Me boombox works fine...
Its soo strange your error,.,.
El dia 15/02/2015 2.42, "Angel" <notifications@github.com> va escriure:

**Comment by twizmwazin** [comment]
I'm pretty sure you just put the XMLs in the wrong folders
