### ISSUE TITLE
/g does not working

### ISSUE THREAD

**Issue by Shipi1** [twizmwazin/CardinalPGM#178]
The command /g does not working in the update.

1.0-SNAPSHOT-git-CardinalPGM-624c987

**Comment by CaptainElliott** [comment]
Dupe https://github.com/twizmwazin/CardinalPGM/issues/174

Please check the issue tracker of already submitted issues before creating one please

**Comment by elespawol** [comment]
Please go to #144
There we are talking about that.
El dia 15/02/2015 16.49, "Shipi1" <notifications@github.com> va escriure:

**Comment by elespawol** [comment]
Nothing faillll
El dia 15/02/2015 16.50, "Elespawol GMail" <elespawol@gmail.com> va
escriure:

**Comment by Shipi1** [comment]
ok.
ty Elliot_
