### ISSUE TITLE
[SUG] Proximity

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#180]
Proximity is very important on CTW matches, mostly on the last tourney of OCN Proximity was a key of the win, I know it's very hard, but at least you can try your best, i know you can with this, i can help if you want too

**Comment by felipufeliu** [comment]
This place is for issues, please try to keep it only for that and not for suggestions.

**Comment by AngelCasillas01** [comment]
@felipufeliu

**Comment by AngelCasillas01** [comment]
So were i can post ideas for this plugin?

**Comment by felipufeliu** [comment]
Via skype or pm them in game, but actually the developers already had in mind to add proximity but I think they are going to do the most important stuff first and then this

**Comment by CaptainElliott** [comment]
Everything that is on the real PGM should get put on cardinal, no need to suggest them

**Comment by AngelCasillas01** [comment]
@CaptainElliott So actually this is in your to do lista. Fine!

**Comment by iEli2tyree011** [comment]
I'll work on this tomorrow.

**Comment by elespawol** [comment]
Nice
El dia 17/02/2015 5.44, "iEli2tyree011" <notifications@github.com> va
escriure:
