### ISSUE TITLE
/team alias doesn't work

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#182]
I think this has something to do with the chat and command fixes that you are doing. 
ERROR: http://prntscr.com/65y9sf
              http://prntscr.com/65y9yy

Version: http://prntscr.com/65ya5m

**Comment by CaptainElliott** [comment]
That command has been overridden by chat channels

**Comment by MrTheSharpie** [comment]
@CaptainElliott I supposed that

**Comment by CaptainElliott** [comment]
https://github.com/twizmwazin/CardinalPGM/pull/184

**Comment by MrTheSharpie** [comment]
@CaptainElliott Wow! That was fast! Thank you :)

**Comment by twizmwazin** [comment]
Closed by e6348aab668df92bdc42e8fb328c312ac389d1b4
