### ISSUE TITLE
Can enter to own wools, The latest version

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#183]

**Comment by twizmwazin** [comment]
We need more details

**Comment by elespawol** [comment]
Me happens the same
El dia 16/02/2015 20.51, "Kevin Phoenix" <notifications@github.com> va
escriure:

**Comment by ItzWid13** [comment]
I was playing an scrim and everyone can enter our own wool

**Comment by twizmwazin** [comment]
I need to know what map, and if you could have a pastebin to your XML, that would be helpful.

**Comment by CaptainElliott** [comment]
Its working fine for me

Tested on dynamo

**Comment by elespawol** [comment]
Wich map?
El dia 16/02/2015 20.52, "ItzWid13" <notifications@github.com> va escriure:

**Comment by ItzWid13** [comment]
On Dynamo,Deepwind Jungle, xml maps.oc.tc
before it works fine

**Comment by CaptainElliott** [comment]
was there any errors when this was happening?
and what is the result of `/cardinal -v`

**Comment by ItzWid13** [comment]
is the latest version of cardinal :cactus:

**Comment by ItzWid13** [comment]
Is my error sorry
