### ISSUE TITLE
/team force,alias,shuffle doesnt work.

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#186]

**Comment by twizmwazin** [comment]
This was fixed in e6348aab668df92bdc42e8fb328c312ac389d1b4. Please update

**Comment by ItzWid13** [comment]
Nope, Isnt working

**Comment by CaptainElliott** [comment]
@ItzWid13 make sure to re-clone this repo so it has the most up to date version

**Comment by ItzWid13** [comment]
i have to do /team alias [TEAM] [New]

**Comment by CaptainElliott** [comment]
yes
