### ISSUE TITLE
Don't show scoreboard in Dynamo and don't show  The Pick Up The Wool Message

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#187]
Latest version of cardinal.

**Comment by Vixo1** [comment]
Provide logs, it will be more easy to find why this happen, also check if is not your xml. (maps.oc.tc)

**Comment by ItzWid13** [comment]
The XML and the map are from maps.oc.tc

**Comment by CaptainElliott** [comment]
Can we see screenshots or a video of what you mean. AS Well as provide error logs if there is any

**Comment by TiTo-418** [comment]
http://imgur.com/VGATnfU
