### ISSUE TITLE
When you take the wool from the chest it appears the pick up message so much

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#188]
IOn CTW maps, if ypu take the wool from chests (If Possible) Appears so much the message heres an example:

AngelCasillas01 Picked up Blue Wool.  (Now you have take 1 wool, the thing is that the message appears when you take the wool, on wool spawners do not have this bug

**Comment by Alfalik** [comment]
Can you explain it better?

**Comment by dentmaged** [comment]
And what version are you running?

**Comment by TiTo-418** [comment]
Version: http://gyazo.com/40bcbb0225ceb4b2d806235105925f13
Video Evidence: http://youtu.be/NqhCAjF8ZXQ

**Comment by AngelCasillas01** [comment]
@TiTo-418 Thank You!

**Comment by iEli2tyree011** [comment]
I'll look into it, thanks

**Comment by AngelCasillas01** [comment]
Thanks for solve the bug!

**Comment by iEli2tyree011** [comment]
No problem, thanks for reporting :)
