### ISSUE TITLE
The scoreboard flashes when updated

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#190]
Video evidence: http://youtu.be/fFFy5AJ7gWc
Version: http://gyazo.com/ffd3c9268524cca7441b316421117a5d

**Comment by twizmwazin** [comment]
@TiTo-418 Please make the video unlisted, not private

**Comment by iEli2tyree011** [comment]
Have a solution to this, I'll try to fix it tomorrow.

**Comment by TiTo-418** [comment]
Ok, thanks. The video no is private, is hidden

**Comment by dentmaged** [comment]
@iEli2tyree011 Change the values of the scoreboard instead of creating a new scoreboard.

**Comment by twizmwazin** [comment]
@dentmaged This can cause issues as we are using the name portion of the scoreboard rather than the score section. The way scoreboards are intended to be used is to have static names and score counts. We reverse that.

**Comment by iEli2tyree011** [comment]
Can you let me know how this works?

**Comment by TiTo-418** [comment]
ok, give me a minutes
