### ISSUE TITLE
TNT Defuser in inventory whilst spectating

### ISSUE THREAD

**Issue by dentmaged** [twizmwazin/CardinalPGM#198]
In @CaptainElliott's pull request, he gave spectators TNT defusers...
Here is a screenshot: ![Bug](http://i.imgur.com/oBjIJMU.jpg)

**Comment by AngelCasillas01** [comment]
This is correct

**Comment by dentmaged** [comment]
Oh yes just noticed in the code, but why have this?

**Comment by CaptainElliott** [comment]
If you are OP you are able to defuse TNT in observers

**Comment by dentmaged** [comment]
@CaptainElliott Ohh I see! My mistake sorry! I'll close this issue.
