### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#199]
http://prntscr.com/66rqkw

**Comment by iEli2tyree011** [comment]
I'll look into it, thanks

**Comment by CaptainElliott** [comment]
@iEli2tyree011 https://travis-ci.org/twizmwazin/CardinalPGM#L653

**Comment by iEli2tyree011** [comment]
@CaptainElliott I know, I already fixed it, waiting for Twiz to make the 500th commit :stuck_out_tongue:

**Comment by CaptainElliott** [comment]
\o/

**Comment by iEli2tyree011** [comment]
Fixed in bf2970fff543c4853465db4dbc3a52f362f3dd4b
