### ISSUE TITLE
Snowflakes not have sound.

### ISSUE THREAD

**Issue by Shipi1** [twizmwazin/CardinalPGM#200]
Not have sounds :(

**Comment by elespawol** [comment]
Wut?? Snowflakes WTF
El dia 18/02/2015 19.57, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by Superjd10** [comment]
@elespawol Snowflakes = Raindrops.

**Comment by elespawol** [comment]
Fun.
El dia 19/02/2015 0.49, "José Daniel Durán" <notifications@github.com> va
escriure:
