### ISSUE TITLE
A touch message appear when the objective is completed

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#202]
Video: http://youtu.be/VvgVANqUVak
Cardinal Version: http://gyazo.com/f63e2a48cf132718da49d21f0830265b

**Comment by twizmwazin** [comment]
I'll look into this

**Comment by AngelCasillas01** [comment]
Please put "A touch message appear when the objective is completed" that title that you put is very confused :C

**Comment by TiTo-418** [comment]
And the obs cant view the touch message

**Comment by elespawol** [comment]
I think thats not a bug.
El dia 18/02/2015 21.17, "TiTo-418" <notifications@github.com> va escriure:

**Comment by AngelCasillas01** [comment]
I don't have the problem when you are join, otherwise the obs problem its true

**Comment by iEli2tyree011** [comment]
Fixed in 767ac10d0f7fe72047c1dc9dc2fa786ea01e5302
