### ISSUE TITLE
Completed objective's sound can only be heared from near 

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#204]
You can only hear the objective completed sound if you are near the core/monument/wool monument etc when they are completed.

**Comment by iEli2tyree011** [comment]
What sound are you referring to?

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 The sound when the match finish

**Comment by iEli2tyree011** [comment]
I don't recall there being a sound when the match ends

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 Well idk :c i thought he reffer to that

**Comment by Vixo1** [comment]
I think he reffers to the fireworks, so this is not a issue...

**Comment by CoWinkKeyDinkInc** [comment]
The wither sounds probably, I've heard that you can toggle them.

**Comment by D4n1e6656** [comment]
to Win: https://www.youtube.com/watch?v=-jTrmrlBW70
losing: https://www.youtube.com/watch?v=36F33OvX4Ss
to complete an objective: https://www.youtube.com/watch?v=sr4jOhkDxVA

**Comment by iEli2tyree011** [comment]
@D4n1e6656 Thank you for listing the sounds, didn't know what they were before :yum:

**Comment by SuHoney** [comment]
http://youtu.be/cvdXx1ukC6w

+Blitz sounds with fixed objective sounds

**Comment by MrTheSharpie** [comment]
@SuHoney Yep, I refered to that sounds. Thank you for clarifying.

**Comment by iEli2tyree011** [comment]
Fixed by 880b233b3ef84264ac895f9a390fe76ec4d6390f
