### ISSUE TITLE
Bold in death messages

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#213]
Hi, this error apparently is implemented with the arrival of /toggle, I see the death of all messages in bold, not just mine.
![2015-02-19_13 55 30](https://cloud.githubusercontent.com/assets/11080069/6274772/814b6df6-b83f-11e4-819f-6482b76d59ab.png)

**Comment by Alfalik** [comment]
It work on bold when you are in the event. Try to get 2 friends, then one of him kill the other. You will se it with normal characters. If not, is an error.
