### ISSUE TITLE
Too Many Scores in Blocks:RAGE

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#215]
Video: Later :c
Latest Version of Cardinal

**Comment by twizmwazin** [comment]
"Latest version" is absolutely useless
Neither Elly or I can figure out what you are talking about

**Comment by iEli2tyree011** [comment]
As @twizmwazin said, we need the output of /cardinal -v, not just "latest version" as the plugin is being constantly updated.  
Also, can you provide a description? And even if you can't get a video up, even just a screenshot of what you're referring to helps.
