### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#223]
The objetive complete sond id this: /playsound portal.travel TiTo_418 0 0 0 1 2 1

**Comment by Alfalik** [comment]
The objetive complete sound is already implemented with no errors, dont see the point of the issue.

**Comment by TiTo-418** [comment]
The sound that is implemented is not the same as in oc.tc
The correct is this: /playsound portal.travel @a 0 0 0 1 2 1

**Comment by Alfalik** [comment]
The sound that is used on Objetive Complete is the same as tm.oc.tc, no oc.tc

**Comment by TiTo-418** [comment]
Nope

**Comment by Superjd10** [comment]
They send the sound to each player, they don't need "@a" in the plugin AFAIK.

**Comment by Alfalik** [comment]
The sounds depends on the objetive and  on the team that you are.

**Comment by Jair07mx** [comment]
Tito-418 is right, should have the sound he is shared
