### ISSUE TITLE
Snowflakes don't have raindrop sound [Missing Feature/Bug]

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#225]
Hello! The raindrop/snowflake sound is /playsound random.levelup @a 0 0 0 1 1.5 1, please add in the plugin.

**Comment by iEli2tyree011** [comment]
It is in the plugin. Can you try /toggle sounds, make sure it is on, and try again?

**Comment by dentmaged** [comment]
Make sure you are using the most recent version of Cardinal.
