### ISSUE TITLE
[BUG] Server crash 

### ISSUE THREAD

**Issue by elespawol** [twizmwazin/CardinalPGM#229]
http://gyazo.com/7c503fbe85615c48655d4f84256e3cbe
This happened to me 3 times :s  
I think that there is a comflict with the world

**Comment by ParaPenguin** [comment]
Seems to me like somebody is storing a player reference in the plugin, without removing it when a player leaves. Naughty people, I'll see what I can do!

**Comment by elespawol** [comment]
I will test in a few hours.
Thanks 
U are the best ParaPenguin :)
