### ISSUE TITLE
[SUG] Add Report Command

### ISSUE THREAD

**Issue by Shipi1** [twizmwazin/CardinalPGM#232]
to report haha xD

**Comment by CaptainElliott** [comment]
Already done it. Needs to be debugged

**Comment by MasterEjay** [comment]
I don't see why Cardinal needs to have a punishment system, considering its just a scrimmage plugin. But if the devs feel the need to implement one, I suggest making a separate plugin to handle punishments, like OCN does.

**Comment by AngelCasillas01** [comment]
@MasterEjay If they do it, they will do from 0 and they will release Cardinal so late so...

**Comment by MasterEjay** [comment]
@AngelCasillas01 I'm not sure what that even means. "Do from 0"

**Comment by AngelCasillas01** [comment]
@MasterEjay Start from the bottom with anything, which will going too be along of time and this will upgrade the time which cardina will be release

**Comment by MasterEjay** [comment]
Not necessarily. The other plugin can be developed independently from Cardinal.

**Comment by dentmaged** [comment]
I agree with @MasterEjay. And aren't you a parapgm dev?

**Comment by MasterEjay** [comment]
Yes, this is correct.

**Comment by CaptainElliott** [comment]
I think me a @twizmwazin decided against this.
This can be closed :)

**Comment by dentmaged** [comment]
@CaptainElliott Your spelling...

**Comment by CaptainElliott** [comment]
@dentmaged what was wrong with it?

**Comment by iEli2tyree011** [comment]
We think it's best that we don't add a reports command, maybe in a separate additions plugin, but we don't think we should add it directly inside Cardinal.

**Comment by dentmaged** [comment]
@CaptainElliott "I think me a @.twizmwazin". You said "me a @.twizmwazin".

**Comment by twizmwazin** [comment]
@dentmaged Are you like Elliott's personal grammar police?
