### ISSUE TITLE
NPE on plugin start

### ISSUE THREAD

**Issue by elespawol** [twizmwazin/CardinalPGM#233]
http://pastebin.com/0nSizX9z

**Comment by Alfalik** [comment]
I got the same error, but you should just use Cardinal & WorldEdit in your \plugins folder.
http://pastebin.com/XWppJKtp

**Comment by elespawol** [comment]
UltraBans, add like /warn and others and its better
and 
NoPluginViewer because i dont want players see my plugins

**Comment by elespawol** [comment]
i am not renaming the plugins, i am hiding /plugins

**Comment by twizmwazin** [comment]
Please use appropriate names for issues, [URGENT] is not appropriate. In the future, please get Cardinal's source by using `git clone` rather than the download zip button. It makes debugging much easier for us.
