### ISSUE TITLE
UUIDs don´t working in authors/contributors

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#234]
Image: http://gyazo.com/8f4ef8bc0fe96f1f75b8bdb7154af3fb
XML (same as maps.oc.tc): http://pastebin.com/nVAPkuLE

**Comment by twizmwazin** [comment]
Should be fixed with f33bce55a6686a8fb2593716fb2b187bb5642f1c.

**Comment by Alfalik** [comment]
Isn´t fixed. Evidence & version: http://gyazo.com/6cee64044d02a4736042ede43418d833

**Comment by twizmwazin** [comment]
Should be fixed with f371b162c8d82b9b393ad74e6dbe1d02dedd224d

**Comment by Alfalik** [comment]
The commit just get authors, not contributors.

Image & version. http://gyazo.com/1dabd9aa17967238962b1807d8ddf168

**Comment by twizmwazin** [comment]
oopsies

**Comment by twizmwazin** [comment]
@Alfalik Now it *should* work

**Comment by Alfalik** [comment]
@twizmwazin Yep, it works. Thanks.
