### ISSUE TITLE
Errors when auto-creating database & demographics

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#235]
Cardinal generate the folder <code>Cardinal/</code> just with config.yml, it don´t create database.xml & demographics.xml, need to reload server with spammed errors. After a few minutes the server crashes.

Video proof: http://youtu.be/OxrnpnY5y8U
Log: http://pastebin.com/P42A2dUX
Crash-report: http://pastebin.com/jY0TxkxM
Version:http://gyazo.com/08dee8e92b24ce8502efbbdccac0f9bb

**Comment by twizmwazin** [comment]
Can someone else on Windows try to reproduce this?

**Comment by ElFlambMC** [comment]
Yes the same

**Comment by twizmwazin** [comment]
It must be a windows file system related issue. I'll set up a VM and look into it.
