### ISSUE TITLE
You can not join with the hat

### ISSUE THREAD

**Issue by RuboTutoGamer** [twizmwazin/CardinalPGM#240]
You can not get to a computer using the hat must use the commands

**Comment by dentmaged** [comment]
What version are you using? And please provide a video

**Comment by RuboTutoGamer** [comment]
Last version https://www.youtube.com/watch?v=LdGik5yjWL8&feature=youtu.be

**Comment by dentmaged** [comment]
Any errors in the console? That is a weird bug though.

**Comment by RuboTutoGamer** [comment]
There isn't any error in the console

**Comment by dentmaged** [comment]
Weird. So you can pick up the hat and put it in your inventory?

**Comment by D4n1e6656** [comment]
The server does again , also helped me

**Comment by javipepe** [comment]
That happened to me yesterday (with the PlayerInteractEvent instead, meaning that the hat did not even open up for me). Today, with the latest version, I'm not getting it anymore.

And I also guess you should have had something in the console like <code>[INFO] Could not pass InventoryClickEvent to Cardinal</code> by the looks of it.

**Comment by AngelCasillas01** [comment]
@javipepe this only happens when the plugin is o spanish :S

**Comment by Jair07mx** [comment]
Indeed, only happens in Spanish
