### ISSUE TITLE
Snowflakes not given when players touch and complete wools

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#241]
Can you do that when you take a wool give snowflakes? and placed

**Comment by SuHoney** [comment]
+ When match ends
+ When damaged objectives

**Comment by AngelCasillas01** [comment]
@twizmwazin wools only?

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 You can't put the plugin for all objectives? like cores, monuments, etc... also, for winning a match, and for being loyal for your team, ETC..

**Comment by iEli2tyree011** [comment]
That's the plan..

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 so why the title says "Snowflakes not given when players touch and complete wools"? people will think that will be only for wools and will come with same question and spamming your repository ;)

**Comment by dentmaged** [comment]
@AngelCasillas01 yeah, maybe "Snowflakes not given when players touch and complete objectives".

**Comment by AngelCasillas01** [comment]
@dentmaged  maybe when your team wns too

**Comment by felipufeliu** [comment]
@AngelCasillas01 Because it's like that because it says what bug is going to be fixed, not a thing saying what they are going to add.

**Comment by dentmaged** [comment]
I believe that this has been added.

**Comment by iEli2tyree011** [comment]
@dentmaged It hasn't. We will close this issue when it has been completely added.

**Comment by dentmaged** [comment]
@iEli2tyree011 Sorry. Has it only been added for wools?

**Comment by Jonmuxu** [comment]
yes but when you complet the objective, the cardinal not give the snowflakes

**Comment by dentmaged** [comment]
@Jonmuxu That will be added in soon.

**Comment by TiTo-418** [comment]
Snowflakes given when players touch and complete wools in the last version

**Comment by iEli2tyree011** [comment]
@TiTo-418 This hasn't been closed because we have not completely added the feature, as stated above, I will close it when it is complete (likely tonight).

**Comment by TiTo-418** [comment]
Snowflakes given when players touch and complete objetives, when your team won, when you are loyal to to your team in the last version

**Comment by dentmaged** [comment]
@TiTo-418 I don't think it has been added for monuments. Correct me if I'm wrong.

**Comment by TiTo-418** [comment]
@dentmaged gyazo.com/c43dbe89f955558107932dd81bb6fe0e
