### ISSUE TITLE
Spawn point issue

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#242]
now with the new update now the respawn point is buggy, you respawn a few blocks but not exactly
the XML FlLE is good i dont change anything

**Comment by Alfalik** [comment]
Map? Version? Video? Screenshots? XML? Please, be more specific.

**Comment by Jonmuxu** [comment]
its on all the maps of my server look the video the version is the new updates 25 min ago : https://www.youtube.com/watch?v=EdZF-DoU9kA&feature=youtu.be

**Comment by Jonmuxu** [comment]
sorry im new on github xD

**Comment by twizmwazin** [comment]
@Jonmuxu Your video is private, please make it unlisted.

**Comment by dentmaged** [comment]
@twizmwazin He's done it

**Comment by Vixo1** [comment]
Happens again with last commit (60580c6)

**Comment by iEli2tyree011** [comment]
@Vixo1 Can you give a bit more detail on the issue that you're getting?

**Comment by Vixo1** [comment]
@iEli2tyree011 Here's a video: https://youtu.be/iaCAdBJDWHs. There's no console error

**Comment by TiTo-418** [comment]
@Vixo1 Try with this xml: https://maps.oc.tc/Other/Tournament/Guardians%20of%20the%20Wool/Deepwind%20Jungle/map.xml

**Comment by felipufeliu** [comment]
@Vixo1 This is not a plugin error, it's a map error.
That map I think you downloaded it from my team server, which has it broken because is not the original version, it's just a remade of the original map, maybe that's why you don't appear in where you should

**Comment by Vixo1** [comment]
@felipufeliu I remade it for me following a minersmovies recording and the xml from the map

**Comment by iEli2tyree011** [comment]
@Vixo1 Can you make sure that the wool rooms are aligned properly? That will tell if the map is offset or not.

**Comment by Vixo1** [comment]
@iEli2tyree011 Was that, my error, sorry
