### ISSUE TITLE
Motd Modification

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#243]
Can you add a new option in motd like : Map motd = on/off Custom Motd= On/OFF

i have the overcast network motd exactly but i cant put because the map motd replace D:

**Comment by felipufeliu** [comment]
I think developers are not going to add that to prevent the abuse of the plugin by turning the motd off and added whatever they want there.

**Comment by AngelCasillas01** [comment]
There is a plugin called motd manager for that use

**Comment by RubeGamerV** [comment]
@AngelCasillas01 Pero no funciona aun asi, el Cardinal tiene como un Overrride MOTD algo asi
