### ISSUE TITLE
Pink and magenta wool squares shouldn't be both ChatColor.LIGHT_PURPLE

### ISSUE THREAD

**Issue by javipepe** [twizmwazin/CardinalPGM#244]
On Cardinal:
<img src="http://i.imgur.com/pjAzKD3.png">

On OCN: 
<img src="http://i.imgur.com/JhADa42.png">

Pink should use ChatColor.RED, while purple is still LIGHT_PURPLE

**Comment by Alfalik** [comment]
You can make a PR, isn´t difficult.

**Comment by twizmwazin** [comment]
@Alfalik Not everyone has technical skills.

**Comment by javipepe** [comment]
Wasn't at home, will do later @Alfalik

**Comment by javipepe** [comment]
@twizmwzin Don't worry, I'll do it later
