### ISSUE TITLE
[SUG] Proximity on/off

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#245]
Let's say that often the server is much laguea by the proximity scoreboards, I want to suggest some line in "config.yml" to disable it.

**Comment by twizmwazin** [comment]
The toggle should be in the XML. Proximity should not create any significant lag.

**Comment by Alfalik** [comment]
The proximity appear when you set a time-limit to the match, or a <code> <time> </code> line in the XML file.

**Comment by Jair07mx** [comment]
http://i.imgur.com/ADdDMY3.png This?

**Comment by Jair07mx** [comment]
I think they're not understanding me, to what I meant by proximity is ...http://i.imgur.com/QtXQd24.png

**Comment by Alfalik** [comment]
@Jair07mx I know what is Proximity.

**Comment by Jair07mx** [comment]
@Alfalik I can not find how to disable it, you can help me find for example Dynamo?

**Comment by Alfalik** [comment]
@Jair07mx It can´t be disabled until developers finish Proximity & Time-limit features.
