### ISSUE TITLE
it doesn't show the disconnect message when you have toggle joinmessage on

### ISSUE THREAD

**Issue by felipufeliu** [twizmwazin/CardinalPGM#246]
http://gyazo.com/b23a69678a68d8cf84acbf927bf66765

**Comment by iEli2tyree011** [comment]
Can you paste your logs?

**Comment by felipufeliu** [comment]
@iEli2tyree011 http://pastebin.com/2KB1yQgv

**Comment by iEli2tyree011** [comment]
That's a different error, which likely caused issues in later ones. Is this on Airship Aces?

**Comment by Alfalik** [comment]
Yes, we was testing it. The error is when you got kicked from the server for fly, the leave/join message doesn´t appear.

**Comment by dentmaged** [comment]
@felipufeliu @Alfalik So the title should be "No disconnect message on player kick despite with join messages enabled" or something like that.
