### ISSUE TITLE
[Missing Feature] Ranks with Flair/Asterisk

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#247]
Optio: &a*
Centurion: &6*
Dux: &5*

Internet Famous: &1*

Administrator: &6❖
Moderator: &c❖
Senior Moderator: &4❖

Event Coordinator: &3❖

Winner: &f*

**Comment by twizmwazin** [comment]
Some of these will be implemented, however not all. I plan on having Mod, Admin, and Dev be ranks.

**Comment by AngelCasillas01** [comment]
You forget Ref, Livestreamer and other .... 
@Edit Ref: §3❖

**Comment by Jair07mx** [comment]
You could add all with no use, but would be great to have them all

**Comment by Superjd10** [comment]
You don't need any "premium package" in a scrimmage server tho

**Comment by twizmwazin** [comment]
I will consider Ref, but that would be about it.

**Comment by AngelCasillas01** [comment]
@twizmwazin Livestreamer too? Official?

**Comment by twizmwazin** [comment]
@AngelCasillas01 Why do we need a livestreamer rank? What would an official be?

**Comment by ElFlambMC** [comment]
@twizmwazin Livestreamer for livestream matches

**Comment by twizmwazin** [comment]
@ElFlambMC Who livestreams scrims? And if they do, why do they need a badge to do it?

**Comment by SungMatt** [comment]
@twizmwazin Instead maybe add a config file to add these prefixes/flairs? I don't see the need for these extra flairs but if some people want it for the looks, maybe add a config file to add flair types and have a /flair command to assign it?

**Comment by ElFlambMC** [comment]
@twizmwazin Pl0x can you make that for all guys

**Comment by twizmwazin** [comment]
@SungMatt @ElFlambMC Make a PR if you want it that badly.

**Comment by ElFlambMC** [comment]
@twizmwazin idk how make it.

**Comment by twizmwazin** [comment]
@ElFlambMC It isn't hard to learn

**Comment by MrTheSharpie** [comment]
I think that OP and ref would be enough. Not dux or optio, I don't see it useful. Nor developer cause except twiz, elliot, ely and a few more there are not developers so I would consider that if a person says that he is a developer, he is, in some way, taking your job...

**Comment by ElFlambMC** [comment]
@mrthesharpie :)

**Comment by twizmwazin** [comment]
@MrTheSharpie The developer rank would be hard-coded in. This means that developers would have the rank on all servers, and you wouldn't be able to just give someone the rank.

**Comment by MrTheSharpie** [comment]
@twizmwazin Okey, that's fine :)

**Comment by dentmaged** [comment]
@twizmwazin Will it be contributors or people who have done 20+ commits?

**Comment by twizmwazin** [comment]
A person will be considered a developer if their contributions were in some way significantly transformative.

**Comment by dentmaged** [comment]
@twizmwazin how would you implement this? Using Player.setPlayerListName?

**Comment by twizmwazin** [comment]
Sounds like it could work. We'd have to add it in chat too.

**Comment by SungMatt** [comment]
public void playerJoin(PlayerJoinEvent e) {
                Player p = e.getPlayer();
                String pname = p.getName();
    if (p.hasPermission("flair.SeniorModerator")) {
                        String member = "" + ChatColor.DARK_RED +  "❖" + ChatColor.RESET + pname + ChatColor.RESET + "";
                        p.setDisplayName(member);


Something like this?

**Comment by twizmwazin** [comment]
@SungMatt Probably. I'd have to test how it interacts with teams and the like.

**Comment by iEli2tyree011** [comment]
@twizmwazin If that's the case, we can always convert to either getName or getDisplayName depending on the situation.

**Comment by CaptainElliott** [comment]
@twizmwazin Depending on how you are setting the team color of a player, setting their flair when they join may be override by the new display name, containing the colour being set. Either way it should be easy to do, I will do permissions later today if I have time

**Comment by twizmwazin** [comment]
@CaptainElliott player.setDisplayName(flair + player.getDisplayName) should avoid the overriding issue.

**Comment by CaptainElliott** [comment]
@twizmwazin Yes, that would be done when the player joins, however when they join a team their display name will then be set to just their name, overriding the flair. However as I said that's an easy fix

**Comment by twizmwazin** [comment]
@CaptainElliott oh yeah, oops

**Comment by dentmaged** [comment]
@CaptainElliott ```ChatColor.DARK_RED +  "❖" + TeamUtils.getTeamByPlayer(player) + player.getName() + ChatColor.RESET;```

**Comment by twizmwazin** [comment]
@dentmaged You wouldn't use "❖," you would use the Unicode char.

**Comment by dentmaged** [comment]
@twizmwazin okay, could I make a PR and start work on this?

**Comment by Jonmuxu** [comment]
if a player has dux, centurion or option, can you edit the snowflakes multiplier?

**Comment by dentmaged** [comment]
@Jonmuxu Donor ranks won't be added, as stated earlier.

**Comment by Jonmuxu** [comment]
D:

**Comment by Jair07mx** [comment]
+    private final String opFlair = ChatColor.GOLD + "❖";
+    private final String modFlair = ChatColor.RED + "❖";
+    private final String devFlair = ChatColor.DARK_PURPLE + "❖";

Thanks :3

**Comment by twizmwazin** [comment]
@Jair07mx Not sure what you are trying to say. Additionally, it isn't proper to directly copy the symbol, rather Unicode codes should be used.
