### ISSUE TITLE
Problems in Effects

### ISSUE THREAD

**Issue by D4n1e6656** [twizmwazin/CardinalPGM#248]
to appear not get effects that gives you the map.
Version: http://gyazo.com/66db23a5cc3abf71f27da52c6bad22c3

**Comment by iEli2tyree011** [comment]
Can you give at least a few details? Map? Server information? Any previous errors?

**Comment by Alfalik** [comment]
The console don´t give errors, the plugin just don´t give the effect or when it does, it last a few seconds.

**Comment by D4n1e6656** [comment]
This only happens with the effects of infinite durability
https://www.youtube.com/watch?v=3ud04mnQOoc&feature=youtu.be

**Comment by SuHoney** [comment]
+ BoomBox too.

**Comment by Alfalik** [comment]
Now it don´t give the effects (Just on the infinity effects). Theres an example on BoomBox, I didn´t have saturation, resistance & slow digging.

Video proof: http://youtu.be/1QIigC9LliA
Cardinal Version: http://gyazo.com/6565465a3807ad99a031c6dad3d151cc
