### ISSUE TITLE
Wools position dont accept decimals

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#252]
http://gyazo.com/faa858faf7b8f5ef0852456b5fcff2cb
You cant place the wool

**Comment by Oxinous** [comment]
You are talking about a specific map, not a plugin error. You can get the correct one from maps.oc.tc

**Comment by TiTo-418** [comment]
Hablas español, asi que:
https://maps.oc.tc/CTW/Standard/Cloud%20Nine/map.xml
De ahi tome la foto, las posiciones de las lanas estan con decimales, pero el plugin no las reconoce cuando las pones :P
