### ISSUE TITLE
The enemy objective complete don't sound correctly

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#253]
The enemy objetive complete sound: portal.travel 0.7 2

The correct: mob.blaze.death 0.8 0.8

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/227

**Comment by TiTo-418** [comment]
Duplicate?

**Comment by Superjd10** [comment]
@TiTo-418 Duplicate of #227. Interesting because you were the one who mentioned it :smile:

**Comment by TiTo-418** [comment]
This issue is for "general" sounds no for specific sounds ;)

**Comment by twizmwazin** [comment]
@TiTo-418 Let us know of the correct sound in that issue, where we are keeping track of all sounds.

**Comment by TiTo-418** [comment]
Ok, thanks for your work :)
