### ISSUE TITLE
The server cras

### ISSUE THREAD

**Issue by RuboTutoGamer** [twizmwazin/CardinalPGM#254]
in the latest versions of the plugin, the server frequently cras

**Comment by twizmwazin** [comment]
This provides absolutely no information to help us fix the issue. When you can provide information, open a new issue.

**Comment by SungMatt** [comment]
Saying that the server crashes isn't enough, can you provide the crash log that comes in your /logs folder?

Just saying it crashes is like saying the car isn't working without seeing that the tyre is out of the car.
