### ISSUE TITLE
The server crash 

### ISSUE THREAD

**Issue by RuboTutoGamer** [twizmwazin/CardinalPGM#255]
in the latest versions of the plugin, the server frequently crash.
Crash-report folder: https://www.mediafire.com/?bgp902txu2wb69w

**Comment by TiTo-418** [comment]
/cardinal -v
The lastest version no say nothing, the plugin is in constant update

**Comment by twizmwazin** [comment]
This isn't related to Cardinal it appears, the issue occurs when saving the worlds. Contact your hosing provider for assistance.
