### ISSUE TITLE
Download for SportBukkit 1.8?, Cant iniciate server.

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#256]

**Comment by iEli2tyree011** [comment]
You can find the latest build of Sportbukkit 1.8 on https://repo.oc.tc/.

**Comment by ItzWid13** [comment]
it doesnt appear

**Comment by twizmwazin** [comment]
https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/sportbukkit-1.8-R0.1-20150222.073527-11.jar

**Comment by SungMatt** [comment]
Here's the latest

https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/sportbukkit-1.8-R0.1-20150228.112444-12.jar

**Comment by AaronGamerYT12** [comment]
Link Sportbukkit 1.8.7? repo.oc.tc link broken

**Comment by Pablete1234** [comment]
You will have to compile it yourself, there is no public download for sportbukkit 1.8 right now, as the old repo is down and the new one doesn't contain the old builds
