### ISSUE TITLE
KoTH not yet implemented

### ISSUE THREAD

**Issue by RubeVi** [twizmwazin/CardinalPGM#265]
https://www.youtube.com/watch?v=-adxkxTajXk

**Comment by SungMatt** [comment]
Calm down, CardinalPGM is still under heavy development. Have you seen his blog? He says its 75% done, and not fully done. Give him and the devs a while.

**Comment by ItzWid13** [comment]
This VIdeo Is In Private, Put it in Unlisted

**Comment by RubeVi** [comment]
06/05/2015, 1.0 are not realesed yet

**Comment by iEli2tyree011** [comment]
That's why it's not closed. Please stop informing us that a feature is incomplete, we know it is incomplete and we work on them accordingly.

**Comment by dentmaged** [comment]
Just a note, KOTH is just control points but they award points instead. Maybe the Hill module should just extend the control point module (still needs to be implemented) and award points to the controlling team.

**Comment by Pablete1234** [comment]
yeah, all koth, ctf and scoreboxes use the same score

**Comment by CaptainElliott** [comment]
it's not to do with using the 'same score'. KOTH as @dentmaged said is exactly the same as control points, however simply has different presets and a slightly different syntax

**Comment by Pablete1234** [comment]
docs.oc.tc: "KotH maps use control points to define hills. Instead of <control-points> they are called <hills> and must be defined inside a main <king> element. The main difference between hills and control points is what their default values are."

**Comment by CaptainElliott** [comment]
@Pablete1234 isn't that what I just said?
>KOTH as @dentmaged said is exactly the same as control points
> however simply has *different presets* and a slightly different syntax

**Comment by Pablete1234** [comment]
@CaptainElliott i just wanted to quote it, don't kill me for it plz

**Comment by Pablete1234** [comment]
Finally, 413 days later, it's done
