### ISSUE TITLE
Wrong message when warn someone

### ISSUE THREAD

**Issue by RubeGamerV** [twizmwazin/CardinalPGM#266]
http://gyazo.com/ee66160110987fc5e2d6cc1104c54d92

*Console kicked {user} for {reason} ---> {Staff} {punish} {user} for {reason}

Example: twizmwazin warn Apple for don´t blow up your own teammates
this message only can see users with access to /a

**Comment by ItzWid13** [comment]
This VIdeo Is In Private

**Comment by Alfalik** [comment]
You cant make a PR if you want to change it

**Comment by CaptainElliott** [comment]
My bad forgot to test that command 🙈
