### ISSUE TITLE
Error when a player do /join and it´s already on a team

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#274]
Video proof & Cardinal version: http://youtu.be/9YL5KAH6RO0
Correct message: http://youtu.be/ahTj6a222Ak

**Comment by CaptainElliott** [comment]
Huh, thought I fixed his, turns out it was just in a PR https://github.com/twizmwazin/CardinalPGM/pull/149
https://github.com/CaptainElliott/CardinalPGM/commit/b3df8cace6e9a50c04b9e063d4e134e3c38970cf
