### ISSUE TITLE
Potions duration filter in <item> should be on ticks, not seconds

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#277]
Heres an example taked from NextGen. The "1600" is the time that the potion-effect will last, now in seconds it´s wrong, because it have a duration of 26:40 Minutes (the correct is 1:20 for the three effects). If you take the "1600" like ticks, it will be the same as said "80" seconds, that is the same as 1:20, the correct effect-duration.
For those who don´t know 20 ticks = 1 second.

```<item damage="8226" potions="speed:1600:0:false;jump:1600:1:false;fast digging:1600:2:false">potion</item>```

**Comment by iEli2tyree011** [comment]
ty
