### ISSUE TITLE
Can´t setnext using the complete name of the map

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#278]
Video proof: http://youtu.be/AyZHw3hpGjg
Cardinal version: http://gyazo.com/018ae4554e1dece7c718ad1c183035b6

**Comment by AngelCasillas01** [comment]
For meworks but like /sn boomte

**Comment by Alfalik** [comment]
You have 3 maps:

+ Map1
+ Map2
+ Map3

If you execute the command "/sn M", the next map is set to Map3, not Map1 how it's supposed to be. Change the priority to A-Z, not Z-A.

**Comment by Vixo1** [comment]
Happens again with the last commit. (12ac90c)

**Comment by SungMatt** [comment]
It works without spaces though, like /setnext GoldenDroughtIII when the map is named "Golden Drought III"
