### ISSUE TITLE
[SUG]Add "》" to punishment messages

### ISSUE THREAD

**Issue by SuHoney** [twizmwazin/CardinalPGM#279]
^^

**Comment by felipufeliu** [comment]
I'm not a official developer of cardinal, but I am adding it :P, don't worry 

http://gyazo.com/fe6b1b404d5c3b57edada16cdae96d9e

(I know the picture is broken, I haven't finished yet)

**Comment by SuHoney** [comment]
Oh, I forgot to close this thread :V
