### ISSUE TITLE
Void filters can be bypassed at Y level 0

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#282]
The Cardinal Version is the new updated 13 hours ago , i dont remember in video put /cardinal -v D: video: https://www.youtube.com/watch?v=PZGSRS1naaE&feature=youtu.be

**Comment by TiTo-418** [comment]
OMG que puto genio!

**Comment by iEli2tyree011** [comment]
Thanks for reporting

**Comment by TiTo-418** [comment]
Isnt fixed

**Comment by twizmwazin** [comment]
Reopening as the issue is currently present.

**Comment by dentmaged** [comment]
@twizmwazin Isn't this like the void bug where you start building at the bottom of the map, and build upwards? I'll try to find it

**Comment by twizmwazin** [comment]
@dentmaged You have correctly read the title.
