### ISSUE TITLE
Legacy Filters not working 

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#288]
the wool and the cobwebs are not breakable in the wool room regions.

**Comment by twizmwazin** [comment]
Please provide what map this is on.

**Comment by kroest** [comment]
it was on deepwind jungle,

 filter name="allow-some" parents="deny-all">
        allow>
            block>glass</block>
            block>fence</block>
            block damage="9">wool</block>
            block damage="13">wool</block>
            block damage="10">wool</block>
            block damage="4">wool</block>
        /allow>
    /filter>

**Comment by MrTheSharpie** [comment]
Yes, this also happened to me recently. I was going to post it here when I had time, but now kroest did it.

**Comment by TiTo-418** [comment]
Es el XML el que esta mal, no el plugins. (The xml is bad, no the plugin)

**Comment by kroest** [comment]
i use the exact same xml from the maps.oc.tc, http://pastebin.com/xtvLQbXU

**Comment by dentmaged** [comment]
I have noticed this on almost the whole of Twisted. It's to do with the void.

**Comment by TiTo-418** [comment]
The void is defined by the xml, no by the plugin :v

**Comment by CaptainElliott** [comment]
The reason the filter is not working is because referencing a filter inside a filter is not working

**Comment by CaptainElliott** [comment]
Right now a quick fix for server owners would be to convert from the legacy filters to the standard ones, to do this do the following:

- Rename the `<allow>` tag to `<any>`
- Remove the `parents="deny-all"` attribute

That should fix the error on your side while we fix it for the plugin

**Comment by kroest** [comment]
yes, i use an older version of the xml, and its running fine now. the xml from maps.oc.tc was a bit broken i guess. thanks for your help.

**Comment by CaptainElliott** [comment]
This is still an issue we need to fix
