### ISSUE TITLE
Double Snowflakes given for killing a player in Blitz

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#289]
New Cardinal Version updated 19 Hours Ago Video:https://www.youtube.com/watch?v=jKq0LiU0D_U&feature=youtu.be

**Comment by TiTo-418** [comment]
This is in Blitz, you kill the player in a team and the player in obs

**Comment by twizmwazin** [comment]
We had a similar issue to this where death messages were displayed twice, so I'm assuming it is related to that.
