### ISSUE TITLE
When you log out in a match started and re-enter, you are dead

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#290]
Video: http://youtu.be/BpLFIVWDiaY
Version: http://gyazo.com/bd730c5af171ea088e1e6a61ab76564f

**Comment by CaptainElliott** [comment]
This is a bug we know of but so far we cannot see what causes it

**Comment by twizmwazin** [comment]
It is related to PlayerUtils.resetPlayer(player) I *think*.

**Comment by TiTo-418** [comment]
This is happening again

**Comment by dentmaged** [comment]
Isn't this to do with kill on disconnect feature? I can't remember the module name.

**Comment by iEli2tyree011** [comment]
@dentmaged It's called the ItemDrop module. It doesn't actually kill the player though, it just drops their items on the ground.

**Comment by Pablete1234** [comment]
maybe what kills the player is not the drop item module, it's the teams module (when you /join obs you get killed)

**Comment by twizmwazin** [comment]
The item drop module never actually affects the player, it just copies their items and dumps them on the ground.

**Comment by dentmaged** [comment]
@iEli2tyree011 @twizmwazin I see. My mistake. Thanks for telling me!

**Comment by twizmwazin** [comment]
I'll take a look at this tomarrow
