### ISSUE TITLE
Mod permissions not working.

### ISSUE THREAD

**Issue by javipepe** [twizmwazin/CardinalPGM#293]
<a href="http://youtu.be/DX9JV9Kvxp0">Video (includes /cardinal -v)</a>

Thanks for your time :)

**Comment by twizmwazin** [comment]
@javipepe For future reference, when you use the `Download ZIP` button on GitHub, `/cardinal -v` is pointless, as the version is `git-unknown`. By cloning the source using git, it gives the most recent commit hash, which is the information we are looking for.

**Comment by AngelCasillas01** [comment]
@javipepe This is the pogram he is asking for it "http://git-scm.com/" you should download, it's like a cmd plataform, you should use this command, go to your desktop (Example) and then, type git clone https://github.com/twizmwazin/CardinalPGM, and then use cd CardinalPGM and then mvn clean install

**Comment by CaptainElliott** [comment]
The player needs to re-log after being modded

**Comment by twizmwazin** [comment]
I'm going to try and see if I can reload the player's permissions automatically.

**Comment by CaptainElliott** [comment]
I guess you could reload them on the command @twizmwazin

**Comment by RubeGamerV** [comment]
@CaptainElliott  Relog don´t work

**Comment by CaptainElliott** [comment]
hmm pretty sure it was working before @iEli2tyree011, are you sure it was working when you made changes to it?

**Comment by RubeGamerV** [comment]
@CaptainElliott are you talking with iEli2tyree011?

**Comment by CaptainElliott** [comment]
yeah

**Comment by iEli2tyree011** [comment]
@CaptainElliott I didn't change any of the actual mechanics, besides updating their name without having to relog.

**Comment by RubeGamerV** [comment]
@iEli2tyree011 the prefix "❖" only update, but the permissions no

**Comment by CaptainElliott** [comment]
if @twizmwazin is not working on this, I will fix it

**Comment by twizmwazin** [comment]
@CaptainElliott Go ahead and fix this, I never got it working fully.

**Comment by CaptainElliott** [comment]
@twizmwazin heads up, when I created the permissions module I created ab enable and disable permissions method. Useful for automatically updating permissions andfor when I  implemented the mute command

**Comment by RubeGamerV** [comment]
@CaptainElliott soo, what that mean?
