### ISSUE TITLE
You can't open "Coming Soon" book

### ISSUE THREAD

**Issue by G61** [twizmwazin/CardinalPGM#295]
Well, is empty but in the future versions there will be text so...

**Comment by CaptainElliott** [comment]
There is currently no text in the book so it does not open

**Comment by TiTo-418** [comment]
Maybe can you edit on Database?

**Comment by CaptainElliott** [comment]
Not to sure what you mean @TiTo-418

**Comment by TiTo-418** [comment]
Sorry, no in database, in config.yml
Maybe the developers con put this:
![image](https://cloud.githubusercontent.com/assets/11008016/6422373/883b0072-beb6-11e4-9f6e-ccc2b05b8482.png)

**Comment by dentmaged** [comment]
I'll work on this tomorrow.

**Comment by twizmwazin** [comment]
@dentmaged You'll probably want to message me on skype before you get too far with that.

**Comment by dentmaged** [comment]
@CaptainElliott twizmwazin doesn't think the book should be customisable, do you agree?

**Comment by CaptainElliott** [comment]
@dentmaged I do not know twiz's intentions with it but I would have though it would be a book with things the developers would like to add for players to read or whatever

**Comment by dentmaged** [comment]
@CaptainElliott I think the players should customise it but I'll make it language based. :(

**Comment by twizmwazin** [comment]
Ok, so I just figured out why no one has been able to get the book to open: the PlayerInteractEvent was being cancelled. I'll fix this tomorrow morning.

**Comment by dentmaged** [comment]
@twizmwazin Ohhhh, so that is why the book never opened even with pages!
