### ISSUE TITLE
Custom MOTD don´t work

### ISSUE THREAD

**Issue by RubeGamerV** [twizmwazin/CardinalPGM#298]

**Comment by CaptainElliott** [comment]
Could you give us a description of what is happening?

**Comment by SungMatt** [comment]
@CaptainElliott He's probably using a custom MOTD plugin, which is probably incompatible.

**Comment by SungMatt** [comment]
Pretty sure CardinalPGM isn't supposed to work with those, as Cardinal makes its own MOTD too.

However, you might be able to try renaming your MOTD .jar file to start with an A, as bukkit loads plugins alphabetically.

**Comment by iEli2tyree011** [comment]
You can disable the custom motd in the config.yml.
