### ISSUE TITLE
Autorotation is not working

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#309]
When a match has finished don't autorotation the map, and don't start automatically, which yes in SporkPGM

Sorry for my English, but I don't want to use a translator

**Comment by Alfalik** [comment]
The plugin is made for Team Scrimmages, not for Public Servers.

**Comment by TiTo-418** [comment]
Duplicate #296 
"I'm going to close this, if we do add it, this will be very low priority and disabled by default."
Español: "Voy a cerrar esto, en el caso de que lo hagamos, va a ser de muy baja prioridad y desactivado por defeto"
