### ISSUE TITLE
executing /start after countdown will push the countdown to 1

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#317]
When you /start with, let's say 20 seconds, and before it finishes you /start again with any other amount of seconds it starts the match as if you had put /start 0.

**Comment by dentmaged** [comment]
Version? I'll look into this.

**Comment by eudaldca** [comment]
1.0-snapshot-git-CardinalPGM-9169286
Sorry, forgot about that.

**Comment by dentmaged** [comment]
@eudaldca It is intended, as you can see here: https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/command/StartAndEndCommand.java#L30
If you want to, I'll try to work on a toggle for this.

**Comment by eudaldca** [comment]
I would appreciate it, as my team-mates tend to exactly this.

**Comment by CaptainElliott** [comment]
@dentmaged it is not intended for the countdown to jump strait to 1

**Comment by dentmaged** [comment]
@CaptainElliott oh, my mistake, I noticed it on my server but I though nothing of it
