### ISSUE TITLE
Entering a scorebox ends the game

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#318]
When you enter a scorebox, regardless if the map has <limit>-1</limit>, it ends the match.
Version 1.0-snapshot-git-CardinalPGM-9169286

**Comment by iEli2tyree011** [comment]
What do you mean by the map having "-1"?

**Comment by eudaldca** [comment]
Having the score limit on -1, a no score limit. https://docs.oc.tc/modules/gamemode_tdm

**Comment by dentmaged** [comment]
@Eudaldca Which map is it on?

**Comment by Eudaldca** [comment]
Facility.

**Comment by dentmaged** [comment]
@Eudaldca Try changing it to 0, but I'm working on a fix now. ;)

**Comment by CaptainElliott** [comment]
why change it to 0? 
The point of declaring -1 is to have no score limit

**Comment by Eudaldca** [comment]
Either way, setting it to 0 fixes it. Maybe it recognises -1 as +1?

**Comment by dentmaged** [comment]
@CaptainElliott that is how the plugin was made, I'm trying to fix it though

**Comment by CaptainElliott** [comment]
@dentmaged just off of the top of my head, you could set the score to `Interger.POSITIVE_INFINITY`

**Comment by dentmaged** [comment]
@CaptainElliott Won't you also have to remove the ----- MAX ----- on the scoreboard?

**Comment by twizmwazin** [comment]
I'm pretty sure that will fix the issue, if it doesn't let me know.

**Comment by Eudaldca** [comment]
@twizmwazin Nope, still ends the game on facility with score limit -1, (I just compiled).

**Comment by twizmwazin** [comment]
@Eudaldca Which version?

**Comment by Eudaldca** [comment]
@twizmwazin http://prntscr.com/6cc9t1

**Comment by twizmwazin** [comment]
@Eudaldca What version of facility?

**Comment by Eudaldca** [comment]
@twizmwazin The one on maps.oc.tc/TDM/standard/facility

**Comment by twizmwazin** [comment]
Ok, so I can't seem to replicate this. Can anyone else?

**Comment by AngelCasillas01** [comment]
@twizmwazin I dont have this problem on my server, tomorrow more details srry :(
