### ISSUE TITLE
Please Could You Do This To The 1.7.x? pls

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#326]

**Comment by twizmwazin** [comment]
There isn't an easy way to implement the plugin on two Minecraft versions at the same time with SportBukkit. Development is focused on 1.8 and 1.8 features. There is no reason to support old versions of Minecraft anyway.

**Comment by iJorGeZz** [comment]
[This](https://github.com/iJorGeZz/CardinalPGM/tree/protocol-compatibility) may result helpful for you.

**Comment by AngelCasillas01** [comment]
@iJorGeZz i think that he is askingor a 1.7.2 build and maybe hewill ask about the new TAB function

**Comment by dentmaged** [comment]
I'm going to work on this either when a completed version is available or update the code every Sunday (or maybe every 3 days)

**Comment by dentmaged** [comment]
@twizmwazin I'm requesting for this to be opened, as later next week, I plan to work on this feature. I'll message you on Skype on how I believe it should be implemented.

**Comment by twizmwazin** [comment]
I haven't checked Skype in months and have no plans on doing so. You cab reach me on Telegram, however. 1.7 + latest compatibility is planned for Cardinal 2, using custom bukkit+craftbukkit forks and cradle subprojects, albeit very slowly.
