### ISSUE TITLE
I can't see the touch of the opposing team

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#328]
CTW, DTC, etc ...
This doesn't happen in oc.tc

**Comment by AngelCasillas01** [comment]
Are you telling that you can't see it as obs?

**Comment by Jair07mx** [comment]
Within a match

**Comment by Superjd10** [comment]
You are not supossed to see the touches of the enemy team. On OCN tourneys you are not able to see them

**Comment by Jair07mx** [comment]
In tournaments you can not, but in scrimmages yes, a setting?

**Comment by iEli2tyree011** [comment]
@Jair07mx Scrimmages are mock tournament matches, which our plugin is trying to replicate..

**Comment by Jair07mx** [comment]
in tm I've seen that you can see the touch, can add an option?

**Comment by MrTheSharpie** [comment]
You can't see the touch even in regular games

**Comment by twizmwazin** [comment]
This is intended.
