### ISSUE TITLE
Custom tab not implemented

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#329]

**Comment by CaptainElliott** [comment]
It is on the todo list, I am still figuring out how to send the player tab slot packets to the client in 1.8.
Should not be too hard to do

**Comment by TiTo-418** [comment]
Implemented in the lastest version: 
<a href="http://imgur.com/BHvBgVu"><img src="http://i.imgur.com/BHvBgVu.png" title="source: imgur.com" /></a>

**Comment by dentmaged** [comment]
@TiTo-418 He means the tab list where players are ordered into teams.

**Comment by MrTheSharpie** [comment]
@dentmaged Yeah, that list.

**Comment by Carlos934** [comment]
When will be added?

**Comment by TiTo-418** [comment]
@Carlos934 Be patient

**Comment by Carlos934** [comment]
@TiTo-418 hype!! :P

**Comment by twizmwazin** [comment]
A custom tab is really low on our priority list, gameplay elements come first. On felipe's server last night, I really like how the tab looked with just the default 1.8 tab. This will not be implemented by Friday.

**Comment by TiTi-418** [comment]
<a href="http://imgur.com/c33QIYq"><img src="http://i.imgur.com/c33QIYq.png" title="source: imgur.com" /></a>

**Comment by Aaron1011** [comment]
For reference, here's the skin used to display the gray box: http://textures.minecraft.net/texture/847b527998465154ad6c238a1e3c2dd3e32965352e3a64f36e16a9405ab8. It has a gray face, and is used as the skin for empty slots, and player counts (e.g. **19/32 Blue**).

Also, I've put the signature and (base64 encoded) texture object in a pastebin (both are required to be sent to the client): http://pastebin.com/4ugRhfF3

**Comment by dentmaged** [comment]
Usernames can only be 16 characters long (as I'm sure you know) so we could have only 16 slots unless if we use ```§r              ``` and ```§r§r            ```. I'm not sure if that would work though.

**Comment by Aaron1011** [comment]
@dentmaged: A display name can be set in the tab list packet, which only affects how the name is displayed in the tab list.

**Comment by dentmaged** [comment]
@Aaron1011 But won't the client crash if there are multiple display names?

**Comment by Aaron1011** [comment]
@dentmaged: I'm really not sure what you mean...

Each tab list entry has a GameProfile and an optional display name. What do you mean by multiple display names?

**Comment by dentmaged** [comment]
@Aaron1011 You can't have multiple display names in the player list.

**Comment by Aaron1011** [comment]
@dentmaged: Take a look here: http://wiki.vg/Protocol#Player_List_Item

When the 'Add Player' action is specified, a display name can optionally specified, along with the GameProfile.

**Comment by dentmaged** [comment]
@Aaron1011 I'm not talking about that, I'm talking about the player list.

**Comment by Aaron1011** [comment]
@dentmaged: What player list are you referring to?

**Comment by Pablete1234** [comment]
@Aaron1011 do you know how the skin and signature were obtained?

if you enter : 
https://sessionserver.mojang.com/session/minecraft/profile/uuid 
it will give the skin, but not the signature, if i put an "?unsigned=false" at the end of the link, i get both skin and signature, but the skin (if you base 64 decode it) contains a "signature:required":"true", that the one you sent doesn't have

**Comment by Aaron1011** [comment]
@Pablete1234: Sorry, I can't remember exactly what I did to get it. I think I might have extracted it from the client...

**Comment by Pablete1234** [comment]
@Aaron1011 nevermind, i found the way to get it, it's really likely that you got it from the client, has cubist's old name and his uuid

**Comment by dentmaged** [comment]
@Pablete1234 Can't you use ```Player#getSkin();```

**Comment by Pablete1234** [comment]
@dentmaged i need a skin data, and a signature.
if you get the player's game profile you can get the texture property
```for (Property property : ((CraftPlayer)player).getHandle().getProfile()..getProperties().get("textures"))```
and there you just post on the log property.getValue and property.getSignature

**Comment by xFracTV** [comment]
Is fixed no?
