### ISSUE TITLE
Timed Fuses do not work (yet!)

### ISSUE THREAD

**Issue by SungMatt** [twizmwazin/CardinalPGM#332]
In Dust, with the 

    <tnt>
        <instantignite>on</instantignite>
        <fuse>1s</fuse>
    </tnt>

tags, there is instant ignition, but time in fuse is still vanilla (4 seconds).

Also, if <fuse> is edited to just a raw value `<fuse>10</fuse>` it still does not work as intended. 

This should be able to be edited in 

CardinalPGM/src/main/java/in/twizmwaz/cardinal/module/modules/tnt/Tnt.java

.

**Comment by CaptainElliott** [comment]
Defining fuse on its own works fine for me.

**Comment by twizmwazin** [comment]
@CaptainElliott I'm pretty sure you were setting the fuse when it explodes rather than ignites.
