### ISSUE TITLE
When TNT is not ingnited by the user (by the XML) theres no damage or destruction on blocks

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#333]
The TNT explode but  dosen't make damge on acceptable regions (tested on wit's end using the exact XML of GotW)

**Comment by iEli2tyree011** [comment]
Brainstorming a few things, I think I have a good solution

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 Nice, if you want i can record you a test when i get home

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 Nice now is working well👍
