### ISSUE TITLE
When you pick up a wool, proximity dosent update anymore

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#335]
Only update if you put a save wool on the floor :( tested on Golden Drought III [TE]

**Comment by twizmwazin** [comment]
@AngelCasillas01 Not sure what you mean. When does it work and when does it not?

**Comment by AngelCasillas01** [comment]
@twizmwazin okey,  Before you touch a wool proximity is working very well, but after you touch proximity dosent update until you put a wool save on the floor

**Comment by twizmwazin** [comment]
@AngelCasillas01 I believe that is intentional.
