### ISSUE TITLE
Proximity in wools shouldn't update constantly

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#337]
As you can see in this video, <a href="https://www.youtube.com/watch?v=4WpQNaLj5Ck">click me</a>, when your team have no-touchs, the proximity stays as Infinity until the plugin track a death, and update the scoreboard with the number of blocks that you are off the wool room. 

Edit: This is how it should be.
Edit 2: Check this video. <a href="https://www.youtube.com/watch?v=KRXkd9nswuI">click me</a>

Cardinal version: http://gyazo.com/2956d132c2a04e9f1a249eebf11d0461

**Comment by TiTo-418** [comment]
Overcast Network - Guardians of the Wool - Team Fishy vs. Cocoa Beans?

**Comment by Alfalik** [comment]
@TiTo-418 You can see how proximity works in that video.

**Comment by TiTo-418** [comment]
Ok

**Comment by Jair07mx** [comment]
I had said that proximity was wrong, but all ignored me
