### ISSUE TITLE
Incorrect stats

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#339]
Totally incorrect K/D. People may have noticed, but just pointing out...
http://i.imgur.com/ng8Gume.png
Version: http://prntscr.com/6crwrn

**Comment by SungMatt** [comment]
There's another one where if you get 5 deaths and 1 kill, it displays as 0 instead of 0.20 . I suspect it's because of the type of variable it is set as, probably an integer.

**Comment by CaptainElliott** [comment]
Just curious, was there any error logs?

**Comment by Eudaldca** [comment]
Nope

**Comment by CaptainElliott** [comment]
Could you please try testing it out now using the latest version?
https://github.com/twizmwazin/CardinalPGM/commit/de7a2f4fe92ad9845e8d05f5688e618619b7dc6d

**Comment by Eudaldca** [comment]
@CaptainElliott Not a single error indeed!

**Comment by CaptainElliott** [comment]
So it is working fine? 

Also, are the team statistics working?

**Comment by Eudaldca** [comment]
Yeah, they are working fine. Team stats count for all the teams: For example, in a test run I killed a player once, and ended, and in the team stats appeared 1 kill 1 death. Is it intended to be for all the teams or only for your team?

**Comment by CaptainElliott** [comment]
It should show who got the most kills on the team and who got the most deaths on a team, is that still an issue?

**Comment by Eudaldca** [comment]
I think it works fine, tomorrow I'll check it.

**Comment by CaptainElliott** [comment]
Stats should be fixed and working
