### ISSUE TITLE
Blockdrops droping XP Orbs when destroyed by TNT

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#341]
Firstly, the Quartz Blocks should not be destroyed, check modules ```<not>``` ```<all>```   ```<any>```, probably there is the problem.
Second, check #276, isnt fixed and its related with this Issue (Video proof: http://youtu.be/GEjta2WhdT4)

Video proof: http://youtu.be/wveQHg3mRtU
Cardinal version: http://gyazo.com/8871e01c6304f1bb3c635ff759ad1adc

**Comment by twizmwazin** [comment]
I don't know why, but I find this a bit amusing. Thanks for reporting.
