### ISSUE TITLE
Sign GUI is still displayed when placing signs at max build height

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#342]
When placing a sign, like any other block, at the max build height for a map, the placement is cancelled. However, with a sign, the sign editor GUI is still displayed.

This can give a player the false impression that the sign was actually placed, leading to them entering text which will be discarded.

Steps to reproduce

1. Place any block at the maximum build height for a map.

2. Attempt to place a sign on top of said block.

3. Observe that the sign edit GUI is displayed.

**Comment by CaptainElliott** [comment]
I Clive this is a client side issue and an OCN issue, I don't think there is anything we can do about it. Unless there is an openInventory or GUI  event

**Comment by TiTo-418** [comment]
@mrapple: This isn't a client side issue.

The <a href="http:/http://wiki.vg/Protocol#Sign_Editor_Open"> Sign Editor Open </a> packet is sent from the server to trigger the sign editor GUI (This allows plugins to do things like open a sign GUI to edit an already placed sign. It's also why the GUI doesn't open when, for example, placing a sign as a (Overcase-style) spectator).

Fixing this requires suppressing the packet when the event is cancelled.

**Comment by SungMatt** [comment]
Pretty sure this happens on Overcast, so do the doors and Pistons.

**Comment by TiTo-418** [comment]
If this is solved, Cardianl is better than original PGM :D

**Comment by elespawol** [comment]
Obiously tito 😉
El dia 06/03/2015 18.52, "TiTo-418" <notifications@github.com> va escriure:

**Comment by twizmwazin** [comment]
This would be easier to patch in SportBukkit than the plugin, so I'm going to do that I think.

**Comment by TiTo-418** [comment]
OMG, 06/03/2015 CARDINALPGM IS BETTER THAN ORIGINAL-PGM!
