### ISSUE TITLE
Missing Feature | Mods-Admins Tools

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#343]
You can see here the Tools: 
An oc.tc video: http://goo.gl/zQbmPP

**Comment by CaptainElliott** [comment]
This is not an OCN a feature it is using an external mod called the macro mod. Besides I don't think we need moderation tools as it is just a scrim plugin

**Comment by ItzWid13** [comment]
Where can i get it?

**Comment by Superjd10** [comment]
@ItzWid13 That's a client side mod called the Macro Mod, https://oc.tc/forums/topics/5252e0e8af7fb04ce6001ec9
