### ISSUE TITLE
No way to see stats BEFORE or DURING a match

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#344]

**Comment by iEli2tyree011** [comment]
I'm going to work in adjusting the statistics tracking system later tonight.

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 👍

**Comment by iEli2tyree011** [comment]
Fixed in f4db34b5f0ea968dfcf679a7687703af61aa9a49

**Comment by AngelCasillas01** [comment]
@iEli2tyree011  Maybe more confortable close the issue with the commit?
