### ISSUE TITLE
Time day/night should not cycle until the match start

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#346]
Cardinal version: http://gyazo.com/d4222a6e0daeda120916903468aac456

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 now the time is broken, for example on RFV2 it's day and dosen't cycle (Compiled 30 mins ago and can't share version while i'm not on the pc sorry)

**Comment by twizmwazin** [comment]
@AngelCasillas01 fixed

**Comment by AngelCasillas01** [comment]
@twizmwazin oh thanks
