### ISSUE TITLE
Not filter does not look for multiple filters and allow-world filter not working correctly 

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#351]
Tnt cannot break gold blocks in the monument of BoomTE, but it can break wool blocks. You can also break the beacon without tnt. I'm using the XML in oc.tc/maps, version 47ef91f.
Log: https://drive.google.com/file/d/0BykQBsE8G63LLVA4d2lQRVdZVE0/view?usp=sharing
(Log was too long to pastebin it)

**Comment by CaptainElliott** [comment]
The error log you gave seems to be another issue

**Comment by Eudaldca** [comment]
Well, I gave the log just in case.

**Comment by CaptainElliott** [comment]
This seems to be a problem with the filters that needs to be fixed
Going to look into it

**Comment by TiTo-418** [comment]
The endstone cuboid can't be broken on Ender Blast

**Comment by elespawol** [comment]
Me happens the same with BoomTE and Boom (normal)
El dia 24/03/2015 15.45, "TiTo-418" <notifications@github.com> va escriure:

**Comment by CaptainElliott** [comment]
i've fixed the not filter but I'm not sure how to fix the `allow-world` filter
not sure if its an issue with the filter itself or the any filter
