### ISSUE TITLE
Tournament scoring system

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#355]
It's on PGM and Referees used for know who is winning,

**Comment by RubeGamerV** [comment]
@twizmwazin Refs only can see the proximity and score, and they will not have ban, warn or kick permissions

**Comment by AngelCasillas01** [comment]
@twizmwazin  this will need some new module?

**Comment by iEli2tyree011** [comment]
@AngelCasillas01  Not a new module, no.

**Comment by AngelCasillas01** [comment]
@iEli2tyree011  How?

**Comment by iEli2tyree011** [comment]
@AngelCasillas01 It's a command, not a module.

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 But it's not only a command, when  a match finish, before the winning team message appears, appear how many points, touches, etc... But you know about that, do how you think, i'm just saying how i think is it

**Comment by dentmaged** [comment]
Probably edit the 'MatchModule'.

**Comment by TiTo-418** [comment]
Hey! The team winning shoud be at the top of the scoreboard
