### ISSUE TITLE
Three missing features.

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#359]
1.- I do not know exactly how this works, but in the video the Kyetho team wins by default, I imagine that event coordinators did something https://www.youtube.com/watch?v=4QsITCYvqc0&t=381

2.- In this video the leader type /ready and starts the countdown https://www.youtube.com/watch?v=UiNR1n80H1Q&t=498

3.- On this video he type /subbed and the player which has been replaced has been kicked https://www.youtube.com/watch?v=UiNR1n80H1Q&t=564

**Comment by CaptainElliott** [comment]
The sub command is pretty old and is not really needed. `/ready` is already implemented

**Comment by twizmwazin** [comment]
1 is completely irrelevant in Cardinal, 2 is implemented, 3 just use /kick
