### ISSUE TITLE
Hi i got a question related to CardinalPGM

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#360]
How can i do for example a Lobby and then the maps. Like in oc.tc that have a lobby and the maps

**Comment by iEli2tyree011** [comment]
This is a scrimmage plugin, it's goal is not to allow you to recreate OCN.

**Comment by ItzWid13** [comment]
Its a question could you answer me?

**Comment by iEli2tyree011** [comment]
@ItzWid13 I answered you.

**Comment by AngelCasillas01** [comment]
@ItzWid13 It's a home created plugin that dosen't have any relation to the PGM

**Comment by CoWinkKeyDinkInc** [comment]
I think the plugin [https://github.com/SpigotMC/BungeeCord](BungeeCord) is what you may be looking for.  It allows easy transport between servers/worlds.

**Comment by twizmwazin** [comment]
@CoWinkKeyDinkInc Way to take the hint
