### ISSUE TITLE
It has since added autocycle, why not autostart?

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#362]
Function useful for some people, I ask you to consider, in the same manner automatically disabled.

**Comment by twizmwazin** [comment]
This feature is extremely low priority, it is not needed for scrimmage plugins.

**Comment by dentmaged** [comment]
We also have /ready, which will auto start the match once the teams are ready.

**Comment by Jair07mx** [comment]
Yeah, are useful things, basically missing features

**Comment by Superjd10** [comment]
@Jair07mx Having /ready starting the match is enough, autostart isn't needed, therefor autostart isn't a missing feature.
