### ISSUE TITLE
Missing Feature, add /tb (temp ban)

### ISSUE THREAD

**Issue by RubeGamerV** [twizmwazin/CardinalPGM#365]

**Comment by CaptainElliott** [comment]
To do this we would need to track punishments in an external database, this would take a lot more effort than it's worth, and it is something that is not needed for a scrim plugin

**Comment by iEli2tyree011** [comment]
@CaptainElliott It's definitely possible, but as you said, unnecessary.

**Comment by twizmwazin** [comment]
I'm pretty sure we've been over this before.
