### ISSUE TITLE
Ban message issue

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#371]
<a href="http://imgur.com/8sk75gQ"><img src="http://i.imgur.com/8sk75gQ.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/4TtCmVV"><img src="http://i.imgur.com/4TtCmVV.png" title="source: imgur.com" /></a>

All OK, but when you try to join...

<a href="http://imgur.com/LFcaHEb"><img src="http://i.imgur.com/LFcaHEb.png" title="source: imgur.com" /></a>

**Comment by CaptainElliott** [comment]
To achieve this we would need to store the ban reason in a database. Although I already did this on another branch I believe we decided against it

**Comment by TiTo-418** [comment]
Why you can only edit the ban reason?

**Comment by CaptainElliott** [comment]
The ban reason would be different for every player so we cannot globally edit it

**Comment by TiTo-418** [comment]
In the banned-players.json the ban reasons are differents for every players
<IMG SRC="http://i.gyazo.com/54e0927b844ce8def2b12177066fed22.png">

**Comment by twizmwazin** [comment]
@CaptainElliott Perhaps it is possible to set a player's ban reason using color codes in the banned-players.json.

**Comment by CaptainElliott** [comment]
I was unaware of this as I have not had much experience developing with 1.8 versions. I will look into it.

**Comment by twizmwazin** [comment]
@CaptainElliott [BanList](http://twizmwaz.in/docs/sportbukkit/org/bukkit/BanList.html) and [BanEntry](http://twizmwaz.in/docs/sportbukkit/org/bukkit/BanEntry.html) might be useful classes.

**Comment by dentmaged** [comment]
@twizmwazin Can't you use §?

**Comment by CaptainElliott** [comment]
@dentmaged if the api does not support color. then I would use the character ''', much like what OCN uses for XML and then translate the color code with ChatColor api

**Comment by TiTo-418** [comment]
<b>§</b>?

**Comment by TiTo-418** [comment]
<a href="http://imgur.com/iQxHaZD"><img src="http://i.imgur.com/iQxHaZD.png" title="source: imgur.com" /></a>

:P

**Comment by TiTo-418** [comment]
I would like more to go:
You are banned from this server!
Reason: test
by TiTo_418

This is too much repetitive

**Comment by twizmwazin** [comment]
@CaptainElliott Perhaps you shouldn't use the exact same message. Maybe there is a way to set the ban disconnect message. If there isn't just display the reason.

**Comment by CaptainElliott** [comment]
Ban connect message should be a bit more tidy

**Comment by AngelCasillas01** [comment]
Need to reopen this.

When disconnect from server apears well (Permantly ban >> Test)
But entering again to the server, (Appears like vanilla message and the reason appears the way should be, ex.)(Vanilla messages; Reason: Permantly Ban>> Teste)

[Cardinal Version](https://github.com/twizmwazin/CardinalPGM/commit/acd3b4ca9b4609913c07319c1ab2afa23313b415)

**Comment by CaptainElliott** [comment]
Although this is small I am going  to fix it
