### ISSUE TITLE
Incorrect format: Ban, Kick and Warn.

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#376]
Example of the correct way: http://i.imgur.com/TCj2K72.png

Other example of the correct way: http://prntscr.com/6fki2a

**Comment by CaptainElliott** [comment]
I'll tidy them up even more shortly

**Comment by AngelCasillas01** [comment]
@CaptainElliott This feature will include the localization right or it comes automatically?

**Comment by CaptainElliott** [comment]
I will add localization for the global part of the ban message, however it is impossible to do it for ht message

**Comment by AngelCasillas01** [comment]
@CaptainElliott Seems that you need to add it automatically is that right?
