### ISSUE TITLE
Deepwind jungle issue

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#382]
video: https://www.youtube.com/watch?v=FY6iFAdF10c&feature=youtu.be
Cardinal -v: CardialPGM version 1.0-SNAPSHOT-git-CardinalPGM-1840ed2

**Comment by CaptainElliott** [comment]
This is an issue with rectangular regions, they should be infinite in all y directions

**Comment by CaptainElliott** [comment]
Still an issue

**Comment by GChevy** [comment]
Rfv2 has The same issue

**Comment by TiTo-418** [comment]
Try to update the XML (maps.oc.tc)

**Comment by CaptainElliott** [comment]
Does rfv2 use a rectangle region for the playable area? It could be a bug with negative regions

**Comment by TiTo-418** [comment]
Deepwing jungle XML: https://maps.oc.tc/CTW/Standard/Deepwind%20Jungle/map.xml
Race for victory 2 XML: https://maps.oc.tc/CTW/Standard/Race%20for%20Victory%202/map.xml
