### ISSUE TITLE
Manually ending a game doesn't execute logic to determine a winner

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#383]

**Comment by iEli2tyree011** [comment]
/end will only have a team win if specified as an argument.

**Comment by CaptainElliott** [comment]
Ending with /timelimit should use the win logic

He said that it did not

**Comment by Alfalik** [comment]
Check #397

**Comment by iEli2tyree011** [comment]
Closing, as setting the time limit *does* execute the logic for this. #397 will be fixed soon and #394 will also be fixed.
