### ISSUE TITLE
Deepwind jungle issue continous... :(

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#384]
video: https://www.youtube.com/watch?v=89la1b24Eps&feature=youtu.be
Cardinal -v: CardinalPGM version 1.0-SNAPSHOT-git-CardinalPGM-c90b2d0

i don't know if it is only on Deepwind jungle... but it contunous...  :(

**Comment by CaptainElliott** [comment]
Please just reopen the on you already have

**Comment by TiTo-418** [comment]
If one Collaborator closed the issue, he cant re-open it

**Comment by CaptainElliott** [comment]
Oh I did not realise, my applogies
