### ISSUE TITLE
please add an modertor rank

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#385]
i would love it if you culd implement an moderator rank, so the one with moderator rank would be able to end, cycle and set next a map, but wont be able to stop, op, ban, kick, or deop people. this would be so nice for scrimmage servers since the issue is usually once you give someone op, next week everyone will have op all of a sudden, and that can be a real pain.

**Comment by elespawol** [comment]
Its alredy implemeted
Use /mod user
El dia 13/03/2015 11.30, "kroest" <notifications@github.com> va escriure:
