### ISSUE TITLE
CTF not yet implemented

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#386]
i would like to see CTF implemented in the plugin, and since i didnt see it in the issue list, i decided to make one, since there is one for koth to.

**Comment by SuHoney** [comment]
KotH is planned for the 1.0 release of Cardinal.

**Comment by SungMatt** [comment]
I'm not sure if CTF is going to be in the 1.0 release of Cardinal, as it is a very new gamemode to overcast itself.

**Comment by SungMatt** [comment]
@SuHoney He is referring to CTF.

**Comment by kroest** [comment]
i just would like to see the feature implemented eventually, especially since i think there is a fairly big chance the next, or the tournament after the next tournament will include ctf.

**Comment by SungMatt** [comment]
The [map repo for CTF](https://maps.oc.tc/CTF/Standard/) doesn't seem decently sized now, and all the maps in it are ones made around a year ago or more, so it might take a while longer than the next tourney.

**Comment by elespawol** [comment]
Ctf is actually in.BETA in oc.tc please keep calm.
El dia 13/03/2015 13.07, "SungMatt" <notifications@github.com> va escriure:

**Comment by twizmwazin** [comment]
This will be implemented eventually, however we have other features higher on our list right now.

**Comment by CaptainElliott** [comment]
CTF is not a fully released gamemode, it is still in alpha, it mechanics and xml syntax could change. There is no need to have it in Cardinal as of now
