### ISSUE TITLE
/cancel doesn't work against /recycle and /cycle

### ISSUE THREAD

**Issue by SungMatt** [twizmwazin/CardinalPGM#387]
In Cardinal version c90b2d0 , (Latest build as of now) /cancel does not work against /recycle and /cycle. 
![screen shot 2015-03-13 at 9 08 53 pm](https://cloud.githubusercontent.com/assets/6725727/6638935/b15c3b28-c9c5-11e4-98c1-1f8948b66366.png)

**Comment by SungMatt** [comment]
Another pic:
![screen shot 2015-03-13 at 9 12 27 pm](https://cloud.githubusercontent.com/assets/6725727/6638943/cfc2131c-c9c5-11e4-93c8-416cfa7d0a0d.png)

**Comment by twizmwazin** [comment]
Appears to be fixed in my testing

**Comment by SungMatt** [comment]
Fixed in 4ed7f33, thanks!

**Comment by elespawol** [comment]
👏👏👏👏👏👏
El dia 19/03/2015 4.40, "SungMatt" <notifications@github.com> va escriure:
