### ISSUE TITLE
time always setted to day, even when the map should be played at time set to x

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#389]
the plugin sets the time to day, while some maps should be played at night. i think this got caused by the fix of the daynightcycle while the game didnt start yet.

**Comment by twizmwazin** [comment]
Double check that the map is saved at night time. To my knowledge, OCN doesn't have a way of configuring the game time in the XML.

**Comment by kroest** [comment]
all the maps are properly loaded with nighttime,
but the plugin just sets the time to daytime somehow, didnt have this with earlier version of cardinal.

**Comment by twizmwazin** [comment]
@kroest Take a copy of the map, and load it on a server with no mods (No Cardinal, no SportBukkit, just vanilla Minecraft) and see what time of day it is.

**Comment by TiTo-418** [comment]
Or load it on singleplayer...

**Comment by SungMatt** [comment]
@TiTo-418 Same thing, Singleplayer runs a server that only you can join.

**Comment by kroest** [comment]
ill upload a video with the proof soon, one moment.
