### ISSUE TITLE
Cycling to the same map fails

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#393]
Log: http://pastebin.com/BVG2UfCV
Version: aab1385
Line, 56, "World X is a duplicate of another world and has been prevented from loading."

**Comment by iEli2tyree011** [comment]
Can you try it again just to make sure?

**Comment by Eudaldca** [comment]
Ok, I deleted uid.dat from the ring race in the maps folder, and worked just fine. It is the presence of this file that causes the error.
