### ISSUE TITLE
Time limit dont cancel/update the countdown, just send the messages

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#394]
I don´t really know if the title is the actual issue, but heres a video.
Video proof & version: http://youtu.be/FttWabOQpSM

**Comment by Alfalik** [comment]
Still happen
Video proof & version: http://youtu.be/A-dchWDduaU

**Comment by Alfalik** [comment]
If the match is running the time should be added, for example, if the player took 5 seconds after the match started to do /timelimit 30s, the match will last 35s. Now, Cardinal just set the limit, doesnt add it.
If the match is waiting, it just should set the time limit.

+ TM video example: http://youtu.be/qGSFnY_0N6s
+ Cardinal video: http://youtu.be/txhSACDhe6I
+ Cardinal version 4ed7f33: http://gyazo.com/9734333fe6a4537750e749e69bdcb55d

**Comment by SungMatt** [comment]
Can we make it such that there can be a /`timelimit set <time>` and `/timelimit add <time>` to keep these 2 different?

**Comment by iEli2tyree011** [comment]
@SungMatt That sounds good, I'll try and work on it tonight.

**Comment by dentmaged** [comment]
@iEli2tyree011 Should I do it?

**Comment by iEli2tyree011** [comment]
@dentmaged If you want, sure. Right now I'm overhauling the scoreboard, but I should be done soon.
