### ISSUE TITLE
NBT attributes

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#398]
Leaving an example that dont work ```<item slot="0" damage="-3000" attributes="generic.attackDamage:add:7">diamond pickaxe</item> ```

Reference: https://docs.oc.tc/reference/attributes
Cardinal version c0ac303499: http://gyazo.com/0a1131ad0705919aeedaa7f11b2df809

**Comment by Aaron1011** [comment]
Resolved in https://github.com/twizmwazin/CardinalPGM/commit/6ed1a60a16b6245c99a6372a43da8a0405de01c4

**Comment by twizmwazin** [comment]
Added in 6ed1a60a16b6245c99a6372a43da8a0405de01c4
