### ISSUE TITLE
[Sug] (hard...)

### ISSUE THREAD

**Issue by Jonmuxu** [twizmwazin/CardinalPGM#399]
i dont know if it is a great idea or a difficult work, but, if you can make a lobby in which you can enter match, would be proud

**Comment by G61** [comment]
This is a scrimmage plugin, you don't need that.

**Comment by Jonmuxu** [comment]
yeah but its a good idea to order all teams in a same lobby

**Comment by dentmaged** [comment]
Some people are forgetting that this isn't a mock if Overcast's PGM (for public matches) plugin.
