### ISSUE TITLE
Proto tag is not implemented

### ISSUE THREAD

**Issue by Aaron1011** [twizmwazin/CardinalPGM#401]
According to the Overcast XML documentation, the map element is required to contain the attribute `proto`, which specifies the PGM version the map was created for.

Source: https://docs.oc.tc/modules/main

**Comment by CaptainElliott** [comment]
I don't think we want to support this, this would mean support **every** version of PGM and having different syntax and mechanics for each proto

**Comment by Aaron1011** [comment]
I don't think we have to support different behaviors for different versions. It could be something as simple as printing a warning if a greater version number is used.

**Comment by CaptainElliott** [comment]
That is not the point of the protocol

**Comment by twizmwazin** [comment]
@Aaron1011 I'll consider implementing a warning when we fully support the latest protocol.
