### ISSUE TITLE
Version for Cardinal [SportBukkit]

### ISSUE THREAD

**Issue by GChevy** [twizmwazin/CardinalPGM#404]
What version do i use for do the plugin work

**Comment by Vixo1** [comment]
Last version of Cardinal and 1.8 version of Sportbukkit

**Comment by GChevy** [comment]
I've download it but it does not work

**Comment by CoWinkKeyDinkInc** [comment]
You need to compile both of them to work.

**Comment by twizmwazin** [comment]
@GChevy What does "does not work" mean? We need logs

**Comment by GChevy** [comment]
http://prntscr.com/6hoyp6 http://prntscr.com/6hoz3h Any cardinal command works

**Comment by Alfalik** [comment]
@GChevy And the rotation.txt?

**Comment by twizmwazin** [comment]
@GChevy I need a log to fix the issue. You can find it in the latest.log file.

**Comment by GChevy** [comment]
16.03 17:52:40 [Server] INFO [17:52:40 INFO]: Done (4.394s)! For help, type "help" or "?"
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:446) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:292) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:336) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:362) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:403) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadCustomPermissions(CraftServer.java:896) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
16.03 17:52:40 [Server] INFO [17:52:40 WARN]: Server permissions file permissions.yml is not valid YAML.
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:446) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:292) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:336) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:362) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:395) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:461) [sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) ~[sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:323) ~[sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:315) ~[sportbukkit.jar:git-SportBukkit-"a58b0f6"]
16.03 17:52:40 [Server] INFO at in.twizmwaz.cardinal.Cardinal.onEnable(Cardinal.java:155) ~[?:?]
16.03 17:52:40 [Server] INFO at in.twizmwaz.cardinal.GameHandler.<init>(GameHandler.java:31) ~[?:?]
16.03 17:52:40 [Server] INFO at in.twizmwaz.cardinal.rotation.Rotation.getNext(Rotation.java:137) ~[?:?]
16.03 17:52:40 [Server] INFO at java.util.ArrayList.get(Unknown Source) ~[?:1.7.0_51]
16.03 17:52:40 [Server] INFO at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.7.0_51]
16.03 17:52:40 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
16.03 17:52:40 [Server] INFO [17:52:40 ERROR]: Index: 0, Size: 0 loading Cardinal v1.0-SNAPSHOT-git-CardinalPGM-70b97cc (Is it up to date?)
16.03 17:52:40 [Server] INFO [17:52:40 INFO]: [CardinalPGM] Deleting match files, this can be disabled via the configuration
16.03 17:52:40 [Server] INFO [17:52:40 INFO]: [CardinalPGM] Enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-70b97cc
16.03 17:52:40 [Server] INFO [17:52:40 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.CraftBukkit_v1_7_R4 as the Bukkit adapter
16.03 17:52:40 [Server] INFO [17:52:40 INFO]: WEPIF: Using the Bukkit Permissions API.
16.03 17:52:38 [Server] INFO [17:52:38 INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
16.03 17:52:38 [Server] INFO [17:52:38 INFO]: Preparing start region for level 2 (Seed: -4938011389529765064)
16.03 17:52:37 [Server] INFO [17:52:37 INFO]: Preparing start region for level 1 (Seed: -4938011389529765064)
16.03 17:52:37 [Server] INFO [17:52:37 INFO]: Preparing spawn area: 69%
16.03 17:52:37 [Server] INFO [17:52:37 WARN]: Could not get latest artifact information: FileNotFoundException
16.03 17:52:36 [Server] INFO [17:52:36 WARN]: Could not get information about this CraftBukkit version; perhaps you are running a custom one?: FileNotFoundException
16.03 17:52:36 [Server] INFO [17:52:36 INFO]: Preparing start region for level 0 (Seed: -4938011389529765064)
16.03 17:52:36 [Server] INFO [17:52:36 INFO]: Preparing level "world"
16.03 17:52:36 [Server] INFO [17:52:36 INFO]: [CardinalPGM] Loading Cardinal v1.0-SNAPSHOT-git-CardinalPGM-70b97cc
16.03 17:52:36 [Server] INFO [17:52:36 INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
16.03 17:52:36 [Server] INFO [17:52:36 INFO]: This server is running SportBukkit version git-SportBukkit-"a58b0f6" (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
16.03 17:52:35 [Server] INFO [17:52:35 INFO]: Starting Minecraft server on 198.143.140.240:25565
16.03 17:52:35 [Server] INFO [17:52:35 INFO]: Generating keypair
16.03 17:52:35 [Server] INFO [17:52:35 INFO]: Default game type: SURVIVAL
16.03 17:52:35 [Server] INFO [17:52:35 INFO]: Loading properties
16.03 17:52:35 [Server] INFO [17:52:35 INFO]: Starting minecraft server version 1.7.10
16.03 17:52:26 [Server] INFO Loading libraries, please wait...
16.03 17:52:25 [Multicraft] Loaded config for "Default"
16.03 17:52:25 [Multicraft] Starting server!
16.03 17:52:25 [Multicraft] Loading server properties
16.03 17:52:24 [Multicraft] Received start command

**Comment by twizmwazin** [comment]
SportBukkit 1.8

**Comment by ryanwarsaw** [comment]
@twizmwazin You should just detect the users SportBukkit version, and if it isn't compatible send them a log message, rather than a error. I am not sure if this is possible on SportBukkit, but I am pretty sure it is on Spigot. Might be worth a try!

**Comment by SungMatt** [comment]
@ryanwarsaw Maybe a feature for the 1.0 milestone? Alternatively, they could read the [Wiki](https://github.com/twizmwazin/CardinalPGM/wiki/Installing-CardinalPGM) in the meantime.

**Comment by twizmwazin** [comment]
@ryanwarsaw You can just do Bukkit.getServer().getClass().getPackage().getName(), and that will return the Minecraft version, ie v1_8_R1 for 1.8 or v1_7_R4 for 1.7.10.
