### ISSUE TITLE
Error when a player enters a portal

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#405]
+ Video proof: http://youtu.be/WMkxfDWzVqk
+ Error log: http://pastebin.com/bZVst72d
+ Entire log: http://pastebin.com/nWzKV459
+ XML: http://pastebin.com/px6gKfM8
+ Cardinal version 1527580: http://gyazo.com/5c66d6eda4a4f841e96d8721dda659bb

```
<portals>
	<portal x="@0" y="@6" z="@55" yaw="180" filter="red-2nd">
		<cuboid min="3,1,92" max="5,4,93"/>
	</portal>
	<portal x="@0" y="@6" z="@23" yaw="180" filter="mid-held">
		<cuboid min="-1,1,92" max="1,4,93"/>
	</portal>
	<portal x="@0" y="@6" z="@-18" yaw="180" filter="blue-2nd">
		<cuboid min="-5,1,92" max="-3,4,93"/>
	</portal>
	<portal x="@0" y="@6" z="@-55" yaw="180" filter="blue-2nd">
		<cuboid min="-5,1,-93" max="-3,4,-92"/>
	</portal>
	<portal x="@0" y="@6" z="@-23" yaw="180" filter="mid-held">
		<cuboid min="-1,1,-93" max="1,4,-92"/>
	</portal>
	<portal x="@0" y="@6" z="@18" yaw="180" filter="red-2nd">
		<cuboid min="3,1,-93" max="5,4,-92"/>
	</portal>
</portals>
```

**Comment by SungMatt** [comment]
It might be the XML tag you are using, because I have a map with a portal (placid spring) and its working fine.

**Comment by AngelCasillas01** [comment]
@SungMatt So why my ender blast dosen't work with maps.oc.tc XML?

**Comment by MrTheSharpie** [comment]
This happened to me also in the map Fourchette (the version avaliable to download uses portals)

**Comment by CaptainElliott** [comment]
@MrTheSharpie the region that you can download may use wrong regions. 

Could someone try and reproduce this?

**Comment by iEli2tyree011** [comment]
Objective filters were being loaded before objectives, which is kind of a problem. However, filters are loaded at `EARLIER` stage...I'm not sure what the consequences are of moving them to `EARLY`. I'll look into it though, I suppose it's good that the problem's cause is known.
