### ISSUE TITLE
I can't join in a team, and I can't see the scoreboard

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#408]
![2015-03-17_19 05 19](https://cloud.githubusercontent.com/assets/11080069/6702194/59a75d74-cced-11e4-9f08-98310afdb5dd.png)

**Comment by twizmwazin** [comment]
@Jair07mx We need logs.

**Comment by AngelCasillas01** [comment]
@twizmwazin  I'm sorry but this error is due to an un-update or invalid sportbukkit, mybe hes ussing 1.7.10 Sport.

**Comment by CaptainElliott** [comment]
@AngelCasillas01 How can you be so sure without error logs, plus if he was using 1.7.10 then the plugin would not load

**Comment by twizmwazin** [comment]
@CaptainElliott I may be mistaken, but I'm pretty sure we don't have any check for the version of SportBukkit/CraftBukkit, so it would load, just then have a lot of issues.

**Comment by AngelCasillas01** [comment]
@CaptainElliott Because i got the same error by using 1.7.10 Sport, when i change to 1.8 the error disapear

**Comment by SungMatt** [comment]
@twizmwazin There was a pull request from @Aaron1011 , #406 , but it was closed by Aaron because the check for Bukkit flavour (SportBukkit, CraftBukkit, Spigot etc.) was not implemented.

**Comment by AngelCasillas01** [comment]
@SungMatt it was @ryanwarsar
