### ISSUE TITLE
Teams and Scoreboard issue 

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#411]
same as #408 but heres the log 

log for /join http://pastebin.com/iBuMiBjs

for the scoreboard, the plugin it's like dosen't have it 

Cardinal Version:http://prntscr.com/6j47ho

**Comment by twizmwazin** [comment]
Don't create duplicate issues, please re-post this in the open issue.

**Comment by twizmwazin** [comment]
Also, we need the full log, the log you linked cuts out the part we need.
