### ISSUE TITLE
Cycle issue

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#412]
Log: http://pastebin.com/01C5S4Yp
Map: https://oc.tc/forums/topics/54ad6ec5c296352d40000017

**Comment by twizmwazin** [comment]
This issue isn't related to Cardinal, it is a map XML issue

**Comment by TiTo-418** [comment]
https://github.com/DoomRobotBoy/Maps-XML/blob/master/Storm%20Cloud.xml

**Comment by iEli2tyree011** [comment]
That's an error in the XML, not our plugin...
Line 27: "cooked pork" -> "grilled pork"
