### ISSUE TITLE
Support global XML includes

### ISSUE THREAD

**Issue by Aaron1011** [twizmwazin/CardinalPGM#413]
[Several XML files](https://maps.oc.tc/) are found at the top level of Overcasts's map repository directory, such as `tutorial.xml`. These files can be used in an `include` tag, without qualifying the path.

I propose that CardinalPGM support a configurable global XML directory. XML files in said directory could be included from any XML file.

**Comment by SungMatt** [comment]
The xml files at the top level, such as `tutorial.xml` And `blitz-global.xml` is supposed to be in the map directory, default being `maps/`. Every xml file in a map folder within `maps/` can access those files. 

I do not see the need for it being configurable, after all it's just 2 xml files to be referenced.

**Comment by CaptainElliott** [comment]
We should make searching for includable xml files encompass every directory in the maps repository

**Comment by iEli2tyree011** [comment]
I added includes, and then Twiz made it so it searched the parent directories. As @SungMatt said, there are other locations where these could be included anyways (the `maps/` directory)

**Comment by Aaron1011** [comment]
Parent directories are only searched if a relative path is specified (e.g. `../other-map.xml`)

**Comment by twizmwazin** [comment]
@Aaron1011 When searching for an included file, three places are looked: the exact relative path given, then the map folder, and then the `maps/` folder.

**Comment by iEli2tyree011** [comment]
Closing, since I'm pretty sure the behavior of Cardinal is similar if not exact to how it should look through the directories. Thanks for bringing it up, though.
