### ISSUE TITLE
Automatically Create Rotation File

### ISSUE THREAD

**Issue by knightopress** [twizmwazin/CardinalPGM#414]
The plugin should automatically create/update the rotation.txt file every time the server starts, manually doing it can become a hassle for some users. I am using the latest version of CardinalPGM.

**Comment by CaptainElliott** [comment]
It does automatically create?

**Comment by knightopress** [comment]
I find no rotation.txt file in my server directory. It might be an issue with updating from a previous version of Cardinal.

**Comment by CaptainElliott** [comment]
Could you try deleting all files and restarting the server, one should be created

**Comment by knightopress** [comment]
Same results occur after completely deleting the server directory and restarting it.
