### ISSUE TITLE
Incorrect KD Calculation

### ISSUE THREAD

**Issue by knightopress** [twizmwazin/CardinalPGM#415]
If a player has 0 kills and 0 deaths, they should have a KD of 0 as shown here: https://oc.tc/Notch. But when CardinalPGM calculates the KD for a player with 0 kills and 0 deaths, it returns the KD value as 1.00 as shown here: http://i.imgur.com/q4GG9O4.png. I am using the latest version of CardinalPGM (git pull and mvn clean install every time I start server).

**Comment by SungMatt** [comment]
Mathematically its invalid though

**Comment by CaptainElliott** [comment]
Mathematically there KD is 1 as they have had the same kills as deaths, not sure if it is something I wan't to fix

**Comment by dentmaged** [comment]
@CaptainElliott But it is confusing for other players. I think it should be fixed.

**Comment by CaptainElliott** [comment]
I don't see how it is confusing

**Comment by knightopress** [comment]
I think we should go by OCN's methods of calculating KD.

**Comment by CaptainElliott** [comment]
@twizmwazin

**Comment by dentmaged** [comment]
@CaptainElliott If someone has 1 kill and 1 death, their KD would be 1. If someone's has 0 kills and 0 deaths, their KD would be 1. Despite it is mathematically correct, I think it should be 0.

**Comment by CaptainElliott** [comment]
I know that it should be 1, I don't think we should represent it as 0, that I why I am asking what @twizmwazin wants

**Comment by iEli2tyree011** [comment]
In my opinion, if a player has 0 kills and 0 deaths, the KD ratio should be 0.

**Comment by nygiants10** [comment]
KD: Indeterminate

**Comment by twizmwazin** [comment]
I think it should be 0 for 0 kills and 0 deaths.

**Comment by SungMatt** [comment]
@CaptainElliot Anything divided by 0 is undetermined. Think of it this way: You have 0 apples. You split it between no one. How many does each person get? The answer is undetermined because there is no one you can observe to find the answer. 

On a side note, this is turning to a Mathematics discussion isn't it?
