### ISSUE TITLE
Incorrect permissons with command /proximity

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#428]
<a href="http://imgur.com/QxgUsfg"><img src="http://i.imgur.com/QxgUsfg.png" title="source: imgur.com" /></a>

**Comment by Alfalik** [comment]
Can you explain the issue?

**Comment by CaptainElliott** [comment]
You should not be able to run the command while playing

**Comment by dentmaged** [comment]
@Alfalik Red's orb hasn't been touched but apparently in /proximity, it has.

**Comment by CaptainElliott** [comment]
@dentmaged you can't see if the enemy team has touches

**Comment by Alfalik** [comment]
@CaptainElliott I asked Elly about it, he wanted permissions. Look here https://github.com/twizmwazin/CardinalPGM/pull/418

**Comment by iEli2tyree011** [comment]
This is intentional. If you have a certain permission, you can use the command, just like /tp, etc.

**Comment by TiTo-418** [comment]
You should not be able to run the command while playing, even if you are admin or moderator. This is a gameplay breaking

**Comment by twizmwazin** [comment]
@TiTo-418 If you are an admin or moderator, you should be mature enough to not use the command while playing.

**Comment by MrTheSharpie** [comment]
@TiTo-418 In that case, you can also join obs to see if they have a touch. I don't think this has to be changed

**Comment by AngelCasillas01** [comment]
A good option is to let this command only for admin rank

**Comment by MrTheSharpie** [comment]
@twizmwazin Just for knowledge; did you finally added the Ref rank? If the answer is yes (I don't think so) what is the command to make someone ref? Thank you ;)

**Comment by CaptainElliott** [comment]
Please keep this on topic @MrTheSharpie 
But to answer your question, no, there will not be a ref rank

**Comment by TiTo-418** [comment]
Please remove the "bug" tag
