### ISSUE TITLE
Double shears in the hotbar

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#429]
<a href="http://imgur.com/re71Rp8"><img src="http://i.imgur.com/re71Rp8.png" title="source: imgur.com" /></a>

**Comment by TiTo-418** [comment]
LOL? Im going to close this

**Comment by CaptainElliott** [comment]
sorry, I misspelled it, no need to laugh xD

**Comment by TiTo-418** [comment]
NP, im **cloes** the issue xD

**Comment by TiTo-418** [comment]
I think it is not fixed, i ll confirm this
