### ISSUE TITLE
On CTW, the "wools" appears in orange instead of white

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#432]
This error is on scoreboard for be specific

[Cardinal Version](https://github.com/twizmwazin/CardinalPGM/commit/a3049d450c277e8416bfcd795f82f6a863b7f18a)

**Comment by iEli2tyree011** [comment]
This is intentional.

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 oh, because on the original PGM I thought it was white sorry :P
