### ISSUE TITLE
Harmful Potions Should Not Effect Teammates

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#436]
When a person throws a de-buff potion, like slowness or weakness, it should not effect other teammates. This can be teamgriefing if done extensively. Also, maybe make buffs , like healing and strength only effect players on the throwers team. Also, potions from spawners should effect all.

**Comment by twizmwazin** [comment]
Is this how it works on Overcast?

**Comment by TiTo-418** [comment]
https://github.com/OvercastNetwork/Issues/issues/231

**Comment by SungMatt** [comment]
Why should the suggestion on strength potions and healing be applied to only the thrower's team? Some 4 team maps allow for teaming, and also, if you throw a strength potion at the opponent, isn't it your fault that you threw it at them?
