### ISSUE TITLE
Observers cannot open furnace/beacon inventory

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#437]
Steps to reproduce:
1. Go on a server with a furnace/beacon
2. Right click the furnace/beacon

**Comment by SungMatt** [comment]
Aren't beacons along with crafting benches unopenable as an observer?

**Comment by TiTo-418** [comment]
The beacon is a tile entity, the crafting table no

**Comment by Aaron1011** [comment]
@TiTo-418: Furnace inventories are working for me in the latest version.

**Comment by TiTo-418** [comment]
Not working in OBSERVERS in 2a4772c701447286848ef0559355d1614ee4974e
