### ISSUE TITLE
Snowballs dissapear when shooting with a teammate infront of you

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#438]
It doesn't happen with arrows but it happens with snowballs

**Comment by Superjd10** [comment]
Sportbukkit issue, confirmed by Apple: https://github.com/OvercastNetwork/Issues/issues/1595#issuecomment-73183918

**Comment by iEli2tyree011** [comment]
As @Superjd10 said, this seems to be a SportBukkit issue, not a Cardinal issue.
