### ISSUE TITLE
On Ring Race, the left wool(for both teams) it's like void for the map

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#439]
[XML.](https://maps.oc.tc/CTW/Standard/Ring%20Race/map.xml)

**Comment by SungMatt** [comment]
Could you describe it in further detail? Is the left wool room in the void or is the place to place the "left wool" in the void? Also, it would help if you could specify which colour wool is the "left wool" as I'm not sure which direction are you looking in.

**Comment by SungMatt** [comment]
At this point it sound more like an XML error, but if you could describe it in further detail, your issue could be more easily resolved.

**Comment by AngelCasillas01** [comment]
@SungMatt Start happening after an update, a long time ago, like in january, was working fine

**Comment by Alfalik** [comment]
Upload YOUR XML, not the one on maps.oc.tc

**Comment by G61** [comment]
Put bedrock under the woolrooms.

**Comment by Alfalik** [comment]
@AngelCasillas01 Can you upload a vídeo, the map & XML or something useful to understand the issue?

**Comment by AngelCasillas01** [comment]
@Alfalik Tomorrow, XML is on the top

**Comment by TiTo-418** [comment]
actualiza el cardinal angel...

**Comment by AngelCasillas01** [comment]
Temporary closed

**Comment by twizmwazin** [comment]
If it isn't fixed don't close it.

**Comment by AngelCasillas01** [comment]
@twizmwazin it is a Cardinal issue 😳

**Comment by AngelCasillas01** [comment]
@twizmwazin Sorry didn't knew it 😥

**Comment by Alfalik** [comment]
I tested Ring Race on my server and it have no problems, the player can place, break & use blocks in the wool regions:

+ Map (if anyone want to test): http://www.mediafire.com/download/0afyo7d2wj97fma/Ring+Race.zip
+ XML: http://pastebin.com/jRktQpzu
+ Video proof: http://youtu.be/WiD9H2YRE04
+ Cardinal version 8b86e8d: http://gyazo.com/0077b9d40b70e970084155b146e00b98

**Comment by iEli2tyree011** [comment]
Going to close this as it seems to be an issue with mismatching maps and XMLs.

**Comment by TiTi-418** [comment]
@G61 that is the problem, thanks

**Comment by TiTi-418** [comment]
I found the error.
On cardinal y=0 need be bedrock, or this region will be void.
@AngelCasillas01's map is the same with oc.tc
Im going to upload a video tomorrow

**Comment by Alfalik** [comment]
@TiTi-418 Because PGM is still on 1.7 and using block 36.
