### ISSUE TITLE
Default Gold Core/Monument Mode not specified in /mode

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#440]
The /mode command only specifies monument modes if it is set in the XML. By default, the cores turn to gold in 15 minutes, but on a map where that is default, like Sky Traffic, it says something like there is no modes.

**Comment by SungMatt** [comment]
I do know of some tourney maps that stay full obsidian throughout.

**Comment by Alfalik** [comment]
Can you pastebin the XML?

**Comment by CaptainElliott** [comment]
I'm not too sure if cardinal has default modes, nor do I thin default modes are a thing on OCN anymore

**Comment by twizmwazin** [comment]
I'm not sure what the deal is on OCN, however we have default modes for cores.

**Comment by iEli2tyree011** [comment]
They appear just fine for me. Make sure your map is actually supposed to have default core modes.

http://i.imgur.com/Yq2TiXq.png
