### ISSUE TITLE
No SnowFlakes awarded on destroyed wool

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#441]
A non important missing feature

**Comment by TiTo-418** [comment]
- turning wool to carpet
- lava
- tnt
(https://github.com/OvercastNetwork/Issues/issues/1182)

**Comment by CaptainElliott** [comment]
@TiTo-418 Could you please stop referencing OCN issues, this is not a duplicate issue tracker, you can describe the issue yourself without referencing

**Comment by TiTo-418** [comment]
@CaptainElliott i know, but much of the issues related with "plugin" be issues of cardinal, and maybe the refence help the developers.

**Comment by Superjd10** [comment]
@TiTo-418 Using URL shortners also ping the Issue IIRC.

**Comment by TiTo-418** [comment]
Test: http://goo.gl/7lqxgX
