### ISSUE TITLE
Fire extinguished in observer mode does not regenerate.

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#442]
Evidence: http://youtu.be/8Dk5fnQpy7Q

**Comment by CoWinkKeyDinkInc** [comment]
This bug is also present in the Original PGM

**Comment by TiTo-418** [comment]
I know

**Comment by iEli2tyree011** [comment]
This is a client-side issue.

**Comment by TiTo-418** [comment]
"It's a bug that isn't fixed"

**Comment by iEli2tyree011** [comment]
@TiTo-418 It's client-side.

**Comment by TiTo-418** [comment]
@Brottweiler

**Comment by CaptainElliott** [comment]
@TiTo-418 there is no need to ping him, that was re opened as we decided that the developers may be able to fix it with a sportkukkit patch, there is no need to chase something up

**Comment by TiTo-418** [comment]
Ok, sorry
