### ISSUE TITLE
Match time is unnecessarily precise, displayed to 3 decimal places

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#443]
When you join a game, the match time is displayed as minutes, seconds and milliseconds. This is confusing to read and unnecessary.

For example:

<a href="http://imgur.com/AOoNBTW"><img src="http://i.imgur.com/AOoNBTW.png" title="source: imgur.com" /></a>

**Comment by SungMatt** [comment]
This is the OCN standard.

**Comment by TiTo-418** [comment]
https://github.com/OvercastNetwork/Issues/issues/1048

**Comment by SungMatt** [comment]
@TiTo-418 Let's first resolve missing features on Cardinal before attempting to bug fix these trivial bugs that have not even been resolved on PGM.

**Comment by TiTo-418** [comment]
obviously, first the missing features, after minimum bugs, but here is the report

**Comment by iEli2tyree011** [comment]
This isn't an issue.

**Comment by twizmwazin** [comment]
I'll add a config option.

**Comment by TiTo-418** [comment]
<3
