### ISSUE TITLE
Observers can modify/move boats in-game

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#444]
Issue

Observers can modify/move/break boats in observers.

How to Re-Create

Have someone in-game place a boat. Have another player in Observers. Have the observer go under the boat, they can re-direct it and move it with their head. Kindda like a flying carpet.

Evidence: http://youtu.be/pmbh7qXkbF8

**Comment by TiTo-418** [comment]
Isn't fixed

**Comment by twizmwazin** [comment]
My bad

**Comment by felipufeliu** [comment]
I think this bug also happend on the Overcast, it would be cool if you guys fix it.
