### ISSUE TITLE
Friendly fire restriction bypassed if shooter joins observers while arrow is in flight

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#445]
The issue

If a player shoots an arrow, then joins observers (e.g. by dying on Blitz), their arrow is able to damage their former teammates.

Proposed solutions

Arrows should remember which team their shooter belonged to at the time they were shot.
or

When a player leaves a team, all arrows shot by them should be removed

**Comment by Alfalik** [comment]
This also happen on OCN, and isnt really an issue.

**Comment by CaptainElliott** [comment]
I could fix this however this is something that is done on OCN, i'll fix it now and see if @twizmwazin wants it or not
