### ISSUE TITLE
Cant summon mobs

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#446]

**Comment by twizmwazin** [comment]
Example or more information please.

**Comment by Aaron1011** [comment]
@TiTo-418: In accordance with the [Mob spawning docs](https://docs.oc.tc/modules/mobs), CardinalPGM disables all mob spawning by default.

Maps can override this with the `mobs` element.

**Comment by TiTo-418** [comment]
You cant summon with spawn eggs or command /summon

**Comment by CaptainElliott** [comment]
That's because the xml will not allow you to

**Comment by TiTo-418** [comment]
Ok, ty
