### ISSUE TITLE
Kill rewards can be given after death but before respawn and therefor offset inventory.

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#447]
Rewards for killing a player can be given after you die but before you respawn, causing all the items in your inventory to be shifted over a slot (or more, depending on how many items are given in the reward).

You can reproduce this by:
1) Joining a map with a specified kill reward.
2) Punching a player from the opposing team off into the void.
3) Being killed before that player dies in the void, and sitting in the respawn menu until they die.

Evidence: http://youtu.be/HYX8b7pTVWg

**Comment by SungMatt** [comment]
@iEli2tyree011 How are you going to fix this issue? The killreward is currently given instantly on player kill, and it does not have a slot assignment. Are you going to delay the killreward until player respawn?

**Comment by twizmwazin** [comment]
@SungMatt We can keep track of players and who is alive and who is dead. If they are dead, the kill reward can be scheduled to run in one tick. If the player is still dead, repeat. If the player logs off or switches teams, cancel.
