### ISSUE TITLE
Useful commands for scrimms

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#448]
/kickall [Team] - Usage to kick a team specific.

/whitelist [Team] - Usage to add in the whitelist a team specific.

/ready - The command exists, but does not automatically start the game when the teams type /ready.

/referee [Player] - For mini tournaments.

**Comment by dentmaged** [comment]
For /ready, is there a timer?

**Comment by AngelCasillas01** [comment]
Yes it start with ready, what version are you using, this works when /ready functionality was implemented, theres no bugs on this, and why you want to kick all people? This command can be abused of that, and for whitelist, there is `/whitelist all` which add all of the peope in the server, referee it's a rank and @twizmwazin maybe will add it.

**Comment by AngelCasillas01** [comment]
@dentmaged yes it does.

**Comment by Jair07mx** [comment]
@AngelCasillas01 Ends Scrimm, and not kicking them one by one is better kicking them to a specific team.
If not added, the whitelist team and kick can make a good set

**Comment by Jair07mx** [comment]
@AngelCasillas01 /ready either because touch some things, so I'll try a virgin version of Cardinal.

**Comment by CaptainElliott** [comment]
Most of them are already implemented
`/whitelist kick` will kick everyone not on the whitelist (generally the other team)
/`ready` when both teams are ready a timer starts
`/whitelist team` whitelists a team

We will not, however, be adding a referee rank

**Comment by TiTo-418** [comment]
"/ready when both teams are ready a timer starts" incorrect, the obs team need be ready too

**Comment by CaptainElliott** [comment]
@TiTo-418  No, cardinal does not need obs to be ready as this is a scrim plugin

**Comment by iEli2tyree011** [comment]
@CaptainElliott I changed that

**Comment by CaptainElliott** [comment]
@iEli2tyree011 I don't think that is a good idea, most scrims will not have obs

**Comment by twizmwazin** [comment]
@CaptainElliott I'm not against Cardinal being used for off-season non-profit community events.

**Comment by CaptainElliott** [comment]
@twizmwazin  Then it should be a config option

**Comment by twizmwazin** [comment]
@CaptainElliott Will do

**Comment by TiTo-418** [comment]
Thanks
