### ISSUE TITLE
Add a feature which monuments can't be fixed.

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#449]
In some XML maps (such as Revenge TE) On the XML file theres is not `<itemremove>` on monuments blocks (for example coal monument) and if you fixed that block counts like had never broke it

**Comment by CaptainElliott** [comment]
Revenge TE has item remove that contains monument blocks

**Comment by AngelCasillas01** [comment]
@CaptainElliott was an example, can happend on a random map :(

**Comment by TiTo-418** [comment]
The monument on Ender Blast can be fixed, this is the idea

**Comment by CaptainElliott** [comment]
There is an objective attribute that allows for a monument not to be fixed. 
We do not want to hard code something like this in

**Comment by iEli2tyree011** [comment]
This is a valid issue, I'll fix it tonight.

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 Thanks!
