### ISSUE TITLE
using /start twice after the second game throws error

### ISSUE THREAD

**Issue by IlPicasso** [twizmwazin/CardinalPGM#456]
I was testing and in the first game if you use /start it will detect that a game is on game 

But after the first cycle if you use /start again it will throw an error

http://pastebin.com/X9hii7gy

**Comment by Jonmuxu** [comment]
it's a bug with the countdown... :(

**Comment by AngelCasillas01** [comment]
@twizmwazin Maybe you should check your new StartTimer module for resolve this, but maybe something broke this code because this was solved a few ago if i'm not bad 🙈

**Comment by IlPicasso** [comment]
IN the first game it wont throw that error

**Comment by twizmwazin** [comment]
This is the weirdest log file I've ever seen
