### ISSUE TITLE
Ban message

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#458]
When disconnect from server apears well (Permantly ban >> Test)
But entering again to the server, (Appears like vanilla message and the reason appears the way should be, ex.)(Vanilla messages; Reason: Permantly Ban>> Teste)

[Cardinal Version](https://github.com/twizmwazin/CardinalPGM/commit/acd3b4ca9b4609913c07319c1ab2afa23313b415)

**Comment by Eudaldca** [comment]
Update your cardinal, it was fixed by #731

**Comment by SungMatt** [comment]
This is issue #371 , discuss there.

**Comment by Eudaldca** [comment]
Update cardinal.

**Comment by AngelCasillas01** [comment]
@Eudaldca you don't see the cardinal version .-.?

**Comment by AngelCasillas01** [comment]
Closing in reference to #371
