### ISSUE TITLE
Failed to load map

### ISSUE THREAD

**Issue by Rafitamolin** [twizmwazin/CardinalPGM#459]
http://pastebin.com/ZyYd2NaF

Tried to load other maps but I get the same error.

Version: ![Version](http://i.imgur.com/jejVs9N.png)

**Comment by ryanw-ny** [comment]
@Rafitamolin It appears that it is trying to send too many requests per minute to Mojang's servers. I might be wrong, but it is responding with error code 429 which typically means too many requests. 

Try waiting a few minutes before starting your server again.

**Comment by SungMatt** [comment]
This is usually an XML error, but to verify, go to `plugins/Cardinal/config.yml` , and change the setting for `displayMapLoadErrors` to `true`, and that will tell you more about the issue. Please attach the logs after you've changed this setting, then we know what XML error it is, or a missing filter.

**Comment by Rafitamolin** [comment]
@SungMatt http://pastebin.com/2Vs7yus1

**Comment by Alfalik** [comment]
Can you pastebin the XML?

**Comment by Rafitamolin** [comment]
@Alfalik Squidditch: https://github.com/Qixit/Squidditch.XML/blob/master/map.xml
Lunar Crescent: http://pastebin.com/XzkwG70L
Secluded: https://github.com/DoomRobotBoy/Maps-XML/blob/master/Secluded.xml

Those 3 maps are giving me errors.

**Comment by SungMatt** [comment]
@Rafitamolin These 3 are all xml errors. Do you want me to send you an edited version of the xml?

**Comment by Rafitamolin** [comment]
@SungMatt It would be great. Thanks :)

**Comment by SungMatt** [comment]
@Rafitamolin 
Here's [Squidditch](https://raw.githubusercontent.com/SungMatt/CorrectedXML/master/Squidditch.xml)
Will update as I fix the other 2.

**Comment by Rafitamolin** [comment]
Thanks again @SungMatt. Closing this because it's a XML issue and not a plugin issue.

**Comment by SungMatt** [comment]
@Rafitamolin You're welcome :)
