### ISSUE TITLE
Update punishemnts commands

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#460]
you maybe can use /l for see punishments for the player, and /appeal, this maybe should use database stuff

**Comment by SungMatt** [comment]
/appeal ? This is a scrimmage server, not a PGM replacement.

**Comment by Superjd10** [comment]
I agree with @SungMatt. This isn't necessary in a scrimmage server.

**Comment by iEli2tyree011** [comment]
We're not adding punishment tracking. The sole reason for the punishment commands is to mute, kick, or ban someone. We don't need an appeal system for this.
