### ISSUE TITLE
Signs issue

### ISSUE THREAD

**Issue by Jair07mx** [twizmwazin/CardinalPGM#464]
![2015-03-24_19 50 44](https://cloud.githubusercontent.com/assets/11080069/6816968/1337d97c-d260-11e4-920d-09e23aa3cbc7.png)

**Comment by Alfalik** [comment]
How it is supposed to be related with Cardinal?

**Comment by iEli2tyree011** [comment]
This isn't related to Cardinal whatsoever, nor do we even support lobbies.

**Comment by Jair07mx** [comment]
In single player are as they should be

**Comment by iEli2tyree011** [comment]
@Jair07mx This is not caused by Cardinal.

**Comment by Jair07mx** [comment]
@iEli2tyree011  A problem of incompatibility between 1.7 and 1.8, I should imagine

**Comment by twizmwazin** [comment]
Networks are NOT supported.
