### ISSUE TITLE
Map description is not displayed on cycle and join

### ISSUE THREAD

**Issue by Carlos934** [twizmwazin/CardinalPGM#466]
If it occurs at tm, and missing in CardinalPGM

![image](https://cloud.githubusercontent.com/assets/11640813/6817450/189b1518-d266-11e4-95ca-6ec046a18ede.png)

**Comment by SungMatt** [comment]
It should display in /map

**Comment by Carlos934** [comment]
No, it shows to enter the server

**Comment by Carlos934** [comment]
@TiTo-418 We are talking about TM, no of public matches

**Comment by AngelCasillas01** [comment]
@twizmwazin a good stuff for the code can be `getobjective()` and `getname()`
