### ISSUE TITLE
Observer spawn does not respect kits.

### ISSUE THREAD

**Issue by SungMatt** [twizmwazin/CardinalPGM#467]
In some maps, like BipBetaMC, and SuperPRISM, Night Vision is used to allow the player to see better in the poorly lit map. As such, every player is given night vision in a `kit` with a `potion` tag. However, `default` does not respect this kit, and does not give the player the potion effect.

I have attempted to modify this default kit, and regardless if it is a potion effect, an item, or a piece of armor, it is ignored.

**Comment by TiTo-418** [comment]
e.g. XML: https://maps.oc.tc/Other/Tournament/House%20of%20Cores/house-of-cores.xml
