### ISSUE TITLE
Wools proximity is not automatically shown on the scoreboard

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#468]
I did the test only in maps without the ```<time result="objectives">x</time>``` module in the XML. In DTC/M it just work fine.

+ Video proof: http://youtu.be/6aU5xQaxDCM
+ Cardinal version 8b86e8d: http://gyazo.com/0077b9d40b70e970084155b146e00b98

**Comment by TiTo-418** [comment]
Proximity is a XML option, try with Golden Drought TE

**Comment by AngelCasillas01** [comment]
I think it's a `<map proto>` feature, proximity start working on `<map proto= 1.3.5>` i'm not sure but make some sense, i update the dyano XML from an old one to a newest one and proximity was showed on scoreboard, but maybe Devs can add a feature which implements an automatic proximity on socrebard

**Comment by twizmwazin** [comment]
@AngelCasillas01 It has nothing to do with the protocol. I'm pretty sure the issue is that when Elly re-wrote the scoreboard he forgot to convert wool proximity to use the new system. Technically speaking, proximity shouldn't even be shown if there is no time limit on the map.

**Comment by Carlos934** [comment]
@twizmwazin So it should be, a tournament mode with timelimit, and other normal mode to practice
