### ISSUE TITLE
Scoreboard Issue

### ISSUE THREAD

**Issue by Prodigy4532** [twizmwazin/CardinalPGM#474]
When a person leaves the game or kiked / banned , the scoreboard does not appear

Video: http://youtu.be/9h6k36jrYic

Cardinal Version: 778d5d5

**Comment by TiTo-418** [comment]
El scoreboad no aparece porque la partida esta terminada, no hay objetivos que mostrar.

**Comment by Prodigy4532** [comment]
Pero igual deverian de salir para gente que no vio la scrimmage o por si se cayeron y querian ver como quedo la partida

**Comment by twizmwazin** [comment]
@TiTo-418 @Prodigy4532 Keep it English in the issue tracker, I need to know what you are saying.

**Comment by TiTo-418** [comment]
Sorry, i say: the scoreboard no appear becouse the match is end, there isnt objs to show

**Comment by Prodigy4532** [comment]
should go for people that just between learns as I finish the game, or people who may unknowingly disconnect

**Comment by RubeGamerV** [comment]
@TiTo-418  Grammar op

**Comment by SungMatt** [comment]
@aprodigy4532 Does google translate suck so bad?

**Comment by Prodigy4532** [comment]
yea im using google :/ sorry

**Comment by TiTo-418** [comment]
Correct google translate: But just deverian out for people who did not see the scrimmage or if dropped and wanted to see how it turned the game

**Comment by Prodigy4532** [comment]
thanks tito <3

**Comment by elespawol** [comment]
Never use google translate
Its extremly horrible!!
El dia 27/03/2015 14.23, "Prodigy4532" <notifications@github.com> va
escriure:

**Comment by Alfalik** [comment]
@elespawol @Prodigy4532 @TiTo-418 @RubeGamerV Can we keep the issue on topic?

**Comment by TiTo-418** [comment]
Sure

**Comment by iEli2tyree011** [comment]
Fixed in d75c09bc6913fb32899b4c1d040f3563a1367575
