### ISSUE TITLE
Missing an option to modify "Cardinal" in tab

### ISSUE THREAD

**Issue by Carlos934** [twizmwazin/CardinalPGM#475]
In TM have name of the team, so I think there should be an option to change this, also translate into Spanish and separate teams in tab.

![image](https://cloud.githubusercontent.com/assets/11640813/6861914/075e9a78-d404-11e4-9369-09dc0cd876b9.png)

**Comment by Carlos934** [comment]
I'm talking about this
![image](https://cloud.githubusercontent.com/assets/11640813/6861967/cff56502-d404-11e4-9788-975884e3f289.png)

**Comment by SungMatt** [comment]
You can change the phrase "Scrimmage Server" in the `Cardinal/config.yml` file. "Cardinal" though, is attribution for the project.
