### ISSUE TITLE
TNT does not ignite others TNTs if the XML have a <blockdrops/> module

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#476]
+ Video proof with ```<blockdrops/>``` in the XML: https://youtu.be/VjadHWOROtc
+ Video proof without ```<blockdrops/>``` in the XML: https://youtu.be/lnUVt2Hub8U
+ Cardinal version 778d5d5: http://gyazo.com/1059d027f2bc2fe089e7a667e6201553

**Comment by CaptainElliott** [comment]
It's working fine for me

**Comment by Alfalik** [comment]
Uh, fixed it changing the XML (<a href=http://pastebin.com/fHZU8Jkc">Old syntax</a>)

```
<blockdrops>
	<rule>
		<filter>
			<block>stone</block>
		</filter>
		<drops>
			<item>stone</item>
		</drops>
	</rule>
	<rule>
		<filter>
			<block>cobblestone</block>
		</filter>
		<drops>
			<item>stone</item>
		</drops>
	</rule>
</blockdrops>
```
