### ISSUE TITLE
TNT is not ingiting when on

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#477]
It's kind of if in XML has `<fuse>` and it has 4 secs, the tnt last 5 secs for destroy objects, appears like lag but i try it on a localhost server and it's the same problem

**Comment by CaptainElliott** [comment]
https://docs.oc.tc/modules/tnt

><fuse>	Time till the TNT explodes once it is ignited.
Must be a value less than 4 seconds since the TNT entity vanishes after that.

**Comment by AngelCasillas01** [comment]
Was an ex, when `<fuse>` is 1 same

**Comment by CaptainElliott** [comment]
A fuse of 1 second works fine for me
