### ISSUE TITLE
Blockdrops drop the same item when breaking a random block

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#478]
The test was on Retalation 2 BC (<a href="https://maps.oc.tc/Other/Tournament/Breaking%20Core/Retaliation%202/map.xml">XML</a>)

```
<blockdrops>
	<rule>
		<block>stone</block>
		<drops>
			<item>stone</item>
		</drops>
	</rule>
	<rule>
		<block>cobblestone</block>
		<drops>
			<item>stone</item>
		</drops>
	</rule>
</blockdrops>
```
+ Video proof: https://youtu.be/JCwkkNsC7R0
+ XML: http://pastebin.com/DNn2uyxn
+ Cardinal version 778d5d5: http://gyazo.com/1059d027f2bc2fe089e7a667e6201553

**Comment by CaptainElliott** [comment]
This also works fine for me

You are using an incorrect syntax, you need to use filters to define when it drops 
https://docs.oc.tc/modules/blockdrops
