### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by elespawol** [twizmwazin/CardinalPGM#48]
I tested to join and start a match, (map: Deepwind Jungle)
And no tp and no kit

**Comment by CaptainElliott** [comment]
Was there any errors in the server log?

**Comment by elespawol** [comment]
Yes a lot, using the lastest sportbukkit version.
El dia 18/01/2015 14.38, "Elliott" <notifications@github.com> va escriure:

**Comment by elespawol** [comment]
http://pastebin.com/ujQ6qCDq logs

**Comment by twizmwazin** [comment]
I will look into the issue, could you try disabling your other plugins to confirm this is an issue with CardinalPGM?

**Comment by elespawol** [comment]
http://pastebin.com/inRbb9Km

**Comment by CaptainElliott** [comment]
I can also confirm this is an issue
kits are not given

**Comment by twizmwazin** [comment]
I am able to reproduce the kit issue, however not the other exceptions you got. Make sure your XML is the latest, and then I may need a copy to try an fix it. The kit issue affects multiple maps, however.

**Comment by elespawol** [comment]
The xml is correct because i tested that in other maps :s and happens the
same
El dia 18/01/2015 16.07, "Kevin Phoenix" <notifications@github.com> va
escriure:

**Comment by twizmwazin** [comment]
I'm looking into it

**Comment by elespawol** [comment]
Its solved no?
El dia 18/01/2015 16.58, "Kevin Phoenix" <notifications@github.com> va
escriure:

**Comment by twizmwazin** [comment]
It should be fixed, reopen the issue if it isn't

**Comment by elespawol** [comment]
http://pastebin.com/LdsbE3xt i tested to put multiverse core plugins,
because, there was no tp,
No kit, no tp, random respawn

2015-01-18 17:05 GMT+01:00 Kevin Phoenix <notifications@github.com>:

**Comment by elespawol** [comment]
nothing, i tested other maps, and now works fine

**Comment by elespawol** [comment]
it depends of the map...
dynamo..,, deepwind jungle doesnt works, but like: warlock and other yes... i think the problem is that the plugin actually ,doesnt have all the things of XML

**Comment by twizmwazin** [comment]
Make sure you have the official XML from https://maps.oc.tc/
Also, I do not suggest using any plugins other than Worldedit 6.x with CardinalPGM.
http://dev.bukkit.org/bukkit-plugins/worldedit/

**Comment by elespawol** [comment]
but that maps (deewind jungle, dynamos etc) works fine actually with sporkPGM

**Comment by twizmwazin** [comment]
Recompile the latest version of the plugin, and tell me exactly what doesn't work and exactly what maps you are having issues on. If there are exceptions, please upload logs.

**Comment by elespawol** [comment]
1* i /setnext deep , /cycle 1. Appears in the same map as the other match,
but changes the obs kit and the scoreboards
2* /join red , /start 1. The match seems start. No tp, no kit, no gm 0. But
i can broke all, when i pick wool, the message appears. I can ENTER on my
own wools (BUG). The max hight works correctly. The placement of the wool,
the same. But if i die, it respawns on the map, but random.

If u want i can.pass my scrimage server ip to see it.
El dia 18/01/2015 21.07, "Kevin Phoenix" <notifications@github.com> va
escriure:

**Comment by elespawol** [comment]
I used the plugin multiversecore to go , to the. World match
El dia 18/01/2015 21.19, "Elespawol GMail" <elespawol@gmail.com> va
escriure:

**Comment by twizmwazin** [comment]
Uninstall multiverse and see if that corrects the issue. CardinalPGM is not designed to work with multiverse.

**Comment by elespawol** [comment]
I only used to tp, then i disabled to test the other things
El dia 18/01/2015 21.22, "Kevin Phoenix" <notifications@github.com> va
escriure:

**Comment by twizmwazin** [comment]
Still, please remove the plugin altogether.

**Comment by elespawol** [comment]
i doit.... and happens the same

**Comment by elespawol** [comment]
:(
