### ISSUE TITLE
When you open a villager inventory the game crash

### ISSUE THREAD

**Issue by Carlos934** [twizmwazin/CardinalPGM#486]

**Comment by twizmwazin** [comment]
We need logs and a more specific explanation

**Comment by Carlos934** [comment]
The server does not, the game yes

**Comment by twizmwazin** [comment]
What?

**Comment by Carlos934** [comment]
The server does crash, is the game

**Comment by twizmwazin** [comment]
We need the logs

**Comment by SungMatt** [comment]
Does the server crash or the client crash?

**Comment by Carlos934** [comment]
http://pastebin.com/vXM8Ah95

**Comment by Carlos934** [comment]
This is an example, but it happens on maps as Necro or chaos dreams

**Comment by ryanw-ny** [comment]
@Carlos934 This isn't a issue with CardinalPGM, it appears that you're on Minecraft version 1.7.4, which if I recall correctly, CardinalPGM supports 1.8 only! Update your version of CardinalPGM, and client.

**Comment by SungMatt** [comment]
Please, please, read the [wiki](https://github.com/twizmwazin/CardinalPGM/wiki) to ensure that you are using Cardinal properly before you file an issue. Thanks.
