### ISSUE TITLE
/Start does not obey the values given

### ISSUE THREAD

**Issue by SungMatt** [twizmwazin/CardinalPGM#494]
If one does `/start 5` , the map starts 5 seconds later.
However, if one does `/start 200` afterwards, the map starts in 200 ticks(10 seconds). This did not happen in version 1ffb5a7 and before.

Tested in Cardinal version c3dfc8c .

**Comment by twizmwazin** [comment]
Thanks for finding this, will try to get this tonight.

**Comment by SungMatt** [comment]
@twizmwazin Thanks for always jumping to fix issues as soon as they appear.
