### ISSUE TITLE
[Question] Final Release

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#496]
hey! You said you were going to do the final release soon aftert HoC finishes. I just want to know more or less a date :)

Keep doing this amazing work :D

**Comment by TiTo-418** [comment]
3 de Abril, podes usar skype para esto...

**Comment by twizmwazin** [comment]
Cardinal is not going to be going with a traditional "release" model, rather we are going to have a rolling release. Cardinal will be continuously updated and Cardinal updates will remain available and easily installable. We may soon implement very easy (possibly automatic) upgrading.
