### ISSUE TITLE
Update Notifications 

### ISSUE THREAD

**Issue by CaptainElliott** [twizmwazin/CardinalPGM#497]
Almost done, just need to do the JSON parsing

**Comment by twizmwazin** [comment]
For Minecraft Json, you can send a message to a player using Player#sendRawMessage(String json);

**Comment by dentmaged** [comment]
@twizmwazin I think Elliott means JSON from the Github API.

**Comment by CaptainElliott** [comment]
Yup, getting used to GSON

**Comment by twizmwazin** [comment]
Implemented
