### ISSUE TITLE
I don't know if this is allowed

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#502]
Last days, I've seen lots of servers with the lobby taken from OCN and having different matches loaded with CardinalPGM. I think that the goal of Cardinal is not recreating a network, so I think you should not allow this.

I will put it an IP of one of these servers as an example: 23.97.136.78 Actually it is offline, but I have seen this here.

**Comment by twizmwazin** [comment]
There isn't much I can do, however I do not support these networks.

**Comment by TiTo-418** [comment]
<a href="http://imgur.com/hukKeoO"><img src="http://i.imgur.com/hukKeoO.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/CckJohs"><img src="http://i.imgur.com/CckJohs.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/7Y5HbXX"><img src="http://i.imgur.com/7Y5HbXX.jpg" title="source: imgur.com" /></a>

**Comment by dentmaged** [comment]
@TiTo-418 They are allowed to do that, however, the developers hate it.

**Comment by TiTo-418** [comment]
@dentmaged That is CardinalPGM with a few things changed...

**Comment by twizmwazin** [comment]
@TiTo-418 If you know who the owners are, you can report them to OCN.

**Comment by TiTo-418** [comment]
@twizmwazin What? That no is original PGM, it is Cardinal.

**Comment by dentmaged** [comment]
@twizmwazin EPGM is made by [https://github.com/XesprimerX](XesprimerX) (or that is his github account). His MC account is [https://oc.tc/esprimer](esprimer). Run /pgm -s to see the version, instead of /cardinal -v. If you want to decompile EPGM, it can be found [www.mediafire.com/download/o2aqgw9cg6tcap0/EPGM-BETA-1.6.jar](here).

**Comment by CaptainElliott** [comment]
I shall report this to OCN admins. Thanks

**Comment by TiTo-418** [comment]
https://www.youtube.com/watch?v=u_EWjbl6-OM&feature=youtu.be

**Comment by TiTo-418** [comment]
@CaptainElliott @dentmaged You need to be logged in to see the dowload
<a href="http://imgur.com/VuuVsrX"><img src="http://i.imgur.com/VuuVsrX.png" title="source: imgur.com" /></a>

**Comment by dentmaged** [comment]
@TiTo-418 What about War Wars?

**Comment by CaptainElliott** [comment]
@dentmaged they are using OCN maps

**Comment by dentmaged** [comment]
@CaptainElliott I see. Thank you. But then why do you need to know about them changing any part which defines CardinalPGM as 'CardinalPGM'?

**Comment by twizmwazin** [comment]
@dentmaged @CaptainElliott Cardinal's license, in simple terms, allows anyone who acquires Cardinal to use, change, distribute, make a profit, or any combination of those things, so long as they note that all code used from Cardinal is owned by me. The name Cardinal is not required to be associated with the project. The warranty note states that I am not required or obligated to provide support under any condition, including if someone manages to damage their computer while using Cardinal.

**Comment by TiTo-418** [comment]
@dentmaged <a href="http://imgur.com/KxpusEV"><img src="http://i.imgur.com/KxpusEV.png" title="source: imgur.com" /></a>

**Comment by dentmaged** [comment]
@twizmwazin Thanks! And I guess they haven't note d that you made it, do what will you do?

**Comment by twizmwazin** [comment]
@dentmaged Nothing most likely

**Comment by TiTo-418** [comment]
Thanks to all :)
<a href="http://imgur.com/rNSLYjl"><img src="http://i.imgur.com/rNSLYjl.png" title="source: imgur.com" /></a>

**Comment by nicogrodri10** [comment]
gg

**Comment by CaptainElliott** [comment]
Locking this as nothing positive can be contributed to this

Feel free to unlock it if you deem it necessary @twizmwazin
