### ISSUE TITLE
Add Automatic Start.

### ISSUE THREAD

**Issue by D4n1e6656** [twizmwazin/CardinalPGM#503]
English: Well, my suggestion is that in the plugin config section had an option of automatic start when two players on a different team .

Español: Bueno, una sugerencia mía es que en la sección de configuración del plugin hubiera una opción de start automático cuando haya dos jugadores en un equipo diferente.

**Comment by AngelCasillas01** [comment]
#362 The answer you may know

**Comment by twizmwazin** [comment]
I don't want your network
