### ISSUE TITLE
3 bugs

### ISSUE THREAD

**Issue by ElFlambMC** [twizmwazin/CardinalPGM#506]
1 if you are in the heigh nivel you are invisible.
2 if you aren't op you wasn't place blocks map (deepwind jungle)
3 if you put in the bedrok a block you can put to the top (this bug is allready know and fixed) but is a dupe idk.
Latest version

**Comment by Vixo1** [comment]
I think you need provide evidence of this bugs, also, the first bug is relationated with 1.8, not the plugin.

**Comment by ElFlambMC** [comment]
I dont in pc to provide

**Comment by SungMatt** [comment]
Can you do `/cardinal -v` and tell us the version that it occurs in?

**Comment by TiTo-418** [comment]
1. Can't confirm
<a href="http://imgur.com/0sk0MRs"><img src="http://i.imgur.com/0sk0MRs.png" title="source: imgur.com" /></a>
2. in server.propieties set spawn-protection=0
3. can confirm

**Comment by twizmwazin** [comment]
1. Can't fix
2. Disable server spawn protection
3. If it is fixed why are you reporting it?

**Comment by TiTo-418** [comment]
Isnt fixed
