### ISSUE TITLE
Players can still defuse their own TNT using shears 

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [twizmwazin/CardinalPGM#507]
OCN now allows you to disable team TNT by punching it.  I think Cardinal should implement this as well.

**Comment by ryanw-ny** [comment]
You should be able to toggle this, since a lot of people of shown frustration in this new system.

**Comment by CoWinkKeyDinkInc** [comment]
A toggle thing is added in the OCN XML so it can't happen on stuff like Harb or Dwyer Hill.

**Comment by CaptainElliott** [comment]
You should be able to punch it? I remember allowing you to, just not in obs

**Comment by CaptainElliott** [comment]
Just checked you can punch TNT to defuse it, however you can;t defuse your own TNT and shears are still needed in obs

**Comment by CaptainElliott** [comment]
Actually, you can defuse your own TNT in game with shears which should not be intentional

**Comment by CoWinkKeyDinkInc** [comment]
You should be able to defuse your own TNT.

**Comment by CaptainElliott** [comment]
It's something that you can't do on OCN because the purpose of defusing tnt is to stop team grief not to fix your mistakes

**Comment by TiTo-418** [comment]
Who will be team grief in a scrimm?

**Comment by elespawol** [comment]
But if u comite a error puting tnt is useful
El dia 02/04/2015 6.50, "TiTo-418" <notifications@github.com> va escriure:

**Comment by iEli2tyree011** [comment]
@elespawol What? The point is to prevent other people from team griefing.

**Comment by TiTo-418** [comment]
@CaptainElliott @iEli2tyree011 In a scrim, you team no will be to team grief

**Comment by iEli2tyree011** [comment]
@TiTo-418 And? You can still defuse your teammates' TNT.

**Comment by elespawol** [comment]
If is for that reason, it think that is not necesary
El dia 02/04/2015 18.49, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by TiTo-418** [comment]
@elespawol +1 "It's something that you can't do on OCN because the purpose of defusing tnt is to stop team grief not to fix your mistakes" and your team mistakes....
