### ISSUE TITLE
My server crash when i leak de core on Cake Wars

### ISSUE THREAD

**Issue by MysticxPvP** [twizmwazin/CardinalPGM#511]
Video: https://www.youtube.com/watch?v=dwuNUhRH8vU&feature=youtu.be
XML: http://pastebin.com/QWjnYyqr
Crash-report: http://pastebin.com/fuQcD0uY
Cardinal version: 9593b9d http://gyazo.com/0696db2f8ff42cd7326c06075b2f55e2

(sorry for my bad english).

**Comment by RubeGamerV** [comment]
Are you using local host?, Estas usando un servidor local?

**Comment by twizmwazin** [comment]
It looks like this is a SportBukkit issue.

**Comment by MysticxPvP** [comment]
@RubeGamerV Si, estaba usando un localhost.

@twizmwazin Ok sorry.
