### ISSUE TITLE
Chests cannot be opened in region

### ISSUE THREAD

**Issue by dentmaged** [twizmwazin/CardinalPGM#520]
I am running Cardinal 519 which is based off 884de07.

I cannot open chests in a non-modifiable region.
Video: https://youtu.be/HjxHAxMnrOA

**Comment by TiTo-418** [comment]
Happening again 
<a href="http://imgur.com/2wgZzy9"><img src="http://i.imgur.com/2wgZzy9.png" title="source: imgur.com" /></a>
