### ISSUE TITLE
Can't enter your own spawn region

### ISSUE THREAD

**Issue by dentmaged** [twizmwazin/CardinalPGM#521]
I am running Cardinal #519 which is based off 884de07.

I can't enter the spawn region (regions need to be re-done). I guess this is related to #520.
Video: http://youtu.be/DRWUHCOipEw

**Comment by CaptainElliott** [comment]
Can you show me the xml

**Comment by dentmaged** [comment]
[map.xml](http://www.mediafire.com/view/2lpcsbjhppgjch1/map.xml)

**Comment by TiTi-418** [comment]
Isn't fixed
