### ISSUE TITLE
Tutorial issue(Incorrect facing direction)

### ISSUE THREAD

**Issue by TiTi-418** [twizmwazin/CardinalPGM#524]
Video proof: http://youtu.be/7DLQTLFIpSU
Cardinal version: 18fb2d4f64c3c95180fa2f61ed17de9b8f61c1f2
Incorrect facing direction

**Comment by CaptainElliott** [comment]
I don't see the issue

**Comment by TiTo-418** [comment]
In overcast: http://youtu.be/4bzbcl_4pnc (uploading...)

**Comment by twizmwazin** [comment]
Are pitch and yaw values ignored?

**Comment by CaptainElliott** [comment]
Probably but the tutorial is throwing a bunch of NPEs for me, that also needs to be fixed

**Comment by dentmaged** [comment]
@twizmwazin Can I apply a patch and give you credit?

**Comment by twizmwazin** [comment]
@dentmaged Can you just contribute to the main project?

**Comment by dentmaged** [comment]
Well how do I know that you will merge it? I don't know if you will implement my rank system, the observer book nor that you will implement my makeshift Boss Bar system.

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/524#issuecomment-94735920 +1

**Comment by twizmwazin** [comment]
@dentmaged You don't know for sure, and that is part of development. Part of development is review. As the owner and administrator of the repository, it is part of my job to  review all code that goes into this repository, including mine. Believe it or not, I generally end up writing a feature multiple times before I commit it, making consistent improvements each time. I will hold others to the same standards in which I hold myself. Generally when we don't merge something, but don't specifically deny it, it should be taken as a notion to improve upon the implementation.
