### ISSUE TITLE
cyclying to own map makes the plugin stop working

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#526]
if you are on deepwind, you do /sn deepwind, and then you do /cycle 0 -f, nothing happens, and you can no longer cycle, try to sn something else, or anything

**Comment by twizmwazin** [comment]
We need log files.

**Comment by Pablete1234** [comment]
i know /recycle works, but it's a bug that if you  try to /cycle it stops

**Comment by Pablete1234** [comment]
[Java ERROR]	java.lang.Thread.run(Thread.java:722) [?:1.7.0]
[Java ERROR]	net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:521) [sportbukkit-1.8-R0.1-20150325.005932-17.jar:git-SportBukkit-10dd8f3]
[Java ERROR]	net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:611) [sportbukkit-1.8-R0.1-20150325.005932-17.jar:git-SportBukkit-10dd8f3]
[Java ERROR]	net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [sportbukkit-1.8-R0.1-20150325.005932-17.jar:git-SportBukkit-10dd8f3]
[Java ERROR]	net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:666) [sportbukkit-1.8-R0.1-20150325.005932-17.jar:git-SportBukkit-10dd8f3]
[Java ERROR]	org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [sportbukkit-1.8-R0.1-20150325.005932-17.jar:git-SportBukkit-10dd8f3]
[Java ERROR]	org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[sportbukkit-1.8-R0.1-20150325.005932-17.jar:git-SportBukkit-10dd8f3]
[Java ERROR]	in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:44) ~[?:?]
[Java ERROR]	in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:46) ~[?:?]
[Java ERROR]	in.twizmwaz.cardinal.cycle.Cycle.run(Cycle.java:42) ~[?:?]
[21:05:24]	[Server thread/ERROR] : [CardinalPGM] Task #62716 for Cardinal v1.0-SNAPSHOT-git-CardinalPGM-18fb2d4 generated an exception
[21:05:24]	[Server thread/INFO] : World matches/57e2ad9f-1ee6-4b16-940e-6cbd07281e38 is a duplicate of another world and has been prevented from loading. Please delete the uid.dat file from matches/57e2ad9f-1ee6-4b16-940e-6cbd07281e38's world directory if you want to be able to load the duplicate world.
[21:05:24]	[Server thread/INFO] : [0;35;22m# # # # # # # # # # # #
[21:05:24]	[Server thread/INFO] : [0;35;22m# # Game over![0;35;22m # #
[21:05:24]	[Server thread/INFO] : [0;35;22m# # # # # # # # # # # #
[21:05:24]	[Server thread/INFO] : Pablete1234 issued server command: /cycle 0 -f

**Comment by twizmwazin** [comment]
Delete the uid.dat

**Comment by KonatoK** [comment]
Even though this is an issue with the map itself, the plugin should only take care of copying the necessary files (level.dat, region directory, etc).

This will prevent future issues with the same thing.

**Comment by CaptainElliott** [comment]
@konatoK it does,minecraft generates these files when a world is made

**Comment by iEli2tyree011** [comment]
@CaptainElliott "the plugin should only take care of copying the necessary files"

**Comment by CaptainElliott** [comment]
@iEli2tyree011 what? that is what the plugin does

**Comment by KonatoK** [comment]
@CaptainElliott Not really, the Cycle class calls GenerateMap#copyWorldFromRepository, which seems to call FileUtils#copyDirectory with no FileFilter, which means all files are copied, otherwise this issue wouldn't be happening.

**Comment by AngelCasillas01** [comment]
[Reference of how does your map folder should look](https://docs.oc.tc/packaging/cleaning_files)
[Another example](https://docs.oc.tc/packaging/compiling_releasing)

**Comment by CaptainElliott** [comment]
@KonatoK the files inside your map folder should only contain the needed ones as @AngelCasillas01 has shown

**Comment by KonatoK** [comment]
@CaptainElliott I know, as I said this is a map-related problem, but considering Cardinal it's intended to be a "user friendly" plugin, it would be better if it just copies what it needs.
