### ISSUE TITLE
pressing "Q" doesn't delete the item

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#528]
when pressing Q on observers, item shouldn't drop(and it doesnt!), but it should get deleted from the inventory (and it doesn't)

**Comment by AngelCasillas01** [comment]
Maybe this can be by a fail on your server, also provide a cardinal version using `/cardinal -v` on your server.

**Comment by CoWinkKeyDinkInc** [comment]
Had you checked the XML that states it should be removed?

**Comment by Pablete1234** [comment]
what i mean is that it stays on the inventory, and it doesnt get deleted

**Comment by CaptainElliott** [comment]
what currently happens if your drop an item in observers?

**Comment by twizmwazin** [comment]
@CaptainElliott Event is cancelled and nothing happens.

**Comment by CaptainElliott** [comment]
Will fix when I wake up

**Comment by Alfalik** [comment]
This seems to occurs again, hope it gets fixed.
