### ISSUE TITLE
Match upload throws an NPE

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#533]
How to view the stats in the page?

**Comment by twizmwazin** [comment]
Click on the provided link?

**Comment by ItzWid13** [comment]
Isnt give me a link

**Comment by twizmwazin** [comment]
Post a screenshot

**Comment by ItzWid13** [comment]
Ok http://prntscr.com/6p9xws

**Comment by ItzWid13** [comment]
http://prntscr.com/6p9yey

**Comment by twizmwazin** [comment]
Is there a message in your logs?

**Comment by ItzWid13** [comment]
http://prntscr.com/6pa0eq

**Comment by twizmwazin** [comment]
I think this may be related to the client's set language

**Comment by twizmwazin** [comment]
Fixed in 0402e3b15a51d891c3670adb2f87ae96640c68aa
