### ISSUE TITLE
Opponent's Captured Wools Not Showing on Scoreboard

### ISSUE THREAD

**Issue by ajtag5** [twizmwazin/CardinalPGM#534]
When playing CTW, you are able to see the wools you have touched and captured on the scoreboard, however you cannot see the wools the opponents have captured. I understand you are not supposed to see the wools your opponents have *touched*, however you should be able to see those they have *capped*.

**Comment by knightopress** [comment]
There's also the issue of random letters like "rr" appearing before the infinity sign on certain maps as shown here: https://youtu.be/ZaZfkSjXDlQ.
