### ISSUE TITLE
Moving results in a console error

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#536]
Every time I Move (tested in observers, in Boom TE) the console prints an error. I have cmdbook installed, but it gives the error even without it. I have the latest version of cardinal, and the latest version of sportbukkit 1.8.
Log: http://pastebin.com/ZyDiSknn

**Comment by iEli2tyree011** [comment]
Can you upload your map.xml and the result of /cardinal -v?

**Comment by Eudaldca** [comment]
The versiin was the latest at the time of the post, and the map.xml is the one on maps.oc.tc.

**Comment by twizmwazin** [comment]
@Eudaldca Just do /cardinal -v, it makes our lives so much easier.

**Comment by iEli2tyree011** [comment]
Can anyone else confirm this? The latest XML and plugin work fine for me.

**Comment by SungMatt** [comment]
@iEli2tyree011 I can't confirm this. Running Sportbukkit 715f5f8 (April 3rd release), Cardinal 31226cb.

**Comment by Eudaldca** [comment]
If you let me tomorrow I'll record it

**Comment by twizmwazin** [comment]
@Eudaldca Try updating Cardinal first

**Comment by iEli2tyree011** [comment]
@Eudaldca Also make sure you copy the latest XML for Boom TE.

**Comment by Eudaldca** [comment]
I was using an xml from maps.oc.tc, I just checked, and it was due to the xml. Now I'm using the one from HoC, I really don't know what XML was that. The one that causes errors is this: http://pastebin.com/FLkCcgxH

**Comment by iEli2tyree011** [comment]
@Eudaldca I'm not sure where you got that XML, but the issue is that it's trying to get region `end` when there is no region with that name exists.
