### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by ElFlambMC** [twizmwazin/CardinalPGM#54]
Plugin org.apache.maven.plugins:maven-clean-plugin:2.4.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.4.1: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.4.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out: connect -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by CaptainElliott** [comment]
Is this an issue when your compiling the plugin to use or getting the dependencies to develop it?

**Comment by ElFlambMC** [comment]
compiling

**Comment by twizmwazin** [comment]
@CaptainElliott The message is copied from the maven build log. It seems he cannot connect to the maven central repository, rather than an issue with the plugin itself.

**Comment by ElFlambMC** [comment]
@twizmwazin how can i solve this?

**Comment by rywarsaw** [comment]
@ElFlambMC Your getting this error because you can't connection the repository. There are several reasons for this, most likely a firewall or anti-virus plugin which is blocking it. Try disabling these and see if that corrects your issue. Don't forget to re-enable it afterwards.

**Comment by elespawol** [comment]
if not, test to compile on anther computer....
