### ISSUE TITLE
Scoreboxes bug

### ISSUE THREAD

**Issue by StraferBoy** [twizmwazin/CardinalPGM#543]
Like this http://prntscr.com/6pnqls

**Comment by StraferBoy** [comment]
He died not and he cored too much times

**Comment by AngelCasillas01** [comment]
#489

**Comment by Vixo1** [comment]
That version is what i did for sportbukkit 1.7, so, don't report bugs of that version, because it may be buggy...

**Comment by twizmwazin** [comment]
Please post the result of /cardinal -v

**Comment by AngelCasillas01** [comment]
@twizmwazin Isn't the same this and  #489 ?

**Comment by TiTo-418** [comment]
@AngelCasillas01 He no died
