### ISSUE TITLE
add something to  detect new map XML

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#544]
On tm server work like this

example:
cycled to spaceship battles!
`<objective>`
Detected new XML changes

**Comment by twizmwazin** [comment]
I have no idea what you are talking about, and it sounds unnecessary.

**Comment by AngelCasillas01** [comment]
@twizmwazin Example
You update your map.xml of ssb
You recycle or cycle to ssb
and you don't need to stop and start the server

**Comment by SuHoney** [comment]
@AngelCasillas01 You mean updates map's xml automatically?

**Comment by AngelCasillas01** [comment]
@SuHoney yes, when you put a newer XML on the map folder 😅 i'm sorry

**Comment by twizmwazin** [comment]
Cardinal will already use a new XML when you cycle.

**Comment by AngelCasillas01** [comment]
@twizmwazin sorry :(

**Comment by twizmwazin** [comment]
It's ok, and you shouldn't get rid of the text

**Comment by AngelCasillas01** [comment]
@twizmwazin i know but it's bad to let this topic like were on the past, again sorry
