### ISSUE TITLE
Region coordinates should not be floored

### ISSUE THREAD

**Issue by Avygeil** [twizmwazin/CardinalPGM#551]
Commit 68442c1565d3dd4b058f5caadfd638b8d287e98e added floored vectors to regions and parsers.

Coordinates should be real numbers and rounding them breaks some mechanisms, like circles and cylinders centered on the middle of a block:
<a href="https://oc.tc/forums/topics/52dc171312ca95a3fa0012a2">
   <img src="http://i.imgur.com/SU3GuFY.png">
</a>

This region cannot work if its center is floored, as it will just be pushed to the lower corner of the middle block (tested and working on build 111 but not on build 112).

**Comment by iEli2tyree011** [comment]
Thanks
