### ISSUE TITLE
Can exceed the max amount of players per team

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#553]
E.G. Cannon Duel

**Comment by RubeGamerV** [comment]
probably xml have [max-overfill="2"] or teams will be forced

**Comment by AngelCasillas01** [comment]
@RubeGamerV On maps.oc.tc says 1, this is due to team force, we should reduce the power of the /team force

**Comment by TiTo-418** [comment]
Isn't fixed

**Comment by iEli2tyree011** [comment]
@TiTo-418 Can you give some more details for which case this isn't working in?

**Comment by TiTo-418** [comment]
Sure, i ll make a video

**Comment by SungMatt** [comment]
@TiTo-418 @iEli2tyree011 

Cannot reproduce.

Replication procedure assumed to be as followed:
1. Load a map with a low `max-overfill` tag
2. Join via `/join <team>` to fill a team
3. ???
4. Profit

Was not able to replicate issue.

[Video](https://www.youtube.com/v/0oWEXBUfI84)


*Tested in Cardinal version `00756e5`*

**Comment by TiTo-418** [comment]
@SungMatt Try that in a non-blitz map.

**Comment by TiTo-418** [comment]
Fixed with the team branch, i will reopen is happens again

**Comment by TiTo-418** [comment]
<a href="http://imgur.com/iKAl0Dv"><img src="http://i.imgur.com/iKAl0Dv.png" title="source: imgur.com" /></a>

**Comment by TiTo-418** [comment]
@Pablete1234 Could you explain the issue?

**Comment by Pablete1234** [comment]
You can bypass the team "max" because that's the "non-vip" max, in cardinal everyone is treated as if they had vip, they can select their team and they can bypass the regular max, what they can't bypass is the "maxOverfill", and some maps don't even have one
What i think would solve this issue is that if maxOverfill is not set, maxOverfill is set to the same as max

**Comment by dentmaged** [comment]
@Pablete1234 https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/module/modules/team/TeamModule.java#L52 and https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/command/JoinCommand.java#L47

That shouldn't happen though.

**Comment by Pablete1234** [comment]
@dentmaged it should happen if it was public matches and you had a dux rank...

**Comment by iEli2tyree011** [comment]
@Pablete1234 We're not adding VIP features in Cardinal. The max-overfill is essentially the maximum amount of players on a team. Since the plugin is designed around scrimmages, the max-overfill can be set to the appropriate number, and then that amount of players can join the team.

**Comment by iEli2tyree011** [comment]
@dentmaged It happens because the max for the team is 10. That is what's displayed in /match. Since everyone has permission to exceed the max, but not the max-overfill, they can join, and it appears that the team is exceeding its limit, similarly to a match on Overcast.

**Comment by Pablete1234** [comment]
@iEli2tyree011 but in tm no one has vip, i think being able to select the team is good, but some maps have the max overfill feature for public matches, but on scrimms the regular max is used, all maps in HOC don't have a max overfill, they only have a 10 players max, and cardinal sets the max overfill to 12, maybe because it's a scrimmage plugin, the max overfill should be set to the max

**Comment by dentmaged** [comment]
@iEli2tyree011 I don't see where it checks the player's permissions.

**Comment by Pablete1234** [comment]
@dentmaged it doesn't need a permision if you want everyone to have it at all times...

**Comment by Eudaldca** [comment]
Not an issue anymore, it now just counts max-overfill instead of the default max.

**Comment by TiTo-418** [comment]
@Eudaldca That's the problem .-.

**Comment by TiTo-418** [comment]
Fixed in https://github.com/twizmwazin/CardinalPGM/commit/7532e7a4087c259c9609f633497ab08bea98436d
