### ISSUE TITLE
Can't use /tp ~ ~1 ~

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#554]
Video proof: http://youtu.be/FC0eXZapeow

**Comment by SungMatt** [comment]
This is more likely a SportBukkit issue, as /tp is not implemented or interfered with in Cardinal. I do know other forks of bukkit (Spigot, CraftBukkit) do not implement /tp with relative coordinates.

**Comment by twizmwazin** [comment]
@SungMatt Actually we did rewrite it. [boop](https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/command/TeleportCommands.java)
