### ISSUE TITLE
Can pick up item frame's items in deny regions

### ISSUE THREAD

**Issue by TiTi-418** [twizmwazin/CardinalPGM#555]

**Comment by iEli2tyree011** [comment]
I'm not sure what this is supposed to mean?

**Comment by TiTo-418** [comment]
You can edit the item frame content, i ll make a video

**Comment by iEli2tyree011** [comment]
Fixed in a70efa4873a15d91cd8a40f4b2d1acf66d30f278

**Comment by TiTi-418** [comment]
Isn't fixed

**Comment by iEli2tyree011** [comment]
@TiTi-418 How so?

**Comment by TiTi-418** [comment]
Im uploading a video.

**Comment by TiTi-418** [comment]
http://youtu.be/6rt76Srs8cc (uploading)
