### ISSUE TITLE
Some names in deaths appears in white

### ISSUE THREAD

**Issue by TiTi-418** [twizmwazin/CardinalPGM#563]
<a href="http://imgur.com/AZW15hE"><img src="http://i.imgur.com/AZW15hE.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/HagJ1yE"><img src="http://i.imgur.com/HagJ1yE.png" title="source: imgur.com" /></a>

**Comment by iEli2tyree011** [comment]
Please do /cardinal -v, and also when you make other issues

**Comment by TiTo-418** [comment]
ed329v1

**Comment by iEli2tyree011** [comment]
Can you try this again on the latest version, and if it doesn't work, then find out how to recreate it?

**Comment by TiTi-418** [comment]
Yeah, i will test it, but i don't know how recreate ir.

**Comment by TiTi-418** [comment]
If this happen again, i ll reopen this
