### ISSUE TITLE
Staff isn't whitelisted automatically

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#566]

**Comment by dentmaged** [comment]
Cardinal uses Bukkit's built-in whitelister, not a custom one.

**Comment by CaptainElliott** [comment]
we do use a custom whitelister https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/command/WhitelistCommands.java

most of it was made by OCN devs but it has been editied for our needs and I plan to make some additions to it also using @ShinyDialga45 unofficial OCN api. I will also implement this

**Comment by dentmaged** [comment]
@CaptainElliott really? O_o

Why does https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/command/WhitelistCommands.java#L52 refer to ```Bukkit.getServer().reloadWhitelist()```? Can you set a custom whitelist object in Bukkit?

**Comment by CaptainElliott** [comment]
@dentmaged I'm sorry, I thought you just meant using the default white list stuff.
But there is really no other way to do a whitelist, especially since the api bukkit has is so flexible

**Comment by Eudaldca** [comment]
If this was done, could it be made via a permission node? This way it can also be applied for other ranks, or removed if you don't want it.

**Comment by dentmaged** [comment]
@Eudaldca I think it may use ```rank.isStaffRank();```
