### ISSUE TITLE
BUG - /maps

### ISSUE THREAD

**Issue by elespawol** [twizmwazin/CardinalPGM#57]
As u can see, if i type /maps 3, it appears a error.... IS VERY STRANGE!
http://gyazo.com/0ecea84d37afac36e7a5bbfd9b963d6e

**Comment by iEli2tyree011** [comment]
How many maps do you have loaded?

**Comment by elespawol** [comment]
20 aprox
El dia 18/01/2015 22.53, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by iEli2tyree011** [comment]
Okay, I'll check the code to see what's wrong.

**Comment by elespawol** [comment]
Ok!
El dia 18/01/2015 22.56, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by twizmwazin** [comment]
@elespawol Can you upload you log? http://pastebin.com/

**Comment by elespawol** [comment]
Yes, but today no, tomorrow 😬
El dia 18/01/2015 23.12, "Kevin Phoenix" <notifications@github.com> va
escriure:
