### ISSUE TITLE
TNT problem (Water push it)

### ISSUE THREAD

**Issue by Thepawer** [twizmwazin/CardinalPGM#571]
I have sportbukkit-1.8-R0.1-20150215.041225-1 and the last Cardinal version.

My bukkit.yml:
# This is the main configuration file for Bukkit.
# As you can see, there's actually not that much to configure without any plugins.
# For a reference for any variable inside this file, check out the Bukkit Wiki at
# http://wiki.bukkit.org/Bukkit.yml
# 
# If you need help on this file, feel free to join us on irc or leave a message
# on the forums asking for advice.
# 
# IRC: #bukkit @ esper.net
#    (If this means nothing to you, just go to http://webchat.esper.net/?channels=bukkit )
# Forums: http://forums.bukkit.org/forums/bukkit-help.6/
# Twitter: http://twitter.com/CraftBukkit
# Bug tracker: http://leaky.bukkit.org/

settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  ping-packet-limit: 100
  use-exact-login-location: false
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  require-all-plugins: false
  deprecated-verbose: default
  shutdown-message: Se cerrï¿½ el server wey
  bungeecord: false
  fetch-skulls: true
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15
chunk-gc:
  period-in-ticks: 600
  load-threshold: 0
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml
database:
  username: bukkit
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: walrus
  url: jdbc:sqlite:{DIR}{NAME}.db
auto-updater:
  enabled: true
  on-broken:
  - warn-console
  - warn-ops
  on-update:
  - warn-console
  - warn-ops
  preferred-channel: rb
  host: dl.bukkit.org
  suggest-channels: true
  water-pushes-tnt: false

I also tried with: 
# This is the main configuration file for Bukkit.
# As you can see, there's actually not that much to configure without any plugins.
# For a reference for any variable inside this file, check out the Bukkit Wiki at
# http://wiki.bukkit.org/Bukkit.yml
# 
# If you need help on this file, feel free to join us on irc or leave a message
# on the forums asking for advice.
# 
# IRC: #bukkit @ esper.net
#    (If this means nothing to you, just go to http://webchat.esper.net/?channels=bukkit )
# Forums: http://forums.bukkit.org/forums/bukkit-help.6/
# Twitter: http://twitter.com/CraftBukkit
# Bug tracker: http://leaky.bukkit.org/

settings:
  water-pushes-tnt: false
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  ping-packet-limit: 100
  use-exact-login-location: false
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  require-all-plugins: false
  deprecated-verbose: default
  shutdown-message: Se cerrï¿½ el server wey
  bungeecord: false
  fetch-skulls: true
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15
chunk-gc:
  period-in-ticks: 600
  load-threshold: 0
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml
database:
  username: bukkit
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: walrus
  url: jdbc:sqlite:{DIR}{NAME}.db
auto-updater:
  enabled: true
  on-broken:
  - warn-console
  - warn-ops
  on-update:
  - warn-console
  - warn-ops
  preferred-channel: rb
  host: dl.bukkit.org
  suggest-channels: true
 

(Note: I had to write water-pushes-tnt: false, because Sportbukkit did not generate it)

**Comment by iEli2tyree011** [comment]
This isn't a Cardinal issue. However, I recommend trying this with the latest download of Sportbukkit. You have a really old version from February 15th, you should try [downloading this version](https://repo.oc.tc/service/local/repositories/snapshots/content/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/sportbukkit-1.8-R0.1-20150404.032812-18.jar) which is much newer.

**Comment by Thepawer** [comment]
I know, but i wanted to know if someone could help me. Thanks you a lot! Maybe it was Sportbukkit problem n_n
