### ISSUE TITLE
(Suggestion) Remove "Join Messages"

### ISSUE THREAD

**Issue by IlPicasso** [twizmwazin/CardinalPGM#573]
I was wondering if we could make Join Messages configurable 

Ridan joined the game.

If we could disable that

**Comment by RubeGamerV** [comment]
type /toggle jms

**Comment by IlPicasso** [comment]
You got me 

Thanks 

^^

**Comment by RubeGamerV** [comment]
close this, because is not a issue

**Comment by Prodigy4532** [comment]
you can use the plugin HideStream for this

**Comment by RubeGamerV** [comment]
@Prodigy4532  no plugins are needed
