### ISSUE TITLE
Blitz doesn't end when one team is dead

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#575]
blitz maps do not end when all of the team members are dead  on one team

for example: cannon duel does not end when one player kills the other (leaving the scoreboard players: 1-0), and the remaining player has to jump to the void, and it will count as if he (the one that just killed himself) is the winner (even tho he died)

**Comment by TiTi-418** [comment]
Update the plugin and try again
Fixed in https://github.com/twizmwazin/CardinalPGM/commit/bf1cf5725bd773325e61afa7f8c9b6aa82a895b7
