### ISSUE TITLE
Add froze system

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#580]
since mods & admins have Team Grief utility, we can add a frozing system just like you want, maybe isn't useful 😕 and sorry if is 🙈

**Comment by CaptainElliott** [comment]
This is not something we are going to implement into the main plugin

**Comment by AngelCasillas01** [comment]
@CaptainElliott  Why did you say "the main plugin" (sorry if you mean another thing)

**Comment by CaptainElliott** [comment]
I believe @ShinyDialga45 is making a utility plugin with things that we don't want to have in this plugin

**Comment by AngelCasillas01** [comment]
@CaptainElliott Oh i didn't knew it sorry 🙈

**Comment by RubeGamerV** [comment]
CommandBook have freeze command and is comaptible with SB
