### ISSUE TITLE
Anyone can leak own Core, and map cycling feature after finishing a match where is? (DTC)

### ISSUE THREAD

**Issue by ignorantcross** [twizmwazin/CardinalPGM#588]
![captura de pantalla 243](https://cloud.githubusercontent.com/assets/8921248/7108783/b9236e4c-e155-11e4-8c01-11be3701aa8a.png)

Thank you

**Comment by TiTi-418** [comment]
Podes preguntarlo en espanol? Intentare reslover las dudas pero no entendi bien lo que queres decir:
1. No podes lekear tu core, a menos que este mal el XML
2. Para cambiar al mismo mapa pon /recycle 0
3. Si queres que se cambie automaticamente podes hacerlo desde config.yml:

**Comment by CoWinkKeyDinkInc** [comment]
If the XML is set up properly, you shouldn't be able to break your own core, not even in creative mode.

**Comment by ignorantcross** [comment]
the XML is set up properly, it has gotten from maps.oc.tc repository

**Comment by SungMatt** [comment]
@ignorantcross Please note that a lot of map downloads do not have the same coordinates of the cores in-game and in the XML. For example, Oculo has an observers spawn that is 500 blocks away from the xml on maps.oc.tc . 

I could try fixing the XML for you, but you can do it yourself by getting the coordinate boundaries of the cores, and changing them in the XML. It shouldn't be too hard, just inputting 6 sets of numbers per core.

**Comment by ignorantcross** [comment]
I didn't know about I must edit the XML code, thankyou.

**Comment by CoWinkKeyDinkInc** [comment]
You have to assign the core to a team that defends it.  That is all that's needed to stop them from breaking their own core.  You can just mention them by colour `blue` or by their full name `Blue Team`.

**Comment by iEli2tyree011** [comment]
@CoWinkKeyDinkInc You should never use a team's display name in the XML. It should always be their ID, which in this case is `blue` because the blue team's element would have `id="blue"`.
