### ISSUE TITLE
cant join a match, cant type in chat before running /t or /g, and many more bugs.

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#590]
i updated to the latest cardinal built, but now i have a looot of issues. The server gets stuck when /recycling, when you cycle, the observers spawn at the normal spawns instead of the actual observer spawns, the players cant chat unless they run /t or /g, the players cant join a game. The time moves to during matches, it doenst pause. 

http://i.imgur.com/2puVJUd.png

i got this in my console when running /join:

http://pastebin.com/DXLaWibz

**Comment by twizmwazin** [comment]
As stated about 2 million times, we do not support 1.7. Upgrade your server to 1.8.

**Comment by kroest** [comment]
sorry, i missed that. may i ask what is the latest version that supports 1.7?

**Comment by dentmaged** [comment]
@kroest There is a version, but it doesn't work. Please use 1.8.
