### ISSUE TITLE
Scoreboard has multiple teams

### ISSUE THREAD

**Issue by dentmaged** [twizmwazin/CardinalPGM#591]
I don't know how this is happening!

![Image](http://i.imgur.com/9r42NYQ.png)

**Comment by CaptainElliott** [comment]
are you able to reproduce it? does the map use blitz?

**Comment by dentmaged** [comment]
Nope, Boom TE. I have also noticed it on Fractal Descent TE. Here is the XML: http://www.mediafire.com/view/akzufj9cmhv4cb0/map(2).xml

**Comment by iEli2tyree011** [comment]
For some reason, Boom TE is using a timer in the score module to time the match..

**Comment by Alfalik** [comment]
@dentmaged Use ```<time result="objectives">10m</time>``` instead of ```<score>
		<time>10m</time>
	</score>```

**Comment by iEli2tyree011** [comment]
@Alfalik The plugin is supposed to replicate the behavior of PGM, not only work under certain conditions.

**Comment by Alfalik** [comment]
@iEli2tyree011 Firstly, both xml at <a href="http://maps.oc.tc">maps.oc.tc</a> use ```<time result="objectives">10m</time>``` (<a href="https://maps.oc.tc/Other/Tournament/Breaking%20Core/Boom/map.xml">BC Version</a> & <a href="https://maps.oc.tc/Other/Tournament/House%20of%20Cores/Boom%20TE/map.xml">HoC Version</a>), not ```<score> <time>10m</time> </score>```
Second, theres a big difference between ```<score>``` & ```<time>``` modules. As you can see here <a href="https://docs.oc.tc/modules/gamemode_tdm">(click me)</a> ```<score>``` is used for TDM maps. And, the ```<time>``` module is used to set a Time Limit <a href="https://docs.oc.tc/modules/other_settings">(click me)</a>

**Comment by TiTi-418** [comment]
Can't reproduce 
<a href="http://imgur.com/kK0qH6W"><img src="http://i.imgur.com/kK0qH6W.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/VGiZn3P"><img src="http://i.imgur.com/VGiZn3P.png" title="source: imgur.com" /></a>

**Comment by SungMatt** [comment]
Cannot reproduce in maps stated, however can be reproduced in other maps.
Boom TE:
![screen shot 2015-04-14 at 11 05 35 am](https://cloud.githubusercontent.com/assets/6725727/7129688/33b9136e-e296-11e4-92e0-55b5b0dbca06.png)

Reproducible in Dead Heat:
![screen shot 2015-04-14 at 11 04 17 am](https://cloud.githubusercontent.com/assets/6725727/7129687/33b8bdec-e296-11e4-9f5a-ee0699af7760.png)

*Running CardinalPGM version `18a0ea8`*

**Comment by dentmaged** [comment]
@Alfalik That fixed it thanks!

![Updated XML](http://i.imgur.com/5if2XUJ.png)

**Comment by iEli2tyree011** [comment]
@dentmaged Where did you get the XML from?

**Comment by dentmaged** [comment]
@iEli2tyree011 I can't remember, I think I redid quite a bit of Boom TE's XML so that is probably why!
