### ISSUE TITLE
Scoreboard issue

### ISSUE THREAD

**Issue by TiTi-418** [twizmwazin/CardinalPGM#593]
<a href="http://imgur.com/Er207aV"><img src="http://i.imgur.com/Er207aV.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/lhczvW2"><img src="http://i.imgur.com/lhczvW2.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/yV7PGuP"><img src="http://i.imgur.com/yV7PGuP.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/CNUQu57"><img src="http://i.imgur.com/CNUQu57.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/rnoW7XO"><img src="http://i.imgur.com/rnoW7XO.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/9j1utrg"><img src="http://i.imgur.com/9j1utrg.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/QjJHJue"><img src="http://i.imgur.com/QjJHJue.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/dCK5h1M"><img src="http://i.imgur.com/dCK5h1M.png" title="source: imgur.com" /></a>

**Comment by MysticxPvP** [comment]
Isn´t fixed

<img src="http://i.gyazo.com/1837970899d9598591d9ae21a1b45345.png">

**Comment by twizmwazin** [comment]
@MysticxPvP That isn't the map that is in the public rotations. Get that version and use OCN's XML, not your own. Then reconfirm for us please.

**Comment by MysticxPvP** [comment]
@twizmwazin 

Still happen:

![2015-04-24_20 53 26](https://cloud.githubusercontent.com/assets/11577297/7331020/72680ecc-eac4-11e4-9451-0680b6e0c1f8.png)
![2015-04-24_20 54 11](https://cloud.githubusercontent.com/assets/11577297/7331021/74830ebe-eac4-11e4-8878-4ddfee095284.png)

XML (maps.oc.tc): http://pastebin.com/BaSnCTjN

**Comment by iEli2tyree011** [comment]
@MysticxPvP This isn't related to the issue, can you make a new issue?

**Comment by MysticxPvP** [comment]
@iEli2tyree011 Ok, np
