### ISSUE TITLE
Multitrade not implemented

### ISSUE THREAD

**Issue by youngpvprock** [twizmwazin/CardinalPGM#595]
Some errors with vills 
http://pastebin.com/177bRz3F

Also the villager can't be open when other is trading, on trade they give xp while it shouldn't and finally, the trades from vills don't end in the custom trades, they also have the normal trades. The map i'm testing it is this --> http://www.mediafire.com/download/7c060s5b2wtk78k/Facility.zip

Also i would like to say that in countdowns for TDM in last seconds like 00:30 or other dont have sound, just appear the message in chat.

**Comment by youngpvprock** [comment]
Sorry for poor english, i'm spanish.

**Comment by TiTi-418** [comment]
Sounds: https://github.com/twizmwazin/CardinalPGM/issues/227

**Comment by CaptainElliott** [comment]
The issue with with the custom trades and other trading issues could be down to the map being made in 1,8. 

However the multitrade feature must not yet have been implemented

**Comment by twizmwazin** [comment]
@CaptainElliott Can confirm the multitrade part not yet being implemented.

**Comment by youngpvprock** [comment]
And there are plans to implement it in a future?

**Comment by twizmwazin** [comment]
@youngpvprock In time

**Comment by Pablete1234** [comment]
Shouldn't therse be in different issues?

**Comment by TiTo-418** [comment]
@Pablete1234 This is just one issue
> However the multitrade feature must not yet have been implemented

**Comment by TiTo-418** [comment]
@iEli2tyree011 @twizmwazin Can you rename this to "Multitrade not implemented" or something like that? Thanks

**Comment by Pablete1234** [comment]
@Tito-418 this was "Multitrade not implemented" + "Time notifications module don't have sounds"

**Comment by dentmaged** [comment]
@Pablete1234 They are to separate issues.

**Comment by Alfalik** [comment]
Just to clarify, the multitrade tag has been removed (https://oc.tc/revisions/plugins & https://github.com/OvercastNetwork/docs.oc.tc/commit/7921c97d9f727329d8ea366c8ca09e8477c4c1eb). But anyway it'll be enabled always (still need to be coded).

**Comment by TiTo-418** [comment]
Fixed in https://github.com/twizmwazin/CardinalPGM/commit/199b29418b569735abc2891f9b75fe0fd3c6bc2b
