### ISSUE TITLE
Blocks regenerate far too quickly in-game, and regenerate more slowly in obs

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [twizmwazin/CardinalPGM#596]
If you are in a match, and you break a "transparent" block, like a torch, grass, flowers etc, and it is in a region where you can't break blocks, it instantly regenerates the second it is broken.  This can cause lag issues, especially with torches.  Holding down the left click causes this effect.  In observers, breaking these blocks don't instantly regenerate and cause this lag issue.

**Comment by twizmwazin** [comment]
Is there a known workaround or fix for this? I think this is just how Minecraft works, and there isn't really a good server-side fix to this.

**Comment by CoWinkKeyDinkInc** [comment]
Blocks don't instantly regenerate in observers, and have a reasonable delay of about 1/4th of a second.  In fact, all blocks regenerate instantly while in teams.  Instant breakable items like torches cause this.

**Comment by twizmwazin** [comment]
@CoWinkKeyDinkInc But how does this behavior differ from Overcast's?

**Comment by CoWinkKeyDinkInc** [comment]
@twizmwazin On OCN all blocks regenerate at about 1/4th of a second on obs and teams, holding down left click on a team does not cause lag like I've mentioned previously.

**Comment by Alfalik** [comment]
@CoWinkKeyDinkInc This have a direct relation with ping and the amount of RAM that the player and server have. I don't think this is an issue that can really be fixed.

**Comment by twizmwazin** [comment]
@Alfalik Ram doesn't have a direct relation to preformance.

@CoWinkKeyDinkInc Was this tested and confirmed on a server that you have approximately the same ping to as Overcast?

**Comment by CoWinkKeyDinkInc** [comment]
@twizmwazin This was tested on my computer that was also running the server.

**Comment by SungMatt** [comment]
@CoWinkKeyDinkInc What's your ping to overcast then? Pinging to your local server should not take more than 1ms

**Comment by twizmwazin** [comment]
Closing as this seems to just be an effect of ping.
