### ISSUE TITLE
Kits not applied in region when teleported by Scorebox

### ISSUE THREAD

**Issue by dentmaged** [twizmwazin/CardinalPGM#597]
I don't know why this is happening
I am running Cardinal Version 6b1135d

Video: https://youtu.be/_IYyc8n2SSo

**Comment by RubeGamerV** [comment]
wheres is the xml

**Comment by CaptainElliott** [comment]
PGM only checks when a player enters a region, that's why you are experiencing this bug. However we should allow the apply kit to be checked when a player is teleported

**Comment by dentmaged** [comment]
@CaptainElliott It worked on OCN. However, isn't a PlayerMoveEvent fired when a player is teleported?

**Comment by CaptainElliott** [comment]
@dentmaged probably but it checks if you enter the region bot if you are in it

**Comment by TiTi-418** [comment]
@RubeGamerV https://maps.oc.tc/TDM/Standard/Zap/map.xml

**Comment by twizmwazin** [comment]
Should be fixed with f44ed208b9820e13170bfeeded0255e76d9778dd
