### ISSUE TITLE
Change lang?

### ISSUE THREAD

**Issue by youngpvprock** [twizmwazin/CardinalPGM#601]
I didn't know where i can ask it, so i puto it here, delete it after. So i see in files that exists some xml with different language but i don't find where i select one of them so, can help me please..

**Comment by twizmwazin** [comment]
Don't ever delete an issue. The language of messages Cardinal sends to a player depends on the client's language. The language of messages sent to the console depends on the system language of the server.

**Comment by dentmaged** [comment]
You can change your client language in Options or on the title screen.
