### ISSUE TITLE
Proximity alarm error

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#607]
+ Video proof: https://youtu.be/mvc-mBeEMbU
+ Entire log: http://pastebin.com/5dBJxhrC
+ XML: http://pastebin.com/h2fV1FUd
+ Cardinal version  6f04c0c: http://gyazo.com/e0a3e6968c7c60d1bc51793cbf6cf1d0

**Comment by dentmaged** [comment]
I attempted to fix this bug, but I don't know what to do. If you look at OCN's docs it doesn't specify 'notify' either.

**Comment by CaptainElliott** [comment]
probably becasue there is no `notify`. I just need to make it default to notifying all players
