### ISSUE TITLE
Ender blast problems

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#608]
- [x] ~~Endstone cuboid can't be broken: http://youtu.be/PlLt4nD7Jh4~~ fixed in beb06774
- [x] No velocity and tps in the spawn area                ^
- [x] Proximity alarm error: https://github.com/twizmwazin/CardinalPGM/issues/607
- [x] ~~Can place water near Endstone Cuboid~~ fixed in 1bbae99
- [x] The wool room can be broken with tnt

Related with https://github.com/twizmwazin/CardinalPGM/issues/153 , https://github.com/twizmwazin/CardinalPGM/issues/120 and https://github.com/twizmwazin/CardinalPGM/issues/605

**Comment by TiTo-418** [comment]
Ender blast was removed from the rotations, i think we should close this and reopen when it be reuploaded

**Comment by iEli2tyree011** [comment]
Just because a map isn't in the Overcast Network rotations doesn't mean it shouldn't work properly with Cardinal.

**Comment by TiTo-418** [comment]
@iEli2tyree011 I know, but maybe there were errors for the xml, i don't know

**Comment by twizmwazin** [comment]
@TiTo-418 I have a funny feeling that isn't why it was removed

**Comment by Pablete1234** [comment]
@twizmwazin I read somewhere in oc.tc forums that the map makers decided to remove it bcos it played poorly (or that's what they said)

**Comment by Pablete1234** [comment]
Tested and wool room can't be broken with tnt anymore
