### ISSUE TITLE
No match page upload when you run /cycle -f 0

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#610]
<a href="http://imgur.com/9lejbaw"><img src="http://i.imgur.com/9lejbaw.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/5RLF3TR"><img src="http://i.imgur.com/5RLF3TR.png" title="source: imgur.com" /></a>

**Comment by dentmaged** [comment]
I tried this the other day,  are you sure it didn't send the message after cycling?

**Comment by iEli2tyree011** [comment]
@dentmaged The module is unloaded and has no access to the other stats modules when the map is immediately ended and cycled from.

**Comment by dentmaged** [comment]
@iEli2tyree011 For me, maybe the message had been sent, but it was in the packet queue?

**Comment by TiTo-418** [comment]
<a href="http://imgur.com/uXCoJZQ"><img src="http://i.imgur.com/uXCoJZQ.png" title="source: imgur.com" /></a>

**Comment by twizmwazin** [comment]
Closing as this feature is being removed due to incompleteness
