### ISSUE TITLE
/score error

### ISSUE THREAD

**Issue by TiTi-418** [twizmwazin/CardinalPGM#612]
<a href="http://imgur.com/y0kLPgj"><img src="http://i.imgur.com/y0kLPgj.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/eHsGXv1"><img src="http://i.imgur.com/eHsGXv1.png" title="source: imgur.com" /></a>

**Comment by TiTi-418** [comment]
I think this is related to https://github.com/twizmwazin/CardinalPGM/issues/609
The /score take notice from proximity although there isn't time limit seted

**Comment by iEli2tyree011** [comment]
Proximity is still tracked no matter the time limit, the only thing changed when you add the time limit is the display of the scoreboard prefix. 

This behavior is intended.

**Comment by TiTi-418** [comment]
But if you want a match without proximity like the above?

**Comment by iEli2tyree011** [comment]
Proximity is always kept track of to determine a winner.
Regardless, in that match, a winner is never determined by the plugin unless a time limit is added.

**Comment by TiTi-418** [comment]
Yes, thanks
