### ISSUE TITLE
Getting CME when loading large number of maps

### ISSUE THREAD

**Issue by SungMatt** [twizmwazin/CardinalPGM#614]
Some maps fail to load with a ConcurrentModificationException error, which seems to be Blitz maps. However, not all Blitz maps fail to load.
When the number of maps in the folder is reduced to just the errored maps, the error does not persist.

If the full log is needed, do tell me.

Here is the error:
![screen shot 2015-04-19 at 10 23 45 am](https://cloud.githubusercontent.com/assets/6725727/7217909/3dd72476-e67e-11e4-825f-a0badcd5076c.png)
![screen shot 2015-04-19 at 10 24 31 am](https://cloud.githubusercontent.com/assets/6725727/7217910/4f4f2140-e67e-11e4-84c1-beee75501ac8.png)

The stack trace seems to be the same for both.

**Comment by iEli2tyree011** [comment]
Can you pastebin the XMLs of a couple of the maps that throw CMEs?

**Comment by SungMatt** [comment]
Here's the XML for [4K](http://pastebin.com/0JFZDNcK) , [Gooseberry](http://pastebin.com/9EA2U2xr) and [Plus Side](http://pastebin.com/PH3uNP1T).

If you do need the entire map directory, I could send it (Its pretty big though, at 2.7 GB)

**Comment by SungMatt** [comment]
Thanks!
