### ISSUE TITLE
Warning in compile

### ISSUE THREAD

**Issue by elraro** [twizmwazin/CardinalPGM#615]
[INFO] --- scriptus:0.1:describe (default) @ CardinalPGM ---
[WARNING] Failed to get HEAD commit hash: java.lang.NullPointerException:null
[INFO] Set property "describe" to "git-CardinalPGM-unknown"

Master branch.

**Comment by Prodigy4532** [comment]
You using Java 7JDK and Maven??

**Comment by elraro** [comment]
Maven 3

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Second, i will test with openjdk 7

**Comment by Prodigy4532** [comment]
You need Java7 JdK for compiling this plugin

**Comment by Prodigy4532** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

**Comment by elraro** [comment]
Dont worry about Java version. It must work with 7, 8, 9 or 999. Its Java.

BTW, same with openJDK7.

java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

**Comment by SungMatt** [comment]
Java 8 works too.

**Comment by elraro** [comment]
Ok, was my fault.

Next time use git clone.

I can compile the plugin with Maven and console command, works great. But i want to add the project to Eclipse (Import -> Maven proyect), but i get this error in pom.xml

Plugin execution not covered by lifecycle configuration: net.md-5:scriptus:0.1:describe (execution: default, phase: initialize)

Thanks for your help guys.

**Comment by twizmwazin** [comment]
@Prodigy4532 Cardinal can be built with Java 7 or higher, and regardless of which JDK it is built with, it will require Java 7 to run. 

@elraro I believe the issue is that eclipse handles maven oddly, having an eclipse plugin for each maven plugin. I don't think their is an eclipse plugin for scriptus. If you would rather not work around it, I would suggest using IntelliJ.
