### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by youngpvprock** [twizmwazin/CardinalPGM#616]
Sometimes server crash. I let server crash log here if it can help, but i think that i happend when throw an item into lava.

http://pastebin.com/xfPXBsKi

**Comment by SungMatt** [comment]
I can't replicate it, are you not using SportBukkit?

**Comment by MysticxPvP** [comment]
#511 Download this version of sportbukkit: https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/sportbukkit-1.8-R0.1-20150414.070927-20.jar

You are using an old version of Sportbukkit
