### ISSUE TITLE
No height limit in fractal descent

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#617]
XML: https://maps.oc.tc/Other/Tournament/House%20of%20Cores/Fractal%20Descent%20TE/map.xml
Include XML: https://maps.oc.tc/Other/Tournament/House%20of%20Cores/house-of-cores.xml

**Comment by SungMatt** [comment]
Adding `<maxbuildheight>(max height)</maxbuildheight>` in to your XML will fix it.

**Comment by TiTo-418** [comment]
This should be work http://gyazo.com/7797d6bfbd9239869dac7e4405415674

**Comment by iEli2tyree011** [comment]
@TiTo-418 Can you post the logs when running a match and placing some blocks above the height limit?

**Comment by TiTo-418** [comment]
sure :)

**Comment by twizmwazin** [comment]
@TiTo-418 What is the message you get? Or is there no message?

**Comment by TiTo-418** [comment]
http://youtu.be/gljO7wRG1gY (uploading...)
There aren't messages

**Comment by twizmwazin** [comment]
The issue is most likely related to included files.

**Comment by iEli2tyree011** [comment]
@TiTo-418 How are there no logs? There's always logs, regardless of an error.

**Comment by TiTo-418** [comment]
@iEli2tyree011 http://pastebin.com/YHEWuHBe

**Comment by iEli2tyree011** [comment]
@TiTo-418 Thanks

**Comment by iEli2tyree011** [comment]
@TiTo-418 Where did you put the `house-of-cores.xml` file?

**Comment by twizmwazin** [comment]
The issue seems to be fixed, it behaves as expected.

**Comment by TiTo-418** [comment]
What? You can built to 256...

**Comment by twizmwazin** [comment]
My copy works perfectly fine, check your XML

**Comment by TiTo-418** [comment]
You can place tnt in height 61?
