### ISSUE TITLE
Mysql / sqlite?

### ISSUE THREAD

**Issue by youngpvprock** [twizmwazin/CardinalPGM#620]
Can add a way to save the stats so the stats can be saved and don't be deleted after each game?

**Comment by twizmwazin** [comment]
Stats should be saved with the flat-file database. Implementing support for multiple database types is planned, including MySQL and SQLite. I'm going to close this, as progress will be tracked with #219.

**Comment by youngpvprock** [comment]
The flat-file don't save anything, when maps cycle or server stop andstart again they reset to 0. Anyway i'll wait for mysql.

**Comment by RubeVi** [comment]
@youngpvprock flat file database only keep players settings, uuid and snowflakes ATM
