### ISSUE TITLE
Scoreboard issue

### ISSUE THREAD

**Issue by MysticxPvP** [twizmwazin/CardinalPGM#622]
- Battle Ecliptica II: 

![2015-04-24_20 53 26](https://cloud.githubusercontent.com/assets/11577297/7334261/1e6f04a2-eb54-11e4-9d0e-3897d06127f0.png)

![2015-04-24_20 54 11](https://cloud.githubusercontent.com/assets/11577297/7334262/272694f2-eb54-11e4-9df7-d1708fd0ea71.png)

- Battle Ecliptica II TE:

![2015-04-24_22 11 51](https://cloud.githubusercontent.com/assets/11577297/7334266/3151b254-eb54-11e4-8ecb-1627074cab09.png)

Cardinal version: 9815475

**Comment by Prodigy4532** [comment]
You have Battle Ecliptica II:TE?

**Comment by MysticxPvP** [comment]
@Prodigy4532 this isn´t related with the issue...
but... yes, i have it.

**Comment by TiTo-418** [comment]
@Prodigy4532 [This isn't related with the issue](https://oc.tc/forums/topics/539dee7967d522ca020024a6?page=1#539df15067d522d3a90023ba)

**Comment by iEli2tyree011** [comment]
@Prodigy4532 @MysticxPvP @TiTo-418 Can we please bring this back on topic? Please use Skype if you need to talk about maps.

**Comment by MysticxPvP** [comment]
@iEli2tyree011 Sorry
