### ISSUE TITLE
Suggestion: Observers in Gamemode 3

### ISSUE THREAD

**Issue by Prodigy4532** [twizmwazin/CardinalPGM#623]
http://gyazo.com/c522af1a309f31195908dbd93758f073

**Comment by twizmwazin** [comment]
This isn't really an issue, and will be considered when there is a fluid way of doing this that doesn't remove functionality.

**Comment by TiTo-418** [comment]
Maybe should be a "toggeable" option
http://gyazo.com/a008993ff7015d686ca4d05d40833316

**Comment by iEli2tyree011** [comment]
@TiTo-418 Spectators don't have a visible inventory

**Comment by TiTo-418** [comment]
@iEli2tyree011 Good point. but:
If you are in gamemode1: lever
If you are in gamemode 3: a command like /sp o /changegm

**Comment by iEli2tyree011** [comment]
Maybe /toggle spectator. That solution seems inconsistent
