### ISSUE TITLE
Proximity doesn't work on wools

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#624]
<a href="http://imgur.com/28ex3rd"><img src="http://i.imgur.com/28ex3rd.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/D6Aork2"><img src="http://i.imgur.com/D6Aork2.png" title="source: imgur.com" /></a>

**Comment by Alfalik** [comment]
What's the actual problem?

**Comment by TiTo-418** [comment]
See the second image

**Comment by Alfalik** [comment]
@TiTo-418 **You** need to kill a player to update the proximity of your team. Not being killed.

**Comment by TiTo-418** [comment]
I didn't know that
