### ISSUE TITLE
Falling block

### ISSUE THREAD

**Issue by youngpvprock** [twizmwazin/CardinalPGM#625]
In the maps where you set that anyone can break, for example if a block of sand or gravel is near of a chest or a button, when you click them you update then near blocks and they fall when it shouldn't. (An example of map to test it is Dust)

**Comment by SungMatt** [comment]
One note to add: the fix must still enable redstone to function, like how Viridun has a lever.

**Comment by twizmwazin** [comment]
@youngpvprock @SungMatt Can someone give me a video of this? I can't even find a valid button to test this with.

**Comment by SungMatt** [comment]
@twizmwazin Sure. Chests also work in updating sand.

**Comment by SungMatt** [comment]
Also, this is more of a block update issue, can I add that ice melts in some maps?

**Comment by SungMatt** [comment]
@twizmwazin Here you go. https://www.youtube.com/watch?v=yjcN0Gg04LE

**Comment by twizmwazin** [comment]
@SungMatt Thanks, I think it should be an easy fix. The music was a fine touch.

**Comment by dentmaged** [comment]
Awww I was really getting into the flow of the music!
