### ISSUE TITLE
Sometimes run /mode push excecute in incorrect order

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#628]
<a href="http://imgur.com/mItd4QK"><img src="http://i.imgur.com/mItd4QK.png" title="source: imgur.com" /></a>

Cardinal version: 5ef7d03c36e1728b22fcf986383e1e45ec895df5

**Comment by SungMatt** [comment]
Only happens in some maps, not all, no idea why though.

**Comment by iEli2tyree011** [comment]
@SungMatt It's probably based on the order in the xml.

**Comment by Prodigy4532** [comment]
In Fractal descent and Revente TE
