### ISSUE TITLE
improve /kick and /ban command

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#631]
right now kick and ban commands have this syntax:
```
/kick <Player> <reason>
/ban <Player> <reason>
```
i think it should be 
```
/kick <Player> [reason]
/ban <Player> [reason]
```
if you put no kick reason the message is just "kicked"
if you put no ban reason the message is just "Permanently banned"

**Comment by TiTo-418** [comment]
+1
