### ISSUE TITLE
Do you can add a "automatic match's start if there are a specific [configurable] amount of players after cycling to a new map and joining the game"?

### ISSUE THREAD

**Issue by BeastPsycho** [twizmwazin/CardinalPGM#633]
I could contribude with "some", i could donate for this project, its so great!

I would do you add a function for auto-starting every match after a cycle, if there are minimum 2 players on server :)

And how i prevent players without rank or "permission" can select their teams "free and overfilling only 1 team"?

**Comment by twizmwazin** [comment]
Cardinal isn't for your network, it is for private scrimmage servers

**Comment by TiTo-418** [comment]
You can donate here: http://twizmwaz.in/donate/
