### ISSUE TITLE
pregunta

### ISSUE THREAD

**Issue by tomastodonte64** [twizmwazin/CardinalPGM#636]
como puedo cambiar los snowflakes para que diga raindros k diga 2,5x ,q este en celeste , etc gracias

**Comment by RubeVi** [comment]
Esto no es una issue

**Comment by iEli2tyree011** [comment]
You can make your own fork and rename them to raindrops if you'd like, but in Cardinal, they are going to be titled "snowflakes".

**Comment by twizmwazin** [comment]
@tomastodonte64 @RubeVi Please keep the issue tracker in English, or provide clear English translations along with your native language. Issue titles should always be in English. None of the developers can speak fluent Spanish.

**Comment by dentmaged** [comment]
@tomastodonte64 Also make sure you change the snowdrop/raindrop colour from white to blue!
