### ISSUE TITLE
Implement rank system

### ISSUE THREAD

**Issue by tomastodonte64** [twizmwazin/CardinalPGM#638]
Hello , I wanted to say if they could implement the Ref range besides the mod, because I am organizing a tournament and I would like to have the reef range , and if already implemented , as placed?

Spanish:
Hola, queria decir si podrian implementar el rango Reef ademas del mod, porque voy a organizar un torneo y me gustaria que tenga el rango reef, y si ya esta implementado, como se coloca?

**Comment by SungMatt** [comment]
Can't you just mod the "Referees"?

**Comment by SelfieOCN** [comment]
Solo dales mod a los árbitros

**Comment by TiTo-418** [comment]
@SelfieOCN "Just give /mod to refs"

**Comment by RubeVi** [comment]
Esto no es una seccion de referencias

**Comment by TiTo-418** [comment]
@RubeVi "This is not a reference section"

**Comment by dentmaged** [comment]
@twizmwazin Shouldn't this have a "missing feature" label?

**Comment by TiTo-418** [comment]
Implemented?

**Comment by iEli2tyree011** [comment]
Added by e042243b83401ec64187bd23dcc730ce0cdb3b1f
