### ISSUE TITLE
Help wanted, ${plugin.name}

### ISSUE THREAD

**Issue by RubeVi** [twizmwazin/CardinalPGM#647]
I don't changed any plugin.yml or stuff like that

<a href="http://gyazo.com/73c3850311e365e181124964acaabb0a"><img src="http://i.gyazo.com/73c3850311e365e181124964acaabb0a.png" /></a>

**Comment by iEli2tyree011** [comment]
Can you pastebin your `pom.xml`?

**Comment by iEli2tyree011** [comment]
Closing as this is a personal issue.

**Comment by RubeVi** [comment]
is the same POM.xml of this plugin

**Comment by iEli2tyree011** [comment]
@RubeVi That doesn't help me. Obviously there's something wrong either in your `plugin.yml`, `pom.xml`, or just importing Maven dependencies. I've seen too many times people claiming they haven't changed anything but ended up just breaking it unknowingly.

**Comment by RubeVi** [comment]
With netbeans

**Comment by RubeVi** [comment]
And i have all the dependencies of the POM.xml

**Comment by twizmwazin** [comment]
You need to build with maven. Don't export with NetBeans.

**Comment by RubeVi** [comment]
I'll do
