### ISSUE TITLE
Touchs

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#65]
http://gyazo.com/aa5450526e647bf1b9a9456abb6e6ba2

In DTC/M the touchs are turned/inverted. 

*A blue player can see the red team touchs but not the own team touchs.

**Comment by iEli2tyree011** [comment]
I'll look into this, thanks.

**Comment by iEli2tyree011** [comment]
This has already been fixed as of #64. Please recompile the plugin and if the problem is still there, please reopen.

**Comment by Alfalik** [comment]
Fixed
