### ISSUE TITLE
Crystal not change to obsidian

### ISSUE THREAD

**Issue by iPolish** [twizmwazin/CardinalPGM#652]
In the map Blocks II if you broke a crystal appears Obsidian (ocn)
And in Cardinal the core leaks when crystal brokes and dont appear obsidian

**Comment by CaptainElliott** [comment]
I don't know what you mean crystal?

**Comment by SungMatt** [comment]
@CaptainElliot Blocks II uses a block replacement mechanic, where in there is a core that looks like a giant potion bottle. When a player breaks the white stained glass (which is the potion bottle, effectively "breaking" the core), PGM replaces the white stained glass with obsidian, so it would be equally hard to destroy as a regular core.

**Comment by SungMatt** [comment]
I believe it is related to the `show` tag in the `<cores>` element not being implemented.

**Comment by twizmwazin** [comment]
Relevant XML so I don't have to go back to the page 500 times

```xml
<blockdrops>
<rule>
<region>
<cuboid min="-139,43,-93" max="-131,49,-85"/>
</region>
<filter>
<block>stained glass</block>
</filter>
<replacement>obsidian</replacement>
</rule>
<rule>
<region>
<cuboid min="-131,43,-251" max="-139,49,-259"/>
</region>
<filter>
<block>stained glass</block>
</filter>
<replacement>obsidian</replacement>
</rule>
</blockdrops>
```
