### ISSUE TITLE
In CTW the proximity appears like "closest player"

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#653]
https://github.com/twizmwazin/CardinalPGM/pull/651

**Comment by Alfalik** [comment]
I already made a PR about this, but no responses. #629

**Comment by TiTo-418** [comment]
In your PR appear like "closest player"
<a href="http://imgur.com/w0QTdza"><img src="http://i.imgur.com/w0QTdza.png" title="source: imgur.com" /></a>

And, why you close it?

**Comment by Alfalik** [comment]
@TiTo-418 That's for cores and monuments, the wools message is here https://github.com/twizmwazin/CardinalPGM/pull/629/files#diff-e04d4c15d64a95603ba962ad735dd3beR48. And I closed it because nobody told me if it was okay, I can't read minds although

**Comment by twizmwazin** [comment]
@Alfalik In the future, you don't need to close pull requests. Feel free to ping me or Elly on a pull request if we haven't commented after a few days.

**Comment by Alfalik** [comment]
@twizmwazin Should I create it again?

**Comment by TiTo-418** [comment]
@Alfalik you can reopen your PR

**Comment by Alfalik** [comment]
@TiTo-418 I deleted my fork, that's why I can't.

**Comment by TiTo-418** [comment]
I think you can reopen it although you delete the fork
