### ISSUE TITLE
Admin star isn't displayed

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#655]
<a href="http://imgur.com/ADKZl9r"><img src="http://i.imgur.com/ADKZl9r.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/tPdE3IN"><img src="http://i.imgur.com/tPdE3IN.png" title="source: imgur.com" /></a>

**Comment by SungMatt** [comment]
Confirmed, *Cardinal version 6e156dc*

**Comment by iEli2tyree011** [comment]
@SungMatt Thank you.  
  
What is the join message, which should be visible from the console?

**Comment by TiTo-418** [comment]
<a href="http://imgur.com/5buBL9H"><img src="http://i.imgur.com/5buBL9H.png" title="source: imgur.com" /></a>
