### ISSUE TITLE
Sometimes, Blitz maps do not properly distribute lives.

### ISSUE THREAD

**Issue by SungMatt** [twizmwazin/CardinalPGM#657]
In multi-life Blitz:RAGE maps, a person can get more than the specified lives in the XML or less than that.

Replication procedure:
 1. In multi-life Blitz maps, die once.
2. After dying, recycle the map using `recycle 0 -f`
3. Note that the lives that you have is now decreased by one.

To get more than one life in a one life map,
1. Play a >1 life game (Let's say it's 2 lives)
2. Don't die, and end the game.
3. Your lives are now carried forward to the next map.

Here's a [Video](https://www.youtube.com/watch?v=fCFcStc89xg).

![screen shot 2015-05-20 at 9 27 11 pm](https://cloud.githubusercontent.com/assets/6725727/7726800/02379bfe-ff37-11e4-9dfb-85816cc12e5c.png) (This screenshot probably doesn't help)

[map.xml for Plus Side](https://gist.github.com/SungMatt/ac0ad288b2de58b968ff)

*Tested in Cardinal version 7a15588*

**Comment by SungMatt** [comment]
Update: I have found the full steps for replication.
1. In multi-life Blitz maps, die once.
2. After dying, recycle the map using `recycle 0 -f`
3. Note that the lives that you have is now decreased by one.

**Comment by SungMatt** [comment]
Here's a [Video](https://www.youtube.com/watch?v=fCFcStc89xg).

**Comment by CaptainElliott** [comment]
I'll look into it after my exams

**Comment by CaptainElliott** [comment]
Could be an issue with the module load time, the module is not being updated
