### ISSUE TITLE
approximate date of launching stage of the finished plugin?

### ISSUE THREAD

**Issue by tomastodonte64** [twizmwazin/CardinalPGM#658]
Says it would be completed by the end of HoC , I am that a lot of work so I ask all kindness as time would fail , because if you love this plugin 'm honest , it's the best plugin to scrimagge away

--TT64--

Español
Dice que estaria terminado al final de HoC , se que es mucho trabajo por eso les pregunto con toda amabilidad cuanto tiempo faltaria, porque si les soy sincero amo este plugin, es el mejor plugin para scrimagge lejos

--TT64--

**Comment by CaptainElliott** [comment]
We do not have a 'finished version' of the plugin. We are maintaining a rolling release type of development, meaning we are pushing updates all the times with bug fixes and new implementations. This means that you should always check fro new versions.

We will not release a 'finished' version of the plugin as we will never be finished developing it, OCN is developing new features all the times - and we always have bugs to patch.
