### ISSUE TITLE
Instant ignite does not check if the block is allowed in a region. 

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#659]
+ Video proof: https://youtu.be/EdKI_ooZVI8
+ Log (no errors although): http://pastebin.com/FXrKccD7
+ Cardinal version 7a15588: http://gyazo.com/073d034a14ba73f47b63af0fb3be9ffa
+ XML:
````xml
<tnt>
	<instantignite>on</instantignite>
	<licensing>off</licensing>
	<friendly-defuse>off</friendly-defuse>
	<fuse>1s</fuse>
	<power>5</power>
</tnt>
```

**Comment by CaptainElliott** [comment]
I'll fix this when I get some more time after exams.
Unless another dev does not get around to it

**Comment by TiTo-418** [comment]
Fixed
