### ISSUE TITLE
Monuments proximity isn't showed in the scoreboard, independent of the number of characters

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#665]
As you can see in this image (<a href="http://i.gyazo.com/12ffa9cf3b48beb9e885f001989a2133.png">first example - Boom TE - Cardinal</a>) the proximity isn't displayed in Cardinal being that in this image of PGM scoreboard (<a href="http://i.gyazo.com/bbdf271894ea3a2f4021352e6841a593.png">second example - Boom TE - PGM</a>). The second and a more difficult case is with longer messages. Here's how now Cardinal shows it right now (<a href="http://i.gyazo.com/5fe8d06ca3e8a7713f94fb218fd39014.png">first example - Fractal Descent TE - Cardinal</a>); now the PGM shows the first 21 characters (in the next case is --> **0%-0/16-§-Left-Monume** nt, the characters number 22 and 23 are removed ("n" and "t" respective)) and the rest or last are removed as showed in this image (<a href="http://i.gyazo.com/649141e8211086b382fa376b892b6d5f.png">second example - Fractal Descent TE - PGM</a>).

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/426

**Comment by iEli2tyree011** [comment]
Color codes are accounted for when using scoreboard prefixes, names, and suffixes. The trade-off in Cardinal is that the scoreboard doesn't flash for proximity changes when the proximity does show. As noted in #426, /proximity can be used to check this in the case that it is not visible on the scoreboard.

**Comment by Alfalik** [comment]
@iEli2tyree011 So, it doesn't have a real solution or fix?

**Comment by iEli2tyree011** [comment]
@Alfalik Not that I'm aware of. What I believe PGM does is I think it considers the name of an objective (out of prefix[16 characters], name[16 characters], suffix[16 characters]) as a simple identifier, then uses the suffix for both proximity and the name of the objective; this is likely in the case that not everything fits in the 16 character prefix. I find this severely limiting, as say you have a proximity of 200.0. That only leaves 10 characters left for the name of the objective, at most. Now, I may be wrong about how PGM solves this, but that is the only fix I can see. And as it's very limiting, I don't think it'd be advantageous to resolve the proximity not fitting using this method.

**Comment by Pablete1234** [comment]
elly, isn't it possible to try to always stick to the prefix method, but when the character limit is higher just use the name and prefix even tho that means it will flash?

**Comment by Pablete1234** [comment]
for example:
§c50% §78/16 §r²⁰⁰∙⁰ Left-Monument
that string = 34 characters
just any string longer than 32 characters will be split into 16/the rest/16
so that means:
prefix: §c50% §78/16 §r²
name: ⁰⁰
suffix: ∙⁰ Left-Monument

**Comment by Eudaldca** [comment]
No longer an issue.
