### ISSUE TITLE
The server doesn't start if it has an invalid rotation.txt

### ISSUE THREAD

**Issue by ghost** [twizmwazin/CardinalPGM#673]
Logs: http://pastebin.com/BE6LUeG9

**Comment by dentmaged** [comment]
Are you sure you have put maps in the map folder?

**Comment by TiTo-418** [comment]
<a href="http://imgur.com/I9tXvDI"><img src="http://i.imgur.com/I9tXvDI.png" title="source: imgur.com" /></a>

**Comment by dentmaged** [comment]
Please may you post your config.yml file?

**Comment by TiTo-418** [comment]
http://pastebin.com/Zkjr7hFL

**Comment by dentmaged** [comment]
@TiTo-418 After restarting your server, does the error still occur?

**Comment by TiTo-418** [comment]
@dentmaged Yes

**Comment by dentmaged** [comment]
@TiTo-418 What does your ```rotation.txt``` file contain?

**Comment by TiTo-418** [comment]
why you're so cool?
i love u

**Comment by TiTo-418** [comment]
http://pastebin.com/CpyLZCMH

**Comment by twizmwazin** [comment]
Still an unhandled exception

**Comment by twizmwazin** [comment]
next guy who makes one of these stupid tags is getting it

**Comment by TiTo-418** [comment]
@twizmwazin Sorry xD

**Comment by Pablete1234** [comment]
@twizmwazin Right now if you open a server without a rotation.txt file the plugin doesn't load, it should just get the first valid map on the repo and just use it as a single map rotation

**Comment by TiTo-418** [comment]
@Pablete1234 The isn't correct, a rotation.txt is generated

**Comment by Pablete1234** [comment]
@TiTo-418 I don't know how it is right now, but a few months ago my server didn't start and it was bcos the rot.txt was missing

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/414

**Comment by twizmwazin** [comment]
@TiTo-418 Is this still an issue?

**Comment by TiTo-418** [comment]
I do not have acces to a computer right now. I will check it on Saturday.

**Comment by TiTo-418** [comment]
@twizmwazin Isn't fixed

**Comment by twizmwazin** [comment]
On what condition does it fail?

**Comment by TiTo-418** [comment]
If there is a line with a map that can not be find on /maps

**Comment by Prodigy4532** [comment]
This issue is fixed no?

**Comment by Pablete1234** [comment]
last time I tested, if the server doesn't have a rotation file, it generates one(and works), but if there is one with invalid maps, it doesn't load

**Comment by twizmwazin** [comment]
I'll take a look at this tonight.

**Comment by Pablete1234** [comment]
To clarify: if the server has no rotation.txt, one containing all maps will be generated, if the server has a rotation, where one of the maps doesn't exist, the server will fail to load

**Comment by Pablete1234** [comment]
fixed in 79f4394
