### ISSUE TITLE
the command "/ restart < time> " is not in the plugin

### ISSUE THREAD

**Issue by Prodigy4532** [twizmwazin/CardinalPGM#678]
In the TM plugin have this command.

**Comment by SungMatt** [comment]
It has the same function as /recycle right? I can probably get a shot at it

**Comment by Prodigy4532** [comment]
No, this command is used to restart the server, without putting " / stop " it is like " / reload" or "/ rl " 2, but with this command you can send a crash

**Comment by Prodigy4532** [comment]
and the server turns on its own

**Comment by SungMatt** [comment]
@Prodigy4532 As far as I know, SportBukkit doesn't really support /reload. A restart is recommended. I have received errors by reloading the server.

**Comment by twizmwazin** [comment]
Cardinal does not support /reload, and I advise against using it. A proper server restart is much better. I may be able to pull strings to get a psuedo-restart.

**Comment by SungMatt** [comment]
@Prodigy4532 Correct me if I'm wrong, but I'm guessing the `restart` command is intercepted by BungeeCord and restarts the server using the shell, and not through the server itself.

**Comment by twizmwazin** [comment]
@SungMatt There are a number of valid ways to implement this, your implementation would definitely be valid in Overcast's context.

**Comment by dentmaged** [comment]
I'm planning to implement this. When you type /restart it will run another jar file (in Cardinal) which will start the server up again.

**Comment by CaptainElliott** [comment]
@dentmaged you should be able to do it by making a script that will rust re execute the jar after the time specified

**Comment by dentmaged** [comment]
@CaptainElliott Good idea! Didn't think of that! But what about Multicraft/McMyAdmin users? McMyAdmin has a plugin called MCMA compat, we could detect for that, but for Multicraft?

**Comment by CaptainElliott** [comment]
@dentmaged I don't understand why you need to check for that? You just need to re execute the batch file that runs the server :)

**Comment by dentmaged** [comment]
@CaptainElliott McMyAdmin automatically starts the server after you type /stop.

**Comment by CaptainElliott** [comment]
If we incorporate it our self players won't need to use it - besides Cardinal does not state it is compatible with other plugins

**Comment by twizmwazin** [comment]
@dentmaged We cannot assume a server is using a specific runtime environment. Windows users will have the server running in a batch environment post likely (unless they use git bash), OS X users will be running in a bash environment, and Linux users could be running one of a million shells, although again most commonly bash. Additionally we can not assume any server management tools, as there are a number of them, and a number of us don't use those tools.

**Comment by twizmwazin** [comment]
I do not think it is appropriate to add this functionality to Cardinal, as the process would vary vy environment. Users are encouraged to restart their server manually.

**Comment by TiTo-418** [comment]
@twizmwazin How Spork manages this?

**Comment by twizmwazin** [comment]
I don't see a single reference to a restart command in Spork

**Comment by Prodigy4532** [comment]
on rixor yes

**Comment by twizmwazin** [comment]
It doesn't actually restart the server, it only stops the server. It needs to restarted manually or by an external task.

**Comment by TiTo-418** [comment]
@twizmwazin And Spigot?

**Comment by twizmwazin** [comment]
doesn't have a command, but rather uses a native script when the server crashes. By default only works on systems using bash or a bash-compatible shell iirc.

**Comment by Pablete1234** [comment]
@twizmwazin most hosted servers use linux-based servers mostly using bash, it's better than nothing, alot of servers would benefit from being able to /restart 5

**Comment by TiTo-418** [comment]
I agree with @Pablete1234

**Comment by twizmwazin** [comment]
You aren't taking into account two major points.
 - Cardinal isn't the server. It doesn't have the same level of control as the server jar, as the plugin will be unloaded before the server itself stops.
 - These hosts you are describing more than likely block runtime access, mostly for security reasons.
