### ISSUE TITLE
Global mute lets you execute /me

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#680]
When in global mute, you can still do /me. It was fixed for the single mute, but not for the gmute.

Also, since its name is *global* mute, shouldn't it only affect global chat, rather than both team and global?

**Comment by TiTo-418** [comment]
I agree with  this

**Comment by TiTo-418** [comment]
"Also, since its name is global mute, shouldn't it only affect global chat, rather than both team and global?"

**Comment by Alfalik** [comment]
@TiTo-418 Global mute mean that **all**players are muted, not that global chat is denied to all players online.

**Comment by Pablete1234** [comment]
well, i feel like team chat should still be aviable, or maybe diferent levels of gmute 
/gmute g
/gmute t
/gmute msg
/gmute me
/gmute msg

**Comment by SungMatt** [comment]
@Pablete1234 Then it wouldn't be called **Global** mute, would it?

**Comment by dentmaged** [comment]
@SungMatt It is called global mute because all players can't talk (globally).

**Comment by Pablete1234** [comment]
it's called global mute bcos it afects all players

maybe the same options could apply to individual mute

/mute player g
...
