### ISSUE TITLE
CTF implementation

### ISSUE THREAD

**Issue by Aaron1011** [twizmwazin/CardinalPGM#684]
CTF has been out for a while now, and the docs for the XML format haven't changed in some time. As such, I think it's now feasible to begin implementing this gamemode in Cardinal.

Miscellaneous information I've gathered so far:
* When a player is holding a flag, it's placed in their helmet armor slot
* Dropped flags use a small ArmorStand to display the name shown above the flag. Note that the ArmorStand is **not** wearing the flag - the flag is placed on the ground.

TODO:
  - [x] Find out what particle(s) is/are being used for the beam effect above a flag, as well as whether magic values are being used to make them animate client-side.

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/386

**Comment by TheMolkaPL** [comment]
> Find out what particle(s) is/are being used for the beam effect above a flag, as well as whether magic values are being used to make them animate client-side.

I think's it's a block break particles.

There is also a firework thrown when flag is respawned with color same as the flag.

**Comment by Pablete1234** [comment]
@Aaron1011 particles are blockcrack_35+data*4096
For example, for red wool (wool:14) it would be:
blockcrack_35+14*4096 = blockcrack_57379

and they do not get animated client.side in any way, they are just spawned above the player, and they tend to fall

this is how it looks like in my cardinal edit:
http://gyazo.com/f49671051db66d0392c8e355dd37295a

**Comment by twizmwazin** [comment]
@Pablete1234 Can you PR your CTF changes? I'd like to have a look

**Comment by dentmaged** [comment]
@twizmwazin It uses command blocks. It is awesome!

**Comment by Pablete1234** [comment]
@twizmwazin how do i pull request this : http://gyazo.com/00eaafac9e34f7798fd9beb013e36a51

**Comment by twizmwazin** [comment]
Never mind, I was under the assumption that you edited Cardinal to get the CTF features

**Comment by Pablete1234** [comment]
@twizmwazin i did (more @dentmaged than me), but just not for the ctf features

**Comment by TiTo-418** [comment]
Relevant info: https://oc.tc/forums/topics/55b24a915f35b9dc72019c5d

**Comment by TiTo-418** [comment]
IMPLEMENTEDDDDDDDDDDDDDDD
