### ISSUE TITLE
My map don't load

### ISSUE THREAD

**Issue by xDofah** [twizmwazin/CardinalPGM#687]
I load my map with an XML created by me,but the map don't loads. It appears this in the console:

06.06 11:11:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.modules.respawn.RespawnModule.onCycleComplete(RespawnModule.java:155) ~[?:?]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.ModuleCollection.getRandom(ModuleCollection.java:70) ~[?:?]
06.06 11:11:12 [Server] INFO at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
06.06 11:11:12 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:521) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:611) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:666) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:44) [CardinalPGM-1.0-SNAPSHOT.jar:?]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:54) [CardinalPGM-1.0-SNAPSHOT.jar:?]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO org.bukkit.event.EventException
06.06 11:11:12 [Server] ERROR Could not pass event CycleCompleteEvent to Cardinal v1.0-SNAPSHOT-git-CardinalPGM-f58a4c1
06.06 11:11:12 [Server] INFO ... 22 more
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.modules.respawn.RespawnModule.onTeamChange(RespawnModule.java:189) ~[?:?]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.ModuleCollection.getRandom(ModuleCollection.java:70) ~[?:?]
06.06 11:11:12 [Server] INFO at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
06.06 11:11:12 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:521) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:611) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:666) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:44) [CardinalPGM-1.0-SNAPSHOT.jar:?]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:54) [CardinalPGM-1.0-SNAPSHOT.jar:?]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.modules.match.MatchModule.onCycleComplete(MatchModule.java:58) [CardinalPGM-1.0-SNAPSHOT.jar:?]
06.06 11:11:12 [Server] INFO at in.twizmwaz.cardinal.module.modules.team.TeamModule.add(TeamModule.java:62) [CardinalPGM-1.0-SNAPSHOT.jar:?]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[custom.jar:git-SportBukkit-bd1e0a9]
06.06 11:11:12 [Server] INFO org.bukkit.event.EventException
06.06 11:11:12 [Server] ERROR Could not pass event PlayerChangeTeamEvent to Cardinal v1.0-SNAPSHOT-git-CardinalPGM-f58a4c1
06.06 11:11:12 [Server] INFO Cycled to Elbatel
06.06 11:11:12 [Server] INFO 97 modules loaded.
06.06 11:11:12 [Server] WARN at java.lang.Thread.run(Thread.java:745)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:521)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:611)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:666)
06.06 11:11:12 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
06.06 11:11:12 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:44)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:52)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:49)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:191)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.spawn.SpawnModuleBuilder.load(SpawnModuleBuilder.java:36)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.regions.RegionModuleBuilder.getRegion(RegionModuleBuilder.java:133)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.regions.RegionModuleBuilder.getRegion(RegionModuleBuilder.java:64)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.regions.parsers.CuboidParser.<init>(CuboidParser.java:26)
06.06 11:11:12 [Server] WARN at java.util.ArrayList.get(ArrayList.java:429)
06.06 11:11:12 [Server] WARN at java.util.ArrayList.rangeCheck(ArrayList.java:653)
06.06 11:11:12 [Server] WARN java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
06.06 11:11:12 [Server] WARN at java.lang.Thread.run(Thread.java:745)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:521)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:611)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
06.06 11:11:12 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:666)
06.06 11:11:12 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
06.06 11:11:12 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:44)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:52)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:49)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:191)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.regions.RegionModuleBuilder.load(RegionModuleBuilder.java:41)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.regions.RegionModuleBuilder.getRegion(RegionModuleBuilder.java:133)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.regions.RegionModuleBuilder.getRegion(RegionModuleBuilder.java:64)
06.06 11:11:12 [Server] WARN at in.twizmwaz.cardinal.module.modules.regions.parsers.CuboidParser.<init>(CuboidParser.java:26)
06.06 11:11:12 [Server] WARN at java.util.ArrayList.get(ArrayList.java:429)
06.06 11:11:12 [Server] WARN at java.util.ArrayList.rangeCheck(ArrayList.java:653)
06.06 11:11:12 [Server] WARN java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
06.06 11:11:12 [Server] INFO Preparing start region for level 4 (Seed: 0)

**Comment by maestro34** [comment]
Can you maybe show us your XML ?

**Comment by xDofah** [comment]
Yeah http://pastebin.com/G37y14Cv

**Comment by maestro34** [comment]
Lines 109 & 115 of the pastebin, you forgot to specify your Y

**Comment by xDofah** [comment]
Oh thanks

**Comment by maestro34** [comment]
If your problem is fixed, you should close the issue.

**Comment by xDofah** [comment]
Its not fixed :(
