### ISSUE TITLE
Obervers can hit ingame players

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#688]
when a player that's about to die gets hit by an observer, the kill is counted for the observers.
for example, if someone falls from a skybridge, and an observer hits him in the air, when he falls to the ground the kill is for the obs, same if someone falls to the void

**Comment by iEli2tyree011** [comment]
Fixed by c369d57faf4db5c7a6d3595528cd2442a50e1a37

**Comment by Pablete1234** [comment]
Still a bug in lastest version, fixed it for 1.9

**Comment by Pablete1234** [comment]
Fixed in 1.9
