### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#69]
Could you add compatibility  with the Sportbukkit 1.7.9RO-3 ?

**Comment by ElFlambMC** [comment]
Yra

**Comment by twizmwazin** [comment]
I don't see a reason to, why are you interested in this?

**Comment by ElFlambMC** [comment]
Yea

**Comment by iEli2tyree011** [comment]
I don't think we plan to add backwards compatibility, but Twiz may have different plans.

**Comment by iEli2tyree011** [comment]
Why do you want it compatible with older versions?

**Comment by ItzWid13** [comment]
Because in the Sportbukkit 1.7.10 that I have  the tnt  cannons doesn't work, I have the  ewes version

**Comment by ItzWid13** [comment]
Newest version*

**Comment by twizmwazin** [comment]
Do you have any other plugins besides Cardinal installed?

**Comment by iEli2tyree011** [comment]
Can you list the contents of your /plugins folder please?

**Comment by ItzWid13** [comment]
Kk

**Comment by ItzWid13** [comment]
WorldEdit,Cardinal

**Comment by iEli2tyree011** [comment]
Can you list the contents of your /plugins folder?

**Comment by ItzWid13** [comment]
Or, could  you pass  e the sport bukkit that you have?

**Comment by twizmwazin** [comment]
[here](https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.7.10-R0.1-SNAPSHOT/sportbukkit-1.7.10-R0.1-20141223.195415-38.jar)

**Comment by ItzWid13** [comment]
![screenshot_2015-01-19-04-26-39](https://cloud.githubusercontent.com/assets/10577625/5797160/8fa00dcc-9f93-11e4-818b-44a7305e748b.png)
![screenshot_2015-01-19-04-25-28](https://cloud.githubusercontent.com/assets/10577625/5797163/95490b7a-9f93-11e4-8d00-f2399d0c1eef.png)

**Comment by ItzWid13** [comment]
There are the plugins

**Comment by twizmwazin** [comment]
For testing purposes, if you could disable plugins besides Cardinal and Worldedit, that would be appreciated.

**Comment by vYuri** [comment]
SportBukkit makes Tracker deaths works better (?

**Comment by ItzWid13** [comment]
In your server the tnt cannons works?

**Comment by twizmwazin** [comment]
I believe so, I'll confirm in the morning

**Comment by iEli2tyree011** [comment]
@twizmwazin Yes, they do

**Comment by ItzWid13** [comment]
Could you confirmate me now? Pls

**Comment by ItzWid13** [comment]
What plugins do you have?

**Comment by iEli2tyree011** [comment]
We **only** have WorldEdit and Cardinal. For testing purposes, I would disable the other plugins.

**Comment by ItzWid13** [comment]
Ok, and you have the latest version  of the sportbukkit?

**Comment by iEli2tyree011** [comment]
I use a version very similar to what @twizmwazin just sent you. I'm assuming what he sent you is what he uses, or works fine with Cardinal.

**Comment by ItzWid13** [comment]
Could you pass me the version that you use?

**Comment by twizmwazin** [comment]
The version I linked is the version that I develop and test with, so full compatibility is ensured.

**Comment by ItzWid13** [comment]
Because in the sport 1.7.9 the cannons works and in the latest version doesn't works

**Comment by twizmwazin** [comment]
I have to go to bed, can anyone else confirm this issue?

**Comment by iEli2tyree011** [comment]
Did you disable **every** plugin besides Cardinal and WorldEdit?

**Comment by ItzWid13** [comment]
@twizmwazin the version that you pass me, you develop it?

**Comment by twizmwazin** [comment]
I don't develop Sportbukkit, OCN does

**Comment by ItzWid13** [comment]
Ok

**Comment by ItzWid13** [comment]
@iEli2tyree011 how can I disable the other plugins?

**Comment by iEli2tyree011** [comment]
However, he uses it to develop. You should use that .jar for the server and make sure Cardinal and possibly WorldEdit are the only plugins enabled.

**Comment by ItzWid13** [comment]
Ok

**Comment by ItzWid13** [comment]
I will see it in the morning, don't close this issue

**Comment by iEli2tyree011** [comment]
You can rename their extensions from .jar to .plugin, and then when you need them enabled again you can change the extension back.

**Comment by iEli2tyree011** [comment]
As long as Bukkit doesn't see a .jar, it will not enable it.

**Comment by ItzWid13** [comment]
Ok

**Comment by ItzWid13** [comment]
I need to go to bed, bye

**Comment by elespawol** [comment]
Good moorning :P
El dia 19/01/2015 8.44, "ItzWid13" <notifications@github.com> va escriure:

**Comment by twizmwazin** [comment]
Update your SportBukkit to the most recent issue, the issue is with SportBukkit rather than Cardinal. See #74 for more detail.
