### ISSUE TITLE
observers can open other observer's inventories

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#691]
observers can open other observer's inventories

**Comment by TiTo-418** [comment]
Reopen please, still can open when the match doesn't start

**Comment by Pablete1234** [comment]
@twizmwazin Reopen, before match has started no one should be able to open anyone else's inventory

**Comment by twizmwazin** [comment]
This can get fixed after we merge the teams branch

**Comment by TiTo-418** [comment]
Now you can open other observer's inventory, but can not open in-game players' inventory

**Comment by twizmwazin** [comment]
man I messed up logic with teams
