### ISSUE TITLE
Maps can't be in sub-folders of the repository

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#692]
if you have as a repository:
/maps

all maps MUST be:
/maps/whatevermap

i think you should be able to do:
/maps/ctw/whatevermap

just how oc.tc repository is made (maps.oc.tc)

**Comment by SungMatt** [comment]
Can it then exclude folders?

**Comment by Pablete1234** [comment]
if you want to exclude folders don't put them in your repo

**Comment by twizmwazin** [comment]
@SungMatt I can make an optional exclude config if that is what you mean.

**Comment by Pablete1234** [comment]
maybe make it so you can set a "list" of repos ,kind of like:
repo:
 - maps/ctw
 - maps/dtc

**Comment by twizmwazin** [comment]
@Pablete1234 I wouldn't include it in the main config, and I probably wouldn't use YAML.

**Comment by Pablete1234** [comment]
personally i don't care what format is used, i just want it to work :P

**Comment by dentmaged** [comment]
@twizmwazin What will you use?

**Comment by twizmwazin** [comment]
@dentmaged I am personally fond of json, it is less finniky compared to YAML. We will see.

**Comment by dentmaged** [comment]
@twizmwazin but JSON is less user friendly.

**Comment by Pablete1234** [comment]
i don't quite understeand why it can't be in the global config, the same way now it's the tag:
"repo: maps" you can't have 
"repo: maps/ctw;maps/dtc"

**Comment by twizmwazin** [comment]
@Pablete1234 It would be a pre-repository config. You would specify a root in the config, and then in the root of the repository there would be an optional config file for that repository.

**Comment by CaptainElliott** [comment]
@dentmaged IMO YML is less user friendly due to it being so sytnaxualry picky, but I can understand where you are coming from

**Comment by dentmaged** [comment]
@CaptainElliott ```[{"what": "is", " this": "?"}] ```

**Comment by twizmwazin** [comment]
@dentmaged malformed json

I hate config formats that can't be parsed because there is an accidental space somewhere.

**Comment by Pablete1234** [comment]
what would it be like? {Repo:["/maps/ctw","/maps/dtc"]}

**Comment by twizmwazin** [comment]
@Pablete1234 

{
  "include": ["dir1", "dir2"],
  "exclude": ["dir1", "dir2"]
}

The include would be optional, and by using include it would tell Cardinal to exclude by default. Specifying a directory will apply the include/exclude to all sub-directories.

**Comment by Pablete1234** [comment]
@twizmwazin looks good to me

**Comment by Prodigy4532** [comment]
Work if you upload the maps to a website?

**Comment by Pablete1234** [comment]
@Prodigy4532 technically i think you can set as a repo a remote server, as long as you have it connected.
atleast in windows, you can go to "My-PC" , right-click and "add a web ubication", there you can select a ftp, webserver, or others, and you can browse it as if it was a local file

**Comment by twizmwazin** [comment]
@Prodigy4532 It should work on any file system that is mounted and that the JVM has access to read. I may add remote maps over HTTP/S, however I don't think many users would use it.

**Comment by Eudaldca** [comment]
'include src' should only try to include xmls in the same (sub)folder, right?

**Comment by dentmaged** [comment]
@twizmwazin Can I implement an online rotation? Does something like this look good? https://github.com/dentmaged/Cardinal-Plus/commit/b5e977acd1fb2787c0270c5325e3f44c825bb7c1

**Comment by twizmwazin** [comment]
@dentmaged I don't want to sound like a jerk here, but there are multiple glaring issues. First, why are there random lines changed in other files? A commit should have a single purpose, to be easily reversible. In WebUtils, there are better library methods to accomplish the same thing. Lastly, the config is not compatible with previous revisions. If you want to implement it, feel free to make a well-formatted PR, and then I will review it. That implementation wouldn't cut it.

**Comment by Pablete1234** [comment]
is this comming anytime soon? cause i would like to have a well organised repo

**Comment by twizmwazin** [comment]
@Pablete1234 I'm not your personal developer. The issue is open, and hopefully I or someone else will get around to implementing this. We all have lives outside of developing, and nagging us doesn't make us want to help you any faster.

**Comment by Pablete1234** [comment]
i didn't mean to be rude, i was just asking about what priority is given to this ...

**Comment by dentmaged** [comment]
@twizmwazin I'll do this, but it would use YAML not JSON.

**Comment by twizmwazin** [comment]
@dentmaged PR it and I'll take a look.

**Comment by dentmaged** [comment]
@twkzmwazin Okay. I'll do it tomorrow.

**Comment by TiTo-418** [comment]
Dropbox please

**Comment by SungMatt** [comment]
@TiTo-418 Why not add support for SpiderOak, Wuala, Treasorit, MEGA, Sync.com, and TeamDrive too?

**Comment by TiTo-418** [comment]
@SungMatt Fell free to make a pull request

**Comment by twizmwazin** [comment]
We don't need to support these silly cloud hosting services. I think it should just stick to local, http, and ftp based repositories. Remote repositories may need an index.

**Comment by ryanw-se** [comment]
@twizmwazin Meh, Dropbox support would be nice although not necessary. It also has a really nice Java API so implementing it wouldn't be that big of a hassle.

**Comment by dentmaged** [comment]
@twizmwazin I'd say SSH, FTP, Local & HTTP

**Comment by SungMatt** [comment]
@dentmaged SSH? Did you mean SFTP? I don't see very sensitive information in a map, so that protocol may not be used that much.

**Comment by dentmaged** [comment]
@SungMatt No, SSH. SSH is a method of accessing a server by Secure SHell, you use it to push to GitHub.

**Comment by CaptainElliott** [comment]
@dentmaged yes, I am going to add git integration, not pure ssh

**Comment by dentmaged** [comment]
@CaptainElliott Awwww :(

**Comment by Pablete1234** [comment]
Fixed in 1.9
