### ISSUE TITLE
Add advanced repository management

### ISSUE THREAD

**Issue by ghost** [twizmwazin/CardinalPGM#694]
i used a resident for 2 weeks, and by running /newmaps, the pgm rescans it repo for changes. i would like to see this implemented in cardinal since i use cardinal a lot for making and testing maps.

**Comment by dentmaged** [comment]
@kroest Can't you use ```/recycle``` or ```/cycle```?

**Comment by Alfalik** [comment]
It's pretty annoying stop and start again the server to load a **new** map. Would be useful.

**Comment by Pablete1234** [comment]
a /errors command would also be apreciated for xml testing

**Comment by SungMatt** [comment]
@Pablete1234 You can use online XML checkers to parse the XML before you load the map, or just keep a repo with one working map and the one that is being tested. Be sure to enable `display-map-load-errors` in `config.yml`

**Comment by Pablete1234** [comment]
sung matt. /errors is not for wrongly phrased xml's, it's also for example if you type a item name incorrectly, then the whole kit doesn't work, if you have some misspelled stuff that can be detected ,etc

**Comment by CaptainElliott** [comment]
@Pablete1234 that would require a huge amount more effort, not something we are going to do right now

**Comment by twizmwazin** [comment]
@CaptainElliott although when writing new features making it fail-safe is a good idea

**Comment by dentmaged** [comment]
@twiznwazin All the modules would have to be rewritten and you could add all the Exceptions to an array list.

**Comment by twizmwazin** [comment]
@dentmaged Not entirely, although the plan is to rewrite most modules in the coming weeks. I am going to do an overhaul of the module system, and Elly planned to do some much needed refractoring and cleanup.

**Comment by Pablete1234** [comment]
Fixed in 1.9
