### ISSUE TITLE
Deaths problem

### ISSUE THREAD

**Issue by maestro34** [twizmwazin/CardinalPGM#695]
I found a bug with death messages in the last version of Cardinal (27cc025).

Few examples :
* Kill with a sword - [Screenshot](http://uplmg.com/61k)
* Kill with a bow - [Screenshot](http://uplmg.com/hop)

There are no killers anymore, so no snowflakes and no proximity update.

**Comment by iEli2tyree011** [comment]
Fixed by 20d87876321378b73177c2e625ea66b538dd1c38
