### ISSUE TITLE
Implement titles

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#697]
I don't think that`s anything hard to code and it's very useful.

**Comment by twizmwazin** [comment]
Please split this into two separate issues

**Comment by Alfalik** [comment]
@twizmwazin Sure

**Comment by Pablete1234** [comment]
Kinda solved by #772 (it adds match start and end titles), not sure if there are more titles to be implemented

**Comment by TiTo-418** [comment]
100% implemented in https://github.com/twizmwazin/CardinalPGM/commit/58c1ae5f680501329180e188bbb006bf28e7dfbe

**Comment by Pablete1234** [comment]
@TiTo-418 Respawn titles are not implemented yet

**Comment by TiTo-418** [comment]
@Pablete1234 That can be tracked on https://github.com/twizmwazin/CardinalPGM/issues/699

**Comment by TiTo-418** [comment]
@twizmwazin Opinions?

**Comment by Eudaldca** [comment]
I guess that this can be closed now.
