### ISSUE TITLE
Implement new respawn timer

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#699]
the fancy respawn timer where they use titles to say what time is left until respawn

**Comment by twizmwazin** [comment]
@Pablete1234 They don't use the title command to give users titles.

**Comment by Pablete1234** [comment]
i don't quite mean the command, but the client feature of being able to display that

**Comment by Aaron1011** [comment]
As a note for whoever implements this, the red tinge around the edge of the screen is accomplished by setting the world border warning distance.

**Comment by TheMolkaPL** [comment]
Some XML documentation https://docs.oc.tc/modules/spawns#respawn
