### ISSUE TITLE
Problem with player statistics

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#700]
console:
http://gyazo.com/0eac8e60a6b5a71c3a1584440e4f365e

i didnt really do anything, i didnt try to setup scoreboards to track any of therse

**Comment by SungMatt** [comment]
A quick fix is to prune your directory. Remove all files from the world folder, except `region` , `level.dat` , `map.xml`, `map.png` if you are using a picture of a map, and `data` iff you are using maps.

All other directories are not needed and can prevent the map from "recycle"-ing.

**Comment by twizmwazin** [comment]
This specific issue is with the vanilla world on your server, and has nothing to do with Cardinal.

**Comment by Pablete1234** [comment]
the world being used only had a region file, level.dat and xml

**Comment by twizmwazin** [comment]
@Pablete1234 Delete the `world` folder from your server directory. The issue has nothing to do with a Cardinal map, or the plugin itself..

**Comment by Pablete1234** [comment]
doesn't "world" get generated automatically by the server.jar? or does cardinal prevent that?

**Comment by dentmaged** [comment]
@Pablete1234 yes, but that world is corrupt. You have to generate a new one.

**Comment by twizmwazin** [comment]
@Pablete1234 This issues has **NOTHING** to do with Cardinal. Having Cardinal on your server won't affect this issue.
