### ISSUE TITLE
problem loading the plugin

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#701]
it was working just fine, i jsut changed the repo path, and it stopped working, i set it back to what it was, and now on server opening:
 http://gyazo.com/786622ced76b8a30c380615a481eaa46

the server opens as a regular survival, and no cardinal commands or anything work

**Comment by Alfalik** [comment]
Make sure you have a ```rotation.txt``` in your server folder.

**Comment by Pablete1234** [comment]
ok, i had a rotation.txt with invalid maps, thanx
