### ISSUE TITLE
My XML don't works.

### ISSUE THREAD

**Issue by xDofah** [twizmwazin/CardinalPGM#702]
Here is the pastebin: http://pastebin.com/WRj7VCdR

**Comment by dentmaged** [comment]
@xDofah Although this isn't a Cardinal issue. Remove the ``9``` from line 71.

**Comment by CaptainElliott** [comment]
Do what @dentmaged said :)

**Comment by xDofah** [comment]
No,not fixed. Anyone can help me? Sorry for posting a problem,not a issue

**Comment by Alfalik** [comment]
Can you provide us the world file?

**Comment by dentmaged** [comment]
@xDofah The XML seems valid.

**Comment by xDofah** [comment]
The World file is correct...

**Comment by CaptainElliott** [comment]
We need error logs

**Comment by xDofah** [comment]
Ok,here is the log: http://pastebin.com/VV0CvgTG

**Comment by CaptainElliott** [comment]
Line 25, your missing a radius for your cylinder

**Comment by xDofah** [comment]
Thanks!! Its fixed! Now close the issue :)
