### ISSUE TITLE
Error of the server

### ISSUE THREAD

**Issue by DaniOurGamer** [twizmwazin/CardinalPGM#703]
Hi, all the time that I try to start my server doesn´t go
This is my log: http://pastebin.com/pdu5aitK

**Comment by TheMolkaPL** [comment]
> java.net.MalformedURLException

You need to specify a valid URL in the fr.xml file.

**Comment by DaniOurGamer** [comment]
Ok resolved but appeared this warns http://pastebin.com/s8Wi0TvW

**Comment by twizmwazin** [comment]
Cardinal is not correctly compiled. Please use official downloads from http://ci.twizmwaz.in/job/Cardinal/
