### ISSUE TITLE
Error when cycling to SSB TE

### ISSUE THREAD

**Issue by Vixo1** [twizmwazin/CardinalPGM#705]
Proof: https://youtu.be/OVuALF77pk8
Version: 4f2c109
XML: http://pastebin.com/S6TVZWLM

**Comment by TiTo-418** [comment]
You can cycle to SSB

**Comment by twizmwazin** [comment]
Please post your logs

**Comment by Vixo1** [comment]
Edited title to be more clear.
Logs: http://pastebin.com/4kgY42Vf

**Comment by Vixo1** [comment]
Any opinion?¿

**Comment by Pablete1234** [comment]
maybe related with how regions are defined? i dont know how well implemented and mirrored regions are

**Comment by Vixo1** [comment]
Fixed in lastest commit
