### ISSUE TITLE
Gold blocks can't be mined on Golden Drought

### ISSUE THREAD

**Issue by Vixo1** [twizmwazin/CardinalPGM#706]
Proof: https://youtu.be/sB7W_se0gYM
Version: 4f2c109
XML: http://pastebin.com/RAgYycfG

**Comment by TiTo-418** [comment]
XML Error https://oc.tc/forums/topics/54e2a85f5f35b957a90085d1?page=1#54e2a906c296355704008c07

**Comment by Vixo1** [comment]
Fixed
