### ISSUE TITLE
strange behaviour on computer suspension

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#709]
http://gyazo.com/18e1563a1fcc333c29fe4db0a851a9e8

as you can see, the computer went into suspension mode at about 15:45, then when i got back home at 17:45, i woke it up, and it tried to process everything happened while it was suspended.

**Comment by SungMatt** [comment]
That happens with all the servers I have ran, especially the older versions.

**Comment by SungMatt** [comment]
Also that's more of a minecraft server issue that got passed on to bukkit and its forks.

**Comment by twizmwazin** [comment]
This issue isn't related to the plugin, it is just how the Minecraft tick tick timer works. Don't suspend your computer with a Minecraft server running.
