### ISSUE TITLE
whitelist team doesn't work properly

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#710]
/wl team <team name> does the same as /wl all, it doesn't properly test for the right team

to reproduce:
join blue team, make sure you are not on the whitelist already
type /wl team red
you will be added to the whitelist while being on blue

tested in: 4f2c109

**Comment by Pablete1234** [comment]
shouldn't this be tagged as bug?

**Comment by Pablete1234** [comment]
this is already fixed

**Comment by TiTo-418** [comment]
@twizmwazin @Pablete1234 Can you reopen this please?
