### ISSUE TITLE
Observers can ready even when the setting is disabled

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#711]
i have the setting:
```observers-ready: false```
if you join red and type /ready, it says "red is ready"
if you join blue and type /ready, it says "blue is ready"
if you join obs and type /unready, it says "your team is already already not ready"

the thing is you can just type /ready on obs, observers will become ready, and then you can /unready, and the start will be canceled

IMO what should happen is that if you have the setting set to false, observers should be ready by default (so if you type /ready it says "your team is already ready"), and it should not allow players on observers to do /unready

**Comment by twizmwazin** [comment]
Would a good way to address this just be to not show any messages about ready status for observers when the setting is off? It is otherwise ignored, so I think just removing the messages would be a fair solution.

**Comment by Alfalik** [comment]
@twizmwazin It will still cancel the start timer

**Comment by TiTo-418** [comment]
@twizmwazin And add a message like: "Observers don't have permissions to /ready, enable it on your config.yml"

**Comment by Pablete1234** [comment]
@twizmwazin i think a "Your team is already ready" is ok, and if you try to unready, a "Observers can't unready"

**Comment by twizmwazin** [comment]
fixed 5afcc52ebf1eb100397043d0f61bc5145b98b2e3
