### ISSUE TITLE
Pistons can push blocks outside the void regions

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#715]
<a href="http://imgur.com/e6wc2Oi"><img src="http://i.imgur.com/e6wc2Oi.png" title="source: imgur.com" /></a>

For reference: https://github.com/twizmwazin/CardinalPGM/issues/559#issuecomment-104130726

**Comment by twizmwazin** [comment]
What happens if you try and do this on PGM?

**Comment by TiTo-418** [comment]
I don't have access to a server with pgm, maybe @CaptainElliott can.

**Comment by Pablete1234** [comment]
pistons never extend, like if they were trying to push obsidian

**Comment by Pablete1234** [comment]
pistons never extend, like if they were trying to push obsidian

**Comment by TiTo-418** [comment]
Fixed https://github.com/twizmwazin/CardinalPGM/commit/3796240759c63b2aa3abc3d4198b7b4fcdcca601
