### ISSUE TITLE
Enemy scoreboard bug

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#717]
Video: http://youtu.be/HkUaAsygn4k
Version: 8094b7003bf7bde7159b58aa85f56a12133cedb8

**Comment by Eudaldca** [comment]
That looks as if it had to do with the proximity, but I'm just guessing, I neither know why it is affecting the order of stuff, as they are supposed to be ordered by the right red numbers.

**Comment by Pablete1234** [comment]
@Eudaldca it's bcos proximity makes the numbers on the right (objectives' order) change, and it makes it for both teams(when it shouldn't)

**Comment by Pablete1234** [comment]
This bug was caused by "set score" setting the objective that has to be 0 to 1 and then to 0 ,because otherwise it doesn't render, i made it so that it's set to -1, then to 0, should fix the order issues

**Comment by Prodigy4532** [comment]
With pablete solution , this issue is fixed.

**Comment by twizmwazin** [comment]
fixed
