### ISSUE TITLE
Iron doors are visible on 1.8

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#718]
<a href="http://imgur.com/xtbPRYh"><img src="http://i.imgur.com/xtbPRYh.png" title="source: imgur.com" /></a>

I think they can be changed to barrier blocks (the same system used to change the block 36)

**Comment by Pablete1234** [comment]
block 36 isnt changed for for barriers, i think you mean the same way oc.tc did it when it was 1.7 & 1.8

**Comment by Eudaldca** [comment]
Iirc what changed half iron doors to barriers was the "1.8 hack" for 1.7.10 servers, it was a feature implemented for version compatibility. As sportbukkit updated, this  feature was removed from sportbukkit. I'm guessing it was this.

**Comment by CoWinkKeyDinkInc** [comment]
This bug was fixed in SportBukkit.  Did they remove the patch?

**Comment by twizmwazin** [comment]
@CoWinkKeyDinkInc This was part of the protocol hack, it is not part of the server itself.

**Comment by twizmwazin** [comment]
Fixed c313771b98999ea7981bd694fb0193b5e1a7b9e3

**Comment by Pablete1234** [comment]
reopen as inconsistency
http://gyazo.com/32065109d6d459d50a3b250b5a749ed6

on one side, it loaded as barriers, on if flew fast to the other side, and only half of them seem to be barriers, the iron doors get switched to barriers on right click

**Comment by TiTo-418** [comment]
Can't reproduce

**Comment by twizmwazin** [comment]
@TiTo-418 It is inconsistent. The server fix does accurately replace the doors, however for some reason the client is still sent some doors.

**Comment by CaptainElliott** [comment]
@twizmwazin what time is the module loading? perhaps the players are being spawned in when it's being replaced causing some issues client side? idk tbh

**Comment by twizmwazin** [comment]
@CaptainElliott All modules are loaded before the client is sent to the new world. The task is run async, which means some of the doors may not be converted in time. This could be fixed by running it in sync, however would greatly increase the cycle time for something largely aesthetic.

**Comment by dentmaged** [comment]
@twizmwazin Couldn't you send a packet to force the user to reload the chunks?

**Comment by twizmwazin** [comment]
@dentmaged Not exactly, and the goal is a not-laggy implementation. In a perfect world server owners could just spend 2 minutes in MCEdit.

**Comment by dentmaged** [comment]
@twizmwazin Can't you use a block update packet?

**Comment by twizmwazin** [comment]
@dentmaged The goal is to not send excessive amounts of packets. There is clearly an issue with craftbukkit in this case, as it should already be sending the block update packet to the client.

**Comment by Pablete1234** [comment]
block update packet is what's needed for client-side fluid problems

**Comment by RubeVi** [comment]
@twizmwazin  is this a Cardinal issue?

**Comment by twizmwazin** [comment]
@RubeVi partially
