### ISSUE TITLE
Cores are still editables

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#720]
The first clip isn't fixed: https://www.youtube.com/watch?v=Q-F0bEGkprA&feature=youtu.be
For reference: https://github.com/twizmwazin/CardinalPGM/issues/660#issuecomment-104850172

Edit: Also happen with blocks with gravity

**Comment by dentmaged** [comment]
Can reproduce

**Comment by twizmwazin** [comment]
3/4 fixed with f2e8d21f66c05a69558bc0896512078780452dd2

**Comment by Pablete1234** [comment]
what's the  1/4 remaining?

**Comment by twizmwazin** [comment]
@Pablete1234 You can still pick up water in certain regions, eg SSB spawn afaik

**Comment by TiTo-418** [comment]
@twizmwazin No, it is client side

**Comment by Pablete1234** [comment]
still, if it's client-side it should be sent back by the server that the water block it's still there

**Comment by Pablete1234** [comment]
tested in ssb's drop
seems to be that you can client-side pick the water, only if you are not pointing to a block

pe: if you get the water block, but you are pointing at the bedrock, it comes back, if you have no block behind, you can pick it

**Comment by twizmwazin** [comment]
@Pablete1234 Can you see if OCN has a fix for this or if it is the same bug?

**Comment by Pablete1234** [comment]
i'm quite sure ocn does have this fixed

**Comment by Pablete1234** [comment]
@twizmwazin i think that ssb's drop does not fit this issue, i think fluids on core are fixed, either change the title to something related with general fluids, or make a new one

**Comment by twizmwazin** [comment]
I think this would be more appropriate to be fixed in SportBukkit/Craftbukkit, as when the event is cancelled the client should be automatically notified.

**Comment by Pablete1234** [comment]
@twizmwazin reopen, you can right-click with water inside of the lava of a core, and the lava gets replaced, it's not client-side

**Comment by dentmaged** [comment]
@twizmwazin In f2e8d21, shouldn't you use ```if (getBlocks().contains(event.getBlockClicked()) /* rest of if statement */)``` on lines 372, 378 and 384?

**Comment by twizmwazin** [comment]
@dentmaged Let me know if I'm wrong, but I don't think it makes a difference in this case

**Comment by dentmaged** [comment]
@twizmwazin see @Pablete1234's comment.

**Comment by TiTo-418** [comment]
https://www.youtube.com/watch?v=LXrn2FOjRL0

**Comment by Pablete1234** [comment]
#803 fixes this

**Comment by TiTo-418** [comment]
Fixed https://github.com/twizmwazin/CardinalPGM/commit/6f1ed8def19da857108f5c4286a5c18c3586b3bb
