### ISSUE TITLE
Sumo doesn't work

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#723]
Temporarily fix: http://pastebin.com/zTA5xJr4 by @Pablete1234 

What is sumo?: https://www.youtube.com/watch?v=alJB0ycrWb0
Proof: http://youtu.be/2J56zEqTACg
XML: https://maps.oc.tc/Other/Tournament/House%20of%20Cores/Sumo/map.xml

**Comment by Eudaldca** [comment]
You are supposed to not be able to break glass, too.

**Comment by dentmaged** [comment]
@Eudaldca You can use a hack to prevent blocks from being broken/placed. I'll post it when I get home.

**Comment by twizmwazin** [comment]
Is the issue here just that monument modes aren't working?

**Comment by twizmwazin** [comment]
whoops

**Comment by Eudaldca** [comment]
@twizmwazin The way in which the xml is written denies block breaking in PGM. In cardinal you can break blocks.

**Comment by dentmaged** [comment]
@Eudaldca What element is that?

**Comment by Eudaldca** [comment]
@dentmaged Inside regions, `<apply block="never"/>`

**Comment by Prodigy4532** [comment]
in my XML Sumo works.

**Comment by dentmaged** [comment]
@Eudaldca I see. Thanks!

**Comment by dentmaged** [comment]
@iEli2tyree011 Do you know what ```<map game="Sumo" />``` does?

**Comment by CaptainElliott** [comment]
@dentmaged set's the scoreboards title

**Comment by Pablete1234** [comment]
i have the map fixed for cardinal, what i changed is the "modes" instead of:
```materials="95:11; 95:14"``` i have ``` materials="stained_glass:11;stained_glass:14" ```
and instead of using regions defined in the regions section:
``` <region id="red-glass"/> ``` i used regions there:
```<region><cuboid min="-166,2,-153" max="-163,5,-149"/></region>```

**Comment by Prodigy4532** [comment]
You can use my XML. http://pastebin.com/HMHYNi5Z

**Comment by Pablete1234** [comment]
prodigy that has different coordinaltes...

**Comment by dentmaged** [comment]
@twizmwazin You can use the following regex to check if a string is numeric: ```string.matches("-?\\d+(\\.\\d+)?");```. If it is, use ```Material.getMaterial(NumUtils.parseInt(string));```. I'll PR this fix later today.

**Comment by CaptainElliott** [comment]
@dentmaged why use regex?

**Comment by dentmaged** [comment]
@CaptainElliott It's the most efficient system I know of.

**Comment by CaptainElliott** [comment]
@dentmaged apache commons, or even the standard `Integer.parseInt(str)` and check for an exception

**Comment by dentmaged** [comment]
@CaptainElliott I think the second one isn't very efficient.

**Comment by twizmwazin** [comment]
I'd go with Elliott's first suggestion, although the second one isn't inefficient so much as there are just better options.

**Comment by TiTo-418** [comment]
@CaptainElliott 
> set's the scoreboards title
It doesn't work

**Comment by Eudaldca** [comment]
@TiTo-418 In PGM, Cardinal doesn't have this feature implemented.

**Comment by TiTo-418** [comment]
@Eudaldca I know

**Comment by Pablete1234** [comment]
I just realized this is a great issue to track down 1.4 issues
- regions should accept both "name" and "id" (atm only name works in cardinal)
- ```<apply block="never">``` doesn't work because
    - "never" and "always" filters not implemented
    - "everywhere" and "nowhere" are not implemented, and apply defaults to everywhere
    - ```<apply block="never" region="something">``` won't work either, region must be child, not attribute
- numerical id's don't work on cardinal
