### ISSUE TITLE
Map gladiators does not work

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#724]
Log: http://pastebin.com/Bz98Jq80
Cardinal version: 8094b70
XML & download in this thread: https://oc.tc/forums/topics/557d980f5f35b91ca80061b1
I can only assume this is due to the fact the map has 16 different teams.

**Comment by TheMolkaPL** [comment]
Your XML is not valid.

**Comment by twizmwazin** [comment]
Cardinal should be able to handle any number of teams with no problem, the issue appears to be with regions. I'll mark this as closed, check back with an XML from maps.oc.tc if this gets loaded.
