### ISSUE TITLE
Match ending on non-TDMs on player death

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#73]
When i start a match, i play, but when someone die the Match Finish,
For Example: I put a ctw someone die an the match Finishes

**Comment by Alfalik** [comment]
This don´t happen to me. Try to recompile again with the last version. Then, just use Cardinal and World Edit in the /plugins folder

**Comment by ItzWid13** [comment]
Pls fix it

**Comment by iEli2tyree011** [comment]
I'll fix this, thank you

**Comment by ItzWid13** [comment]
This is what happens: http://gyazo.com/e01718d747a2b7b49dbdb8a04c571940
