### ISSUE TITLE
ItemDropModule bug

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#733]
<a href="http://imgur.com/0H2vUMa"><img src="http://i.imgur.com/0H2vUMa.png" title="source: imgur.com" /></a>

**Comment by twizmwazin** [comment]
Whoops

**Comment by twizmwazin** [comment]
Steps to reproduce?

**Comment by TiTo-418** [comment]
I don't know the extacts steps to reproduce, but try join a team and leave the server

**Comment by Pablete1234** [comment]
yes, steps to reproduce:
before starting the game: 
join a team
log out

items will drop

**Comment by TiTo-418** [comment]
Happens again 

<a href="http://imgur.com/bSbjbRg"><img src="http://i.imgur.com/bSbjbRg.png" title="source: imgur.com" /></a>
