### ISSUE TITLE
Dispensers explosions do not cause TNT to spawn

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#737]
dispensers that get blown up on OCN dispense the tnt that they have in them

**Comment by twizmwazin** [comment]
Please don't attempt to add your own tags, they annoy me to no end. We have proper tags that we can use to label your issues.

**Comment by Pablete1234** [comment]
ok sorry

**Comment by Aaron1011** [comment]
@Pablete1234: Unfortunately, that's not possible - only people with commit access can add labels.

**Comment by Pablete1234** [comment]
@Aaron1011 too bad, would be nice if you could edit the github options to allow ppl to set their own tags

**Comment by twizmwazin** [comment]
@Pablete1234 No it wouldn't. Most people would mislabel their issues.

**Comment by Pablete1234** [comment]
maybe a rank on the project like "colaborator", a new one that's "mod" and can label issues etc, but can't edit the code without using commits

**Comment by SungMatt** [comment]
@Pablete1234 Github does not have a multi customizable permission level system that can be altered for a user repository. They have the "Owner" and "Collaborator" permission levels..
Refer to [this](https://help.github.com/articles/permission-levels-for-a-user-account-repository/) article for more information.

**Comment by Pablete1234** [comment]
yes @SungMatt , i know that's how it works, just saying it would be nice if github had that feature

**Comment by iPGz** [comment]
Added in f84e276
