### ISSUE TITLE
TNT is not working with cannons/pushing other TNT

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#74]
TNT Dont ignite correctly, look at the video.

+ Tested on 2 servers, so I dont think is my problem.

**Comment by Alfalik** [comment]
https://www.youtube.com/watch?v=6w72JG5fw9Q&feature=youtu.be

**Comment by twizmwazin** [comment]
What is the output of /pl?

**Comment by firstvirus92** [comment]
This might be related to #39. Can you please confirm that this is a bug with this plugin, not any other plugin or SportBukkit?

**Comment by twizmwazin** [comment]
Also #69

**Comment by twizmwazin** [comment]
@Alfalik do you have any other plugins installed?

**Comment by Alfalik** [comment]
http://gyazo.com/4a1f608640c0adc695e8435c80f1a35c

Just this

**Comment by iEli2tyree011** [comment]
Can you temporarily disable Tracker just to verify that it's not causing the problem?

**Comment by Alfalik** [comment]
Same test, with Cardinal & World Edit.

https://www.youtube.com/watch?v=qd7wb03XoCU&feature=youtu.be

**Comment by Alfalik** [comment]
Test 03: Just using Cardinal as plugin.

http://youtu.be/avTE9D5zR8c

**Comment by twizmwazin** [comment]
@Alfalik Thanks for the videos. Just to make sure that the issue is with Cardinal, can you do one more test with no plugins?

**Comment by Alfalik** [comment]
Test 04: No plugins used.

http://youtu.be/sNqjaND5R_c

Result: Sporkbukkit problem.

**Comment by twizmwazin** [comment]
I'm on the very latest build of Sportbukkit. Make sure you are using [this] (https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.7.10-R0.1-SNAPSHOT/sportbukkit-1.7.10-R0.1-20141223.195415-38.jar) build of Sportbukkit. If the problem persists, make an issue [here] (https://github.com/OvercastNetwork/SportBukkit)

**Comment by Alfalik** [comment]
Actually works, Thanks.
Theres already an issue in Sportbukkit 

https://github.com/OvercastNetwork/SportBukkit/issues/129

**Comment by TiTo-418** [comment]
Hey! Now this doesnt work

**Comment by twizmwazin** [comment]
@TiTo-418 Make sure your cannon doesn't have flowing water.

**Comment by TiTo-418** [comment]
Ok, im uploading a video, but... this will be patched in a sportbukkit update?

**Comment by SungMatt** [comment]
@TiTo-418 You have to check with the SportBukkit people.

**Comment by Superjd10** [comment]
@TiTo-418 Are you using the lastest SportBukkit version for 1.8?

**Comment by TiTo-418** [comment]
@Superjd10 Si, gracias. Igualmente los canonns no son igual que en la 1.7 :(
