### ISSUE TITLE
double jumping not implemented

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#745]
Tips to implement:
oc.tc detects double jumping using the "canFly" nbt on all players with a kit than can double-jump, and if flying=1, they set flying=0 and apply the velocity

**Comment by twizmwazin** [comment]
We need to find the specific vector that is applied, it might be on docs. Also, unless you have only a single finger, please make an attempt at capitalization, it makes it easier to read and looks more professional.

**Comment by Pablete1234** [comment]
isn't the vector defined by the map in xml?

**Comment by CaptainElliott** [comment]
@Pablete1234 No

**Comment by TiTo-418** [comment]
https://docs.oc.tc/modules/kits

**Comment by dentmaged** [comment]
@twizmwazin @TiTo-418 The `power` is `3`, `recharge-time` is `2.5s` and `recharge-before-landing` is `false`.

**Comment by twizmwazin** [comment]
@dentmaged Thanks for reading Tito's screenshot for me. It still doesn't have the vector that I need.

**Comment by TiTo-418** [comment]
@twizmwazin What do you mean whit "vector"?

**Comment by CaptainElliott** [comment]
@TiTo-418 velocity

**Comment by dentmaged** [comment]
@twizmwazin oh lol, I didn't see that screenshot.

**Comment by Pablete1234** [comment]
@CaptainElliott you are a map developer, can't you create a dev map with double jumping power 1, and always looking up test /vel 0 ? 0 , and the double jump, and keep testing until you find out what the motion applied to the player is when double jumping with power 1

**Comment by TiTo-418** [comment]
Maybe this can help https://repo.oc.tc/content/repositories/snapshots/tc/oc/double-jump/

**Comment by dentmaged** [comment]
@twizmwazin @TiTo-418 https://github.com/rmsy/DoubleJump

**Comment by TiTo-418** [comment]
'''
Vector normal = VectorUtil.calculateLookVector(player.getLocation());

            normal.setY(0.75 + Math.abs(normal.getY()) * 0.5);
            event.getPlayer().setVelocity(normal);

            player.getWorld().playSound(player.getLocation(), Sound.ZOMBIE_INFECT, 0.5f, 1.8f);
'''

**Comment by TiTo-418** [comment]
' ' '
test
' ' '

**Comment by Pablete1234** [comment]
Fixed with Kits Rewrite
