### ISSUE TITLE
Could not pass event PlayerMoveEvent to Cardinal

### ISSUE THREAD

**Issue by Ferdzz** [twizmwazin/CardinalPGM#749]
I'm trying to build something on top of CardinalPGM, for some reason, on a certain map, I keep getting stack traces about "Could not pass event PlayerMoveEvent to Cardinal". Did I install something wrong or is it already known?

Stack trace: http://pastebin.com/R8kM57eW
Map's XML (not mine): http://pastebin.com/xqSZwiDf

**Comment by TiTo-418** [comment]
Try with this xml: https://maps.oc.tc/CTW/Standard/Downforce/map.xml
Also update your cardinal: http://ci.twizmwaz.in/job/Cardinal/lastSuccessfulBuild/

**Comment by Ferdzz** [comment]
Thanks, I'll try changing the xml. On another hand, I can't really "update" the cardinal, as I am building on top of the source (I want to add private features).. I used the source available on Github, should that be a problem?

**Comment by TiTo-418** [comment]
No if you follow the <a href="https://github.com/twizmwazin/CardinalPGM/blob/master/LICENSE">LICENSE</a>

**Comment by Ferdzz** [comment]
I already checked the license, I'm pretty careful when playing around with other people's code. What I meant was, could building the source myself be a problem?

**Comment by TiTo-418** [comment]
If you will use maven, no.
