### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#75]
I cant compile the last release of the plugin

**Comment by firstvirus92** [comment]
Please provide more information in your issues, in this case the error log.

**Comment by ItzWid13** [comment]
Ok

**Comment by ItzWid13** [comment]
http://gyazo.com/7283ed656637542dd240f5e9693d6628

**Comment by iEli2tyree011** [comment]
Sorry about that, should be fixed. Thanks for reporting!
