### ISSUE TITLE
Tnt launched by dispensers do not count as player's tnt

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#751]
If you place a dispenser, fill it up with tnt, and fire it, the tnt that comes out from it is not counted as the player that placed the dispensers' tnt

This means:
 - Monument/core touches made with cannons with dispensers don't even give out a message
 - Kills with dispenser cannons don't count towards the player

**Comment by CaptainElliott** [comment]
This requires better tracking.

**Comment by Pablete1234** [comment]
Can bukkit add it's own nbt tags to tile-blocks?
If so, you need to add an "Owner" tag to dispensers, and add it to whatever is dispensed out of that too

**Comment by CaptainElliott** [comment]
we would use meta data

**Comment by Pablete1234** [comment]
Then go for it :P

**Comment by CaptainElliott** [comment]
I'll work on it when I get home

**Comment by iEli2tyree011** [comment]
I'm also going to try to fix up some of the current logic with the tracking. Currently, I'm fairly sure that if the TNT moves at least 1 block after being primed, it does not work with the tracker since the `ExplosionPrimeEvent` seems to get called right before the explosion, not when the actual TNT is lit.

**Comment by iEli2tyree011** [comment]
@CaptainElliott Do you plan to use block metadata and just set the entire dispenser to that player's TNT?

**Comment by CaptainElliott** [comment]
@iEli2tyree011 what about making a new event called `TntIgniteEvent` which we fire when a player makes TNT ignite or when TNT comes out of a dispenser, from there we could also get the owner of the TNT

**Comment by CaptainElliott** [comment]
@iEli2tyree011 I was planning on doing that, but I think a new event could be a better idea ^

**Comment by iEli2tyree011** [comment]
@CaptainElliott Okay, that sounds like a good addition. Sportbukkit hasn't added any event that already does that, right? I looked up, but couldn't find anything about something like that for the Bukkit API but that sounds like something that Sportbukkit may have added.

**Comment by CaptainElliott** [comment]
@iEli2tyree011 there is a `ExplosionPrimedByEntityEvent` which I think would actually do the trick
https://github.com/OvercastNetwork/SportBukkit/blob/36a5624c076368c6a566fc3ab0f0bd5d029c1378/Bukkit/0049-Add-ExplosionPrimeByEntityEvent.patch

**Comment by iEli2tyree011** [comment]
@CaptainElliott What about when the TNT is lit by a redstone block?

**Comment by CaptainElliott** [comment]
@iEli2tyree011 looks like that event needs an update 
https://github.com/OvercastNetwork/SportBukkit/blob/36a5624c076368c6a566fc3ab0f0bd5d029c1378/CraftBukkit/0111-Add-ExplosionPrimeByEntityEvent.patch#L50

**Comment by iEli2tyree011** [comment]
@CaptainElliott Possibly Sportbukkit has changed the behavior of the ExplosionPrimeEvent, after looking at that

**Comment by CaptainElliott** [comment]
@iEli2tyree011 are you going to work on this, or would you like me to?

**Comment by iEli2tyree011** [comment]
@CaptainElliott If you can work on the actual issue, that would be good. I'm just going to clean up some old code for this, and actually clean up several other modules as well.

**Comment by CaptainElliott** [comment]
@iEli2tyree011 should I leave the new event to when you clean up the code?

**Comment by iEli2tyree011** [comment]
@CaptainElliott No, feel free to make anything you'd like to help fix this issue. I'm going to clean up other modules first, then eventually get to this one.

**Comment by Pablete1234** [comment]
fixed in 66489a3
