### ISSUE TITLE
Raindrops are given when you kill yourself

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#759]
I'm supposing that the same happen with teammates, but didn't test. Would be helpful if anyone can test if this happen.

+ Video proof: https://youtu.be/wH_A9SXPMP4
+ Log: http://pastebin.com/dmKvKbyY
+ XML (if necessary): http://pastebin.com/RWNHfMxe
+ Cardinal version  4f72ab8: http://gyazo.com/9179f50ebe80d3b1c0490b063715f3ce

**Comment by twizmwazin** [comment]
We don't have raindrops :smile:

**Comment by Alfalik** [comment]
@twizmwazin sh!
