### ISSUE TITLE
Water pushes tnt in 1.8 and ruins the use of cannons on my faction server! 

### ISSUE THREAD

**Issue by XxSilentBeastGxX** [twizmwazin/CardinalPGM#765]
Is there a way or plugin I can use that will make water flow not make tnt flow with it?. I've seen water not make push tnt on the mineage Pvp server... That server is in 1.8 so I need help figuring this out! Thank you in advance!

**Comment by CaptainElliott** [comment]
It's a sportbukkit config option
```yml
settings:
    water-pushes-tnt: false```

**Comment by dentmaged** [comment]
How is this related to Cardinal in any way?

**Comment by Cl0udNine** [comment]
@dentmaged +1

**Comment by XxSilentBeastGxX** [comment]
I was reading his post then I clicked new thread lol I didn't mean to tag him in but anyway I have another question.

I currently run spigot.. If I change to paper spigot will that be better? Will I lose my world? Will It corrupt any of my plugins that I currently have?

**Comment by CoWinkKeyDinkInc** [comment]
You're not supposed to use Spigot to run CardinalPGM, you're supposed to use SportBukkit.

**Comment by twizmwazin** [comment]
Cardinal is not compatible with Spigot and CraftBukkit, as it depends on SportBukkit features. Many features will not work.

**Comment by dentmaged** [comment]
@twizmwazin Please can you add an 'invalid' tag? The creator doesn't even have CardinalPGM on this server, I don't see why we're offering help.
