### ISSUE TITLE
/end command should end to the winning team by default

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#766]
If you do /end b , end will win, if you do /end r, red will win, but if you do /end, it should end towards the team that was winning, instead of ending it as a tie

**Comment by Alfalik** [comment]
I don't think /end should end the match with the winner. It should have a new flag, something like ```/end -w```

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/pull/463#issuecomment-85784155

**Comment by Pablete1234** [comment]
in tm.oc.tc if you /end it ends towards the winning team
