### ISSUE TITLE
Scoreboard Issue | Revenge TE

### ISSUE THREAD

**Issue by Prodigy4532** [twizmwazin/CardinalPGM#767]
Someone can translate? :s.

Spanish: Cuando entral al mapa Revenge TE, el scoreboard no añade 1 monumento, cuando te metes a un equipo, (red) el equipo contrario no tiene 1 monumento, y asi pasa igual cuando te metes al azul.

English: When /cycle Revenge TE, the scoreboard jumps 1 monument, when you join a team for example blue, you don't see the other team dosen't have a monument, and that happen if you join the another team.

http://youtu.be/pUfq9iRz3pA

**Comment by Pablete1234** [comment]
what xml are you using?

**Comment by TiTo-418** [comment]
Update your XML

**Comment by twizmwazin** [comment]
@Prodigy4532 I don't recommend using "anti-lag" or "clear lag" plugins with Cardinal, they often end up making the server more laggy and only hurt gameplay by destroying items.

**Comment by Pablete1234** [comment]
@twizmwazin +1

**Comment by Prodigy4532** [comment]
Thanks twizm, it will remove

**Comment by AngelCasillas01** [comment]
Traduction in english: When /cycle Revenge TE, the scoreboard jumps 1 monument, when you join a team for example blue, you don't see the other team dosen't have a monument, and that happen if you join the another team

@Prodigy4532

**Comment by Prodigy4532** [comment]
Thanks

**Comment by twizmwazin** [comment]
48bf316b75a945324c9132c5043bcabc98dcea89
