### ISSUE TITLE
Teleporters does not work

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#769]
Proof: https://www.youtube.com/watch?v=Ka8gB37ZzCs&feature=youtu.be
Cardinal V: 67f8beee8ee18590477651164398abf9e57cedad

**Comment by Prodigy4532** [comment]
Thanks <3

**Comment by iEli2tyree011** [comment]
Pretty sure this is the result of @twizmwazin making teams optional.

**Comment by TiTo-418** [comment]
@iEli2tyree011 Isn't fixed

**Comment by iEli2tyree011** [comment]
@TiTo-418 Are you using the latest version of Cardinal, unmodified?

**Comment by TiTo-418** [comment]
@iEli2tyree011 Yes

**Comment by TiTo-418** [comment]
Logs: http://pastebin.com/5xZQarBD

**Comment by twizmwazin** [comment]
@TiTo-418 First few things reading your log:
 - Update your java
 - Please only run Cardinal and a recent version of Worldedit when testing. Cardinal is not written to ensure compatibility. Also your version of Citizens doesn't support anything past 1.8.0.
 - Update SportBukkit or build it yourself. A few people now seem to have gotten a broken version. It is missing methods that are definitely present.

**Comment by TiTo-418** [comment]
I tested it on a shared host (Java 7), i'll test it again with your tips

**Comment by TiTo-418** [comment]
@twizmwazin That was the problem, thanks!
