### ISSUE TITLE
Plugin not always cycling to the next map properly

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#77]
When i cycle maps the plugin bug

**Comment by iEli2tyree011** [comment]
Which maps are you having issues with? Also, please try to make the titles of your issues relevant to what the issue is.

**Comment by elespawol** [comment]
Mee too, like endeblast cristmas, deepwind jungle, spaceships battles,
dynamo
El dia 19/01/2015 21.50, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by twizmwazin** [comment]
I started looking into this, I will try to have a patch tomorrow.

**Comment by ItzWid13** [comment]
Pls fix this now

**Comment by twizmwazin** [comment]
Don't be rude, I'm in class right now and I will look more into this later.

**Comment by elespawol** [comment]
Jajajajajajjajaja
El dia 20/01/2015 17.37, "Kevin Phoenix" <notifications@github.com> va
escriure:

**Comment by rywarsaw** [comment]
@ItzWid13 Not sure if you can read, but the README.md clearly states that the plugin is still in development phase and isn't suited for public scrimmages yet. Demanding people to fix things isn't going to fix anything.

**Comment by elespawol** [comment]
That s true, so people be patient
El dia 20/01/2015 18.08, "RyanW" <notifications@github.com> va escriure:

**Comment by twizmwazin** [comment]
I addressed a few spawning issues in [this] (https://github.com/twizmwazin/CardinalPGM/commit/ba3f82d9924e2b23728448717687543113da557b) commit last night. However, it doesn't seem to be entirely one issue, rather a collection of minor issues which are each preventing maps from loading.

**Comment by ItzWid13** [comment]
Its Good now :D
