### ISSUE TITLE
Typing -f anywhere returns: Unknown flag: f

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#773]
If you try to type -f in the chat (like "/g asdf -f ", or without "/g") it results in a "Unknown flag: f" error
Also happens with -n

**Comment by Eudaldca** [comment]
It happens with any character(s) that have a "-" before them. All the commands can "recognise" flags, but only certain commands can use flags, such as end, cycle and so on. This is normal, as writing in the chat is the same as writing /g, /t or /a and your message, depending on your default channel.

**Comment by Pablete1234** [comment]
This does not happen on ocn, so it should be fixed, only commands that use the flags should care about them

**Comment by twizmwazin** [comment]
This is an upstream command framework issue. I'll look into this at some point.

**Comment by dentmaged** [comment]
@twizmwazin This is why you should use Channels.

**Comment by iEli2tyree011** [comment]
@dentmaged Why should we change dependencies because of something that can be fixed by setting a boolean to `true`? :wink:

**Comment by dentmaged** [comment]
@iEli2tyree011 Wait what, you can do that? omg I should really read the Javadocs. meh too lazy.
