### ISSUE TITLE
Observers can modify armor stands

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#774]

**Comment by Eudaldca** [comment]
When testing this, when you've joined a team, you cannot place an armor stand, neither can it be summoned.

**Comment by Pablete1234** [comment]
Eudald, they are like mobs, you can's spawn mobs, you need to add them in the XML, and if you do, and have one in the map, you can place armor on them

**Comment by Eudaldca** [comment]
@Pablete1234 Oh, ok, I really wasn't aware they were treated as mobs.

**Comment by Pablete1234** [comment]
@Eudaldca that might be a bug by itself, the same way villagers are not treated as mobs, and they can be summoned in a match without a ```<mobs>``` module in the xml, maybe armor stands should also be handled like that

**Comment by Prodigy4532** [comment]
You steal my issue :c

**Comment by TiTo-418** [comment]
Fixed
