### ISSUE TITLE
Error when breaking blocks

### ISSUE THREAD

**Issue by Vixo1** [twizmwazin/CardinalPGM#776]
Proof: https://youtu.be/NJrw2ZvOtxs
Logs: http://pastebin.com/Lx7dnLWi

**Comment by twizmwazin** [comment]
you know you can edit your issue rather than open a new one

**Comment by Vixo1** [comment]
ye ik :sweat_smile:

**Comment by iEli2tyree011** [comment]
Can you update your Sportbukkit and make sure you still have this problem? I could not recreate the issue.

**Comment by Vixo1** [comment]
Was my mistake. Thanks @iEli2tyree011
