### ISSUE TITLE
/rank info isn't implemented

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#778]

**Comment by twizmwazin** [comment]
What do we want this command to do? Just display the permissions?

**Comment by TiTo-418** [comment]
The permissions and the ppl who have it?

**Comment by twizmwazin** [comment]
Should it show online players or all players who have the rank?

**Comment by iEli2tyree011** [comment]
@twizmwazin I think online players is fine, all players would get a little spammy. It should also show if the rank is a staff rank and if it's a default rank.

**Comment by Pablete1234** [comment]
@iEli2tyree011 how about adding a ```/rank list player``` that displays the list of ranks the player has?
