### ISSUE TITLE
Forcing cycle with map fails

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#781]
[This](http://youtu.be/fl5LZ5xjWY4).
Version:
![screenshot_223](https://cloud.githubusercontent.com/assets/8332105/8775095/26355b4e-2ee5-11e5-9a60-476c94d02153.png)

**Comment by CaptainElliott** [comment]
Looking into it

**Comment by dentmaged** [comment]
@CaptainElliott Just replace "-f" in ```args.getJoinedStrings(1);```

**Comment by CaptainElliott** [comment]
@dentmaged check my PR. 

But I don't want to do it like that, it's just not very nice

**Comment by dentmaged** [comment]
@CaptainElliott Yeah, Didn't see that, I deleted the comment because I derped.
