### ISSUE TITLE
Changing your rank(s) sends the message twice

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#782]
![2015-07-20_13 51 29](https://cloud.githubusercontent.com/assets/8332105/8775216/72001f9a-2ee6-11e5-8274-49057577a3c2.png)
Should a message "You _removed your_/_have given yourself the_ (rank) rank." be implemented?

**Comment by CaptainElliott** [comment]
this looks intentional

**Comment by Pablete1234** [comment]
i think it should be a differen't message

**Comment by TiTo-418** [comment]
This is intentional

**Comment by twizmwazin** [comment]
I think it would make sense to only show a single message when giving yourself ranks.
