### ISSUE TITLE
Tab Headers and Footers don't display

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#784]
<a href="http://imgur.com/rVfCeFx"><img src="http://i.imgur.com/rVfCeFx.png" title="source: imgur.com" /></a>

**Comment by twizmwazin** [comment]
#329

**Comment by TiTo-418** [comment]
Wait what? Did you remove the "Scrimmage Server" - Time:00:00 - Cardinal ?

**Comment by TiTo-418** [comment]
This 
<a href="http://imgur.com/BHvBgVu"><img src="http://i.imgur.com/BHvBgVu.png" title="source: imgur.com" /></a>

**Comment by TiTo-418** [comment]
Here you have a clearer image
<a href="http://imgur.com/ILbb1AE"><img src="http://i.imgur.com/ILbb1AE.jpg" title="source: imgur.com" /></a>

**Comment by twizmwazin** [comment]
much better title

**Comment by TiTo-418** [comment]
It is inconsistent :P
<a href="http://imgur.com/g7aRYn0"><img src="http://i.imgur.com/g7aRYn0.jpg" title="source: imgur.com" /></a>

**Comment by TiTo-418** [comment]
Whaaaaaaaat? I just care, it has the last map Headers and Footers.

**Comment by twizmwazin** [comment]
@TiTo-418 Can you find a pattern or are there exceptions in the logs?

**Comment by TiTo-418** [comment]
http://pastebin.com/KD6AUdVR

**Comment by Pablete1234** [comment]
@TiTo-418 did it just not work for your fist map? (the map that was playing when you joined the game)

**Comment by TiTo-418** [comment]
@Pablete1234  Nope, Fractal neither

**Comment by twizmwazin** [comment]
see if 15284074693f87aa6ff47ce21729b8e9bf2e0d22 makes a difference

**Comment by TiTo-418** [comment]
Yeah, it is fixed
