### ISSUE TITLE
Proximity does not work in wool

### ISSUE THREAD

**Issue by D4n1e6656** [twizmwazin/CardinalPGM#785]
video proof: https://www.youtube.com/watch?v=cRVowXXsGZ8&feature=youtu.be

Version: http://gyazo.com/c92078c3eb776a94286f21ea01786959

**Comment by Pablete1234** [comment]
¿Que se supone que no funciona?
What isn't working?

**Comment by Alfalik** [comment]
You need to kill a player in the enemy team to get the proximity updated.

**Comment by iPolish** [comment]
In the ocn its not the same

**Comment by D4n1e6656** [comment]
disculpen si hablo en español, pero si se fijan en el vídeo aparece el proximity cuando agarras la lana y debería ser al revés

**Comment by Pablete1234** [comment]
No, hay proximity de llegar a la lana, (que se cuenta por la kill mas cercana a la lana que te hagas), y hay proximity de vuelta, el save mas cercano que pongas a tu base
Si funciona como deberia

**Comment by D4n1e6656** [comment]
disculpa mi error
