### ISSUE TITLE
Sometimes the stars are white

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#786]
In the chat, not in the tab
<a href="http://imgur.com/jfx0SBe"><img src="http://i.imgur.com/jfx0SBe.png" title="source: imgur.com" /></a>

**Comment by iEli2tyree011** [comment]
I'm not sure what would cause this, again, make sure you're testing on a Cardinal server with pretty much WorldEdit being the only other plugin. Other plugins may cause conflicts in Cardinal, and Cardinal is not based around the idea that it should be compatible with those other plugins.

**Comment by TiTo-418** [comment]
Just to note, this was an incompatibility with ColorMe too.
