### ISSUE TITLE
Server crashes on startup if mojang servers are down

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#789]
After loading the maps (and displaying a warn for failed loads), cardinal does something related with mojang servers(maybe getting map author's names?), and if they are down, it takes longer than it should, and server crashes because a single tick took too long
log: http://pastebin.com/RLcdBwdg
Crash: http://pastebin.com/3qzz3ccn

Maybe there should be a check for mojang servers online, if they are offline skip whatever it is

**Comment by DaniOurGamer** [comment]
Puedes pasar el crash report que dice que ha creado.
Can you pass the crash report that says that was created.

**Comment by CaptainElliott** [comment]
We need to crash report..

**Comment by dentmaged** [comment]
It looks like an invalid map error to me. Possible corrupt chunks?

**Comment by Pablete1234** [comment]
@dentmaged any map with problems just gets skipped, (or used to), I've always gotten that warns when opening the server and never gave any errors

**Comment by dentmaged** [comment]
@Pablete1234 well, you may have one map or a corrupt world. But you really need to specify more information.

**Comment by Pablete1234** [comment]
@dentmaged I actually have more than 1 map that doesn't work, and all from A to Z (the ones that don't work) showed the warn, i have the feeling it does pass thru the loading repo stage

**Comment by CoWinkKeyDinkInc** [comment]
Try loading the world in single player.  If it crashes try using older versions of Minecraft and see if it works there.

**Comment by twizmwazin** [comment]
Try @CoWinkKeyDinkInc 's suggestion. Try removing the first map from your repository and see if that changes anything. I feel this is more of a map issue than a Cardinal issue.

**Comment by Pablete1234** [comment]
@twizmwazin @CoWinkKeyDinkInc I tried to open the server with only 1 map on the repo (one that i know that works), and the problem is still the same, the server stops after deleting old match files, and crashes afterwards

**Comment by Pablete1234** [comment]
I think the problem is servers crash because they try to load the author's names, and because the mojang servers are down it can't load them, and  because of the time it took for the plugin to wait for mojang servers' respones, it crashes

**Comment by Prodigy4532** [comment]
Pablete go to bukkit.yml `allow-end: false` | server.PROPERTIES `allow-nether=false` | Delete `world`, delete rotation and try.

**Comment by Pablete1234** [comment]
@Prodigy4532 this is something that only happens when mojang servers are down, do you think i can test it?

**Comment by Prodigy4532** [comment]
You can use AlwaysOnline.

**Comment by Pablete1234** [comment]
@Prodigy4532 cardinal is thought to work by itself, without external plugins.

**Comment by Prodigy4532** [comment]
When servers are down Mojang is better to have something outside who can help.

**Comment by Prodigy4532** [comment]
This server for example: Node42.Minecrafted.net:25593

**Comment by Pablete1234** [comment]
@Prodigy4532 i don't care about your servers, my localhost for testing purposes should be able to load when mojang servers are down, and simply not load author names, let them be "null" and done, and if i set it to offline-mode, i should be able to join

**Comment by Prodigy4532** [comment]
offline-mode ignore the mojang server login, you can enter whit not problem.

**Comment by Pablete1234** [comment]
@Prodigy4532 you are not understeanding the issue, even if you set your server to offline-mode, cardinal will not be able to load if mojang servers are down, it will crash on startup

**Comment by Prodigy4532** [comment]
How much memory is dedicated to your server, i have 1024 mb and ofline mode and i dont have this issue :/ | https://gyazo.com/a6913ea7c00a156d7431f55f8aa8ccce

**Comment by Pablete1234** [comment]
@Prodigy4532 again, you are not understeanding the issue, cardinal can't load because it waits a mojang response for the authors on startup

**Comment by TiTo-418** [comment]
Another crash report http://pastebin.com/jKBvqpfv

**Comment by dentmaged** [comment]
@Pablete1234 Offline mode should be a good recreation of Mojang's servers being down, or atleast I think so. I haven't done Bukkit in ages.

**Comment by Pablete1234** [comment]
@dentmaged i belive cardinal crashes on startup because it tries to get mapmakers' names from the mojang api, if mojang is down, it waits for a response, and 10 seconds later or so, the request times out and the server continues doing other stuff.
The problem is that the downloading was expected to be done in 1 tick, but it took more than the "max-tick-lenght" (or some name like that) and considers itself crashed.

**Comment by Pablete1234** [comment]
fixed in cca5fa4
