### ISSUE TITLE
no moderator system in latest update.

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#795]
http://i.imgur.com/0z5JXlx.png

actually, all players lost their mod, and the /mod command is unknown.

**Comment by twizmwazin** [comment]
This hard-coded feature has been superseded by a much more flexable rank system.

**Comment by kroest** [comment]
@twizmwazin  where can i find info about the new rank system? since it is different from the overcasts rank system.

**Comment by twizmwazin** [comment]
Documentation is pending, I'd appreciate it if someone made English and Spanish articles on how to use it. For now, check out the rank command.

**Comment by iEli2tyree011** [comment]
If you're wondering what the new alternative for the command is, it would be /rank add <player> Moderator. The `Moderator` rank is included by default with the plugin, but the new ranks system allows you to customize and add new ranks with whatever permissions you'd like that rank to have. The "new" moderator rank includes all of the previous permissions that it used to have.

**Comment by kroest** [comment]
i should not use this for help with compiling, but i cant sem to compile the latest version: http://pastebin.com/GiQSqNJp 

any help?

**Comment by twizmwazin** [comment]
You shouldn't be using the download zip button to download the plugin sources. Either clone it properly from git or download a precompiled jar from my build server.

**Comment by kroest** [comment]
@iEli2tyree011  it seems like it doenst detect the new ranks i added in the ranks.xml, i saw that the moderator rank was still in the config file, am i supposed to add the new ranks and permissions in that? or could i remove them there?

**Comment by twizmwazin** [comment]
@kroest Did you restart your server?

**Comment by kroest** [comment]
@twizmwazin 

yes like 10 times, tried out multiple things, this is how my ranks.xml looks now: 

http://pastebin.com/mWj1JVte

and this is my config, 

http://pastebin.com/mwePiKg8

didnt add the ranks below first, didnt work, now i manually added the ranks that i added in the xml, but it doenst recognise any. the worst thing is that it doenst recognise rank 'moderator' now as well.

**Comment by Pablete1234** [comment]
@kroest You have 2 default ranks...

**Comment by kroest** [comment]
@Pablete1234  thanks, fixed tht, but it didnt solve the problem.

**Comment by Pablete1234** [comment]
@kroest remove the permission list on config,yml

**Comment by kroest** [comment]
didnt fix it.

new config: http://pastebin.com/MbUzV7ST

new rank.xml: http://pastebin.com/sytrxUQQ

**Comment by Mystixc** [comment]
@kroest Try using this rank.xml: http://pastebin.com/gS1Wp5hf

**Comment by kroest** [comment]
@Mystixc  that was stupid lmao, thanks, its fixed, it solved the problem.

**Comment by Pablete1234** [comment]
@Mystixc actually it can be done with the structure:
```    <rank name="DMG" staff="true" flair="`4❖" parent="Moderator">
    </rank>```
but it was but it needs to be done right, he had ```</rank>``` twice in every row, that's why it didn't work

**Comment by SungMatt** [comment]
@twizmwazin I'll go make it. Are there only 5 tags in `<rank>`? (Namely `name`, `staff`, `flair`, `parent`, and `default`?

**Comment by TiTo-418** [comment]
@SungMatt I will translate it

**Comment by twizmwazin** [comment]
@SungMatt I believe so
