### ISSUE TITLE
Update proximity color

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#797]
<a href="http://imgur.com/BUmMwtp"><img src="http://i.imgur.com/BUmMwtp.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/Q2RREwx"><img src="http://i.imgur.com/Q2RREwx.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/S577ZLJ"><img src="http://i.imgur.com/S577ZLJ.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/x0B9g5O"><img src="http://i.imgur.com/x0B9g5O.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/4GUh0Xa"><img src="http://i.imgur.com/4GUh0Xa.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/wrgLiyE"><img src="http://i.imgur.com/wrgLiyE.png" title="source: imgur.com" /></a>

**Comment by Pablete1234** [comment]
It just changes the "closest player" (DTC) or "closest kill" (CTW) to gray, and "closest save" (CTW) to yellow

**Comment by Pablete1234** [comment]
@TiTo-418 @iEli2tyree011 fixed in #798 , should be closed
