### ISSUE TITLE
Game wont start

### ISSUE THREAD

**Issue by JugadorNinja** [twizmwazin/CardinalPGM#800]
the games don't start automatically, we have to be online to start every games after its done which is not cool. we don't want to be always online to start every game.
it would be cool to add  Minimum player percentage to start it automatically.

**Comment by ryanw-se** [comment]
This feature isn't required for scrimmages, there have been multiple tickets previously created for this feature and I don't think it will be implemented anytime soon, because people abuse these types of features to create networks, which is against the original intentions of the author. See, #796

**Comment by dentmaged** [comment]
@JugadorNinja go the fuck away with your networks. This is a scrimmage plugin. We aren't your private developers. Hire your own developers and make your own plugin.

**Comment by JugadorNinja** [comment]
Fuck you too than motherfucker

**Comment by Pablete1234** [comment]
@JugadorNinja Cardinal is a scrimmage plugin, not a public server plugin

**Comment by TiTo-418** [comment]
@JugadorNinja Please do not insult, use /report

**Comment by ryanw-se** [comment]
@dentmaged Please be civil, there is no need to be rude or obnoxious. You don't speak on behalf of anyone and the code is licensed under MIT, he can pretty much do anything he wants with the plugin and its code.

**Comment by ryanw-se** [comment]
@JugadorNinja Simply put, the original intentions of the author who created this plugin was for scrimmaging purposes, not for a network. Of course you can use the plugin for whatever you like, however you won't get support if you decide to branch off into that avenue.

**Comment by twizmwazin** [comment]
@dentmaged just because I swear in the issue tracker doesn't mean it is ok for you too.

Closing for pretty obvious reasons. I though about adding this as I thought people were done with their networks, but twice in a row I've been proved wrong.

**Comment by dentmaged** [comment]
@twizmwazin What's wrong with swearing? It's just a word that society has become so scared about. I am entitled to say as I wish and I am doing such a thing.

**Comment by SungMatt** [comment]
@dentmaged Why does a civil conversation require swearing? Dropping an F here and an S there doesn't drive the point home, so why bother? We don't have to use such language on others, do we? (That is unless you are EA. EA is that poor fella who eats at the table alone. EA is truly, a piece of cow manure.)

**Comment by twizmwazin** [comment]
@dentmaged Follow my rules or get blocked, straight forward

**Comment by dentmaged** [comment]
@twizmwazin Be my guest, I have nothing to contribute to a project such as this. I have my own plugins to work on.

**Comment by ryanw-se** [comment]
@dentmaged I'm not sure that you are familiar with the MIT license, the MIT license allows anyone to do what they want with the code as long as attribution is provided back and you don't hold the author liable for damages or anything of that sort.

The link you provided clearly breaks the license terms and it is grounds for a DMCA, saying something is grounds for a DMCA is one thing, actually doing it is another. I also found it rather refreshing that you blamed your age for failing to read one paragraph on http://choosealicense.com/.

**Comment by twizmwazin** [comment]
why are we still talking
