### ISSUE TITLE
server wont cycle to next map

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#801]
i did end the current game, and it does not matter to what map i am cycling.

log: http://pastebin.com/VypbDzLK

chat screenshot: http://i.imgur.com/64YqN5R.png

**Comment by Pablete1234** [comment]
remove uid.dat from the map in the repo

**Comment by kroest** [comment]
@Pablete1234 the map does not consist of a uid.dat, the match map does, which is a bug of the plugin.

**Comment by dentmaged** [comment]
Post the full log.

**Comment by TiTo-418** [comment]
@kroest Delete your match/ folder

**Comment by kroest** [comment]
@TiTo-418  i setted in the config that it automatically deletes the files in there when it ends a match, but ill see if the error reappears.

**Comment by TiTo-418** [comment]
@kroest There are a config for that? O.o

**Comment by dentmaged** [comment]
@TiTo-418 https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/resources/config.yml#L3

**Comment by TiTo-418** [comment]
> i setted in the config that it automatically deletes the files in there when <b>it ends a match</b>, but ill        
>  see if  the error reappears.

**Comment by dentmaged** [comment]
@TiTo-418 Well I guess that is a spelling mistake because I haven't seen any commit adding that.

**Comment by kroest** [comment]
@TiTo-418  it cant remove the match world when its still loaded, but when you end the match and cycle to a new map, it removes the old match world.

**Comment by twizmwazin** [comment]
Matches are deleted when the server is started with that config setting, not when the match ends. Some file systems consider the match files still in use after it is unloaded, and refuse to delete them. That is my workaround.
