### ISSUE TITLE
Default rank isn't given if the player is deoped

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#809]
If you are opped on a server, and you get de-opped, you will not get the default rank. And if you (after being de-opped) get a rank that has the default as parent (like mod), you won't get the default rank either, it's only when you get Mod removed that you get it back.

**Comment by twizmwazin** [comment]
I'm thinking the best way to combat these issues is to move admin over to a rank, and then completely ignore op status altogether.

**Comment by TiTo-418** [comment]
@twizmwazin Yes :D

**Comment by Pablete1234** [comment]
@twizmwazin there is some stuff that doesn't have permissions, it's a op-only feature, are therese getting a permission, so that the admin rank can have them (for example the always-whitelisted & you don't get kicked on /wl kick)

**Comment by twizmwazin** [comment]
@Pablete1234 Perhaps this will apply to any rank that `staff="true"`

**Comment by Pablete1234** [comment]
@twizmwazin it makes sense, start replacing everywhere in the code IsOp for isStaff

**Comment by Pablete1234** [comment]
Fixed in 1.9
