### ISSUE TITLE
Colors in the tab are not applied correctly

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#814]
When the server is closed:
<a href="http://imgur.com/hRiVt61"><img src="http://i.imgur.com/hRiVt61.png" title="source: imgur.com" /></a>
When i open the server:
<a href="http://imgur.com/L0qNZX0"><img src="http://i.imgur.com/L0qNZX0.png" title="source: imgur.com" /></a>
In-game:
<a href="http://imgur.com/kZZGtQd"><img src="http://i.imgur.com/kZZGtQd.png" title="source: imgur.com" /></a>

**Comment by iEli2tyree011** [comment]
You can use `\`` for color codes now

**Comment by dentmaged** [comment]
@iEli2tyree011 On OCN, I think you can use `\`` and `&`

**Comment by iEli2tyree011** [comment]
@dentmaged For what?

**Comment by dentmaged** [comment]
@iEli2tyree011 Just in general, https://github.com/vemacs/Commons/blob/master/bukkit/src/main/java/tc/oc/commons/bukkit/util/BukkitUtils.java#L23

**Comment by TiTo-418** [comment]
@iEli2tyree011 Still not working, when you try to use a color the server-message is changed to "Scrimmage Server"

**Comment by iEli2tyree011** [comment]
@TiTo-418 Logs?

**Comment by TiTo-418** [comment]
@iEli2tyree011 http://pastebin.com/9jNYn1S4

**Comment by iEli2tyree011** [comment]
@TiTo-418 plugin.yml?

**Comment by TiTo-418** [comment]
Where can i find it?

**Comment by iEli2tyree011** [comment]
@TiTo-418 Oops, meant config.yml. I just want to see what you have the message set to

**Comment by TiTo-418** [comment]
I have the default, and i changed "Scrimmage Server" to "'   '1Arya   "

**Comment by iEli2tyree011** [comment]
@TiTo-418 The character is `, not '

**Comment by TiTo-418** [comment]
Ohhh `, ok thanks!

**Comment by TiTo-418** [comment]
`test`

**Comment by TiTo-418** [comment]
@iEli2tyree011 http://pastebin.com/QNP0B9d7

**Comment by SungMatt** [comment]
Does \` work then?

**Comment by TiTo-418** [comment]
@SungMatt Yes, be sure you use this format: 

`
server-message: "`1SungMatt"
`

**Comment by Prodigy4532** [comment]
You can use all - http://ess.khhq.net/mc/
unly use `

**Comment by twizmwazin** [comment]
I think what @SungMatt is asking is if using a backslash will escape the grave symbol. I don't think it will.

**Comment by TiTo-418** [comment]
I think the color characters should be ignored on the motd
<a href="http://imgur.com/TMFBzIu"><img src="http://i.imgur.com/TMFBzIu.png" title="source: imgur.com" /></a>
