### ISSUE TITLE
server crashes/plugin deosnt respond after multiple /recycle 0 or /cycle 0

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#819]
http://pastebin.com/mKRraA3z

**Comment by dentmaged** [comment]
Your server ran out of memory.

**Comment by Pablete1234** [comment]
old maps should get unloaded when map is cycled, and maybe they could be deleted from the disk if the "delete-matches" setting is on

**Comment by iEli2tyree011** [comment]
@Pablete1234 Matches are never completely unloaded until the server is shut down, and therefore have to be deleted on the next server startup.

**Comment by Pablete1234** [comment]
@iEli2tyree011 but is it not possible to totally unload the map when you cycle?

**Comment by iEli2tyree011** [comment]
@Pablete1234 No, the server always keeps it in memory until it is completely shut down.

**Comment by Pablete1234** [comment]
@iEli2tyree011 then this should be closed as there is no way to fix it

**Comment by kroest** [comment]
@Pablete1234  are you sure there are no ways to optimize the plugin and decrease the chances of it running out of memory?

**Comment by Pablete1234** [comment]
@kroest i'm not the one you should be asking to, try asking elly or twiz

**Comment by dentmaged** [comment]
@krost Yes, have global listeners not loads of uselessodules filled with @EventHandlers.

**Comment by kroest** [comment]
@Pablete1234  don't say this should get closed if you don't know if there is a fix for it

**Comment by ryanw-se** [comment]
@kroest I would give http://downloadmoreram.com/ a shot, might fix your problem :laughing:

**Comment by dentmaged** [comment]
@ryanw-se Did you really fall for that scam?

**Comment by kroest** [comment]
@dentmaged  its a joke, dayum

**Comment by Krost** [comment]
Мне кажется вы ошиблись. Я не знаю кто вы и о чем вообще идёт речь.
5 авг. 2015 г. 17:58 пользователь "Jan-Paul Mosterdijk" <
notifications@github.com> написал:

**Comment by ryanw-se** [comment]
@Krost Мои извинения, мой друг mistagged пользователя по имениkroest и вместо вошлиkrost.

**Comment by Krost** [comment]
Не страшно. Удачи в решении проблем :)

5 августа 2015 г., 18:07 пользователь Ryan W <notifications@github.com>
написал:

**Comment by ryanw-se** [comment]
@Krost Спасибо, поздравления из Америки :)

**Comment by iPolish** [comment]
Хахаха )) чо за...

**Comment by twizmwazin** [comment]
Stop running your server on a potato

**Comment by twizmwazin** [comment]
@Pablete1234 memory is has nothing to do with disk space or storage. He is running out of memory, not disk space, so unloading the matches is useless. There may be ways to make the garbage collector more aggressive to free more memory, but I've never tried it.

**Comment by dentmaged** [comment]
@ryanw-se Whopps lol poor krost.
