### ISSUE TITLE
Players being invisible when rejoin an started match

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#82]
After further testing I can con conclude that when the match is started, then any player rejoin it being invisible and nobody can see him.

@Edit Can´t comment more, Ill be on vacations until 27.

**Comment by iEli2tyree011** [comment]
Can you go into further detail? There aren't any player visibility issues on my end.

**Comment by Alfalik** [comment]
Example: 5v5 are playing / Time elapsed 00:05 - Anyone drop connection/have lagg then disconnect and join again. After this, when he join again his team, nobody the server can see him.

**Comment by iEli2tyree011** [comment]
Okay, it looks like there's an issue, I'll look into it.

**Comment by iEli2tyree011** [comment]
The commit did not fix the issue, I'll go into further investigation

**Comment by iEli2tyree011** [comment]
This has been fixed, thanks for reporting.
