### ISSUE TITLE
plugin doens't remove worlds in matches folder, causing /recycle to bug out.

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#820]
http://pastebin.com/cDCdSqXn

[09:57:54] [Server thread/INFO]: Cycling to Deepwind Jungle in 1 seconds
[09:57:55] [Server thread/INFO]: World matches/9e91f0d2-6907-4a74-b6e2-a02a13bcdf74 is a duplicate of another world and has been prevented from loading. Please delete the uid.dat file from matches/9e91f0d2-6907-4a74-b6e2-a02a13bcdf74's world directory if you want to be able to load the duplicate world.

related to https://github.com/twizmwazin/CardinalPGM/issues/801 but i should not be supposed to remove the files there myself and reboot it. this is an issue.

**Comment by twizmwazin** [comment]
The error message literally tells you how to fix it. Delete your uid.dat.

**Comment by kroest** [comment]
like i said, i can remove it every time it bugs out, but it keeps reappearing. isnt there a way to prevent the plugin expecting you to reboot and remove the file manually?

**Comment by twizmwazin** [comment]
stop the server, delete the file from the map folder in "maps/", and restart the server

**Comment by dentmaged** [comment]
@kroest Your server is using an unofficial version of Cardinal, right?

**Comment by kroest** [comment]
@dentmaged i only modified the modt. i found the issue however, i checked all the worlds in my repo, and some indeed had some unnecessary stuff in them.

**Comment by dentmaged** [comment]
@kroest Did you rebase your edit on master?
