### ISSUE TITLE
When you join any team while you are on a playing team already, you're dead.

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#821]
Last version of Cardinal.

**Comment by twizmwazin** [comment]
This was how PGM used to handle this, it isn't a bug. When we switch to the title system this will be removed.

**Comment by AngelCasillas01** [comment]
@twizmwazin oh ok, my bad :p

**Comment by twizmwazin** [comment]
Don't change the issue name

**Comment by AngelCasillas01** [comment]
@twizmwazin again, i'm sorry, it's been a while i haven't come to the repo :/
