### ISSUE TITLE
Reload configuration command

### ISSUE THREAD

**Issue by unixfox** [twizmwazin/CardinalPGM#823]
Ability to reload configuration CardinalPGM (config.yml + ranks.xml) without restarting the server.

**Comment by Pablete1234** [comment]
reloading the map repo would be nice too

**Comment by TiTo-418** [comment]
@Pablete1234 https://github.com/twizmwazin/CardinalPGM/issues/694

**Comment by Pablete1234** [comment]
@TiTo-418 yep

**Comment by AngelCasillas01** [comment]
Why not a /restart ?

**Comment by TiTo-418** [comment]
@AngelCasillas01 https://github.com/twizmwazin/CardinalPGM/issues/678

**Comment by CaptainElliott** [comment]
@AngelCasillas01 /restart physical stops the server and starts it meaning that any games that are in the middle of running are stopped. It also can be unsafe

**Comment by Pablete1234** [comment]
./cardinal reload

**Comment by unixfox** [comment]
@Pablete1234 :+1:

**Comment by twizmwazin** [comment]
I'm thinking more cardinal -r

**Comment by CaptainElliott** [comment]
agreed @twizmwazin

**Comment by ryanw-se** [comment]
Not a big fan of the flag system, its relatively hard for new users to figure out what they mean and most users will attempt to run /cardinal reload rather than /cardinal -r.

**Comment by twizmwazin** [comment]
anything in the cardinal command is generally not something a typical user would need or want to run. With basic documentation, it should be fairly straightforward. Perhaps we can add the long names as well for those who really want to type out more

**Comment by Pablete1234** [comment]
@twizmwazin I still don't get the purpose of /cardinal -v using a flag, when it could be /cardinal version or /cardinal v (alias), and same could apply for reload

**Comment by TiTo-418** [comment]
I agree with @Pablete1234 and @ryanw-se

**Comment by twizmwazin** [comment]
I like flags

**Comment by CaptainElliott** [comment]
we should keep things consistent. The cardinal command uses flags. We can also put a comment in the ranks yml telling you how to reload it.

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/866, then this only will work with ranks.xml

**Comment by twizmwazin** [comment]
@TiTo-418 Or both on anyone using a sane OS.

**Comment by Pablete1234** [comment]
Fixed in 1.9
