### ISSUE TITLE
Help, What means this error code when i´m compiling Cardinal?

### ISSUE THREAD

**Issue by BeastPsycho** [twizmwazin/CardinalPGM#824]
![captura de pantalla 16](https://cloud.githubusercontent.com/assets/8921248/9126908/e63b04de-3c78-11e5-8313-2cc8eff3b733.png)

Any help?

**Comment by iEli2tyree011** [comment]
Build the plugin using the source by doing `git clone https://github.com/twizmwazin/cardinalpgm`, not by using the `Download Source` button.
