### ISSUE TITLE
Scoreboard bug battle ecliptica II

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#825]
You always see all the teams have the same ones as your team has:
![image](https://cloud.githubusercontent.com/assets/11789291/9127440/6b614e06-3cbb-11e5-86fc-11375760de8b.png)
and if you change team, you will always see everyone with the same wools as your team

**Comment by TiTo-418** [comment]
Dupe

**Comment by Pablete1234** [comment]
@TiTo-418 it's not the same issue

**Comment by TiTo-418** [comment]
Yes it is

**Comment by Pablete1234** [comment]
i thought #707 was #593 , sorry
