### ISSUE TITLE
When you do /summon primedtnt on obs, they can destroy objectives and the map

### ISSUE THREAD

**Issue by AngelCasillas01** [twizmwazin/CardinalPGM#828]

**Comment by TiTo-418** [comment]
Just don't do it .-.

**Comment by dentmaged** [comment]
It's the same on Overcast.

**Comment by Pablete1234** [comment]
Tnt spawned via /summon does not have a "player" tag, it doesn't know who placed it, and it should be kept as that for the time being, as tnt on dispensers act like that on cardinal atm

**Comment by Pablete1234** [comment]
@twizmwazin what do you think about this?

**Comment by twizmwazin** [comment]
It probably should behave this way, as this would be the way that pre-placed TNT behaves. Open for opinions though

**Comment by twizmwazin** [comment]
I'm going to close this, I think this is probably the best behavior, pre-placed TNT (not tied to a layer) should damage objectives
