### ISSUE TITLE
Team picker not updated

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#829]
![2015-08-08_13 26 13](https://cloud.githubusercontent.com/assets/8332105/9150281/2702c570-3dd1-11e5-8f88-d944e4e28591.png)
This has recently been added to PGM, when you join a team before the match starts it will no longer remove the helmet picker. Only when you have joined, it will show the boots in the team picker.

**Comment by twizmwazin** [comment]
fixed
