### ISSUE TITLE
Lava inside core shouldn´t be editable & only become in stone with water

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#83]
@Edit bye, im on vacations o/ Ill be testing next wekk.

**Comment by iEli2tyree011** [comment]
This has a planned feature and was just not implemented yet. Thanks for bringing it up though, I'll try to get to it tonight.

**Comment by TiTo-418** [comment]
Still happen, i ll make a video, but you can test it with a bucket

**Comment by TiTo-418** [comment]
@iEli2tyree011
