### ISSUE TITLE
New PROTO

### ISSUE THREAD

**Issue by Lmmb74** [twizmwazin/CardinalPGM#834]
I have been testing with maps using proto 1.4.0 and none of them gets detected by the plugin. But any map using a below version proto, they all work. I don't know if the plugin has not updated its proto or if it's actually my fault. Please tell me

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/401

**Comment by twizmwazin** [comment]
check the xmls for errors, and enable map load errors in the config

**Comment by twizmwazin** [comment]
Going to close this as we are still working towards support for new features. Proto support is of course to be included.
