### ISSUE TITLE
Mirror regions don't return the right values

### ISSUE THREAD

**Issue by iEli2tyree011** [twizmwazin/CardinalPGM#85]

**Comment by twizmwazin** [comment]
So in math I think we figured out the equation `2(orgin) - given`

**Comment by iEli2tyree011** [comment]
Mirror a point across an origin:
    (-1 * (x - originX) + originX)
    (-1 * (z - originZ) + originZ)

**Comment by iEli2tyree011** [comment]
So if origin is (4, 3) and the given point is (5,1), then 2(4) - 5 = 3. 2(3) - 1 = 5.
In my equation, (-1 * (5 - 4) + 4) = 3, and (-1 * (1 - 3) + 3) = 5. So yes, either formula should work.

**Comment by twizmwazin** [comment]
I think that Mirror regions are working correctly, however when loading EnderBlast, it took 36 seconds to load DestroyableObjective.
