### ISSUE TITLE
Observers count towards proximity

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#851]
How to reproduce:
 On DTC, one player joins team read, the other one stays on obs
 /start, and as the joined player gets closer to blue's core/monument, on the scoreboard red appears first (winning team)
 as soon as the observer, goes closer to red's core than the joined player to blue, blue starts winning
 /scores also say that the team with no joined players is winning

**Comment by TiTo-418** [comment]
Forgot to close
