### ISSUE TITLE
You can damage yourself with your arrows

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#855]
![2015-08-26_20 17 57](https://cloud.githubusercontent.com/assets/8332105/9502216/445237f6-4c30-11e5-9bf3-4d5db8edfc4d.png)
Latest [versions](http://prntscr.com/8970xq)

**Comment by dentmaged** [comment]
You also get awarded a kill in TDM.

**Comment by TiTo-418** [comment]
> This is not a bug. You are supposed to be able to hurt yourself with arrows. A bug in Minecraft prevented self-damage if you were on a team with friendly-fire disabled, and I fixed that bug yesterday. The bug affected TNT as well, but only if you activated it with a flint & steel, so few people noticed.
