### ISSUE TITLE
/proximity command is messed up, only shows teams

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#856]
![2015-08-26_20 29 37](https://cloud.githubusercontent.com/assets/8332105/9502383/2e632daa-4c31-11e5-8b65-d8a5e50b6bca.png)
Latest [versions](http://prntscr.com/897345).

**Comment by Pablete1234** [comment]
#853

**Comment by TiTo-418** [comment]
Fixed https://github.com/twizmwazin/CardinalPGM/commit/43c4a332de071ab3174ec0ad0725c0930695abdd
