### ISSUE TITLE
Bossbar blinks

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#858]
![](https://i.gyazo.com/945653c94eb213080294df32d80ced95.gif)
randomly sometimes it blinks

**Comment by TiTo-418** [comment]
@Alfalik

**Comment by Alfalik** [comment]
Does it happen repeatedly/constantly? It occurs in a specific map, or in various?

**Comment by Pablete1234** [comment]
@Alfalik i've seen it happening in different maps, but never towards the start of the match, it always happens towards the end, and when it starts happening, it's quite repeatedly, like every 10 seconds it blinks a couple times

**Comment by twizmwazin** [comment]
I think what is happening here is that the wither is getting repeatedly spawned and renamed. Perhaps we could try reusing withers for as long as possible, that may help to alleviate if not fix the issue entirely.

**Comment by Pablete1234** [comment]
@twizmwazin that's what ocn does, and i said it in the original PR, ocn spawns 1 wither, and then keeps changing the name of that wither, and the position gets updated only if the player moves or moves the camera

**Comment by Pablete1234** [comment]
@Alfalik @twizmwazin It happens only after all mode-changes have ocurred, but when it starts happening it keeps happening quite repeatedly

**Comment by Pablete1234** [comment]
@Alfalik i would also like to point out the empty wither (blank name) does not have any tags with it, so you can see the death animation at 20 blocks of you
I think the distance from the wither to the player should be increased, when falling from a high place, you can see the particles (for example respawn drops)

**Comment by Alfalik** [comment]
@Pablete1234 It was being deleted caused by a wrong inequality, thanks for finding the bug. And about the wither distance, I'll leave it for @twizmwazin, ask him
