### ISSUE TITLE
Can't cycle if the value isn't 5

### ISSUE THREAD

**Issue by Vixo1** [twizmwazin/CardinalPGM#86]
When I try to cycle to another map, if the value is not 5, the plugin doesn't change of map.
For example if I do "/cycle 10" it doesn't do nothing.

**Comment by iEli2tyree011** [comment]
Will look into, thanks for reporting

**Comment by twizmwazin** [comment]
I think this has been long standing for extended periods of time.Time 5 seconds or less I've never had issues with.
