### ISSUE TITLE
When do you join the game after match has started do yo spawn dead!

### ISSUE THREAD

**Issue by BeastPsycho** [twizmwazin/CardinalPGM#865]
Bug? If match has started, after joining the server, you spawn dead, but the "respawn button" sometimes "bugs" and can not respawn the button becomes gray, like this image,
But you join the server dead ever:

![2015-08-31_23 36 47](https://cloud.githubusercontent.com/assets/8921248/9596379/94ebf172-5039-11e5-9a09-b065173c8197.png)

**Comment by TiTo-418** [comment]
Dupe https://github.com/twizmwazin/CardinalPGM/issues/290
