### ISSUE TITLE
config.yml can not be edited while the server is open

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#866]

**Comment by Pablete1234** [comment]
this happens because when the server stops, the config that the server opened gets saved and overwrites the changes you made while the server is open (maybe the config.yml should be read-only and never saved back to, and ranks should be a separate file)

**Comment by twizmwazin** [comment]
This is a Windows filresystem thing, not a Cardinal thing. Nothing I can do about it other than encourage users to upgrade.

**Comment by Pablete1234** [comment]
@twizmwazin i think you could if you only read from the config, and never saved values to it (and save ranks to another file)

**Comment by TiTo-418** [comment]
@twizmwazin Why this do not happen with ranks.xml?

**Comment by dentmaged** [comment]
@TiTo-418 The ranks.xml file uses jDOM, instead of Bukkit's configuration system. jDOM only opens it to read, not to write (which Bukkit's configuration system does).

I think...

**Comment by Pablete1234** [comment]
@TiTo-418 as I said, ranks.xml does not get edited by the server, and therefore is not saved by the server.
the config file contains the list of players with ranks, and it's modified by the server, and saved by the server when the server shuts down

**Comment by twizmwazin** [comment]
@TiTo-418 If I had to assume, @dentmaged is sorta right. The config.yml is a bukkit thing that we use, so it really isn't Cardinal that handles it. I presume craftbukkit keeps an open IO stream to the config files while the server is running. The ranks.xml, on the other hand, is all handled in-house, and we only quickly access it and then close the stream, and then open a new stream later if necessary.

Either way, disallowing concurrent streams is a Windows thing, just about every other operating system under the sun will allow you to have multiple applications accessing the same file. If this is a major issue for you, the only advice I could give would be to write a PR for CraftBukkit (they are really slow to respond to PRs, let alone merge them), or try out a more flexible operating system.

**Comment by TiTo-418** [comment]
@twizmwazin Shared hosts uses Windows?

**Comment by Pablete1234** [comment]
@TiTo-418 most hosted servers use linux-based OS's
