### ISSUE TITLE
Player deals 4 hearts with fists

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#871]
This is a really wierd bug, but sometimes, a player that just joined, deals 4 hearts of damage with his fists, it gets fixed when the player relogs

**Comment by SungMatt** [comment]
How does one recreate this issue, and is this due to strength at spawn?

**Comment by Pablete1234** [comment]
@SungMatt it's not a spawn effect, it's a really random bug that happens sometimes
atm i am getting it kinda consistently on my server if you want to come test it

**Comment by iEli2tyree011** [comment]
@Pablete1234 What does it say a player was killed by if the person with the problem kills someone else?

**Comment by Pablete1234** [comment]
@iEli2tyree011 everything works as usual, it's just like if the player had a str pot (only on fists) and deals 4 hearts consistebtly

**Comment by Pablete1234** [comment]
![](https://i.gyazo.com/c87f003e37f4c59ac09df00603c62137.gif)

**Comment by Pablete1234** [comment]
I don't know why it happens, but the steps that i'm following atm and always gives me the same is:
Piblo joins the game
Piblo clicks autojoin (team picker)
Pablete1234 joins
Pablete1234 /start
Pablete1234 /join
Pablete1234 /j (WE command to to tp faster to the celling)
Pablete1234 /tp Piblo Pablete1234

**Comment by iEli2tyree011** [comment]
@Pablete1234 What happens when someone who is having the problem hits someone else with a wooden sword? Does their damage per hit decrease?

**Comment by Pablete1234** [comment]
@iEli2tyree011 Wooden sword deals 2,5 hearts (1 default +4 wooden sword = 5)
sword damage is correct

**Comment by Pablete1234** [comment]
@iEli2tyree011 the bug gets fixed when the player that deals 4 hearts changes to a sword, and back to the fist

**Comment by Pablete1234** [comment]
This is due to a player keeping an attribute modifier, even after stopping the server (attibute modifiers get saved in the player's .dat file), and it never going away for some reason

**Comment by Pablete1234** [comment]
Fixed in 1.9
