### ISSUE TITLE
You should be able to /! from observers

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#874]
You should be able to use `worldedit.navigation.unstuck` from obs.

**Comment by Pablete1234** [comment]
what does that do?

**Comment by Eudaldca** [comment]
Unstuck. If you're stuck inside blocks, it teleports you outside of them.

**Comment by Vixo1** [comment]
You can get outside of the blocks with the compass in obs

**Comment by Pablete1234** [comment]
yeah @Eudaldca as @Vixo1 said you can /j to get out
