### ISSUE TITLE
Bug with localization

### ISSUE THREAD

**Issue by felipufeliu** [twizmwazin/CardinalPGM#875]
This happened to me before but I am not at computer atm so I can't show a pic

If I have my Minecraft on english and someone, for example Elly has it on spanish it will show a message in spanish when elly do something, for example doing /team alias

It was like this:

felipu: Minecraft in english
Elly: Minecraft in spanish

*felipu_feliu* joined the game
You joined Blue Team
(elly did /team alias blue CAPARAZON)
*on everyone's Minecraft it showed this on spanish*
El equipo Blue Team ha sido renombrado a CAPARAZON exitosamente

In case you don't understand this, i'll show a pic tomorrow, i got to go now

**Comment by TiTo-418** [comment]
Fixed in https://github.com/twizmwazin/CardinalPGM/commit/6f8b889023bdd2a4748e665d1ee4c8649af5a2f1

**Comment by felipufeliu** [comment]
Dang, I didn't notice @tito-418, ty

**Comment by felipufeliu** [comment]
Dang, I didn't notice @tito-418, ty
