### ISSUE TITLE
Core lava primes TNT near it

### ISSUE THREAD

**Issue by dentmaged** [twizmwazin/CardinalPGM#878]
I haven't tried this on OCN, but I don't think it happens. I was testing out a new core defence and I found this happen to me a lot, which I found very annoying.

Sorry I can't record a video, it would be too laggy for me.

Version: ce931d0

**Comment by Pablete1234** [comment]
@dentmaged in ocn the lava inside the core does prime tnt that's close to it

**Comment by dentmaged** [comment]
@Pablete1234 oh, maybe we can fix this regardless of that?

**Comment by Pablete1234** [comment]
@dentmaged i don't see a reason, look at cake wars matches, lava burning down the base is a feature, not a bug

**Comment by twizmwazin** [comment]
I'm pretty sure this isn't an issue. Lava inside of cores is still lava, and should keep the properties of lava.
