### ISSUE TITLE
BossBar doesn't delete after cycling

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#880]
<a href="http://imgur.com/3X4iGS9"><img src="http://i.imgur.com/3X4iGS9.png" title="source: imgur.com" /></a>

**Comment by Pablete1234** [comment]
@TiTo-418 only happens on /cycle 0

**Comment by iEli2tyree011** [comment]
I'm assuming this is because the wither spawn packet is sent after the wither despawn packet

**Comment by dentmaged** [comment]
@iEli2tyree011 Can we please remove support for ```/cycle 0```? It drives me crazy when people do that.

**Comment by twizmwazin** [comment]
@dentmaged  No, that's pointless.

**Comment by Pablete1234** [comment]
maybe /cycle 0 should be a /cycle 1 tick, that may fix the issue

**Comment by Eudaldca** [comment]
0e1a349

**Comment by twizmwazin** [comment]
Fixed
