### ISSUE TITLE
I don't know if this is allowed 

### ISSUE THREAD

**Issue by ElRichMC** [twizmwazin/CardinalPGM#891]
Last days, I've seen lots of servers with the maps stolen from OCN and having different matches loaded with CardinalPGM. I think that the goal of Cardinal is not recreating a network or play ilegal maps, so I think you should not allow this.

I will put it an IP of one of these servers as an example: scrimm.beastmc.com

**Comment by nicogrodri10** [comment]
Thanks to all :)
![desktop 22-09-2015 18-54-45-809](https://cloud.githubusercontent.com/assets/12702702/10025997/91e4ba40-615f-11e5-9224-7667b7cfefd2.png)

**Comment by nicogrodri10** [comment]
Thanks to all :)
![screenshot_1](https://cloud.githubusercontent.com/assets/12702702/10026055/e1db342a-615f-11e5-9dff-067b1f4cb70a.png)

**Comment by colopocositio** [comment]
gg

**Comment by dentmaged** [comment]
rip

**Comment by nicogrodri10** [comment]
EPGM IS BETTER

**Comment by Pablete1234** [comment]
Tito only owns the lobby, all other servers are not his servers... he didn't pay the hosts

**Comment by Alfalik** [comment]
Pretty sure that Tito have OCN's permissions to create a scrimmage network, and as Pablete said, he only owns the lobby, not all servers inside it.

**Comment by Pablete1234** [comment]
@Alfalik yes, he asked ocn for permission, and ocn gave him permission to do it

**Comment by twizmwazin** [comment]
It makes me sad that some of you take pride in hurting those who are really trying to help better a community, taking care not to violate any rules. You aren't the people I want participating in my project.

**Comment by twizmwazin** [comment]
http://prntscr.com/8jf7e7
