### ISSUE TITLE
Fireworks

### ISSUE THREAD

**Issue by Prodigy4532** [twizmwazin/CardinalPGM#909]
In "Overcast Network" Fireworks Work different, when you complete a monument 4 fireworks are launched around the monument. In "CardinalPGM" is released only 1 and the player who complete the monument.

**Comment by SungMatt** [comment]
Things I've found while testing this bug:
There is no firework released at the monument regardless of destruction method.

A firework is only released at the player's location upon the player breaking it, not by player's TNT.

I'll try my hand at this in my flight later today if no one else is going to!

**Comment by TiTo-418** [comment]
Fixed in https://github.com/twizmwazin/CardinalPGM/commit/f317d0254647f22c06ce34bd7aa3c4e72ae66993
