### ISSUE TITLE
[BUG] There's a enter space on the broadcast thing (TIPS)

### ISSUE THREAD

**Issue by felipufeliu** [twizmwazin/CardinalPGM#91]
http://gyazo.com/61c011d80fe9e8c4e3a7739999e64445
Map: NextGen.

**Comment by iEli2tyree011** [comment]
That just looks like a chat size issue. I'll look into it though.

**Comment by iEli2tyree011** [comment]
This is either a non-Cardinal issue or just a small chat size, there's nothing in the code to indicate a new line though.

**Comment by felipufeliu** [comment]
I already make the chat looks bigger, also I tried with full screen and without it and still with the same problem

**Comment by iEli2tyree011** [comment]
http://i.imgur.com/Xy6XKnD.png

**Comment by twizmwazin** [comment]
Make sure you are on the latest version of Cardinal and XML, and then get back to us.

**Comment by iEli2tyree011** [comment]
Can anyone else confirm this issue?

**Comment by iEli2tyree011** [comment]
Closed, can be reopened if necessary...but it seems that no one else is having the issue.
