### ISSUE TITLE
Unknown errors on all commands

### ISSUE THREAD

**Issue by elephant-coder** [twizmwazin/CardinalPGM#912]
Unknown errors are succouring whenever I execute a command. The only thing that works is using /g, /a or /t as a toggle, but even then nothing happens after. I believe it's to do with a non correct rotation config, as that's what the console says. I'm running the latest version taken from the downloads page (336) and also built it myself. I can't figure out the error, but I assume I've made a simple mistake, as nobody else has reported anything. I've posted on the [project Ares forums already](https://oc.tc/forums/topics/551f0fd0c296351fd9000722) but no help was found. 

[An example of the error](http://pastebin.com/H7bCgtrA]
[Server Start to Finish](http://pastebin.com/vjFVjHPB)
[Rotation.txt Screenshot](http://imgur.com/DnIbq65)
[maps repo](http://imgur.com/uTEvCKT)

I have valid map.xml files for each map. I have no idea what could be causing the issue, and I've tried pretty much everything I can think of.

Thanks.

**Comment by elephant-coder** [comment]
The only other plugin I am running is WorldEdit, and even with this removed I still get errors. And my config does point to the correct map directory.

**Comment by twizmwazin** [comment]
The name of the map that you include in the rotation file should be the name found in the map's xml. Cardinal does not care about the folder name in the map repo. Alternatively, try deleting the rotation file. If that still doesn't work try enabling map loading errors in the config.

**Comment by dentmaged** [comment]
Config file?

**Comment by elephant-coder** [comment]
Ah, okay. deleting the rotation file fixed it, although some maps are still not loaded. Any ideas why not? They have valid XML files.

**Comment by twizmwazin** [comment]
Are they missing a level.day or a region folder? Also is the XML actually valid or is it just there?

**Comment by elephant-coder** [comment]
I think I was missing a folder. Redeowloaded maps and it's all working. Thanks!
