### ISSUE TITLE
Private messages sounds are not implemented yet.

### ISSUE THREAD

**Issue by Brokennz** [twizmwazin/CardinalPGM#913]

**Comment by SungMatt** [comment]
Do you know which sounds are played when a PM arrives? It would be nice if you could add that to the [Index of Sounds](https://github.com/twizmwazin/CardinalPGM/issues/227)

**Comment by TiTo-418** [comment]
@SungMatt Same as raindrops

**Comment by SungMatt** [comment]
Cheers, @TiTo-418 .

**Comment by SungMatt** [comment]
Should be fixed with #926.

**Comment by Pablete1234** [comment]
implemented in 1e380db
