### ISSUE TITLE
There is a little delay between the time (bossbar) and the tablist time.

### ISSUE THREAD

**Issue by Brokennz** [twizmwazin/CardinalPGM#916]
I was playing on my cardinal server and I realized that there is a slight delay of 1 second between the "tab" and the time on the bossbar.

[Using the most updated Cardinal Version.]

**Comment by twizmwazin** [comment]
You need to specify which version of cardinal you are using, saying latest isn't helpful, as we update frequently here.

**Comment by Pablete1234** [comment]
@twizmwazin this has always happened (since bossbars came out)

**Comment by twizmwazin** [comment]
Which time is accurate?

**Comment by Pablete1234** [comment]
i think the withers are just a bit off bocs bossbars usually take some time to update client.side, but i never tested

**Comment by Brokennz** [comment]
@twizmwazin I'm using the Build 338.

**Comment by Pablete1234** [comment]
@Brokennz just run /cardinal -v , it should be a commit name like "09d13e7"

**Comment by Brokennz** [comment]
@Pablete1234 @twizmwazin commit 09d13e7

**Comment by GamerPasion** [comment]
It happens on OCN http://i.imgur.com/VloJvMF.png
But anyway , it's a bug.

**Comment by Pablete1234** [comment]
Fixed in 1.9
