### ISSUE TITLE
Scoreboard Issue.

### ISSUE THREAD

**Issue by Prodigy4532** [twizmwazin/CardinalPGM#917]
TDM: No records the points | https://gyazo.com/6f7f88430d69bf7455776a0cb8b8acd2

NAMES: No updates the names on the scoreboard|

https://gyazo.com/30923fd78c9a68465b0371b92fef9025
https://gyazo.com/35a2dd7f8d224301bf5b291a55014cf7

cardinal -v | https://gyazo.com/11fdbcdefcb05ccc446855bb4543445b

**Comment by Alfalik** [comment]
From my quick testing, the problem seems to be <a href="https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/module/modules/scoreboard/ScoreboardModule.java#L539">here</a>.

**Comment by Pablete1234** [comment]
@Alfalik only 262 lines away from the actual error

**Comment by Alfalik** [comment]
you are welcome
