### ISSUE TITLE
Players can be teleported outside of the world

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#920]
Right now on TM servers you can :
/tp someone 99999999 0 0 and crash their client / ilegal position error, if you try:
/minecraft:tp someone 99999999 0 0 it says the number is too big, max is 30000000.

**Comment by TiTo-418** [comment]
Im stupid

**Comment by Pablete1234** [comment]
error 404 , relation between TM and Cardinal not found
