### ISSUE TITLE
When TNT is used the server is laggy.

### ISSUE THREAD

**Issue by Zenzoh** [twizmwazin/CardinalPGM#923]
Error Log: http://pastebin.com/Zgie4p70
Last CardinalPGM build, last SportBukkit build.

Server: http://i.imgur.com/h5wafsF.png (HostHorde)

**Comment by Pablete1234** [comment]
map / map.xml would be appreciated

**Comment by dentmaged** [comment]
Server RAM? Server Host?

I've never encounted this problem on a localhosted server w/ 1 GB RAM.

**Comment by Pablete1234** [comment]
@dentmaged  looking at the logs i belive it is map dependent, some problem with monument modes
(i also saw tnt lag problems in some maps, specially wits end, but i never looked console for errors)

**Comment by Prodigy4532** [comment]
I have one server with 3GB - Minecrafted.net and i dont have this problem.

Node29.Minecrafted.net:25731

**Comment by Pablete1234** [comment]
Guys stop talking about server specs, start talking about the bug

**Comment by dentmaged** [comment]
Oh... This bug
Only occurs on maps with big monuments, if I remember correctly

**Comment by Zenzoh** [comment]
Server: 4GB Ram, HostHorde
XML: https://maps.oc.tc/Other/Tournament/hocArchive/Cannon%20Duel/map.xml

**Comment by Pablete1234** [comment]
@Zenzoh tested right now on cannon duel and everything seems to work nice, and no errors on console

**Comment by dentmaged** [comment]
@Zenzoh when did you last restart your server?

**Comment by Zenzoh** [comment]
@dentmaged Today

**Comment by Zenzoh** [comment]
@Pablete1234 What could it be?

**Comment by Zenzoh** [comment]
Solved, was this...
https://maps.oc.tc/Other/Tournament/hocArchive/house-of-cores.xml

**Comment by Pablete1234** [comment]
@twizmwazin @iEli2tyree011 @CaptainElliott mark this as invalid
