### ISSUE TITLE
When monument mining it doesn't show up in chat

### ISSUE THREAD

**Issue by TeamDDG** [twizmwazin/CardinalPGM#924]
http://pastebin.com/7zaYTkqb

https://gyazo.com/0db741aa40902e7cfbf7b44660487d03

Please help me

**Comment by Pablete1234** [comment]
The map should have the obsidian when you start it, if it's missing, it will be a 0 blocks monument, but a not destroyed monument

**Comment by TeamDDG** [comment]
i got on that cords Obsidian

**Comment by Pablete1234** [comment]
the gyazo doesn't say the same...

**Comment by TeamDDG** [comment]
ill resend a new gyazo

**Comment by TeamDDG** [comment]
https://gyazo.com/a7a248b67b8d632e46bc5a57d42df3a8

**Comment by Pablete1234** [comment]
i can only say make sure that is the coordinate

**Comment by Pablete1234** [comment]
by the way 
<cuboid min="7,74,-897" max="7,74,-897"/>
try to set the min block and the max block properly, a block doesn't start at 7 and end at 7, it either starts at 6 and ends at 7, or starts at 7 and ends at 8 (idk if you understeand what i mean)

**Comment by TeamDDG** [comment]
i made the Cords with F3

**Comment by TeamDDG** [comment]
https://gyazo.com/5b50e3855a2905a6a37f7f148f7e7b51

**Comment by TeamDDG** [comment]
i tried this first and didny work to



27.<destroyables name="Core" completion="100%" materials="obsidian">


28.        <destroyable owner="Luna">      


29.            <cuboid min="7.0,74.0,-709.0" max="7.0,74.0,-709.0"/>


30.    </destroyable>


31.        <destroyable owner="Luna">


32.            <cuboid min="-7.0,73.0,-709.0" max="-7.0,74.0,-709.0"/>


33.    </destroyable>


34.    <destroyable owner="Celestia">


35.            <cuboid min="-7.0,74.0,-897.0" max="-7.0,74.0,-897."/>


36.        </destroyable>


37.    <destroyable owner="Celestia">


38.            <cuboid min="7.0,74.0,-897.0" max="7.0,74.0,-897.0"/>


39.        </destroyable>


40.    </destroyables>

**Comment by Prodigy4532** [comment]
Dont use the same name in all monuments,    example Monument A, Monument B Monument C.

Example: https://maps.oc.tc/Other/Tournament/hocArchive/Fractal%20Descent%20TE/map.xml

**Comment by TeamDDG** [comment]
like this 1 now
http://pastebin.com/jSuzniWQ

**Comment by TeamDDG** [comment]
still doesnt work...

**Comment by Prodigy4532** [comment]
`<cuboid min="7,73,-709" max="7,75,-709"/>`

**Comment by TeamDDG** [comment]
Still doesnt Work

**Comment by TiTo-418** [comment]
Look at the gyazo .-.
![](https://i.gyazo.com/5b50e3855a2905a6a37f7f148f7e7b51.png)
"Looking at: -7,74,-893"

So

`<cuboid min="-7,74,-893" max="-7,74,-893"/>`

**Comment by Pablete1234** [comment]
guys, let's do some math:
``` <cuboid min="7.0,74.0,-897.0" max="7.0,74.0,-897.0"/>```
x: 7.0-7.0 = 0
y = 74.0 - 74.0 = 0
 (-897.0) - (-897.0) = 0
your region is 0x0x0

how do you expect the monument to work...

if it says "block : -7 74 -897", it means the center of the block is that coord, but you need the min and the max
example in Y: if it says Y: 74, it means the center of the block is in 74.5, so the block, goes from 74.0 to 75.0
(take care with negative numbers, they are not what you expect, stand on the corner of the block (between 4 blocks) and look at "XYZ: x / y / z", it will be close to a round number(the one you need), if you stand on the middle it will be close to a 0.5 number)

**Comment by TeamDDG** [comment]
i got this now
http://pastebin.com/qqmnVYmS

**Comment by Pablete1234** [comment]
Max and min coords are the same, min should be 1 block lower than max

**Comment by dentmaged** [comment]
Avicus map, eh?

**Comment by Pablete1234** [comment]
@twizmwazin i belive it's an xml error, not a plugin error, mark as invalid

**Comment by Alfalik** [comment]
Since the people believe that all of us know XML, here it is.
```xml
<destroyables materials="obsidian" owner="Luna">
    <destroyable name="Left Monument">
        <cuboid min="8,75,-708" max="6,73,-710"/>
    </destroyable>
    <destroyable name="Right Monument">
        <cuboid min="-8,75,-708" max="-6,73,-710"/>
    </destroyable>
    <destroyable name="Back Monument">
        <cuboid min="-1,89,-680" max="1,91,-678"/>
    </destroyable>
</destroyables>
<destroyables materials="obsidian" owner="Celestia">
    <destroyable name="Left Monument">
           <cuboid min="8,73,-896" max="6,75,-898"/>
    </destroyable>
    <destroyable name="Right Monument">
        <cuboid min="-8,73,-896" max="-6,75,-898"/>
    </destroyable>
    <destroyable name="Back Monument">
        <cuboid min="-189,-926" max="1,91,-928"/>
    </destroyable>
</destroyables>
```
Hope it fix your monument not being recognized, regards.

**Comment by dentmaged** [comment]
@Alfalik Don't you think it would be simpler just to use:
`<block>7, 74, -897</block>`?

**Comment by Alfalik** [comment]
@dentmaged Was just clarifying how to use cuboid regions, it'll be the same anyway.
