### ISSUE TITLE
Lets talk about ethics

### ISSUE THREAD

**Issue by rywarsaw** [twizmwazin/CardinalPGM#93]
Hey guys, this isn't really a issue more a discussion of where CardinalPGM is headed. I've been watching the progress of CardinalPGM and its really been making leaps and bounds however some things disturb me. 

The idea behind CardinalPGM was to create a system for tournament teams to do scrimmages? Yes? Well I'm seeing that more and more features are being added to CardinalPGM that aren't really needed to perform a actual Scrimmage, and more act like a PGM clone. 

I see this plugin being abused and not used a tournament plugin, and more as a way for public networks to clone the Overcast Network. Now I am not sure about the legal aspects of this, but I believe that CardinalPGM should respect the fact that the PGM plugin is private for a reason and based apon thousands of hours of hard work put in by its founders. 

Conclusion, lets focus more on what actually needs to be done to perform a scrimmage on this server, and less on it being a word for word, color for color OCN clone. Here are some suggestions that make sense for your average scrimmage.

CTW, DTM, DTC, TDM, and KOTH all are gamemodes you might find at a Overcast Network tournament! These should be the main focus, specifically.

Scoreboard cloning, XML tip broadcasts, completely copy and pasted in-game messages, and other various things that aren't needed to perform a scrimmage, shouldn't be present. Just playing around with the plugin, you could actually trick someone into thinking they are playing on the Overcast Network, which isn't your guys intentions and isn't a good thing. 

Thanks for reading guys,

Don't take this as a bash to your project, I'm merely giving my feedback!

**Comment by elespawol** [comment]
+1
El dia 21/01/2015 19.04, "RyanW" <notifications@github.com> va escriure:

**Comment by iEli2tyree011** [comment]
How are some of the things you listed unnecessary for a scrimmage plugin?

**Comment by elespawol** [comment]
Like: rotations
Are not necesary if is not public, because u put a map when u want to do a
scrim
Rotations is like something automatic
El dia 21/01/2015 19.09, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by iEli2tyree011** [comment]
While that may be true, what map will the server start on? What map will be next? We can't just remove cycling.

**Comment by elespawol** [comment]
In config.yml u can put a setting that is: what map to start/RANDOM
El dia 21/01/2015 19.14, "iEli2tyree011" <notifications@github.com> va
escriure:

**Comment by rywarsaw** [comment]
@iEli2tyree011 There was alot of time spent on formatting of messages, what colors, etc. That was my main point there is alot of time spent in making it look exactly like OCN, @elespawol has a point with rotations but I think that goes too far. Removing rotations would just remove functionality from the plugin, I'm mainly discussing things that are completely aesthetic, and some non-aesthetic ones.

**Comment by CaptainElliott** [comment]
I think some  hard coded some tips stating the fact that this is only to be used a s scrimmage plugin, in addition I think the rotation should be removed, its not needed for scrimmages and that is what could make this server into a clone of PGM

However you have to remember even if we did not include all of the aesthetically things in PGM (like broadcasts) it only takes someone with a little java knowledge to add them to this plugin.

There isn't much that can be done, I don't really know the legal stuff behind these types of things.

**Comment by rywarsaw** [comment]
@CaptainElliott Thats a really good way of putting things, didn't think about it like that. I don't think CardinalPGM will have any legal problems, this was mainly brought up to show respect to the author of the original PGM plugin by not complete making something that looks and functions exactly how creators version does. 

Removing formatting is more of a way to distinguish CardinalPGM as instead of just a Overcast Network tournament plugin, as a more broad generic one that can be used across networks. I know several PvP networks that at the time used SporkPGM so CardinalPGM is no different. 

Even though though it is intended to be used as only a Scrimmage Plugin, it can be abused to become a full public server network plugin. Unfortunately we live in a world where people don't really give a damn about licenses, or authors intent.

**Comment by rywarsaw** [comment]
Also, check this out: http://lmgtfy.com/?q=PGM+Plugin+Clone

**Comment by twizmwazin** [comment]
CardinalPGM's main goal is to be a feature-complete PGM clone. That is what the project description is, that is what I set out to create, and that is what I will finish. If you do not support my plan, then you can either fork the plugin as it is and go your own way, or you can choose to abstain from involvement in the project altogether. 

There are no agreed upon terms (EULA) to play and observe the mechanics of the Overcast Network. All of the resources used in this project have been obtained legitimately. I have not ever viewed or possessed any, in part or whole, PGM source. Cardinal is entirely reversed engineered, and therefore no legal repercussions could be made. The only grounds that could be debated are using "PGM" in the name, as that is an Overcast Network trademark. However, if I am ever approached be a representative of the Overcast Network on this, I can easily remove all references to "PGM" from the project.
