### ISSUE TITLE
Bug with kits in latest version

### ISSUE THREAD

**Issue by unipablojorge** [twizmwazin/CardinalPGM#930]
Hello, im making a map for oc.tc. I was trying the map and suddently the kits don't work.
I have updated the Cardinal and SportBukkit version but still not working.

Here you have some links with the map and XML and the crash i get when i cycle there. (the cycle event is working well, i can cycle to the map)

Map with XML: http://www.mediafire.com/download/9mlmbpv522vkqr2/SkyBattle_2.0.zip

Error I get before the cycle finishes: http://pastebin.com/Xe4UqHxJ

I hope you can help me!

Thanks.

**Comment by CaptainElliott** [comment]
Can we get just a pastbin of the xml please?

**Comment by unipablojorge** [comment]
http://pastebin.com/w8mmnhX1 there you go

**Comment by Alfalik** [comment]
@unipablojorge Kits are not being applied. Your forgot to apply kits on the ```<spawn>``` module, I'll fix that section for you:
```xml
<teams>
    <team kit="blue" id="blue-team" color="blue" max="14">Blue Team</team>
    <team kit="red" id="red-team" color="dark red" max="14">Red Team</team>
</teams>
```
Hope it fix your problem, regards.

**Comment by Alfalik** [comment]
@unipablojorge You are missing a ```6``` on the line 29 (instead of ```006cc``` it should be ```0066cc```).

**Comment by unipablojorge** [comment]
I have done that but still getting the error...

**Comment by Alfalik** [comment]
@unipablojorge A complete log would be very useful, besides the XML and the map (if you don't want it public, contact me via Skype).

**Comment by xFracTV** [comment]
` <kit id="spawn">
                <item slot="0">wooden sword</item>
                <item slot="8" amount="64">carrot</item>
        </kit>
        <kit id="red" parents="spawn">
                <helmet color="cd0000">LEATHER_HELMET</helmet>
                <chestplate>DIAMOND_CHESTPLATE</chestplate>
                <leggings>DIAMOND_LEGGINGS</leggings>
                <boots color="cd0000">LEATHER_BOOTS</boots>
        </kit>
        <kit id="blue" parents="spawn">
                <helmet color="006cc">LEATHER_HELMET</helmet>
                <chestplate>DIAMOND_CHESTPLATE</chestplate>
                <leggings>DIAMOND_LEGGINGS</leggings>
                <boots color="0066cc">LEATHER_BOOTS</boots>
        </kit>`

Dont use: DIAMOND_LEGGINGS
  Correct: diamond leggings

**Comment by Pablete1234** [comment]
@xFracTV i'm not sure if the "helmet, chestplate, leggings and boots" tags are implemented

**Comment by Pablete1234** [comment]
as it seems like it's fixed i'm closing, @unipablojorge if it didn't work, say something and i'll reopen it
