### ISSUE TITLE
Portals doesn't work

### ISSUE THREAD

**Issue by Shipi1** [twizmwazin/CardinalPGM#936]
In 1.0-SNAPSHOT-git-CardinalPGM-08f7a6d the portals doesn't work....

**Comment by SungMatt** [comment]
Can you please provide the XML of the map that is provided? It may be similar to issue #712.

**Comment by Shipi1** [comment]
https://maps.oc.tc/CTW/Standard/Ethereal/map.xml

**Comment by Pablete1234** [comment]
@Shipi1 make sure you have the lastest sportbukkit version, i remember older versions having issues with that

**Comment by xFracTV** [comment]
You need use SportBukkit 1.8.7.

**Comment by Shipi1** [comment]
I have the lastest SportBukkit version (1.8.7-041720)

**Comment by twizmwazin** [comment]
Are they any errors on the log?

**Comment by twizmwazin** [comment]
Closing as it is likely invalid or a duplicate
