### ISSUE TITLE
Bug in /team force [name] [team]

### ISSUE THREAD

**Issue by vYuri** [twizmwazin/CardinalPGM#94]
Well, today testing the command /team force found a bug, If I force a player who is playing to obs team, so I can see pushing TAB (as shown in the picture) http://gyazo.com/ca5fb09847b41c192253548e6c19d578

**Comment by iEli2tyree011** [comment]
What is the actual issue here?

**Comment by iEli2tyree011** [comment]
Nevermim, got it.

**Comment by iEli2tyree011** [comment]
When did you last compile the plugin? This should have been fixed along with #82.

**Comment by vYuri** [comment]
I compile the plugin yesterday about #83.

**Comment by iEli2tyree011** [comment]
Can you recompile and test again please?

**Comment by vYuri** [comment]
Sure, I'll tell happens after this compilation.

**Comment by vYuri** [comment]
This still happens

**Comment by iEli2tyree011** [comment]
I'll look into it when I get home, thanks for reporting. So it happens when someone that is playing is forced to observers?

**Comment by vYuri** [comment]
If this happens when a player is forced to observers, they also once again joineen can see others obs

**Comment by iEli2tyree011** [comment]
Closed in b76f5bf.
