### ISSUE TITLE
Bossbar flag "min"

### ISSUE THREAD

**Issue by xFracTV** [twizmwazin/CardinalPGM#951]
When the XML has the flag "min = 6" the bossbar says only missing 2 and not updated.

`<team color="blue" min="6" max="10" max-overfill="10">Blue</team>`
`<team color="red" min="6" max="10" max-overfill="10">Red</team>`

https://gyazo.com/b8e3e6ad28509e269b84b63d48aee9fd

**Comment by Pablete1234** [comment]
fixed in c798a6e
