### ISSUE TITLE
MySQL Stats Database - Missing Feature

### ISSUE THREAD

**Issue by Lmmb74** [twizmwazin/CardinalPGM#953]
Hello, I think it would be awesome to add a stats system just like oc.tc has. So when a player gets a kill, places a wool, or destroys a core, it gets stored into a database.

**Comment by Pablete1234** [comment]
it would get griefed so easy...

**Comment by Lmmb74** [comment]
But wouldn't it be cool to have a stats system?

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/219

**Comment by Lmmb74** [comment]
Ok.

**Comment by Pablete1234** [comment]
@Lmmb74 it would be nice to have a stats system, but anyone could start setting everyone's objectives to 100000 and it would make no sense to have it anymore

**Comment by Lmmb74** [comment]
Despite of that, it should get implemented for any serious pvp network using this plugin.

**Comment by Pablete1234** [comment]
@TiTo-418 it's a different thing, #219 is about the local database, used to store snowflakes, and other stuff, this is talking about a database on a server

@Lmmb74 this is a scrimmage plugin, not a plugin for networks

**Comment by Lmmb74** [comment]
#219 that is what I was talking about, sorry if I didn't express correctly

**Comment by Pablete1234** [comment]
@Lmmb74 so, local database?

**Comment by Lmmb74** [comment]
any stats on its local database, or an external database using mysql

**Comment by Pablete1234** [comment]
I think it should be tracked in #219
