### ISSUE TITLE
Players with invisibility do not have their nametags set invisible

### ISSUE THREAD

**Issue by SungMatt** [twizmwazin/CardinalPGM#959]
In maps that have invisibility potions for stealth, nametags should automatically disappear upon receiving the invisibility effect.

https://www.youtube.com/v/MpwOUXiCP4g

**Comment by Pablete1234** [comment]
@SungMatt doesn't it work exactly like that ATM on ocn?
the only solution i can think of (1.8 minecraft) is when creating the teams, create a "blue team" and a "hidden blue team", when a player gets invisibility, send to players not on the same team the packet that the player joined the "hidden blue team", that way, reds will not see names for players inside "hidden blue team"
still, i would like to see if ocn fixes this at all
https://bugs.mojang.com/browse/MC-48730

**Comment by SungMatt** [comment]
@Pablete1234 OCN has implemented this invisible players with invisible nametags since I started playing (Last few months of 2013). Trench Warfare 2 would be hillarious without it, the invisible guys are 2 hits away from death, and with the name tag what is the use of invisibility?

**Comment by Pablete1234** [comment]
@SungMatt that was in 1.7, in 1.8 it's broken, i know because i've played mutated matches with invisibility

**Comment by Pablete1234** [comment]
It's a bug related to minecraft / bukkit / sportbukkit, and can't be fixed via cardinal in 1.8, and in 1.9 it's already fixed
