### ISSUE TITLE
[Question] plugin.yml

### ISSUE THREAD

**Issue by Rafitamolin** [twizmwazin/CardinalPGM#96]
I compiled CardinalPGM without errors but when I try to open my server with the plugin it says that the plugin.yml file is invalid. The thing I'm getting there is:

>name: ${plugin.name}
>description: ${project.description}
main: ${plugin.mainClass}
version: ${project.version}
authors: [twiz_mwazin]
prefix: CardinalPGM

I don't what should I do to fix that. Can someone help me, please? Thanks

**Comment by twizmwazin** [comment]
Try recompiling, all of those values should be filled in by maven.

**Comment by Rafitamolin** [comment]
I tried three times but nothing happens. I followed [this](https://www.youtube.com/watch?v=khetsOtDoPU) tutorial to compile the plugin, and I get those warnings: http://i.imgur.com/Y0DLBn9.png.

Is there something I'm doing wrong?

**Comment by twizmwazin** [comment]
Follow [this] (https://github.com/twizmwazin/CardinalPGM/wiki/Installing-CardinalPGM) one, and compile it with mavan, not eclipse.

**Comment by Rafitamolin** [comment]
Thank you so much. I didn't even notice there was a wiki page explaining all the process. I compiled the plugin now without any errors :)
