### ISSUE TITLE
Spleefing yourself awards a point to your team

### ISSUE THREAD

**Issue by intenseoxygen** [twizmwazin/CardinalPGM#974]
Hello,

I was playing around with this plugin and i found that if you spleef yourself in a TDM game, the point goes to your team, so people can abuse it by spleefing themselves and spoofing their score on the scoreboard.

**Comment by SungMatt** [comment]
In overcast, does this decrement a point? Will be willing to work on it.

**Comment by twizmwazin** [comment]
I'd think the fix should just be adding a check [here](https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/module/modules/score/ScoreModule.java#L101).

**Comment by intenseoxygen** [comment]
Also, this is unrelated, but I was experimenting with the map.xml and is there any way to prevent negative points in the map.xml? cause my friends and I were scrimmaging and sometimes they'd jump into the void/lava and purposely kill themselves which takes a point away from the score. (TDM)

**Comment by Pablete1234** [comment]
@intenseoxygen look at docs.oc.tc, yes, you can set ponts awarded per kill, and points removed per death

**Comment by intenseoxygen** [comment]
@Pablete1234 by default does it remove 1 point? Cause that's what I see happening

**Comment by Pablete1234** [comment]
https://docs.oc.tc/modules/scoring

in proto 1.3 (when cardinal was created) i belive the default was +1 or -1

**Comment by intenseoxygen** [comment]
@Pablete1234 thanks!

**Comment by Pablete1234** [comment]
@intenseoxygen fixed the "side" bug in 1378bad (it's needed for the future ctf, as some old maps need to have it as a default to 1, and new maps need it default to 0)

**Comment by intenseoxygen** [comment]
Awesome thanks!
