### ISSUE TITLE
Regions on Terricreus does not work

### ISSUE THREAD

**Issue by Betah** [twizmwazin/CardinalPGM#976]
XML: http://pastebin.com/yUNAENHG
Cardinal: f84e276
SportBukkit: 2712c8d

If can not implement the new region filters of Map Proto 1.4.0, can anyone help me with the XML? Thanks very much.

**Comment by Pablete1234** [comment]
I properly tested this, and it's only due to the fact that the xml contains a `<below y="18"/>` region, if you want a fix for it, use `<cuboid min="-oo,-oo,-oo" max="oo,18,oo"/>` instead, this should be followed in #888
