### ISSUE TITLE
Console can use /minecraft:tell

### ISSUE THREAD

**Issue by Betah** [twizmwazin/CardinalPGM#978]
I think it's a bug because the console can't use /cardinal:msg

**Comment by Betah** [comment]
I know, but console can use /minecraft:tell `http://i.imgur.com/c42bs0G.png`
Reading comprehension.

**Comment by TiTo-418** [comment]
@Betah What's the problem with it?

**Comment by Betah** [comment]
@TiTo-418 In theory the console should not be able to send private messages to players, but can do it.

**Comment by TiTo-418** [comment]
It has nothing to do with cardinal

**Comment by Betah** [comment]
@TiTo-418 But can easily disable it.

**Comment by Pablete1234** [comment]
@Betah minecraft:tell is a minecraft command, ask mojang to change it.

**Comment by Betah** [comment]
@Pablete1234 It's a command used by all, unlike a bugged plugin.

**Comment by twizmwazin** [comment]
We can change player permissions to disable players from using any command, however we cannot modify permissions of the console.

**Comment by Betah** [comment]
Sorry.
