### ISSUE TITLE
Issue with core modes

### ISSUE THREAD

**Issue by Vixo1** [twizmwazin/CardinalPGM#98]
We was playing "Iris DTC" and at 15min of the match the core changed to gold core mode.
I checked on the xml of the map but theres nothing about core modes.

I'll test if it happens on all maps or only on Iris.

EDIT: I checked on another map that don't have core modes in the xml and it happens too
![2015-01-23_03 44 47](https://cloud.githubusercontent.com/assets/10608917/5870763/33ef1b22-a2b2-11e4-959b-fca0c096de14.png)

![2015-01-23_03 35 31](https://cloud.githubusercontent.com/assets/10608917/5870737/d5969e2e-a2b1-11e4-911a-26b4f03487aa.png)
![2015-01-23_03 42 07](https://cloud.githubusercontent.com/assets/10608917/5870736/d59604e6-a2b1-11e4-97b7-443c3da89def.png)

**Comment by twizmwazin** [comment]
Gold and glass core modes occur by default, this is intentional. For Iris make sure you have a correct XML.

**Comment by iEli2tyree011** [comment]
I think there's a problem with Iris, but Blocks is supposed to have core modes...

**Comment by iEli2tyree011** [comment]
Never mind; your version of Iris's XML actually has the core modes in it.

**Comment by Vixo1** [comment]
The problem only happens in Iris DTC, can you revise it please?

**Comment by iEli2tyree011** [comment]
What is the problem?

**Comment by Vixo1** [comment]
Gold core mode, because in scrimmages the core needs to be obsidian I think...

**Comment by twizmwazin** [comment]
It varies by map. By default, the core is obsidian, gold, glass. However, a map maker can specify other core modes if he/she chooses.

**Comment by TiTo-418** [comment]
I think this isn't working on Cake Wars
XML: https://maps.oc.tc/Other/Tournament/hocArchive/Cake%20Wars%20TE/map.xml

**Comment by TiTo-418** [comment]
`In order for an objective to change modes, it must have mode-changes="true" in its element tag.`

https://docs.oc.tc/modules/monument_modes
