### ISSUE TITLE
Potion module not implemented

### ISSUE THREAD

**Issue by Lmmb74** [twizmwazin/CardinalPGM#980]
Hi, I found that the modules potion, void and the new kit module are not implemented in Cardinal, could somebody add them?

**Comment by Pablete1234** [comment]
@Lmmb74 `<above y="90"/>` half space regions are not implemented

**Comment by Lmmb74** [comment]
Thanks

**Comment by Lmmb74** [comment]
Pablete, necesito que me ayudes en algo, si tenes skype contactame por favor, mi usuario es Lmmb74 en skype

**Comment by twizmwazin** [comment]
@Lmmb74 This issue tracker is english-only. If you are going to say something in your native language, provide an english translation, or at least your best attempt.

**Comment by Lmmb74** [comment]
Ok, I was telling Pablete to contact me on skype, since I need his help. And sorry.

**Comment by Pablete1234** [comment]
Fixed with Kits Rewrite
