### ISSUE TITLE
Error occurred while enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-f84e276 (Is it up to date?)

### ISSUE THREAD

**Issue by NurdTurd** [twizmwazin/CardinalPGM#981]
Here's a link to the log: http://pastebin.com/zY2eqp9N

I'm running version v1.0-SNAPSHOT from the build server.

To produce the bug: Start up the server.

I'm using SportBukkit version 1.8.7.

**Comment by NurdTurd** [comment]
I only had 1 map in my `maps/` folder. Adding 2 made it work. Keeping this open until I make sure that's the issue.

**Comment by twizmwazin** [comment]
To understand Cardinal's versioning, every version of Cardinal to date has beed 1.0-SNAPSHOT. The important version that we need is the git commit, which is the last 6 characters of the version, `f84e276` according to your log.

**Comment by twizmwazin** [comment]
Double check that one map as well. It looks at a glance that the one map you are trying to use isn't loaded for some reason. Cardinal requires a map.xml, region.dat, and a region folder to consider loading a map.

**Comment by NurdTurd** [comment]
http://pastebin.com/Y7hqfX2s

Both maps have a `map.xml`, `region.dat` and a `region/` folder, and a `level.dat`.

**Comment by NurdTurd** [comment]
Adding on to that, it threw me this: http://pastebin.com/R42ztiDg

**Comment by NurdTurd** [comment]
Seems to be an issue with the map I tried.

**Comment by twizmwazin** [comment]
Could you provide the XML?

**Comment by NurdTurd** [comment]
Sure. http://pastebin.com/gNVZz5QQ

**Comment by NurdTurd** [comment]
Also, why is TNT very laggy? It's very slow.

**Comment by twizmwazin** [comment]
It may be possibly related to @Pablete1234's long distance TNT rendering. But that's off topic

**Comment by NurdTurd** [comment]
Alright.

**Comment by NurdTurd** [comment]
What is 1.4 proto ?

**Comment by Pablete1234** [comment]
@twizmwazin that commit number does not have the long render distance tnt patch
TNT is laggy "by default" in all 1.4 proto maps, because regions / applied give npe's that fill up the whole console and freeze the server

**Comment by Pablete1234** [comment]
@NurdTurd The error you are getting is part of an invalid rotation.txt, delete it to generate a valid one automatically, or put valid maps on it

**Comment by Lmmb74** [comment]
This should be closed if @NurdTurd has solved his problem.
