### ISSUE TITLE
Autocycle

### ISSUE THREAD

**Issue by intenseoxygen** [twizmwazin/CardinalPGM#984]
Hi,

From a prior issue, it looked like autocycle was implemented, but I'm not sure. Does the game autocycle when it ends? Or is there something I'm missing out on? It doesn't autocycle for me, and when my friends and I scrimmage I always have to keep doing /cycle since I'm the only one Opped.

**Comment by Lmmb74** [comment]
Have you taken a look in the config? There is an option to enable it and set the time before it cycles.

**Comment by Pablete1234** [comment]
@intenseoxygen Autocycle does work, you just need to change the setting in the config
(To change the config, you need to turn off the server first)

**Comment by intenseoxygen** [comment]
I skimmed through it, guess I never looked enough. Thanks :+1:
