### ISSUE TITLE
Set global as the default channel

### ISSUE THREAD

**Issue by intenseoxygen** [twizmwazin/CardinalPGM#985]
Hey,

Sorry for creating this, but is there a way to set the global channel as default? I looked through the config, and couldn't find anything. I know we can do it ingame, but is there a way to set it default for the entire server?

**Comment by twizmwazin** [comment]
/g. Issues are not for questions.

**Comment by intenseoxygen** [comment]
I know, but everyone has to do it. By default all players are in team chat and have to do /g to get out of it.

**Comment by twizmwazin** [comment]
I don't know, perhaps ask other users. There is no implemented method to make global chat default.

**Comment by intenseoxygen** [comment]
Thanks
