### ISSUE TITLE
Who is 'Infinity' ?

### ISSUE THREAD

**Issue by NurdTurd** [twizmwazin/CardinalPGM#987]
![Screenshot](https://shel.io/f/8Sq.png)

Happens when you execute `/proximity`.

There is only me online on the server.

**Comment by Pablete1234** [comment]
Infinity is a number

**Comment by NurdTurd** [comment]
I'm so confused though. Why would it say Infinity?

**Comment by Pablete1234** [comment]
because  no one made any proximity to that core, join the team, get proximity, and it will turn into a number

**Comment by NurdTurd** [comment]
Right, but technically it shouldn't say Infinity.

**Comment by NurdTurd** [comment]
Infinity is a valid term for what's going on.

**Comment by NurdTurd** [comment]
"No Teams" or "No Player" would be better.

**Comment by Pablete1234** [comment]
@NurdTurd It's just the parsing of a number, it could be closest player, closest block, or closest kill, so it's nlt worth fixing and adding a diferent translation

**Comment by NurdTurd** [comment]
Fair enough.
