### ISSUE TITLE
Access Denied (Maven trying to built Cardinal)

### ISSUE THREAD

**Issue by GChevy** [twizmwazin/CardinalPGM#99]
Maven version 3.2.5

And i get the correct git

http://gyazo.com/720cc75b640c34881e27b3b04e72da90

**Comment by CaptainElliott** [comment]
you need to navigate to the main directory where Cardinal PGM is by using the `cd` command 
or you could `shift + right click` inside the main directory where Cardinal is.
then you can execute the command `mvn clean install` - but make sure not to add any extra arguments.

Also make sure you have opened the command line with administrator privileges

**Comment by GChevy** [comment]
Thank you!

**Comment by GChevy** [comment]
http://gyazo.com/e53821dd06b9ef2cab2af8b76ccc6773 How i can re-run Maven?

**Comment by twizmwazin** [comment]
Pull the latest code from git and then run `mvn clean install` again

**Comment by GChevy** [comment]
I already did but it did not fix it

**Comment by twizmwazin** [comment]
Try re-cloning the repository and then run maven.

**Comment by AngelCasillas01** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project CardinalPGM: Compilation failure: Compila
tion failure:
[ERROR] error reading C:\Users\Angel\.m2\repository\org\bukkit\bukkit\1.4.7-R1.0
\bukkit-1.4.7-R1.0.jar; error in opening zip file
[ERROR] error reading C:\Users\Angel\.m2\repository\in\parapengu\commons\1.1.2\c
ommons-1.1.2.jar; error in opening zip file
[ERROR] error reading C:\Users\Angel\.m2\repository\com\comphenix\executors\Bukk
itExecutors\1.0.0\BukkitExecutors-1.0.0.jar; error in opening zip file
[ERROR] error reading C:\Users\Angel\.m2\repository\org\bukkit\bukkit\1.4.7-R1.0
\bukkit-1.4.7-R1.0.jar; error in opening zip file
[ERROR] error reading C:\Users\Angel\.m2\repository\in\parapengu\commons\1.1.2\c
ommons-1.1.2.jar; error in opening zip file
[ERROR] error reading C:\Users\Angel\.m2\repository\com\comphenix\executors\Bukk
itExecutors\1.0.0\BukkitExecutors-1.0.0.jar; error in opening zip file
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/gameScoreboard/GameObjectiveScoreboardHandler.java:[3,34] p
ackage in.parapengu.commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjectiveBuilder.java:[3,34] package in.parapengu
.commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/SphereRegion.java:[3,34] package in.parapengu.
commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/disableDamage/DisableDamageBuilder.java:[3,34] package in.p
arapengu.commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/projectiles/ProjectilesBuilder.java:[3,34] package in.parap
engu.commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CuboidRegion.java:[3,34] package in.parapengu.
commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[3,34] package in.parapengu.commons.uti
ls does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjective.java:[3,34] package in.parapengu.common
s.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CylinderRegion.java:[3,34] package in.parapeng
u.commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/toolRepair/ToolRepairBuilder.java:[3,34] package in.parapen
gu.commons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/team/TeamModuleBuilder.java:[3,34] package in.parapengu.com
mons.utils does not exist
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/gameScoreboard/GameObjectiveScoreboardHandler.java:[35,24]
cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.gameScoreboard.GameO
bjectiveScoreboardHandler
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/gameScoreboard/GameObjectiveScoreboardHandler.java:[37,24]
cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.gameScoreboard.GameO
bjectiveScoreboardHandler
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/gameScoreboard/GameObjectiveScoreboardHandler.java:[39,24]
cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.gameScoreboard.GameO
bjectiveScoreboardHandler
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjectiveBuilder.java:[27,34] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.wools.WoolObjectiveB
uilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjectiveBuilder.java:[63,38] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.wools.WoolObjectiveB
uilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/SphereRegion.java:[56,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.SphereR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/SphereRegion.java:[57,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.SphereR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/SphereRegion.java:[58,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.SphereR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/SphereRegion.java:[59,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.SphereR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/SphereRegion.java:[60,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.SphereR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/SphereRegion.java:[61,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.SphereR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/disableDamage/DisableDamageBuilder.java:[23,41] cannot find
 symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.disableDamage.Disabl
eDamageBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/projectiles/ProjectilesBuilder.java:[24,49] cannot find sym
bol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.projectiles.Projecti
lesBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CuboidRegion.java:[71,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.CuboidR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CuboidRegion.java:[72,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.CuboidR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CuboidRegion.java:[73,20] cannot find symbol
[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.CuboidR
egion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[35,57] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[43,64] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[45,64] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[74,57] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[80,39] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[87,64] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[89,64] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/kit/KitBuilder.java:[100,45] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.kit.KitBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjective.java:[117,138] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.wools.WoolObjective
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjective.java:[139,138] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.wools.WoolObjective
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjective.java:[166,135] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.wools.WoolObjective
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjective.java:[176,79] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.wools.WoolObjective
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/wools/WoolObjective.java:[180,75] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.wools.WoolObjective
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CylinderRegion.java:[63,20] cannot find symbol

[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.Cylinde
rRegion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CylinderRegion.java:[64,20] cannot find symbol

[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.Cylinde
rRegion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/regions/type/CylinderRegion.java:[65,20] cannot find symbol

[ERROR] symbol:   variable OtherUtil
[ERROR] location: class in.twizmwaz.cardinal.module.modules.regions.type.Cylinde
rRegion
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/toolRepair/ToolRepairBuilder.java:[21,31] cannot find symbo
l
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.toolRepair.ToolRepai
rBuilder
[ERROR] /C:/Users/Angel/Desktop/CardinalPGM-master/src/main/java/in/twizmwaz/car
dinal/module/modules/team/TeamModuleBuilder.java:[41,31] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class in.twizmwaz.cardinal.module.modules.team.TeamModuleBuild
er
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc



Thats what appears for me

**Comment by twizmwazin** [comment]
Re-clone the repository. Somehow your copy of the code got really messed up, some important files were deleated.

**Comment by AngelCasillas01** [comment]
How i do that? i just only downloaded by Download zip and with cmd enter to the file with cd Desktop and then cd CardinalPGM-master

That's what i do

**Comment by twizmwazin** [comment]
In English: https://github.com/twizmwazin/CardinalPGM/wiki/Installing-CardinalPGM
En español: https://github.com/twizmwazin/CardinalPGM/wiki/Instalando-CardinalPGM
