### ISSUE TITLE
Give effect levitation 255 from XML don't work

### ISSUE THREAD

**Issue by esprimer** [twizmwazin/CardinalPGM#991]
As you can see: give effect levitation 255 from XML don't work.

Example:    
_
**KITS**
` <kit name="take-levitation" force="true">
      <potion duration="oo" amplifier="255">levitation</potion>
    </kit>`

**REGIONS**
`    <apply kit="take-levitation">
      <region name="levitation-bridge"/>
    </apply>`
_

Well, the result of that doesn't give me levitation 255, it gives me another type of levitation like 240 or something like that.

**Comment by Pablete1234** [comment]
@esprimer In /effect, you specify an amplifier (amplifier 255 is effect lvl 256), in PGM, where you specify amplifier, you specify a level (amplifier 255 is effect lvl 255), what you are looking for is `amplifier="256"`

**Comment by TiTo-418** [comment]
i'M sUrE It woRks On EPGm!!!!11111

**Comment by esprimer** [comment]
Thanks @Pablete1234 sorry for that!
