### ISSUE TITLE
OCN's new attack speed is 5x

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#995]
Well, so the last update was Pablete setting attack speed to 3x, but it has been changed to 5x now. You can check it out here.

https://oc.tc/forums/topics/5701ebc75f35b9140c000013

**Comment by Pablete1234** [comment]
@MrSharpie multiplying it x3, makes it 4 times faster, but still, look at #994, that should fix your issue

**Comment by twizmwazin** [comment]
fixed in fd4498f1a6724851055f486edc5a00c45156fd2e
